### ISSUE TITLE
Move to Python3 shebangs

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/openscap#1034]
Python 2 will be sunset in 2020: https://pythonclock.org

Some modern Linux distributions will not support Python 2 anymore.
Our code is compatible with both Python 2 and 3.
However, the shebangs often contain python2.
The downstream packagers will have to patch these code.

For example, see: https://github.com/OpenSCAP/openscap/blob/maint-1.2/utils/scap-as-rpm#L1

Do you want to change shebangs to `#!/usr/bin/python3`?

Another problem is that we sometimes use "#!/usr/bin/env` which is forbidden by Fedora: https://fedoraproject.org/wiki/Packaging:Guidelines#Shebang_lines

**Comment by dahaic** [comment]
I would say it's good opportunity to finally get rid of dependency on Python2, so I am all for changing shebangs to `python3`

**Comment by jan-cerny** [comment]
We in OpenSCAP team think that a correct solution will be to apply the shebang patch to openscap master, get the PR merged, remove all support for python2 in that PR, and clean it all up.

**Comment by jan-cerny** [comment]
Fixed in #1070
