### ISSUE TITLE
Remote Assessment Report does not get copied back on the assessor machine

### ISSUE THREAD

**Issue by praving5** [OpenSCAP/openscap#104]
I have setup oscap 1.2.5 on the assessor machine and my target machine has oscap 1.1.0. I can evaluate the results remotely but the report.html file is not getting copied back to the assessor machine. 

I did some investigation and found that report.html file isn't even getting created on the target machine under /tmp/tmp.<>/ directory. I can however see the oval results at console of the assessor machine.
<img width="960" alt="assessor machine" src="https://cloud.githubusercontent.com/assets/11082039/8641877/691442e2-2939-11e5-9279-70bdf7553f86.PNG">
<img width="363" alt="target machine" src="https://cloud.githubusercontent.com/assets/11082039/8641878/691ac266-2939-11e5-8fc5-ba3625daf0a6.PNG">

Any pointers? Please check out the attached snapshot.

Please help.

Thanks and regards,
Pravin Goyal

**Comment by mmsrubar** [comment]
Hi Pravin Goyal,

you're right that the --report in eval module doesn't work at the moment but you can use the following workaround:
oscap oval eval --results oval-results.xml oval_defs.xml | oscap oval generate report oval-results.xml

**Comment by isimluk** [comment]
Hello Pravin,

Michal has just fixed this maint-1.2 branch. Next openscap-1.2.x upstream release will contain the fix.

Thank You for your report.
