### ISSUE TITLE
Handle xccdf:Rule @multiple='true' in HTML report

### ISSUE THREAD

**Issue by donpellegrino** [OpenSCAP/openscap#1044]
"Table 9: \<xccdf:Rule\> Element Properties" from "Specification for the Extensible Configuration Checklist Description Format (XCCDF) Version 1.2" lists an optional "multiple" attribute. This attribute is documented as:

> Applicable in cases where there are multiple instances of a target. For
example, a rule may provide a recommendation about the configuration of
application user accounts, but an application may have many user accounts.
Each account would be considered an instance of the broader assessment
target of user accounts. If the @multiple attribute is set to true, each
instance of the target to which the rule can apply SHOULD be tested
separately and the results SHOULD be recorded separately. If @multiple
is set to false, the test results of such instances SHOULD be combined. If the
checking system does not combine these results automatically, the results of
each instance SHOULD be ANDed together to produce a single result using
the AND truth table in Section 6.4.4.4. (default:false)
If the benchmark consumer cannot perform multiple instantiation, or if
multiple instantiation of the rule is not applicable for the target system, then
the benchmark consumer MAY ignore this attribute. For example, OVAL
checks cannot produce separate results for individual instances of a target.
See Section 7.2.3.5.2.

The XSLT style sheet that generates HTML from XCCDF does not seem to handle the case of a Rule with multiple='true' and then a set of rule-result nodes that all have an idref set to that single Rule. Instead of rendering each rule-result instance, only one entry is shown in the HTML report for the Rule.

Ideally, the HTML report would list a row for each rule-result instance in the TestResults even when there is only one corresponding Rule entry in the Benchmark.

**Comment by evgenyz** [comment]
@jan-cerny I believe we finished fixing this issue, did we?

**Comment by jan-cerny** [comment]
@evgenyz I can't find anything. You might confuse it with `multi-check` attribute.
