### ISSUE TITLE
when i run autogen.sh then get error

### ISSUE THREAD

**Issue by prashantvidja** [OpenSCAP/openscap#1045]
Hello,

I am compiling openscap scanner in my debian 9 . i have installed automake,autoconf and libtool as per your instruction. but when i run autorun.sh I am getting below error.

```
aclocal: configure.ac: 0: macro `AM_RUN_LOG' not found in library
aclocal: macro `_gl_DEFUN_ONCE([$1' required but not defined
aclocal: macro `gl_MULTIARCH' required but not defined
aclocal: macro `AM_PROG_MKDIR_P' required but not defined
aclocal: macro `_LT_DECL_SED' required but not defined
aclocal: macro `_LT_FUNC_STRIPNAME_CNF' required but not defined
aclocal: macro `gl_USE_SYSTEM_EXTENSIONS' required but not defined
aclocal: macro `gl_LARGEFILE' required but not defined
aclocal: macro `gl_SNPRINTF_RETVAL_C99' required but not defined
aclocal: macro `gl_PREREQ_VASNPRINTF_LONG_DOUBLE' required but not defined
aclocal: macro `gl_PREREQ_VASNPRINTF' required but not defined
aclocal: macro `gl_USE_SYSTEM_EXTENSIONS' required but not defined
aclocal: configure.ac: 27: macro `AM_PROG_CC_C_O' not found in library
autoreconf: aclocal failed with exit status: 1
```

Thanks

**Comment by matejak** [comment]
Hello, could you tell us versions of your autoconf and automake?

**Comment by prashantvidja** [comment]
hello @matejak ,

autoconf (GNU Autoconf) 2.69,
automake (GNU automake) 1.15

Thanks

**Comment by matejak** [comment]
It seems that you have broken installation of automake and/or autoconf. Could you try to reinstall them? Also take a look into `/usr/share/aclocal-1.15/`, there should be a file `runlog.m4` that defines `AM_RUN_LOG`.

**Comment by jan-cerny** [comment]
@prashantvidja Did the reinstallation help?

**Comment by prashantvidja** [comment]
@jan-cerny yes it worked.
@matejak thanks for help now i am closing this issue.
