### ISSUE TITLE
xccdf_org.ssgproject.content_rule_set_firewalld_default_zone says DefaultZone=drop

### ISSUE THREAD

**Issue by amitkumar50** [OpenSCAP/openscap#1058]
As per: http://iase.disa.mil/stigs/os/unix-linux/Pages/index.aspx

U_Red_Hat_Enterprise_Linux_7_V1R4_Manual_STIG/U_Red_Hat_Enterprise_Linux_7_STIG_V1R4_Manual-xccdf.xml
STIG only requires that firewalld is active and rules are configured. There is no mention of setting the default zone

In /usr/share/xml/scap/ssg/content/.ssg-rhel7-ds.xml xccdf_org.ssgproject.content_rule_set_firewalld_default_zone
The title, description, rationale, and oval check are to set the firewall DefaultZone to drop

**Comment by cipherboy** [comment]
See: https://github.com/OpenSCAP/scap-security-guide/issues/2964
