### ISSUE TITLE
xccdf_org.ssgproject.content_rule_configure_firewalld_ports 

### ISSUE THREAD

**Issue by amitkumar50** [OpenSCAP/openscap#1059]
/usr/share/xml/scap/ssg/content/.ssg-rhel7-ds.xml xccdf_org.ssgproject.content_rule_configure_firewalld_ports for DISA STIG RHEL-07-040100 automatically fails as it has no check. 

As per: http://iase.disa.mil/stigs/os/unix-linux/Pages/index.aspx
U_Red_Hat_Enterprise_Linux_7_V1R4_Manual_STIG/U_Red_Hat_Enterprise_Linux_7_STIG_V1R4_Manual-xccdf.xml
This almost needs to be manual , or notchecked, as the DISA STIG is asking for the firewall rules to meet the PPSM CLSA which would be different for every system.

**Comment by cipherboy** [comment]
See: https://github.com/OpenSCAP/scap-security-guide/issues/2963
