### ISSUE TITLE
xccdf_org.ssgproject.content_rule_accounts_password_pam_maxrepeat selector="2". DISA STIG RHEL-07-010180 = 3

### ISSUE THREAD

**Issue by amitkumar50** [OpenSCAP/openscap#1064]
Problem:
Rule ID xccdf_org.ssgproject.content_rule_accounts_password_pam_maxrepeat for DISA STIG RHEL-07-010180 has an incorrect value. The description, oval check, and remediation all have maxrepeat = 2, but the DISA STIG says that this should be maxrepeat = 3

From http://iase.disa.mil/stigs/os/unix-linux/Pages/index.aspx/Red Hat Enterprise Linux 7 STIG - Ver 1, Rel 4/U_Red_Hat_Enterprise_Linux_7_STIG_V1R4_Manual-xccdf.xml
Add the following line to "/etc/security/pwquality.conf conf" (or modify the line to have the required value):^M
^M
maxrepeat = 3</fixtext><fix id="F-78267r2_fix" /><check system="C-72147r2_chk"><check-content-ref name="M" href="DPMS_XCCDF_Benchmark_RHEL_7_STIG.xml" /><check-content>The "maxrepeat" option sets the maximum number of allowed same consecutive characters in a new password.

From /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml
Profile id="xccdf_org.ssgproject.content_profile_common"
Profile id="xccdf_org.ssgproject.content_profile_stig-rhevh-upstream"
Profile id="xccdf_org.ssgproject.content_profile_ospp-rhel7"
Profile id="xccdf_org.ssgproject.content_profile_nist-800-171-cui"
refine-value idref="xccdf_org.ssgproject.content_value_var_password_pam_maxrepeat" selector="2"/

**Comment by cipherboy** [comment]
@amitkumar50 Thanks for the issue, however, this is the wrong project for this issue (and #1059, #1058, #1057). You should file them over at the [scap-security-guide](https://github.com/OpenSCAP/scap-security-guide/issues) project as that's where the guides are built. If GH provided issue migration between projects, I'd do it myself... But if I did it manually, you wouldn't be the issue owner. When you get them moved over there, if you want to open a PR--and credit for the fix--I'd be happy to point you to the right place. 

(`openscap` is just scanner, `scap-security-guide` is a community project to build content for `openscap` and other scanners--including ansible fixes!--and `scap-workbench` is a GUI front-end to `openscap`).

Sorry about not catching this sooner! :(

**Comment by amitkumar50** [comment]
@cipherboy Hey Alxender Thanks for direction. Yes this is issue in security-guide.
I will copy paste these issues to security-guide.
Would generate PR as find time. :)
Thanks for support.

**Comment by cipherboy** [comment]
Thanks!

**Comment by cipherboy** [comment]
See: https://github.com/OpenSCAP/scap-security-guide/issues/2962
