### ISSUE TITLE
Add a Find command to the SCAP Workbench

### ISSUE THREAD

**Issue by donpellegrino** [OpenSCAP/openscap#1067]
The main SCAP Workbench dialog includes a list of Rules. There may be many rules displayed. However, the user interface lacks a Find command. It would be useful to support a find operation so that users can navigate to specific rules more quickly.

**Comment by cipherboy** [comment]
@donpellegrino The SCAP Workbench has a separate repository: https://github.com/OpenSCAP/scap-workbench -- do you mind reopening your issue over there? If I copy the description, you lose ownership of the issue.

**Comment by donpellegrino** [comment]
Opps. Sorry about that. I filed it over in scap-workbench: https://github.com/OpenSCAP/scap-workbench/issues/180
