### ISSUE TITLE
Add CMake targets to build all the HTML documentation

### ISSUE THREAD

**Issue by matusmarhefka** [OpenSCAP/openscap#1083]
We forgot to port the dist-hook (https://github.com/OpenSCAP/openscap/blob/maint-1.2/Makefile.am#L95) from the root `Makefile.am` from the `maint-1.2` into the `master` branch. CPack should be extended to generate documentation files using `doxygen` and `asciidoctor` and we should also document in `README.md` that `doxygen` and `asciidoctor` packages are needed for CPack.

**Comment by mpreisler** [comment]
doc_doxygen may be too special for people to discover / try, hence this issue.

How about renaming it to "docs", having it build all the docs and documenting it?

**Comment by jan-cerny** [comment]
@mpreisler  Yes, That would be OK for me.

Is it expected to have the docs in the source tarball made by `make package-source`? I'm afraid CMake doesn't have a concept similar to dist-hook in Automake.

**Comment by jan-cerny** [comment]
It doesn't make sense to include HTML files in the source tarballs. The practice in maint-1.2 branch is considered wrong. We don't have to port this from maint-1.2 to master 1:1. Instead, we need to make sure all the HTML documentation can be build using CMake.

**Comment by jan-cerny** [comment]
This is closed because we don't prefer to include build artifacts into source tarball.
