### ISSUE TITLE
Add AppVeyor integration into GH

### ISSUE THREAD

**Issue by redhatrises** [OpenSCAP/openscap#1091]
Not sure if this is a limitation of AppVeyor support, but it would be really helpful to have AppVeyor report status back to GH if a build passes or fails for the master branch rather than manually checking if AppVeyor passed or not.

**Comment by jan-cerny** [comment]
@redhatrises This used to work, there is a problem with permissions after recent GitHub permissions changes.

**Comment by jan-cerny** [comment]
I think I have fixed it. AppVeyor should be reporting the build status to the GitHub pull requests. For example https://github.com/OpenSCAP/openscap/pull/1106
Thanks @mpreisler for great help!
