### ISSUE TITLE
Fix profile titles in generated ansible roles

### ISSUE THREAD

**Issue by matusmarhefka** [OpenSCAP/openscap#1112]
#### Description of Problem:
When there are newlines in profile title there are no commentary marks for these newlines in the generated ansible role headers. This results in an invalid generated ansible roles.

#### Steps to Reproduce:
To reproduce you need to build older version of SSG (tested with `0.1.36`) which has one such a profile title. The role with the issue is `ssg-rhel6-role-nist-cl-il-al.yml`.

This issue is also reported in [RHBZ#1548499](https://bugzilla.redhat.com/show_bug.cgi?id=1548499) and can be fixed in a simillar way as the profile description was fixed in the PR #838.

**Comment by redhatrises** [comment]
This appears to have been fixed. Closing.

**Comment by jan-cerny** [comment]
@redhatrises Unfortunately, it hasn't been fixed. 

If you modify the content eg. the following way:

```
<title xml:lang="en-US" override="true">
OSPP
Protection
Profile
for
General
Purpose
Operating
Systems
</title>

```
and then your run 

```
oscap xccdf generate fix --profile ospp --fix-type ansible ssg-fedora-ds.xml > fix.yml
```
Then you get this:

```
---
###############################################################################
#
# Ansible Playbook for 
OSPP
Protection
Profile
for
General
Purpose
Operating
Systems

#
# Profile Description:
# This profile reflects mandatory configuration controls identified in the
# NIAP Configuration Annex to the Protection Profile for General Purpose
# Operating Systems (Protection Profile Version 4.2).
```
Notice the missing `#`s at the beginning of lines. That makes the playbook invalid.
