### ISSUE TITLE
[Proposal] Migrate OpenSCAP code away from C

### ISSUE THREAD

**Issue by redhatrises** [OpenSCAP/openscap#1114]
I know this may be controversial and may be frowned upon, but this is a proposal to move OpenSCAP away from C code to GOLANG (or something else). Plus not going to lie, I do have very basic C skills. Python could be an option, but I am not sure if having a security scanner where the code can easily be changed by anyone makes sense. 

Why?

1. Biggest reason is to increase the diverse set of contributors able to provide code to the project.
2. Faster development.
3. Easier to write probes and expand OS probe support.
4. Easier to compile/utilize against multiple OSes.
5. Better CI/CD support and integration.

I ask that this be seriously considered and not rejected immediately. This obviously wouldn't happen immediately with the other priorities that we have right now, but after we get the big stuff closed, I say that we should move forward with a migration. This conversation has happened a few times throughout the years with us ultimately saying no, but I think as we look to the future, adding more and more capability to the scanner, etc. that this should seriously be considered.

**Comment by jan-cerny** [comment]
It is nice idea, but I'm afraid it would take a lot of time.

**Comment by redhatrises** [comment]
> It is nice idea, but I'm afraid it would take a lot of time.

It would, but could be really worth it in the long run especially since the majority of contributions are from you and Martin.

**Comment by mpreisler** [comment]
![image](https://user-images.githubusercontent.com/753153/42648345-a0bf8cec-85d4-11e8-8e97-4bb25b086026.png)

**Comment by mpreisler** [comment]
> I ask that this be seriously considered and not rejected immediately.

![image](https://user-images.githubusercontent.com/753153/42648821-f09219c8-85d5-11e8-8b6c-6231d251b1c9.png)

**Comment by mpreisler** [comment]
OK, more seriously now :-)

If we could transform OpenSCAP codebase to C++14 or Go or Python3, etc... for free I think we should. However the cost of doing that migration is severe. We are talking months of intense effort of a whole team for sure. The benefits are there but C is not really a huge problem. I would even claim that more people know C than Go, although that may be changing. Furthermore, SCAP as a standard is not evolving rapidly anymore so the codebase is not as active anymore. Migrating a maintenance-phase project to another programming language doesn't seem wise.

Overall, I think we have projects with massively better ROI than this.

**Comment by cipherboy** [comment]
(Wrong button)

I agree with the motive @redhatrises. I agree with @mpreisler that if we had done this at the start (well, I guess that's equivalent to free...), it could have been interesting, but now I don't think is the time. If OpenSCAP were less niche and there was a bigger community of developers wanting a language switch, perhaps. But with fewer people working on it, perhaps not. :) 

On the other hand, if you wish to get started... I'd like Go and a [blue](https://www.thebikeshedcompany.com/shopimages/products/normal/SHED-65.jpg) bikeshed please. :)

**Comment by matejak** [comment]
We have Python bindings and a plan to make a Python-based thin CLI frontend. Therefore, in theory, one could replace C functions called by Python by pure Python implementations one-by-one, without anybody noticing.
On the other hand, SCAP is a standard that OpenSCAP already implements, so there is no pressing need to add new features. As another, significantly different standard will show up sooner or later, I think that it makes more sense to concentrate on something more permanent - e.g. on the SSG build system, or on the SSG test suite. I think that you have made a good observation and you are right, but the cost of this move is too big for our team.

**Comment by mpreisler** [comment]
Seems we have a consensus here, please reopen if you think otherwise.
