### ISSUE TITLE
Build output is so long that it can't be displayed by Travis CI

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/openscap#1123]
#### Description of Problem:
The build output of OpenSCAP is so verbose that it couldn't be completely displayed by Travis CI.
Travis CI displays a warning in its user interface.

> This log is too long to be displayed. Please reduce the verbosity of your build or download the raw log. 

For example see Ubuntu build in (scroll down)
https://travis-ci.org/OpenSCAP/openscap/jobs/404423906

#### OpenSCAP Version:
current master as of HEAD d88b85949bcb04b3811e0d2508b2f8a60fb44f64

#### Operating System & Version:
all

#### Steps to Reproduce:
1.  Open a PR against OpenSCAP and watch what Travis CI does
2. 
3. 

#### Actual Results:
Output is not visible completely in Travis CI.

#### Expected Results:
Output is visible completely  in Travis CI.

**Comment by jan-cerny** [comment]
It looks like most of the annoying output is produced by PERL bindings.

**Comment by mpreisler** [comment]
We should disable compiler warnings from swig bindings because we can't fix them anyway.

**Comment by jan-cerny** [comment]
@mpreisler Actually, I am looking into the warning reduction right now. I agree with disabling warnings for SWIG. I also would like to investigate if it would be possible to run Doxygen in some "quiet" mode because Doxygen also produces terribly long output.

**Comment by jan-cerny** [comment]
I think right now we should focus on removing Doxygen warnings.

**Comment by jan-cerny** [comment]
The Travis CI output now can fit into the UI, eg. https://travis-ci.org/OpenSCAP/openscap/jobs/640415027?utm_medium=notification&utm_source=github_status
