### ISSUE TITLE
Test of sysctl probe fails with procps-ng >= 3.3.13

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/openscap#1152]
#### Description of Problem:
Linux 4.1.0 introduced a per-NIC IPv6 stable_secret file. The stable_secret file cannot be read until it is set.

To workaround this problem, we have created a fix in 7b8ca9c7829969232cc11c4363790c09d8e41806
to skip the stable_secret files when it is not readable. Otherwise we collect them.

That behavior was consistent with behavior of `sysctl` command. `sysctl` command also skipped them.

However, at procps-ng 3.3.13 the sysctl command changed its behavior concerning the stable_secret files. The change has been introduced in https://gitlab.com/procps-ng/procps/commit/854e2c5528e85420af253da51e8ec4703c679bb3#2ac4d3e6ddf3306cb8fcbae7b632520feb2ff20e
Since procps-ng 3.3.13, `sysctl` doesn't skip stable_secret files anymore.

This change starts to break test `probes/sysctl/all.sh`. In this test, we compare a list of items obtained by `sysctl -aN --deprecated` with OVAL results produce by OpenSCAP scan of ` tests/probes/sysctl/test_sysctl_probe_all.oval.xml`.
In OVAL results, the `stable_secret`items are not present, whereas in sysctl output they are present.

We need to find a way of being consistent with `sysctl` behavoir and at the same time not breaking the OpenSCAP test suite if using procps-ng older than 3.3.13. 

#### OpenSCAP Version:
current upstream master as of d8dd104b962451a35cc19b8153a5bf49d43e43ad

#### Operating System & Version:
Fedora Rawhide

#### Steps to Reproduce:

1. ctest --verbose -R probes/sysctl/all.sh

or
1. oscap oval eval --results results.xml tests/probes/sysctl/test_sysctl_probe_all.oval.xml
2. sysctl -aN --deprecated 
3. compare OVAL results with sysctl output

#### Actual Results:
Output of sysctl probe is not consistent with output of `sysctl` tool from procps-ng >= 3.3.13 regarding `stable_secret` files.

#### Expected Results:
Output of sysctl probe is consistent with output of `sysctl` tool from any procps-ng regarding `stable_secret` files.

**Comment by matusmarhefka** [comment]
We discussed this with @jan-cerny and we think that `stable_secret` parameters should not be skipped by our probe. In case of input/output error when reading the `stable_secret` parameter we should output an empty value to the OVAL results and print a warning that I/O error occurred (which means that `stable_secret` parameter is empty).

There is also another issue that our probe does not list `vm.stat_refresh` kernel parameter, but the `sysctl` from procps-ng 3.3.15 does.

**Comment by matusmarhefka** [comment]
We can also fix the following RHBZ within this issue: https://bugzilla.redhat.com/show_bug.cgi?id=1607382
