### ISSUE TITLE
`make install` is broken

### ISSUE THREAD

**Issue by redhatrises** [OpenSCAP/openscap#1161]
#1148 broke `make install`

```
CMake Error at docs/cmake_install.cmake:31 (file):
  file INSTALL cannot find
  "/Users/travis/build/OpenSCAP/scap-workbench/openscap/build/docs/manual".
Call Stack (most recent call first):
  cmake_install.cmake:39 (include)
make: *** [install] Error 1
```

**Comment by jan-cerny** [comment]
I think that `make install` needs to have a dependency on `make docs`.

**Comment by jan-cerny** [comment]
Then, the install commands needs to be run only if the respective target is build.

**Comment by cipherboy** [comment]
To expand on this a bit (I'm still not sure how to solve this):

It does affect `scap-workbench` [as well](https://travis-ci.org/OpenSCAP/scap-workbench/builds/416765897#L2291-L2305): 

```

-- Installing: /usr/local/bin/oscap-vm
-- Installing: /usr/local/share/man/man8/oscap-vm.8
-- Installing: /usr/local/bin/scap-as-rpm
-- Installing: /usr/local/share/man/man8/scap-as-rpm.8
CMake Error at docs/cmake_install.cmake:31 (file):
  file INSTALL cannot find
  "/Users/travis/build/OpenSCAP/scap-workbench/openscap/build/docs/manual".
Call Stack (most recent call first):
  cmake_install.cmake:39 (include)
make: *** [install] Error 1
The command "make install" failed and exited with 2 during .
Your build has been stopped.
/Users/travis/.travis/job_stages: line 187: shell_session_update: command not found
```

**Comment by cipherboy** [comment]
@jan-cerny said:
> Then, the install commands needs to be run only if the respective target is build.

I looked into this a bit when you posted that, however, I was unable to come up with anything concrete. As far as I can tell, you can check _if_ a target exists, not if a target is built / up to date.

**Comment by jan-cerny** [comment]
We can add an option ENABLE_DOCS that would be turned of by default and then guard all the install commands that install the docs by checking ENABLE_DOCS.

**Comment by cipherboy** [comment]
Sure. I'll do that then.
