### ISSUE TITLE
SDS schema shall include OVAL-5.11.1

### ISSUE THREAD

**Issue by isimluk** [OpenSCAP/openscap#118]
We have sds schema patched to use 5.11 schemas. See 0aa1a0d02046f26935aa0f3833e7edf531662237 *and* 8da0f0a894de52f42b0bb97d08664d42b1b13f13.

We perhaps should patch SDS schema now to include 5.11.1. However, this needs some testing before it is done.

Test plan:
 * ours `make check` shall include test that creates datastream from simple 5.11.1 oval file
 * ssg's `make validate` shall pass when we patch our schema.

**Comment by isimluk** [comment]
@jan-cerny, could you please look into this?

**Comment by jan-cerny** [comment]
@isimluk Yes, I can !
