### ISSUE TITLE
oscap reports all items as not applicable (Win7, MS Win7SP1 xccf from SCM 4.0)

### ISSUE THREAD

**Issue by jmarsden** [OpenSCAP/openscap#1181]
#### Description of Problem:
Exporting a SCAP file for Windows 7 SP1 from Microsoft SCM 3.0, running scap with it returns a report saying every single item is "not applicable".  This is not useful, and probably not intended.

#### OpenSCAP Version:
1.3.0_alpha2 downloaded from
https://github.com/OpenSCAP/openscap/releases/tag/1.3.0_alpha2 , specifically the .msi installer at https://github.com/OpenSCAP/openscap/releases/download/1.3.0_alpha2/OpenSCAP-1.3.0-win32.msi

#### Operating System & Version:
Windows 7 Professional Service Pack 1
Microsoft Windows Version 6.1 (Build 7601: Service Pack 1)

#### Steps to Reproduce:

1. Install openscap 1.3.0_alpha2
2. Download Microsoft Security Compliance Manager 4.0 from https://www.microsoft.com/en-us/download/confirmation.aspx?id=53353
3. Run the downloaded `Security_Compliance_Manager_Setup.exe` file to install it.  Use all defaults.
4. Run Security Compliance Manager, let it update and install all the included Baselines
5. Click on the + sign next to "Windows 7 SP1" to expand it in the left panel of SCM
6. In the right panel of SCM, under Export, click "SCAP v1.0 (.cab) and save the cab file using its default name of "Win7SP1 Computer Security Compliance_SCAP.CAB". [ You will get a message about some records being dropped from the export and logged, which can be ignored.]
7. Extract the files from that .cab file, uzing 7zip or any other .cab archive extractor.  This should result in the creation of files named "Win7SP1 Computer Security Compliance-oval.xml" and "Win7SP1 Computer Security Compliance-xccdf.xml" (among others).
8. Run
```
    oscap.exe info "Win7SP1 Computer Security Compliance-xccdf.xml"
```
which should reveal a profile id of Win7SP1_Computer_Security_Compliance
9. Run a scan with oscap.exe as follows (command is all one line) in an elevated Command prompt window, from the directory containing the extracted .xml file:
```
    oscap xccdf eval --profile Win7SP1_Computer_Security_Compliance --results-arf
 win7-comp-arf.xml --report win7-comp-report.html "Win7SP1 Computer Security Compliance-xccdf.xml"
```
10. Open the results file win7-comp-report.html in a web browser.

#### Actual Results:
The Score is reported as 0.0, and every individual result is shows as "notapplicable".

#### Expected Results:
A non-zero score and some results passing, others failing, others showing as "unknown" since oscap.exe is still alpha on Windows.

#### Additional Information / Debugging Steps:
Tried using the SCAP file from SCM 3.0, same result, files seem identical.
Tried using a different SCAP file, and got more expected results (mix of fail, unknown, and pass).
I do not know how to check whether the issue is with the Microsoft SCAP data, or the oscap.exe port to Windows.  
Are there free/open SCAP or XCCF validation tools that could help with this?  
Are there debug options to oscap that would provide useful further insight?

**Comment by redhatrises** [comment]
@jmarsden can you upload the XCCDF XML file so that we can test with it?

**Comment by jmarsden** [comment]
[win7-comp-xccf.zip](https://github.com/OpenSCAP/openscap/files/2319751/win7-comp-xccf.zip)

**Comment by jmarsden** [comment]
Uploaded zip file containing the xccf file, the oval file, the arf and report results files.

**Comment by jmarsden** [comment]
@redhatrises Any ideas on this?  Any further tests I can do here to validate the XCCDF file, or otherwise "see" more of what is happening?

**Comment by jmarsden** [comment]
Looking at the contents of the XCCDF file exported from SCM and one from DISA that "works", I noticed two things: 
- The SCM is SCAP 1.0, the DISA STIG one is SCAP 1.2
- The SCM export is actually four separate files, whereas the DISA one is one file that seems to include the other info too.

How could I recombine the four files:
```
Win7SP1 Computer Security Compliance-cpe-dictionary.xml
Win7SP1 Computer Security Compliance-cpe-oval.xml
Win7SP1 Computer Security Compliance-oval.xml
Win7SP1 Computer Security Compliance-xccdf.xml
```
into one "more complete" XCCDF file, which oscap,exe could (hopefully) then use?  I can try manually hacking the XML around in Emacs, but I would hope there is a better way :)

**Comment by redhatrises** [comment]
> @redhatrises Any ideas on this? Any further tests I can do here to validate the XCCDF file, or otherwise "see" more of what is happening?

Unfortunately, I don't have a windows 7 machine to test this with, so my help might be very limited.

What happens you try the following:

```oscap info Win7SP1 Computer Security Compliance-xccdf.xml```

and

```oscap xccdf eval --profile Win7SP1_Computer_Security_Compliance --results-arf
 win7-comp-arf.xml --report win7-comp-report.html --cpe "Win7SP1 Computer Security Compliance-cpe-dictionary.xml" "Win7SP1 Computer Security Compliance-xccdf.xml"```

**Comment by jmarsden** [comment]
The first one gets me:
```
C:\Program Files (x86)\OpenSCAP 1.3.0\temp>oscap info "Win7SP1 Computer Security Compliance-xccdf.xml"
Document type: XCCDF Checklist
Checklist version: 1.1
Imported: 2018-08-24T10:49:06
Status: draft
Generated: 2009-11-19
Resolved: false
Profiles:
        Title: Win7SP1 Computer Security Compliance
                Id: Win7SP1_Computer_Security_Compliance
Referenced check files:
        Win7SP1 Computer Security Compliance-oval.xml
                system: http://oval.mitre.org/XMLSchema/oval-definitions-5

C:\Program Files (x86)\OpenSCAP 1.3.0\temp>
```
That looks OK to me.

The second one doesn't seem to be correct -- I can't "execute" an xml file.  Maybe oscap and some command is missing from the start of the second command line you posted?

I did fine one more item that is perhaps relevant.  The report.html files produced have an "Evaluation Characteristics" table, and one item in it is "Test System".  When I run oscap the reports say the "Test System" is `cpe:/a:redhat:openscap:1.3.0_alpha2` . That doesn't seem correct to me. I think it should be more like `cpe:/o:microsoft:windows7`  ?  Or am I misunderstanding the intended use of that field?

Lastly: Do you have access to any Windows machines at all for testing?  I can perhaps run oscap.exe on other machines rather than this Win7 workstation, and see if I can duplicate the issues there.

**Comment by shawndwells** [comment]
I have a Win10 VM, happy to use that to help troubleshoot.

**Comment by redhatrises** [comment]
I have a 2012 VM.

**Comment by jmarsden** [comment]
OK, I exported the WS2012R2 Member server baseline from SCM 4.0 and used oscap on  Windows 2012 R2 server here, same exact issue, all items shows as `notapplicable` .  Can you duplicate that result on your 2012 VM and then we can go forward from there?

Or, how do I tell oscap to use the data from the other 3 XML files that are exported from SCM, not just the xccddf one?

Zip containing the 4 xml files exported by SCM is attached.
[ws2012-xccdf.zip](https://github.com/OpenSCAP/openscap/files/2329373/ws2012-xccdf.zip)

**Comment by jmarsden** [comment]
Just in case: the version of Windows running on this server (according to winver.exe) is 
```
Windows Server 2012 R2
Microsoft Windows Server
Version 6.3 (Build 9600)
```

**Comment by jmarsden** [comment]
@shawndwells If you could follow the "Steps to Reproduce" above but using the Win10-1607 Computer Security Compliance baseline from SCM 4.0, on a Windows 10 machine, and see if you get similar results (all items are evaluated as `notapplicable`), that would be useful.  Thanks.

**Comment by redhatrises** [comment]
@jmarsden this appears to work for me:

```
C:\Program Files (x86)\OpenSCAP 1.3.0>oscap xccdf eval --profile WS2012R2_Member
_Server_Security_Compliance --report test.html --cpe "WS2012R2 Member Server Sec
urity Compliance-cpe-dictionary.xml" "WS2012R2 Member Server Security Compliance
-xccdf.xml"
```

Try specifying the CPE dictionary file as part of your scan.

**Comment by jmarsden** [comment]
@redhatrises Thanks, that seems to work for me too.  I thought I had tried that at one stage, but apparently not (or not correctly!).  How can I tell, for a given XCCDF file, if it needs an associated --cde option, or not?  Just try it and see?  Or is there a better way?

Also, what are the _other_ two exported XML files (suffixed `-cpe-oval.xml` and `-oval.xml` ) used for, and how would I tell oscap to use them when it needs to?

**Comment by jan-cerny** [comment]
I think we should add Windows CPE entries to our inbuilt CPE dictionary.

https://github.com/OpenSCAP/openscap/blob/master/cpe/openscap-cpe-dict.xml
https://github.com/OpenSCAP/openscap/blob/master/cpe/openscap-cpe-oval.xml

**Comment by redhatrises** [comment]
> How can I tell, for a given XCCDF file, if it needs an associated --cpe option, or not?

@jmarsden if you get the results `not applicable` is when you should use the cpe option as typically
the `not applicable` results means that it doesn't apply to your os, or scap content doesn't know what os and os version that the XCCDF applies to.

**Comment by jan-cerny** [comment]
@jmarsden It's a little tricky.

If the input SCAP file uses CPEs to determine applicability of rules, then they always need to be specified "somewhere".
There are basically 3 sources that are considered.
1. The input SCAP file can contain its own CPE dictionary and definitions. That happens eg. with the DISA content, we do the same thing in SCAP Security guide.
2. You can provide CPE dictionary and definitions in a separate file and tell OpenSCAP to use it using `--cpe` option.
3. OpenSCAP uses its own inbuilt CPE dictionary and definitions.

If the CPE is not found in any of those 3 places, then OpenSCAP tells that the rule is `not applicable` even if it should be applicable, because in fact it was unable to resolve the applicability of the rule (it doesn't know the CPE identifier).

**Comment by jmarsden** [comment]
@jan-cerny That helps.  So, should (the Windows port of) oscap have the CPE definitions used by official Microsoft baselines in its "inbuilt CPE dictionary and definitions"?  Is that planned to be added?  Is it a worthwhile enhancement request?  I would expect that, now oscap runs on Windows, quite a few Windows users will want it to work easily with SCAP data that comes from Microsoft.

**Comment by jan-cerny** [comment]
@jmarsden I think we definitely need Windows CPEs in OpenSCAP inbuilt CPE dictionary. We have there entries for all Linux distributions where OpenSCAP is shipped, so it makes sense to add there Windows as well. I have already created some CPEs in pull request https://github.com/OpenSCAP/openscap/pull/1189.

**Comment by redhatrises** [comment]
Closing as Windows CPEs have been added to OpenSCAP. `--cpe` flag can be used as well. Please reopen if this is till an issue or more CPEs need to be added that are incompatible with the changes made in #1189
