### ISSUE TITLE
openscap suse 11

### ISSUE THREAD

**Issue by degilq** [OpenSCAP/openscap#1198]
#### Description of Problem:
OpenSCAP security guide for suse 11 not work

#### Operating System & Version:

suse 11

#### Steps to Reproduce:

1. what are xccd or oval file for suse 11
2. how I can install sag for suse 11
3.

**Comment by redhatrises** [comment]
@degilq can you provide more information here?

**Comment by evgenyz** [comment]
Year-old unclear report.
