### ISSUE TITLE
OpenSCAP reports fail CCE-26555-3 if ALL ciphers aren't included

### ISSUE THREAD

**Issue by hexadiam** [OpenSCAP/openscap#121]
Gives me a fail simply because I disallow 3DES. The test should check to see if all allowed ciphers are compliant, not if all compliant ciphers exist.

**Comment by shawndwells** [comment]
On 8/1/15 10:25 PM, hexadiam wrote:
>
> Gives me a fail simply because I disallow 3DES. The test should check 
> to see if all allowed ciphers are compliant, not if all compliant 
> ciphers exist.
>

Hi @hexadiam - Because this ticket relates to content, please (re)open 
ticket on the SCAP Security Guide project 
(https://github.com/OpenSCAP/scap-security-guide).
