### ISSUE TITLE
oscap reports showing notapplicable SLES for SAP

### ISSUE THREAD

**Issue by domlock** [OpenSCAP/openscap#1231]
#### Description of Problem:
Hi all
I am in the process of migrating our current oscap configuration from our existing SLES 11.4
environment; to our newly upgrade SLES 12.2 & 12.3 systems.
I originally had to change the platform id ref within the scap-yast2sec-xccdf.xml file; from <platform idref="cpe:/o:suse:linux"/> to <platform idref="cpe:/o:suse:sles:12"/>; to get the reports to come through with actual results. Before I edited and change the parameter; all reports generated with "notapplicable" as their result set.
After I changed the value, all reports came through with results.
However; we also have 8 SLES for SAP servers; with this value set within the /etc/os-release file:
CPE_NAME="cpe:/o:suse:sles_sap:12:sp3"
This value does not match any value defined within openscap-cpe-dict.xml; and all attempts by me to change this value has not succeeded in generating any different results.
I even tried changing it to the defailt paramete as per oscap --version - Inbuilt CPE names section; but the report still generates with a value of "notapplicable"

I have logged a call with SUSE; just wanted to know if there is (maybe) a way that I can get this to go whilst waiting.

#### OpenSCAP Version:
OpenSCAP command line tool (oscap) 1.2.9

#### Operating System & Version:
NAME="SLES"
VERSION="12-SP3"
VERSION_ID="12.3"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP3"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles_sap:12:sp3"

#### Steps to Reproduce:

1. Install oscap on SLES for SAP 12.3
2. Generate report

#### Actual Results:
notapplicable

#### Expected Results:
Security Flaw/Enhancement feedback

**Comment by jan-cerny** [comment]
This is basically the same thing that is discussed in #1224
