### ISSUE TITLE
RFE: Include error message in HTML report by default

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/openscap#1262]
When viewing the OpenSCAP HTML report for an ``error`` result, no information is given about what the error is. Could details be included in the results?

Current:
![image](https://user-images.githubusercontent.com/5713754/48144888-ae6e7a80-e27f-11e8-8c7b-b19493469203.png)

Could new row could be added, or perhaps a "details" link to expand the ``error`` row, to show the error?

**Comment by redhatrises** [comment]
@shawndwells what happens when you add `--oval-results` to the scan?

**Comment by shawndwells** [comment]
``--oval-results`` isn't in documentation, labs, etc. 

Why not include detailed results by default?

**Comment by redhatrises** [comment]
@shawndwells what if you are not using OVAL?

**Comment by shawndwells** [comment]
Even more reason to include scan results by default.

**Comment by jan-cerny** [comment]
@shawndwells @redhatrises 

I like the idea that `--oval-results` and `--check-engine-results` could be turned on by default. That will be easy to change.

There is other problem that some errors don't show any information in the HTML report even if you add `--oval-results`. That would be more difficult to fix.

**Comment by redhatrises** [comment]
@shawndwells btw adding `--oval-results` shows why there is an error.

**Comment by redhatrises** [comment]
To be able to close this, error details should be given by default without having to specify `--results-arf` or `--oval-results`. See https://github.com/OpenSCAP/openscap/pull/1267#issuecomment-452024470
