### ISSUE TITLE
Memory leaks in registry_probe.c

### ISSUE THREAD

**Issue by mazkasa** [OpenSCAP/openscap#1269]
I found a memory leak in registry_probe.c.

A temporary variable `tmp` is leaking in following codes
To fix this issue, append `SEXP_free(tmp);` after L477.

https://github.com/OpenSCAP/openscap/blob/778754441b6757c6e3def40bfa76a2a6d1868750/src/OVAL/probes/windows/registry_probe.c#L473-L481

**Comment by matusmarhefka** [comment]
@mazkasa Hello, are you planning to propose a PR with a fix?

**Comment by mazkasa** [comment]
@matusmarhefka Hello, I'll try it.

**Comment by jan-cerny** [comment]
Fixed in #1276
