### ISSUE TITLE
false positive for multiple audit rules with profile C2S for CentOS Linux 7

### ISSUE THREAD

**Issue by sysadmincapsi** [OpenSCAP/openscap#1271]
Hi 
I have been improving security for one of our CentOS 7.5 Server. I have found that a few false positive for audit rules. I have ensure that required rules as mentioned in are present in `/etc/audit/rules.d/audit.rules` .

I have been using the following to run a scanner.

```
oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_C2S \ 
    --results-arf arf.xml --report $TIME-report.html --oval-results \
    --fetch-remote-resources /usr/share/xml/scap/ssg/content/ssg-centos7-ds.xml

```

Please find below more information for the rules it is producing false positives.
```
Ensure auditd Collects Information on the Use of Privileged Commands
Ensure auditd Collects File Deletion Events by User - rmdir
Ensure auditd Collects File Deletion Events by User - unlink
Ensure auditd Collects File Deletion Events by User - unlinkat
Ensure auditd Collects File Deletion Events by User - rename
Ensure auditd Collects File Deletion Events by User - renameat
Ensure auditd Collects Information on Exporting to Media (successful)
Add noexec Option to /dev/shm
Use Only FIPS 140-2 Validated Ciphers
Use Only FIPS 140-2 Validated MACs
```
I have been using the following version.

```
OpenSCAP command line tool (oscap) 1.2.16
Copyright 2009--2017 Red Hat Inc., Durham, North Carolina.

==== Supported specifications ====
XCCDF Version: 1.2
OVAL Version: 5.11.1
CPE Version: 2.3
CVSS Version: 2.0
CVE Version: 2.0
Asset Identification Version: 1.1
Asset Reporting Format Version: 1.1
CVRF Version: 1.1
```
Host information is as follow.

```
   Static hostname: xxxx
         Icon name: computer-vm
           Chassis: vm
        Machine ID: b30d0f2110ac3807b210c19ede3ce88f
           Boot ID: 9239d62bc0214cd38ac467b7cfc29717
    Virtualization: xen
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-862.14.4.el7.x86_64
      Architecture: x86-64

```

The required rules for above false positive in  the `/etc/audit/rules.d/audit.rules` are as follow.

```
grep 'rmdir\|rename\|unlink\|unlinkat\|renameat' /etc/audit/rules.d/audit.rules
-a always,exit -F arch=b64 -S rename -F auid>=1000 -F auid!=4294967295 -F key=delete
-a always,exit -F arch=b64 -S renameat -F auid>=1000 -F auid!=4294967295 -F key=delete
-a always,exit -F arch=b64 -S rmdir -F auid>=1000 -F auid!=4294967295 -F key=delete
-a always,exit -F arch=b64 -S unlink -F auid>=1000 -F auid!=4294967295 -F key=delete
-a always,exit -F arch=b64 -S unlinkat -F auid>=1000 -F auid!=4294967295 -F key=delete
```

The required rules for above false positive in  the `/etc/audit/audit.rules` are also present as follow.

```
grep 'rmdir\|rename\|unlink\|unlinkat\|renameat' /etc/audit/audit.rules
-a always,exit -F arch=b64 -S rename -F auid>=1000 -F auid!=4294967295 -F key=delete
-a always,exit -F arch=b64 -S renameat -F auid>=1000 -F auid!=4294967295 -F key=delete
-a always,exit -F arch=b64 -S rmdir -F auid>=1000 -F auid!=4294967295 -F key=delete
-a always,exit -F arch=b64 -S unlink -F auid>=1000 -F auid!=4294967295 -F key=delete
-a always,exit -F arch=b64 -S unlinkat -F auid>=1000 -F auid!=4294967295 -F key=delete
```

Also for the /dev/hsm

```openscap]# grep hsm /etc/fstab
[root@ipxxxx openscap]#
```
I would appreciate your help.
Please let me know if you need more information.

**Comment by sysadmincapsi** [comment]
<img width="1149" alt="false_positives_openscap" src="https://user-images.githubusercontent.com/44080255/48667695-29614c00-eb30-11e8-9885-d560efd3579e.png">

**Comment by sysadmincapsi** [comment]
FIPS Ciphers related configs.

```
grep Ciphers /etc/ssh/sshd_config
# Ciphers and keying
# Per CCE-CCE-27295-5: Set Ciphers aes128-ctr,aes192-ctr,aes256-ctr,aes128-cbc,3des-cbc,aes192-cbc,aes256-cbc in /etc/ssh/sshd_config
Ciphers aes128-ctr,aes192-ctr,aes256-ctr,aes128-cbc,3des-cbc,aes192-cbc,aes256-cbc

```

**Comment by sysadmincapsi** [comment]
```
 grep MACs /etc/ssh/sshd_config
# Per CCE-CCE-27455-5: Set MACs hmac-sha2-512,hmac-sha2-256,hmac-sha1,hmac-sha1-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com in /etc/ssh/sshd_config
MACs hmac-sha2-512,hmac-sha2-256,hmac-sha1,hmac-sha1-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com
```

**Comment by sysadmincapsi** [comment]
Please let me know if I am missing something obvious.

**Comment by matusmarhefka** [comment]
Hello @sysadmincapsi
thank you for reporting this! Will you be able to open an issue in the https://github.com/ComplianceAsCode/content project (which is packaged as `scap-security-guide` in centos 7) as it seems like an issue in content in the audit rules. What version of `scap-security-guide` have you used?

@yuumasato I believe these rules were passing on fedora, have we done some updates to them?

**Comment by yuumasato** [comment]
Hello, 

The failures in the audit rules could be because rules for `arch=b32` are missing. Unfortunately the rule description doesn't mention it, but if the system is 64bits the check is looking for rules for both arches.
An explanation of why can be found [here](https://static.open-scap.org/ssg-guides/ssg-rhel7-guide-C2S.html#xccdf_org.ssgproject.content_group_audit_dac_actions), it is description for a different audit rule, but the same thing applies.

And it looks like centos 7 has version 0.1.36, which is pretty old. 
If possible I suggest you try a newer version, you can get builds for CentoOS here: https://copr.fedorainfracloud.org/coprs/openscapmaint/openscap-latest/

**Comment by sysadmincapsi** [comment]
Hi yuumasato, thank you for your prompt reply. I can confirm that by adding `arch=b32` resolved audit  rules issue.

Many thanks.

**Comment by sysadmincapsi** [comment]
I wonder if there is any way to fix `Use Only FIPS 140-2 Validated MACs` and `Use Only FIPS 140-2 Validated Ciphers`

**Comment by redhatrises** [comment]
> I wonder if there is any way to fix `Use Only FIPS 140-2 Validated MACs` and `Use Only FIPS 140-2 Validated Ciphers`

@sysadmincapsi the only way to fix FIPS rules is to install Red Hat Enterprise Linux.

**Comment by sysadmincapsi** [comment]
Thank you for your help. I can close this issue
