### ISSUE TITLE
Using openscap for scanning Windows

### ISSUE THREAD

**Issue by bgoyal** [OpenSCAP/openscap#1280]
Hello Everyone,

I'm new to openscap. Hence apologize a novice question. I see a project on adding support for scanning Windows targets using openscap. What's the latest status of this project? Can someone use openscap to scan a Windows host? What Windows OSes are planned to be supported?

Best,
BG.

**Comment by aaronk1** [comment]
@bgoyal I think you can, but it's "experimental" still.

https://github.com/OpenSCAP/openscap/issues/1175

https://twitter.com/OpenSCAP/status/989107760464834560

**Comment by aaronk1** [comment]
Does work using the Issue #1175 I referenced.  Download OpenSCAP MSI here

List of Releases:  https://github.com/OpenSCAP/openscap/releases/
Newest as of today:  https://github.com/OpenSCAP/openscap/releases/download/1.3.0/OpenSCAP-1.3.0-win32.msi

Run oscap.exe with -h for some decent documentation on the commands

**Comment by peruzzijl** [comment]
@aaronk1 Is there a list of supported windows OS's?  I have 1.3.0 installed on a Windows 2008 R2 server and the exe just crashes.

**Comment by instigardo** [comment]
@aaronk1 Hi
I am trying to run benchmark for Windows Server 2012 R2, I got the xccdf file from one of the issues. But when i run it with --remediate flag, it doesn't seem to work.
Can you provide xccdf file for the same.

Thanks

**Comment by redhatrises** [comment]
@instigardo the `--remediate` flag won't work if fix content is not defined in the XCCDF file which I believe to be the case.

**Comment by instigardo** [comment]
@redhatrises can you tell me where can i get the content file for Windows Server 2012 R2?

**Comment by redhatrises** [comment]
@instigardo there is not separate fix content for XCCDF. It should be embedded in the XCCDF file itself under the `<fix />` XML tags.

**Comment by evgenyz** [comment]
@peruzzijl It looks like you issue is related to #1335. Otherwise this issue is mostly related to the content, and we do not provide any content for Windows OS. Please join #1335 if you have any additional information about the crash.

**Comment by 0katz** [comment]
Hi where can I find `U_Windows_10_V1R8_STIG_SCAP_1-1_Benchmark\U_Windows_10_V1R8_STIG_SCAP_1-1_Benchmark-xccdf.xml`

I have only found U_MS_Windows_10_STIG_V1R20_Manual-xccdf.xml it's the one provided on 

https://public.cyber.mil/stigs/downloads/?_dl_facet_stigs=operating-systems%2Cwindows

which gives me an error while running. Every test case comes back as `W: C:\Program Files (x86)\OpenSCAP 1.3.2\oscap.exe: Skipping rule that requires an unregistered check system or incorrect content reference to evaluate. Please consider providing a valid SCAP/OVAL instead of C-XXXX`

These are the arguments I used: `oscap xccdf eval C:\Users\Random_User\Downloads\U_MS_Windows_10_V1R20_STIG\U_MS_Windows_10_V1R20_Manual_STIG\U_MS_Windows_10_STIG_V1R20_Manual-xccdf.xml`

**Comment by evgenyz** [comment]
Please don't closed issues unless you know that issue is definitely related to your problem. It looks like it does not. Please create new issue and add there as much information as you could: fill the template and add scanner output (preferably also with `--verbose DEVEL` option).

**Comment by daz2712** [comment]
Hi team...what command should i run to generate a report ???? btw is there any way to fix findings???? thx in davance for your help....

**Comment by Darckilo** [comment]
> Hi team...what command should i run to generate a report ???? btw is there any way to fix findings???? thx in davance for your help.... 

I would try adding "--report "FileName.txt""

Are you using oscap to verify your security implementation?

**Comment by daz2712** [comment]
yes we are trying to use openscap for HCs Windows servers...any idea if someelse have this already implemented....???? thx in advance!!!!

**Comment by daz2712** [comment]
btw --report switch is not working..seems this is the error....

C:\Program Files (x86)\OpenSCAP 1.3.4>oscap xccdf eval U_MS_Windows_Server_2019_V1R3_STIG_SCAP_1-2_Benchmark.xml  --report report.txt
OpenSCAP Error: Unable to open file: '--report' [C:\projects\openscap\src\source\oscap_source.c:288]
Failed to create OVAL definition model from: '--report'. [C:\projects\openscap\src\XCCDF\xccdf_session.c:1117]

**Comment by ggbecker** [comment]
you need to provide all the options before `U_MS_Windows_Server_2019_V1R3_STIG_SCAP_1-2_Benchmark.xml`

OpenSCAP expects that the last element in the command line is the benchmark in this case. OpenSCAP has a rusty argparsing

**Comment by daz2712** [comment]
what is the way to create a custom profile for windows in  order to not just check but remediate?? any recipe you are using...thx 4 your help!!!!

**Comment by daz2712** [comment]
did anyone try to use this up benchmark with a custom profile and a tailoring file? if so pls can you let us know how to run ..i`ve  tried this but not working so far...

oscap xccdf eval --report test.html --profile xccdf_mil.disa.stig_profile_MAC-1_Classified_customized_DAZ --tailoring-file tailoring-xccdf.xml U_MS_Windows_Server_2019_V1R3_STIG_SCAP_1-2_Benchmark.xmlclear
OpenSCAP Error: Unable to open file: 'U_MS_Windows_Server_2019_V1R3_STIG_SCAP_1-2_Benchmark.xml

**Comment by daz2712** [comment]
anyone knows how to add more seetings this benchmark?????? Regards!!!

**Comment by ggbecker** [comment]
> what is the way to create a custom profile for windows in order to not just check but remediate?? any recipe you are using...thx 4 your help!!!!

@daz2712 I believe the only type of remediation supported for Windows at the moment would be the [SCE](https://www.open-scap.org/features/other-standards/sce/). But this engine support is not available in latest OpenSCAP windows build, you would have to use an older version probably (1.2.x).

> did anyone try to use this up benchmark with a custom profile and a tailoring file? if so pls can you let us know how to run ..i`ve tried this but not working so far...
> 
> oscap xccdf eval --report test.html --profile xccdf_mil.disa.stig_profile_MAC-1_Classified_customized_DAZ --tailoring-file tailoring-xccdf.xml U_MS_Windows_Server_2019_V1R3_STIG_SCAP_1-2_Benchmark.xml

What's exactly the output here?

> anyone knows how to add more seetings this benchmark?????? Regards!!!

What do you mean by `add more settings`? Is it new configuration checks? If yes, then I'm afraid it will be hard to achieve that unless the provider of these files release new versions containing new checks. [github.com/ComplianceAsCode/content](github.com/ComplianceAsCode/content) is the place for open-source security content is created, but at the moment there is no Windows content.

If you still have doubts and questions, I encourage you to create a new issue and put as much information as you can, files, outputs, etc as you can so we can have a clear understanding of your problem. Regards.

**Comment by zakaria-ahmd20** [comment]
No such module: --report
oscap xccdf --report test.html  eval U_MS_Windows_11_V1R1_STIG_SCAP_1-2_Benchmark.xml
Can anyone help?

**Comment by ggbecker** [comment]
> No such module: --report oscap xccdf --report test.html eval U_MS_Windows_11_V1R1_STIG_SCAP_1-2_Benchmark.xml Can anyone help?

I think you need to pass `eval` before the `--report` parameter, like:

`oscap xccdf eval --report test.html U_MS_Windows_11_V1R1_STIG_SCAP_1-2_Benchmark.xml`
