### ISSUE TITLE
Remotely scanning a target machine without installing openscap

### ISSUE THREAD

**Issue by bgoyal** [OpenSCAP/openscap#1281]
Hello there,

Wondering this has come up on the forum. I see openscap-ssh but it requires openscap to be deployed on the target machine. Is there a way to remotely run openscap without actually deploying openscap on the target.

Best,
BG.

**Comment by matejak** [comment]
What you talk about is known as Agentless Scanning. We don't plan to work on that in foreseeable future, but we can provide guidance for other community developers that would like to undertake work on this feature.
