### ISSUE TITLE
README for 1.3.0 doesn't contain steps to build with CMake

### ISSUE THREAD

**Issue by yahanvesh** [OpenSCAP/openscap#1284]
#### Description of Problem:
The README file for 1.3.0 doesn't contain steps on how to build with cmake. Im new to cmake, so i wouldnt know where to start. The README still refers to configure command which is not even available in 1.3.0.

**Comment by ggbecker** [comment]
Hello,

CMake is usually straightforward, you would just run:

$ cd build
$ cmake ..
$ make -j4

and if all dependencies are met, then it shouldn't be a problem to build the openscap.

But of course this will be part of the documentation some day when it is released.

Thank you.

**Comment by yahanvesh** [comment]
@ggbecker i dont see any build directory in 1.3.0, i do see there are lots of places with CMake. Also looks like we need to use cmake3 only and looks like some installation steps are required for cmake.

**Comment by redhatrises** [comment]
The `build` directory definitely exists for 1.3.0. See https://github.com/OpenSCAP/openscap/tree/1.3.0/build

The above build steps work for me. Also going into the `maint-1.3` branch, the build instructions are correct at https://github.com/OpenSCAP/openscap/blob/maint-1.3/docs/developer/developer.adoc

The default branch for the repo is maint-1.2. Please make sure to change branches to maint-1.3

**Comment by yahanvesh** [comment]
@redhatrises Thanks for the build instructions , can this be updated in the README.
Also I cannot see build directory in the 1.3.0 release tar ball. So i assume the release tar ball contains only the executable and no need to build then. But the build steps you have given assumes there is build directory inside tar ball as well.

**Comment by redhatrises** [comment]
Huh... that's odd that the build directory doesn't exist, but anyway, all you have to do is `mkdir` it anyway... a link to the build instructions are already in the readme. I am not sure why we would duplicate them as that makes updating the instructions more difficult to keep in sync.

**Comment by jan-cerny** [comment]
Yes, the build instructions for different systems have been moved to Developer documentation. https://github.com/OpenSCAP/openscap/blob/maint-1.3/docs/developer/developer.adoc
