### ISSUE TITLE
OpenSCAP 1.3.0 fails to compile on IBM AIX7.1.0.0

### ISSUE THREAD

**Issue by QsdRty** [OpenSCAP/openscap#1286]
#### Description of Problem:
OpenSCAP 1.3.0 fails to compile on IBM AIX7.1.0.0

#### OpenSCAP Version:
1.3.0

#### Operating System & Version:
IBM AIX 7.1.0.0
curl-devel-7.57.0-1
libssh2-devel-1.8.0-1
openssl-devel-1.1.0g-1withsslv2
zlib-devel-1.2.11-1
libidn-devel-1.33-1
libxml2-devel-2.9.7-1
xz-devel-5.2.3-1
libxslt-devel-1.1.32-1
libgcrypt-devel-1.8.2-1
libgpg-error-devel-1.27-1
pcre-devel-8.41-1
openldap-devel-2.4.46-1
gettext-devel-0.19.8.1-3
bzip2-devel-1.0.6-2
gcc-cpp-6.3.0-2
gcc-6.3.0-2
libgcc-6.3.0-2

#### Steps to Reproduce:

1. 
./configure \
--enable-util-oscap=no \
--enable-util-oscap-vm=no \
--enable-util-oscap-chroot=no \
--enable-util-oscap-ssh=no \
--enable-util-oscap-docker=no \
--enable-util-scap-as-rpm=no \
--enable-debug=no \
--enable-regex-posix=yes \
--prefix=/opt/openscap

.....

OpenSCAP will be compiled with the following settings:

oscap tool:                    no
scap-as-rpm tool:              no
oscap-ssh tool:                no
oscap-docker tool:             no
oscap-vm tool:                 no
oscap-chroot tool:             no
python2 bindings enabled:      yes
python3 bindings enabled:      no
perl bindings enabled:         no
use POSIX regex:               yes
SCE enabled                    no
debugging flags enabled:       no
CCE enabled:                   no

  === probes ===
  family:                      yes
  textfilecontent:             yes
  textfilecontent54:           yes
  variable:                    yes
  xmlfilecontent:              yes
  filehash:                    yes
  filehash58:                  yes
  environmentvariable:         yes
  environmentvariable58:       yes
  sql:                         NO (missing: header files)
  sql57:                       NO (missing: header files)
  ldap57:                      yes
  dnscache:                    yes
  runlevel:                    yes
  file:                        yes
  fileextendedattribute:       NO (missing: header files)
  password:                    NO (missing: header files)
  process:                     yes
  process58:                   NO (missing: )
  shadow:                      NO (missing: header files)
  uname:                       yes
  interface:                   NO (missing: header files)
  xinetd:                      yes
  sysctl:                      yes
  routingtable:                NO (missing: header files)
  symlink:                     yes
  gconf:                       NO (missing: header files)
  isainfo:                     NO (missing: header files)
  package:                     yes
  patch:                       yes
  smf:                         yes
  partition:                   NO (missing: header files)
  inetlisteningservers:        NO (missing: header files)
  iflisteners:                 NO (missing: header files)
  selinuxboolean:              NO (missing: header files)
  selinuxsecuritycontext:      NO (missing: header files)
  rpminfo:                     NO (missing: header files)
  rpmverify:                   NO (missing: header files)
  rpmverifyfile:               NO (missing: header files)
  rpmverifypackage:            NO (missing: header files)
  dpkginfo:                    NO (missing: )
  systemdunitproperty:         NO (missing: header files)
  systemdunitdependency:       NO (missing: header files)
  system_info:                 always enabled

  === configuration ===
  probe directory set to:      /opt/openscap/libexec/openscap

  === crypto === 
  library:                     GCrypt
     libs:                     -L/opt/freeware/lib -lgcrypt -lgpg-error
   cflags:                     -I/opt/freeware/include

Valgrind checks enabled:       no
CFLAGS:                        -g -O2 -pipe -std=c99 -W -Wall -Wnonnull -Wshadow -Wformat -Wundef -Wno-unused-parameter -Wmissing-prototypes -Wno-unknown-pragmas -D_GNU_SOURCE -DOSCAP_THREAD_SAFE -D_POSIX_C_SOURCE=200112L -Wno-unused-function
CXXFLAGS:   
2. 
make
........
  CC       system_info.o
independent/system_info.c:89:3: error: #error "Sorry, your OS isn't supported."
 # error "Sorry, your OS isn't supported."
   ^~~~~
independent/system_info.c: In function '_offline_get_menuentry':
independent/system_info.c:373:15: error: 'MAX_BUFFER_SIZE' undeclared (first use in this function)
  char grubcfg[MAX_BUFFER_SIZE+1] = { '\0' };
               ^~~~~~~~~~~~~~~
independent/system_info.c:373:15: note: each undeclared identifier is reported only once for each function it appears in
independent/system_info.c:374:11: error: 'PCRE_ERROR_NOMATCH' undeclared (first use in this function)
  int rc = PCRE_ERROR_NOMATCH;
           ^~~~~~~~~~~~~~~~~~
independent/system_info.c:415:2: error: unknown type name 'regex_t'
  regex_t preg;
  ^~~~~~~
independent/system_info.c:416:2: error: unknown type name 'regmatch_t'
  regmatch_t pmatch[1];
  ^~~~~~~~~~
independent/system_info.c:418:7: warning: implicit declaration of function 'regcomp' [-Wimplicit-function-declaration]
  rc = regcomp(&preg, _REGEX_MENUENTRY, REG_EXTENDED|REG_NEWLINE);
       ^~~~~~~
independent/system_info.c:418:22: error: '_REGEX_MENUENTRY' undeclared (first use in this function)
  rc = regcomp(&preg, _REGEX_MENUENTRY, REG_EXTENDED|REG_NEWLINE);
                      ^~~~~~~~~~~~~~~~
independent/system_info.c:418:40: error: 'REG_EXTENDED' undeclared (first use in this function)
  rc = regcomp(&preg, _REGEX_MENUENTRY, REG_EXTENDED|REG_NEWLINE);
                                        ^~~~~~~~~~~~
independent/system_info.c:418:53: error: 'REG_NEWLINE' undeclared (first use in this function)
  rc = regcomp(&preg, _REGEX_MENUENTRY, REG_EXTENDED|REG_NEWLINE);
                                                     ^~~~~~~~~~~
independent/system_info.c:424:4: warning: implicit declaration of function 'regfree' [-Wimplicit-function-declaration]
    regfree(&preg);
    ^~~~~~~
independent/system_info.c:429:9: warning: implicit declaration of function 'regexec' [-Wimplicit-function-declaration]
    rc = regexec(&preg, grubcfg, 1, pmatch, 0);
         ^~~~~~~
independent/system_info.c:440:30: error: request for member 'rm_so' in something not a structure or union
  char *ptr = grubcfg + pmatch->rm_so + sizeof("menuentry '") - 1;
                              ^~
independent/system_info.c:444:16: error: request for member 'rm_eo' in something not a structure or union
  grubcfg[pmatch->rm_eo] = '\0';
                ^~
independent/system_info.c:375:6: warning: variable 'len' set but not used [-Wunused-but-set-variable]
  int len;
      ^~~
independent/system_info.c:373:7: warning: unused variable 'grubcfg' [-Wunused-variable]
  char grubcfg[MAX_BUFFER_SIZE+1] = { '\0' };
       ^~~~~~~
independent/system_info.c: In function '_offline_get_arch':
independent/system_info.c:499:2: error: unknown type name 'regex_t'
  regex_t preg;
  ^~~~~~~
independent/system_info.c:500:2: error: unknown type name 'regmatch_t'
  regmatch_t pmatch[1];
  ^~~~~~~~~~
independent/system_info.c:502:22: error: '_REGEX_ARCH' undeclared (first use in this function)
  rc = regcomp(&preg, _REGEX_ARCH, REG_EXTENDED|REG_NEWLINE);
                      ^~~~~~~~~~~
independent/system_info.c:502:35: error: 'REG_EXTENDED' undeclared (first use in this function)
  rc = regcomp(&preg, _REGEX_ARCH, REG_EXTENDED|REG_NEWLINE);
                                   ^~~~~~~~~~~~
independent/system_info.c:502:48: error: 'REG_NEWLINE' undeclared (first use in this function)
  rc = regcomp(&preg, _REGEX_ARCH, REG_EXTENDED|REG_NEWLINE);
                                                ^~~~~~~~~~~
independent/system_info.c:512:21: error: request for member 'rm_eo' in something not a structure or union
  size_t len = pmatch->rm_eo - pmatch->rm_so - 1; // Skip '.' char
                     ^~
independent/system_info.c:512:37: error: request for member 'rm_so' in something not a structure or union
  size_t len = pmatch->rm_eo - pmatch->rm_so - 1; // Skip '.' char
                                     ^~
independent/system_info.c:516:32: error: request for member 'rm_so' in something not a structure or union
  ptr = strncpy(ptr, os + pmatch->rm_so+1, len);
                                ^~
independent/system_info.c: In function '_offline_get_os_name':
independent/system_info.c:528:19: error: 'MAX_BUFFER_SIZE' undeclared (first use in this function)
  char saved_entry[MAX_BUFFER_SIZE+1];
                   ^~~~~~~~~~~~~~~
independent/system_info.c:576:2: error: unknown type name 'regex_t'
  regex_t preg;
  ^~~~~~~
independent/system_info.c:577:2: error: unknown type name 'regmatch_t'
  regmatch_t pmatch[1];
  ^~~~~~~~~~
independent/system_info.c:579:22: error: '_REGEX_SAVED_ENTRY' undeclared (first use in this function)
  rc = regcomp(&preg, _REGEX_SAVED_ENTRY, REG_EXTENDED|REG_NEWLINE);
                      ^~~~~~~~~~~~~~~~~~
independent/system_info.c:579:42: error: 'REG_EXTENDED' undeclared (first use in this function)
  rc = regcomp(&preg, _REGEX_SAVED_ENTRY, REG_EXTENDED|REG_NEWLINE);
                                          ^~~~~~~~~~~~
independent/system_info.c:579:55: error: 'REG_NEWLINE' undeclared (first use in this function)
  rc = regcomp(&preg, _REGEX_SAVED_ENTRY, REG_EXTENDED|REG_NEWLINE);
                                                       ^~~~~~~~~~~
independent/system_info.c:589:28: error: request for member 'rm_so' in something not a structure or union
  ptr = saved_entry + pmatch->rm_so + sizeof("saved_entry=")-1;
                            ^~
independent/system_info.c:590:20: error: request for member 'rm_eo' in something not a structure or union
  saved_entry[pmatch->rm_eo] = '\0';
                    ^~
independent/system_info.c:528:7: warning: unused variable 'saved_entry' [-Wunused-variable]
  char saved_entry[MAX_BUFFER_SIZE+1];
       ^~~~~~~~~~~
make: 1254-004 The error code from the last command is 1.

Stop.
make: 1254-004 The error code from the last command is 1.

Stop.
make: 1254-004 The error code from the last command is 1.

Stop.
make: 1254-004 The error code from the last command is 2.

Stop.

3.  Also i commented out all calls of GNU program_invocation_short_name in debug.c

**Comment by yuumasato** [comment]
Hello, could you please double check the version you are trying to build?

I couldn't find mentioned line 
`independent/system_info.c:89:3: error: #error "Sorry, your OS isn't supported."`
in `maint-1.3` branch, but I could find it on `maint-1.2`.

**Comment by QsdRty** [comment]
My mistake, sorry.
Anyway in version 1.3.0  i have compilation errors like this:

root@s-msk-t-comlaix:build# make     
Scanning dependencies of target compat_object
[  1%] Building C object compat/CMakeFiles/compat_object.dir/dev_to_tty.c.o
Target "compat/CMakeFiles/compat_object.dir/build" is up to date.
[  1%] Built target compat_object
Scanning dependencies of target common_object
[  1%] Building C object src/common/CMakeFiles/common_object.dir/bfind.c.o
[  1%] Building C object src/common/CMakeFiles/common_object.dir/compat_pthread_barrier.c.o
[  1%] Building C object src/common/CMakeFiles/common_object.dir/debug.c.o
/usr/sys/inst.images/Wazuh/openscap-1.3.0/src/common/debug.c: In function 'debug_message_start':
/usr/sys/inst.images/Wazuh/openscap-1.3.0/src/common/debug.c:66:27: error: 'program_invocation_short_name' undeclared (first use in this function)
 # define GET_PROGRAM_NAME program_invocation_short_name
                           ^
/usr/sys/inst.images/Wazuh/openscap-1.3.0/src/common/debug.c:208:40: note: in expansion of macro 'GET_PROGRAM_NAME'
  fprintf(__debuglog_fp, "%c: %s: ", l, GET_PROGRAM_NAME);
                                        ^~~~~~~~~~~~~~~~
/usr/sys/inst.images/Wazuh/openscap-1.3.0/src/common/debug.c:66:27: note: each undeclared identifier is reported only once for each function it appears in
 # define GET_PROGRAM_NAME program_invocation_short_name
                           ^
/usr/sys/inst.images/Wazuh/openscap-1.3.0/src/common/debug.c:208:40: note: in expansion of macro 'GET_PROGRAM_NAME'
  fprintf(__debuglog_fp, "%c: %s: ", l, GET_PROGRAM_NAME);
                                        ^~~~~~~~~~~~~~~~
/usr/sys/inst.images/Wazuh/openscap-1.3.0/src/common/debug.c: In function 'debug_message_devel_metadata':
/usr/sys/inst.images/Wazuh/openscap-1.3.0/src/common/debug.c:66:27: error: 'program_invocation_short_name' undeclared (first use in this function)
 # define GET_PROGRAM_NAME program_invocation_short_name
   program_invocation_short_name, (long) getpid(), thread_name,

So i added AIX definition for GET_PROGRAM_NAME  in debug.c
#if defined(OS_WINDOWS)
# include <windows.h>
# define GET_PROGRAM_NAME get_program_name()
#elif defined(OS_APPLE)
# define GET_PROGRAM_NAME getprogname()
#elif defined(OS_AIX)
# define GET_PROGRAM_NAME getprogname()
#else
# define GET_PROGRAM_NAME program_invocation_short_name
#endif


Next,

[ 47%] Building C object src/OVAL/probes/independent/CMakeFiles/independent_probes_object.dir/system_info_probe.c.o
/usr/sys/inst.images/Wazuh/openscap-1.3.0/src/OVAL/probes/independent/system_info_probe.c: In function '_offline_get_menuentry':
/usr/sys/inst.images/Wazuh/openscap-1.3.0/src/OVAL/probes/independent/system_info_probe.c:497:15: error: 'MAX_BUFFER_SIZE' undeclared (first use in this function)
  char grubcfg[MAX_BUFFER_SIZE+1] = { '\0' };
               ^~~~~~~~~~~~~~~
/usr/sys/inst.images/Wazuh/openscap-1.3.0/src/OVAL/probes/independent/system_info_probe.c:497:15: note: each undeclared identifier is reported only once for each function it appears in
/usr/sys/inst.images/Wazuh/openscap-1.3.0/src/OVAL/probes/independent/system_info_probe.c:505:11: error: 'PCRE_ERROR_NOMATCH' undeclared (first use in this function)
  int rc = PCRE_ERROR_NOMATCH;
           ^~~~~~~~~~~~~~~~~~
/usr/sys/inst.images/Wazuh/openscap-1.3.0/src/OVAL/probes/independent/system_info_probe.c:506:22: error: '_REGEX_RES_VECSIZE' undeclared (first use in this function)
  int erroffset, ovec[_REGEX_RES_VECSIZE];
                      ^~~~~~~~~~~~~~~~~~
/usr/sys/inst.images/Wazuh/openscap-1.3.0/src/OVAL/probes/independent/system_info_probe.c:508:2: error: unknown type name 'pcre'
  pcre *re;
  ^~~~
/usr/sys/inst.images/Wazuh/openscap-1.3.0/src/OVAL/probes/independent/system_info_probe.c:509:7: warning: implicit declaration of function 'pcre_compile' [-Wimplicit-function-declaration]
  re = pcre_compile(_REGEX_MENUENTRY, 0, &error, &erroffset, NULL);
       ^~~~~~~~~~~~
/usr/sys/inst.images/Wazuh/openscap-1.3.0/src/OVAL/probes/independent/system_info_probe.c:509:20: error: '_REGEX_MENUENTRY' undeclared (first use in this function)
  re = pcre_compile(_REGEX_MENUENTRY, 0, &error, &erroffset, NULL);
                    ^~~~~~~~~~~~~~~~
/usr/sys/inst.images/Wazuh/openscap-1.3.0/src/OVAL/probes/independent/system_info_probe.c:516:4: warning: implicit declaration of function 'pcre_free' [-Wimplicit-function-declaration]
    pcre_free(re);
    ^~~~~~~~~
/usr/sys/inst.images/Wazuh/openscap-1.3.0/src/OVAL/probes/independent/system_info_probe.c:522:9: warning: implicit declaration of function 'pcre_exec' [-Wimplicit-function-declaration]
    rc = pcre_exec(re, NULL, grubcfg, len, ovec[1], 0, ovec, _REGEX_RES_VECSIZE);
         ^~~~~~~~~
/usr/sys/inst.images/Wazuh/openscap-1.3.0/src/OVAL/probes/independent/system_info_probe.c:506:17: warning: unused variable 'ovec' [-Wunused-variable]
  int erroffset, ovec[_REGEX_RES_VECSIZE];
                 ^~~~
/usr/sys/inst.images/Wazuh/openscap-1.3.0/src/OVAL/probes/independent/system_info_probe.c:497:7: warning: unused variable 'grubcfg' [-Wunused-variable]
  char grubcfg[MAX_BUFFER_SIZE+1] = { '\0' };
       ^~~~~~~
/usr/sys/inst.images/Wazuh/openscap-1.3.0/src/OVAL/probes/independent/system_info_probe.c: In function '_offline_get_arch':
/usr/sys/inst.images/Wazuh/openscap-1.3.0/src/OVAL/probes/independent/system_info_probe.c:565:22: error: '_REGEX_RES_VECSIZE' undeclared (first use in this function)
  int erroffset, ovec[_REGEX_RES_VECSIZE] = { 0 };
                      ^~~~~~~~~~~~~~~~~~
/usr/sys/inst.images/Wazuh/openscap-1.3.0/src/OVAL/probes/independent/system_info_probe.c:567:2: error: unknown type name 'pcre'
  pcre *re;
  ^~~~
/usr/sys/inst.images/Wazuh/openscap-1.3.0/src/OVAL/probes/independent/system_info_probe.c:569:20: error: '_REGEX_ARCH' undeclared (first use in this function)
  re = pcre_compile(_REGEX_ARCH, 0, &error, &erroffset, NULL);
                    ^~~~~~~~~~~
/usr/sys/inst.images/Wazuh/openscap-1.3.0/src/OVAL/probes/independent/system_info_probe.c:574:12: error: 'PCRE_ERROR_NOMATCH' undeclared (first use in this function)
  if (rc == PCRE_ERROR_NOMATCH)
            ^~~~~~~~~~~~~~~~~~
/usr/sys/inst.images/Wazuh/openscap-1.3.0/src/OVAL/probes/independent/system_info_probe.c:565:17: warning: unused variable 'ovec' [-Wunused-variable]
  int erroffset, ovec[_REGEX_RES_VECSIZE] = { 0 };
                 ^~~~
/usr/sys/inst.images/Wazuh/openscap-1.3.0/src/OVAL/probes/independent/system_info_probe.c: In function '_offline_get_os_name':
/usr/sys/inst.images/Wazuh/openscap-1.3.0/src/OVAL/probes/independent/system_info_probe.c:592:19: error: 'MAX_BUFFER_SIZE' undeclared (first use in this function)
  char saved_entry[MAX_BUFFER_SIZE+1];
                   ^~~~~~~~~~~~~~~
/usr/sys/inst.images/Wazuh/openscap-1.3.0/src/OVAL/probes/independent/system_info_probe.c:606:22: error: '_REGEX_RES_VECSIZE' undeclared (first use in this function)
  int erroffset, ovec[_REGEX_RES_VECSIZE] = { 0 };
                      ^~~~~~~~~~~~~~~~~~
/usr/sys/inst.images/Wazuh/openscap-1.3.0/src/OVAL/probes/independent/system_info_probe.c:608:2: error: unknown type name 'pcre'
  pcre *re;
  ^~~~
/usr/sys/inst.images/Wazuh/openscap-1.3.0/src/OVAL/probes/independent/system_info_probe.c:610:20: error: '_REGEX_SAVED_ENTRY_NR' undeclared (first use in this function)
  re = pcre_compile(_REGEX_SAVED_ENTRY_NR, 0, &error, &erroffset, NULL);
                    ^~~~~~~~~~~~~~~~~~~~~
/usr/sys/inst.images/Wazuh/openscap-1.3.0/src/OVAL/probes/independent/system_info_probe.c:626:20: error: '_REGEX_SAVED_ENTRY' undeclared (first use in this function)
  re = pcre_compile(_REGEX_SAVED_ENTRY, 0, &error, &erroffset, NULL);
                    ^~~~~~~~~~~~~~~~~~
/usr/sys/inst.images/Wazuh/openscap-1.3.0/src/OVAL/probes/independent/system_info_probe.c:606:17: warning: unused variable 'ovec' [-Wunused-variable]
  int erroffset, ovec[_REGEX_RES_VECSIZE] = { 0 };
                 ^~~~
/usr/sys/inst.images/Wazuh/openscap-1.3.0/src/OVAL/probes/independent/system_info_probe.c:592:7: warning: unused variable 'saved_entry' [-Wunused-variable]
  char saved_entry[MAX_BUFFER_SIZE+1];
       ^~~~~~~~~~~
make: 1254-004 The error code from the last command is 1.


Stop.
make: 1254-004 The error code from the last command is 2.


Stop.
make: 1254-004 The error code from the last command is 2.


Stop.

**Comment by yuumasato** [comment]
All undeclared definitions come from within an `#if deffined(OS_LINUX)` on ```src/OVAL/probes/independent/system_info_probe.c:88```
And the place where the undeclared code is used is within `#ifndef OS_WINDOWS`.
And clearly AIX is not Linux and not Windows.

Could you evaluate the definitions and includes and assess if they are valid for AIX systems?
It may be the case that the functions will need some changes too.

**Comment by QsdRty** [comment]
I think AIX platform support from 1.2.16 release notes announced too early.
/tmp/openscap-1.3.0/src/OVAL/probes/unix/password_probe.c
```
+ #if defined(OS_AIX)
+ #include <aixif/net_if.h>
+ #include <login.h>
+ #include <pcre.h>
+ #define _REGEX_RES_VECSIZE     3
+ #define _REGEX_MENUENTRY       "(?<=menuentry ').*?(?=')"
+ #define _REGEX_SAVED_ENTRY_NR  "(?<=saved_entry=)[0-9]+"
+ #define _REGEX_SAVED_ENTRY     "(?<=saved_entry=).*"
+ #define _REGEX_ARCH            "(?<=\\.)i386|i686|x86_64|ia64|alpha|amd64|arm|armeb|armel|hppa|m32r" \
+                        "|m68k|mips|mipsel|powerpc|ppc64|s390|s390x|sh3|sh3eb|sh4|sh4eb|sparc"
+ #define MAX_BUFFER_SIZE        4096
+ 
+ #endif
+ 
```

Next i don't known wthat to do with password probes
/tmp/openscap-1.3.0/src/OVAL/probes/unix/password_probe.c
```
- #ifdef OS_APPLE
+ #if defined(OS_APPLE) || (defined(OS_AIX)) 
```
```
Target "src/OVAL/probes/independent/CMakeFiles/independent_probes_object.dir/build" is up to date.
[ 50%] Built target independent_probes_object
Scanning dependencies of target unix_probes_object
[ 50%] Building C object src/OVAL/probes/unix/CMakeFiles/unix_probes_object.dir/password_probe.c.o
/usr/sys/inst.images/Wazuh/openscap-1.3.0/src/OVAL/probes/unix/password_probe.c: In function 'read_password':
/usr/sys/inst.images/Wazuh/openscap-1.3.0/src/OVAL/probes/unix/password_probe.c:126:46: error: '_PATH_LASTLOG' undeclared (first use in this function)
                          FILE *ll_fp = fopen(_PATH_LASTLOG, "r");
                                              ^~~~~~~~~~~~~
/usr/sys/inst.images/Wazuh/openscap-1.3.0/src/OVAL/probes/unix/password_probe.c:126:46: note: each undeclared identifier is reported only once for each function it appears in
/usr/sys/inst.images/Wazuh/openscap-1.3.0/src/OVAL/probes/unix/password_probe.c:129:42: error: storage size of 'll' isn't known
                           struct lastlog ll;
                                          ^~
/usr/sys/inst.images/Wazuh/openscap-1.3.0/src/OVAL/probes/unix/password_probe.c:129:42: warning: unused variable 'll' [-Wunused-variable]
make: 1254-004 The error code from the last command is 1.


Stop.
make: 1254-004 The error code from the last command is 2.


Stop.
make: 1254-004 The error code from the last command is 2.


Stop.

```

**Comment by QsdRty** [comment]
any ideas ?

**Comment by yuumasato** [comment]
@QsdRty Sorry for delay,

`_PATH_LASTLOG` points to a path where last user logins are recorded, in this case this is defined in `<paths.h>` and points to `/var/log/lastlog`.
In AIX it seems to be `/etc/security/lastlog`, see https://www.ibm.com/support/knowledgecenter/en/ssw_aix_71/com.ibm.aix.files/lastlog.htm
I'm not sure if this path is defined somewhere.

**Comment by remotekernel** [comment]
Is AIX 7.1 supported by openscap? I couldn't find any official documentation on IBM side. There is only a release note for 1.2.16 "The AIX platform is supported." Does anyone have information about that?

**Comment by evgenyz** [comment]
We don't build or test OpenSCAP on that platform. But we could try to fix issues if someone can pinpoint exact problems and we will definitely accept PRs that would fix these problems (although if changes are big it's better to discuss them in an issue beforehand). Also, we can integrate gating CI for this platform if someone would provide us the means to do this.
