### ISSUE TITLE
`Profile Title` was dropped causing a problem with uploading to Ansible Galaxy

### ISSUE THREAD

**Issue by redhatrises** [OpenSCAP/openscap#1300]
In #1261, `Profile Title` was dropped causing a problem with uploading to Ansible Galaxy for new repos. 

Why was this dropped (trying to understand the reasoning)?

**Comment by evgenyz** [comment]
@jan-cerny  @matusmarhefka There were two PRs related to this issue: #1261, https://github.com/ComplianceAsCode/content/pull/4276. This issue still manifesting? 

@redhatrises What is the root cause of the problem with uploading?

**Comment by jan-cerny** [comment]
@evgenyz The string `Profile Title:` isn't present in the generated remediation header. There is only the actual profile title. It was recommended by reviewer in https://github.com/OpenSCAP/openscap/pull/1261#discussion_r231577465. It is easy to change it back or in any other way.

**Comment by jan-cerny** [comment]
The relevant code is now in _write_script_header_to_fd in src/XCCDF_POLICY/xccdf_policy_remediate.c

**Comment by redhatrises** [comment]
@evgenyz trying to understand why https://github.com/OpenSCAP/openscap/pull/1261/files#diff-e11e8275691648465496f53fc291e74fL863 was done.... Profile Title was used to create metadata content.

**Comment by jan-cerny** [comment]
@redhatrises There was no real reasoning, only a feeling that it looks better, we weren't aware that it is read by another tool.

Should it be added back?
