### ISSUE TITLE
Create table to show rule maturity

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/openscap#1303]
Something to visualize maturity/completeness of a given rule. For example:

| Rule | OVAL | Bash | Ansible | Test Suite |
| --- | --- | --- | --- | --- |
| rule1 | X | - | X | - |
| rule 2 | X | X | X | X |
| rule 3 | - | - | X | X |
| rule 4 | X | - | - | - |

Would allow easy visualization of what rules need what kinds of improvements.

Something like...
MVP: HTML table generated during build
v1: Build auto publishes to a GitHub page after every PR, ensuring content dynamic/auto updated

Random features:
- clicking on a rule would bring you to GitHub URL of where rule lives in the code, so you don't have to hunt for it

**Comment by redhatrises** [comment]
This should be a ticket created under the ComplianceAsCode project and not here in Openscap.

**Comment by shawndwells** [comment]
yah just noticed that too
