### ISSUE TITLE
More details on OpenSCAP Evaluation Report

### ISSUE THREAD

**Issue by Albaheja** [OpenSCAP/openscap#1309]
Hello Everyone,

I'm new to openscap. Hence apologize a novice question. After scanning, I get unknown results, for example: Reversible password encryption must be disabled. I do not understand why?
Can you help me better understand and especially how to make this result pass or fail.

Thank you in advance for your help.

**Comment by shawndwells** [comment]
Hey @Albaheja ! There is some ongoing work to make the reports have more detail. See https://github.com/OpenSCAP/openscap/pull/1267#issuecomment-452024470 for that work.

For your specific scan results, try re-running the scan with the ``--oval-results`` flag, e.g 
``oscap xccdf eval --profile <foo> --oval-results .......``

The results should be a bit clearer after that. If not, any chance you could share your results.xml or results.html?

**Comment by Albaheja** [comment]
Hi shawndwells@! Thank you for your help, it works with this script.
thanks again.

**Comment by shawndwells** [comment]
On 3/11/19 12:09 PM, Albaheja wrote:
> Hi shawndwells@! Thank you for your help, it works with this script.
> thanks again.


Great! Future versions of the tooling will have the --oval-results 
argument used by default. Should help make the reports clearer.

If everything is working, would you mind closing the ticket?

-Shawn
