### ISSUE TITLE
understand why i have a lot of unknown in my test

### ISSUE THREAD

**Issue by Albaheja** [OpenSCAP/openscap#1312]
Hi all,

The results of my test have a lot of unknowns, how to unlock this situation.
Here is an example of results:
Benchmark ID xccdf_mil.disa.stig_benchmark_Windows_Server_2016_STIG

Results

Windows 2016 account lockout duration must be configured to 15 minutes or greater. medium
unknown
SRG-OS-000021-GPOS-00005 1x unknown
The number of allowed bad logon medium
unknown
SRG-OS-000021-GPOS-00005 1x unknown
The period of time before the end of the day must be 15 minutes or greater. medium
unknown
SRG-OS-000077-GPOS-00045 1x unknown
The password history must be configured to 24 passwords remembered. medium
unknown

Thanks for your help

**Comment by jan-cerny** [comment]
Hi @Albaheja,

The problem is that the Windows support is only experimental and we're missing many probes implemented. We will be happy if anybody would like to develop the missing Windows probes.

**Comment by Albaheja** [comment]
@ jan-cerny thank you for your help

**Comment by Albaheja** [comment]
Hi jan-cerny,

Can you tell me exactly what is missing for OpenSCAP to work well on Windows and if you have an idea of the development effort that it takes. I will not want to start something without being able to finish it.

And please, if you have any references to advise me

**Comment by redhatrises** [comment]
@Albaheja basically the probes from https://github.com/OVAL-Community/OVAL/blob/master/oval-specifications/oval-windows-extension-specification.docx that are not already in https://github.com/OpenSCAP/openscap/tree/maint-1.3/src/OVAL/probes/windows need to be coded and added.

**Comment by Albaheja** [comment]
very well, thanks for the information.
