### ISSUE TITLE
Error- Image is not based on RHEL

### ISSUE THREAD

**Issue by Swatikp** [OpenSCAP/openscap#1318]
#### Description of Problem:
I have a RHEL machine (7.5) on which I have pulled some Debian docker images. When I run the below command to scan debian image:
`oscap-docker image-cve <debian-image-name>`
I get below error:

```
E: probe_rpmverifyfile: RPM: Unable to open /usr/lib/rpm/rpmrc for reading: No such file or directory.

error: Unable to open /usr/lib/rpm/rpmrc for reading: No such file or directory.
E: probe_rpminfo: RPM: Unable to open /usr/lib/rpm/rpmrc for reading: No such file or directory.

error: Unable to open /usr/lib/rpm/rpmrc for reading: No such file or directory.

E: probe_rpmverifyfile: RPM: Unable to open /usr/lib/rpm/rpmrc for reading: No such file or directory.

error: Unable to open /usr/lib/rpm/rpmrc for reading: No such file or directory.

E: probe_rpminfo: RPM: Unable to open /usr/lib/rpm/rpmrc for reading: No such file or directory.

error: Unable to open /usr/lib/rpm/rpmrc for reading: No such file or directory.

registration-processor-packet-generator-service:0.9.8.1067 is not based on RHEL

```
But I have read in other [issues](https://github.com/OpenSCAP/openscap/issues/749) that it is possible with oscap-docker but not able to get the desired result.

**My OpenSCAP command line tool (oscap) 1.2.17**

#### Operating System & Version:
Operating system is RHEL version 7.5

#### Steps to Reproduce:

`oscap-docker image-cve <debian-image-name>`

#### Actual Results:
```
E: probe_rpmverifyfile: RPM: Unable to open /usr/lib/rpm/rpmrc for reading: No such file or directory.

error: Unable to open /usr/lib/rpm/rpmrc for reading: No such file or directory.
E: probe_rpminfo: RPM: Unable to open /usr/lib/rpm/rpmrc for reading: No such file or directory.

error: Unable to open /usr/lib/rpm/rpmrc for reading: No such file or directory.

E: probe_rpmverifyfile: RPM: Unable to open /usr/lib/rpm/rpmrc for reading: No such file or directory.

error: Unable to open /usr/lib/rpm/rpmrc for reading: No such file or directory.

E: probe_rpminfo: RPM: Unable to open /usr/lib/rpm/rpmrc for reading: No such file or directory.

error: Unable to open /usr/lib/rpm/rpmrc for reading: No such file or directory.

registration-processor-packet-generator-service:0.9.8.1067 is not based on RHEL

```

#### Expected Results:
Should give scan result

**Comment by jan-cerny** [comment]
Scanning Debian images is not supported at the moment.

First problem is the `image-cve` module should automatically detect the type of the operating system in the container and download the right list of the packages automatically, however it works only for RHEL guests, so you probably need to do this manually:
Download the XML for your version of Debian from https://www.debian.org/security/oval/ and use it with docker:
`oscap-docker image <image-name> oval eval --report report.html <oval-definition-xml>`

Second problem is that the OpenSCAP shipped in RHEL 7 doesn't contain "dpkg" probe which means it cannot analyze the dpkg database. But we have this probe in upstream, so you can try to build OpenSCAP from source.

**Comment by Swatikp** [comment]
Hi Thanks for the information @jan-cerny, It worked with above command but in the report velnerability results are unknown, may be because of second problem you told. 
Is there any documentation for second problem that I can follow, or can you provide the steps to make it work for RHEL 7.5

**Comment by evgenyz** [comment]
I think that regarding the second problem there is another culprit: the dpkg probe is not capable of doing the offline mode scan (which is what oscap-docker does). See #736, #1365.

**Comment by evgenyz** [comment]
PR #1387 is a part of 1.3.2 release. Offline mode is now implemented in dpkginfo probe. Please, open a new bug should there be any problems.

Also, as of now, we are not planning to release 1.3.2 for RHEL7.
