### ISSUE TITLE
Console output of check with multi-check="true" is confusing

### ISSUE THREAD

**Issue by yuumasato** [OpenSCAP/openscap#1320]
#### Description of Problem:

When OpenSCAP is evaluating a rule whose check is `multi-check="true"`, the console output is confusing.

#### OpenSCAP Version:
OpenSCAP 1.2.17
Very likely reproducible in OpenSCAP 1.3 too

#### Steps to Reproduce:

1. Use Datastream linked below
2. oscap xccdf eval --profile pci-dss --fetch-remote-resources --results results.xml --report report.html ./ssg-rhel7-ds-1.2-catalog-component.xml
3. There will be multiple reports for rule `security_patches_up_to_date`.
4. In `results.xml` file it is possible to see that each XCCDF result entry is for a different OVAL definition.

#### Actual Results:
```
Title   Disable Prelinking
Rule    xccdf_org.ssgproject.content_rule_disable_prelink
Ident   CCE-27078-5
Result  pass

Title   Ensure Software Patches Installed
Rule    xccdf_org.ssgproject.content_rule_security_patches_up_to_date
Ident   CCE-26895-3
Result  fail

Title   Ensure Software Patches Installed
Rule    xccdf_org.ssgproject.content_rule_security_patches_up_to_date
Ident   CCE-26895-3
Result  pass

Title   Ensure Software Patches Installed
Rule    xccdf_org.ssgproject.content_rule_security_patches_up_to_date
Ident   CCE-26895-3
Result  pass

Title   Ensure Software Patches Installed
Rule    xccdf_org.ssgproject.content_rule_security_patches_up_to_date
Ident   CCE-26895-3
Result  fail
```

#### Expected Results:
It is somehow clear from console output that each result for `security_patches_up_to_date` is about a different CVE.

#### Additional Information / Debugging Steps:
RHEL7 DataStream SCAP1.2 with `multi-check="true"` attribute in Rule `security_patches_up_to_date`: https://fedorapeople.org/~wsato/DS/ssg-rhel7-ds-1.2-multi-check.xml

**Comment by jan-cerny** [comment]
Also reported in https://bugzilla.redhat.com/show_bug.cgi?id=1771438
