### ISSUE TITLE
Cmake cannot find vcpkg PTHREADS_WIN32 Lib

### ISSUE THREAD

**Issue by vivekhegde7** [OpenSCAP/openscap#1321]
#### Steps to Reproduce:

1. C:\devel\openscap\build>cmake -D ENABLE_PYTHON3=FALSE -D CMAKE_TOOLCHAIN_FILE=c:
/devel/vcpkg/scripts/buildsystems/vcpkg.cmake ..
2. 
3. 

#### Actual Results: CMake Error at C:/Program Files/CMake/share/cmake-3.14/Modules/FindPackageHandle
StandardArgs.cmake:137 (message):
  Could NOT find Threads (missing: THREADS_PTHREADS_WIN32_LIBRARY)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.
cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindThreads.cmake:232 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  C:/devel/vcpkg/scripts/buildsystems/vcpkg.cmake:234 (_find_package)
  CMakeLists.txt:145 (find_package)

**Comment by NancyLi1013** [comment]
The same issue.
