### ISSUE TITLE
oscap-docker: command not found

### ISSUE THREAD

**Issue by notquitedilbert** [OpenSCAP/openscap#1328]
#### Description of Problem:
I'm trying to run oscap-docker on an aws ec2 instance so that I can scan other images

I'm using the AWS ami for RHEL8 (HVM) and following the instructions here - https://www.open-scap.org/resources/documentation/security-compliance-of-rhel7-docker-containers/

However I can only get as far as step 5.1 as the command ` oscap-docker container-cve our-rhel7-container ` fails with - `-bash: oscap-docker: command not found`

I've checked the open/closed issues but I can't see any other issues like this.

#### OpenSCAP Version:
Oscap -V gives version as 1.3.0
No trace of oscap-docker

#### Operating System & Version:
RHEL8

#### Steps to Reproduce:

1. create ec2 instance using default aws RHEL8 image
2. ssh to instance
3. install software as per instructions
4. run command `oscap-docker container-cve our-rhel7-container`

#### Actual Results:

 `-bash: oscap-docker: command not found`
#### Expected Results:

Not sure -but not that error

#### Additional Information / Debugging Steps:

some of the install instruction (ie. docker-registry) don't work for the aws image, but the essential bits install without any errors

**Comment by redhatrises** [comment]
@notquitedilbert the `openscap-containers` package isn't available right now in RHEL8.

**Comment by shawndwells** [comment]
On 5/16/19 11:13 AM, Gabe Alford wrote:
> @notquitedilbert <https://github.com/notquitedilbert> the 
> |openscap-containers| package isn't available right now in RHEL8.


While oscap-docker doesn't exist, are there any other tools (e.g. 
specific to podman) that could be tested?

**Comment by matusmarhefka** [comment]
@notquitedilbert Hello, you can try to compile openscap from `maint-1.3` branch and test the https://github.com/OpenSCAP/openscap/blob/maint-1.3/utils/oscap-podman script, but expect issues.

**Comment by evgenyz** [comment]
1.3.2-4 release will provide `oscap-podman` when it will be released.
