### ISSUE TITLE
SELinux probes do not correctly check if SELinux is enabled when scanning in offline mode

### ISSUE THREAD

**Issue by matusmarhefka** [OpenSCAP/openscap#1332]
#### Description of Problem:
The https://github.com/OpenSCAP/openscap/blob/maint-1.2/src/OVAL/probes/unix/linux/selinuxsecuritycontext.c#L332 probe is using function `is_selinux_enabled()` when checking if SELinux is enabled. This function does not have a capability to check SELinux status of the mounted filesystem as it only looks at the status of SELinux of the host machine (the machine which runs the scan). 

When we used `chroot()` approach this was not a problem, but now it became an issue as we started to use `PROBE_OFFLINE_OWN` and path prefixes. Therefore, to support offline scan properly, we either need to:
* do what `is_selinux_enabled()` function does but against prefixed file paths,
* or switch back to `chroot()` approach (SELinux probes will not be used for container scanning as SELinux is not namespaced and it does not run in containers anyway).

Furthermore, the https://github.com/OpenSCAP/openscap/blob/maint-1.2/src/OVAL/probes/unix/linux/selinuxboolean.c probe does not support offline scan at all (it does not specify the `probe_offline_mode_supported()` function).

#### OpenSCAP Version:
all, including all branches in the upstream

**Comment by evgenyz** [comment]
The is_selinux_enabled function is basically `return (selinux_mnt && has_selinux_config);`. And this global variable `selinux_mnt` is defined in `init_selinuxmnt()`, which actually goes through entries in */proc/mounts* and looks for selinuxfs.

In which scenario this function was working properly under `chroot()` call?
