### ISSUE TITLE
The application was  unable to start correctly (0xc000007b). 

### ISSUE THREAD

**Issue by SecuSolve** [OpenSCAP/openscap#1335]
After running the oscap executable the following error message will apear:

The application was  unable to start correctly (0xc000007b). 
Click OK to close the application.

#### Description of Problem:
The vcruntime140.dll is a x64 dll. After replacing it with a x86 version the program will run as normal.

#### OpenSCAP Version:
1.3.0

#### Operating System & Version:
Windows 10 or Windows Server 2016 on Hyper-V

#### Steps to Reproduce:

1. Just run the oscap executable.

**Comment by Harvester57** [comment]
I confirm, I had the same problem with v1.3.1 this morning. Replacing the DLL did the trick.

**Comment by Harvester57** [comment]
Ping @jan-cerny

**Comment by evgenyz** [comment]
Duplicate of #1175?
