### ISSUE TITLE
OVAL

### ISSUE THREAD

**Issue by vivekhegde7** [OpenSCAP/openscap#1339]
#### Steps to Reproduce:

1. C:\Debug>oscap xccdf eval --results test.xml --report test.html C:\Debug\U_MS_Wi
ndows_2012_and_2012_R2_DC_V2R16_STIG_SCAP_1-2_Benchmark.xml
2. 
3.

**Comment by vivekhegde7** [comment]
Can I have any particular link to get latest supporting OVAL definition for Windows 2012.

**Comment by Memnarch** [comment]
"OVAL object not supported"
Which object in particular?
The warning should not cause any issues.

**Comment by evgenyz** [comment]
List of probes (OVAL objects) that are supported by the scanner `oscap --version`. Please. add more information about the probe in question (preferably with exemplary datastream) before reopening this bug.
