### ISSUE TITLE
OS X planned?

### ISSUE THREAD

**Issue by GETandSELECT** [OpenSCAP/openscap#135]
Is there a an OS X port planned? Roadmap?

**Comment by mpreisler** [comment]
OpenSCAP `master` branch and SCAP Workbench already work on *OS X* and *Windows*.

Check out http://martin.preisler.me/2015/03/scap-workbench-1-1-0/

http://martin.preisler.me/wp-content/uploads/2015/03/sw-1.1.0_3.png

However, we do not have any *OS X* or *Darwin* -specific OVAL tests implemented. Contributions greatly appreciated.
