### ISSUE TITLE
Oscap-vm giving all unknowns on ubuntu-16.04 virtual machine image

### ISSUE THREAD

**Issue by abhinavkumar311997** [OpenSCAP/openscap#1365]
#### Description of Problem: 
Running offline scan using oscap-vm on ubuntu-16.04 virtual machine image evaluates all the oval definitions as unknown.

#### OpenSCAP Version:
oscap -V gives 1.3.2

#### Operating System & Version:
CentOS Linux 7

#### Steps to Reproduce:

1.  Downloaded the ubuntu 16.04 vm image:
     https://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-disk1.img
2. Downloaded the oval definitions xml file:
     https://people.canonical.com/~ubuntu-security/oval/com.ubuntu.xenial.cve.oval.xml
3. Ran oscap-vm on it.
    # oscap-vm image xenial-server-cloudimg-amd64-disk1.img oval eval --report report.html com.ubuntu.xenial.cve.oval.xml

#### Actual Results:
The definition for checking operating system is ubuntu 16.04 evaluates to true but all the other definitions evaluates to unknown.

#### Expected Results:
Should have evaluated definitions to either true or false- depending on whether a vulnerability was present or not. 

#### Additional Information / Debugging Steps:
On terminal I get messages like:

W: oscap:     OVAL object not supported.
Definition oval:com.ubuntu.xenial:def:200851440000000: unknown
Definition oval:com.ubuntu.xenial:def:200843920000000: unknown
Definition oval:com.ubuntu.xenial:def:200767610000000: unknown
Definition oval:com.ubuntu.xenial:def:200767520000000: unknown
Definition oval:com.ubuntu.xenial:def:200767180000000: unknown
W: oscap:     OVAL object not supported.
Definition oval:com.ubuntu.xenial:def:200751090000000: unknown
Definition oval:com.ubuntu.xenial:def:200737320000000: unknown
Definition oval:com.ubuntu.xenial:def:200719230000000: unknown
Definition oval:com.ubuntu.xenial:def:200713290000000: unknown
Definition oval:com.ubuntu.xenial:def:200706670000000: unknown

and then definitions evaluate to unknown except for that single definitions mentioned above.

**Comment by abhinavkumar311997** [comment]
I went through the supported OVAL objects after installing by following the developer docs.

environmentvariable            
environmentvariable58       
family                                   
filehash                                
filehash58                  
system_info                 
textfilecontent             
variable                
xmlfilecontent           
iflisteners                
inetlisteningservers         
partition                   
rpminfo                     
rpmverify                    
rpmverifyfile               
rpmverifypackage            
selinuxboolean             
selinuxsecuritycontext       
systemdunitdependency        
systemdunitproperty        
dnscache                 
file                         
gconf                  
interface           
password                  
process                      
process58                    
routingtable                
runlevel                     
shadow                       
symlink                      
sysctl                       
uname                       
xinetd       

It is missing the dpkg info probe, so even the live scans(installing openscap inside VM) do not work.

Am I missing something in the installation process?

**Comment by evgenyz** [comment]
The problem is basically the same as in #736. The reason is that dpkg probe does not support "offline" mode yet.

**Comment by evgenyz** [comment]
PR #1387 is a part of 1.3.2 release. Offline mode is implemented now in `dpkginfo` probe. Please, open a new bug should there be any problems.
