### ISSUE TITLE
dpkginfo_free_reply should return NULL

### ISSUE THREAD

**Issue by jobenye** [OpenSCAP/openscap#1367]
- Is this an issue with SCAP Workbench?
    - don't know
- Is this an issue with SCAP Security Guide (i.e., related to the content of scans, not the scanner proper)?
    - don't know
- Is this an issue during the OS installation process?
    - don't know

Thanks!

#### Description of Problem:
When run `oscap oval collect --id ID OVAL.XML`, prog will crash. By debugging, I found this function messed the caller's stack because it doesn't return value as its function signature declared.

#### OpenSCAP Version:
git clone in 6/20/2019

#### Steps to Reproduce:

1. oscap oval collect --id ID OVAL.XML
   where id is oval:com.ubuntu.disco:obj:2017111090000000
2.

#### Actual Results:
crash

#### Expected Results:
not crash

#### Additional Information / Debugging Steps:
n/a

**Comment by evgenyz** [comment]
The prototype and the implementation are defined as `void * dpkginfo_free_reply(struct dpkginfo_reply_t *reply)` but there is no return in the body.

The only user of the function `dpkginfo_probe.c` does not expect anything to be returned.

Copy/paste bug with dangling `*`?
