### ISSUE TITLE
Request: Build for Arch linux

### ISSUE THREAD

**Issue by vdun** [OpenSCAP/openscap#1374]

**Comment by evgenyz** [comment]
There is an AUR package https://aur.archlinux.org/packages/openscap/, a bit outdated (1.2) though.
Do you have any particular problem with this package?

**Comment by redhatrises** [comment]
@vdun we don't do Arch Linux builds. I would recommend getting in touch with the original submitter, or you might have to become the new submitter for Arch Linux.

**Comment by evgenyz** [comment]
Here is the package for 1.3.2: https://github.com/openprivacy/archlinux-openscap
