### ISSUE TITLE
Empty namespace in XML file causes oscap crash

### ISSUE THREAD

**Issue by nrathaus** [OpenSCAP/openscap#1391]
#### Description of Problem:
Empty namespace causes a crash at oval_sysModel.c, I added a debug line just before to show:
```
[../../../src/OVAL/oval_sysModel.c:249] namespace: (null), OVAL_SYSCHAR_NAMESPACE: http://oval.mitre.org/XMLSchema/oval-system-characteristics-5
```

It appears to happen when namespace variable is NULL (i.e. it wasn't defined inside the XML file)

The crash will actually occur on:
```
int is_ovalsys = strcmp((const char *)OVAL_SYSCHAR_NAMESPACE, namespace) == 0;
```

#### OpenSCAP Version:
1.2.16 (as provided by Debian)

#### Operating System & Version:
Debian 10 (Buster)

#### Steps to Reproduce:

I am unable to reduce my XML file to a minimal case as the crash doesn't tell me where (what line) in the XML it triggered this crash, I can provide more information if some guidance is provided regarding minimizing the XML

```
oscap oval analyse --result result file.xml system-characteristics.xml
```

#### Actual Results:
Crash of oscap (Segmentation fault)

#### Expected Results:
XML being processed (i.e. ignoring lack of namespace) or hard exit

**Comment by nrathaus** [comment]
It appears the crash is not related to the namespace directly, simply having this:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<!-- Crash -->
```

Before the:
```xml
<oval_system_characteristics
```

Will cause a crash

**Comment by redhatrises** [comment]
@nrathaus can you provide the full XML file for testing?

**Comment by nrathaus** [comment]
@redhatrises 

Any XML you take that has 
`<!-- Crash -->`

Just after the `<?xml>`  tag would trigger the crash - at least for me

Aren't you seeing the same outcome?

**Comment by redhatrises** [comment]
> @redhatrises
> 
> Any XML you take that has
> `<!-- Crash -->`
> 
> Just after the `<?xml>` tag would trigger the crash - at least for me
> 
> Aren't you seeing the same outcome?

Sorry. I didn't pay attention that you were using `analyse`. Yes, I am reproducing it. Definitely a bug as I believe the XML specification allows for a comment after an `<xml />` declaration.
