### ISSUE TITLE
"Obtrusive data from probe!" error on every xml with regular expressions in Windows registry

### ISSUE THREAD

**Issue by DenisNovac** [OpenSCAP/openscap#1394]
#### Description of Problem:
I had package of xml-files written for OVALdi version 5.10. I want to switch to OpenSCAP since it still in development and supports OVAL Language updates. But most of my files does not work. I get the "Obtrusive data from probe" error:

> PS C:\Users\dyablochkin\Documents\dev\oval\wincc> oscap oval eval --report report.html .\wincc_cve_2019_6568.xml
> W: C:\Program Files (x86)\OpenSCAP 1.3.0\oscap.exe:     Obtrusive data from probe!

It is just a warning, but it freezes the process. Seems like it happens when i use regular expressions in registry_object for Windows.

Works great:
`<key>SOFTWARE\WOW6432Node\SIMENS\Automation\_InstalledSW\HMIRTM_V11\EditionMain</key>`

Obtrusive data:
`<key operation="pattern match">^SOFTWARE\\WOW6432Node\\SIMENS\\Automation\\_InstalledSW\\HMIRTM_V\d*\\EditionMain</key>`

From a verbose-log-file i can tell that oscap doing .* check, not my mask. There is every registry branch in output from HKLM hive:

> [C:\Program Files (x86)\OpenSCAP 1.3.0\oscap.exe(6704):unknown(2ba0):c:\projects\openscap\src\oval\probes\windows\registry_probe.c:446:registry_recurse_down]
> D: C:\Program Files (x86)\OpenSCAP 1.3.0\oscap.exe:     Can't open registry key 'DRIVERS\DriverDatabase\DriverPackages\wnetvsc.inf_amd64_86f2f8310179e55e\Configurations\netvsc_Device\Properties': RegOpenKeyExW error: Отказано в доступе.
> 
>  [C:\Program Files (x86)\OpenSCAP 1.3.0\oscap.exe(6704):unknown(2ba0):c:\projects\openscap\src\oval\probes\windows\registry_probe.c:446:registry_recurse_down]
> D: C:\Program Files (x86)\OpenSCAP 1.3.0\oscap.exe:     Can't open registry key 'SAM\SAM': RegOpenKeyExW error: Отказано в доступе.
> 
>  [C:\Program Files (x86)\OpenSCAP 1.3.0\oscap.exe(6704):unknown(2ba0):c:\projects\openscap\src\oval\probes\windows\registry_probe.c:446:registry_recurse_down]
> D: C:\Program Files (x86)\OpenSCAP 1.3.0\oscap.exe:     Can't open registry key 'SECURITY': RegOpenKeyExW error: Отказано в доступе.
> 
>  [C:\Program Files (x86)\OpenSCAP 1.3.0\oscap.exe(6704):unknown(2ba0):c:\projects\openscap\src\oval\probes\windows\registry_probe.c:446:registry_recurse_down]
> D: C:\Program Files (x86)\OpenSCAP 1.3.0\oscap.exe:     Can't open registry key 'SOFTWARE\Logishrd\DownloadAssistant\046d_c52b_4003': RegOpenKeyExW error: Отказано в доступе.

#### OpenSCAP Version:
OpenSCAP command line tool (oscap) 1.3.0

#### Operating System & Version:
Windows 10 Enterprise

#### Steps to Reproduce:
Write regular expression in registry_object.

**Comment by redhatrises** [comment]
@DenisNovac do you have the `recurse_down` behavior set?

**Comment by DenisNovac** [comment]
@redhatrises, do you mean recuse_direction="down"? I do not have it since i use regular expressions only to deal with keys like SOMETHING_VXXX where XXX - is a number. I thought that recurse_direction and max_depth are used for searching for something in several places of registry (like check all folders but do not go in sub-folders).
And i tried to add this:
`<behaviors recurse_direction="down"/>`
And this:
`<behaviors recurse_direction="down" max_depth="-1"/>`
And this:
`<behaviors recurse_direction="down" max_depth="1"/>`
And nothing works, still get "Obtrusive data from probe!" error.

**Comment by redhatrises** [comment]
@DenisNovac Can you actually provide the XML file or at least the registry_test, registry_object and registry_state?

**Comment by DenisNovac** [comment]
@redhatrises sure. Here it is.
[wincc_cve_2019_6575.zip](https://github.com/OpenSCAP/openscap/files/3528800/wincc_cve_2019_6575.zip)

**Comment by redhatrises** [comment]
Looks like the regex is working... the error appears to be with the use of <set />. It is a non-fatal error and just a warning. https://ovalproject.github.io/getting-started/tutorial should give a passing example of using <set/> with using registry_object.

**Comment by DenisNovac** [comment]
@redhatrises thank you. I tried it and it really worked. But it takes A LOT of time since it searches in wrong folders. Here is the example for regex:

`^SOFTWARE\\WOW6432Node\\SIEMENS\\Automation\\_InstalledSW\\HMIRTM_V\d*\\EditionMain$`
>  [C:\Program Files (x86)\OpenSCAP 1.3.0\oscap.exe(9664):unknown(1d88):c:\projects\openscap\src\oval\probes\windows\registry_probe.c:446:registry_recurse_down]
> D: C:\Program Files (x86)\OpenSCAP 1.3.0\oscap.exe:     Can't open registry key 'DRIVERS\DriverDatabase\DriverPackages\usbvideo.inf_amd64_470f936ab85dc0f2\Configurations\USBVideo.NT\Properties': RegOpenKeyExW error: Отказано в доступе.
> 
>  [C:\Program Files (x86)\OpenSCAP 1.3.0\oscap.exe(9664):unknown(1d88):c:\projects\openscap\src\oval\probes\windows\registry_probe.c:446:registry_recurse_down]
> D: C:\Program Files (x86)\OpenSCAP 1.3.0\oscap.exe:     Can't open registry key 'SAM\SAM': RegOpenKeyExW error: Отказано в доступе.
> 
>  [C:\Program Files (x86)\OpenSCAP 1.3.0\oscap.exe(9664):unknown(1d88):c:\projects\openscap\src\oval\probes\windows\registry_probe.c:446:registry_recurse_down]
> D: C:\Program Files (x86)\OpenSCAP 1.3.0\oscap.exe:     Can't open registry key 'SECURITY': RegOpenKeyExW error: Отказано в доступе.
> 
>  [C:\Program Files (x86)\OpenSCAP 1.3.0\oscap.exe(9664):unknown(1d88):c:\projects\openscap\src\oval\probes\windows\registry_probe.c:446:registry_recurse_down]
> D: C:\Program Files (x86)\OpenSCAP 1.3.0\oscap.exe:     Can't open registry key 'SOFTWARE\Logishrd\DownloadAssistant\046d_c52b_4003': RegOpenKeyExW error: Отказано в доступе.
> 
>  [C:\Program Files (x86)\OpenSCAP 1.3.0\oscap.exe(9664):unknown(1d88):c:\projects\openscap\src\oval\probes\windows\registry_probe.c:446:registry_recurse_down]
> D: C:\Program Files (x86)\OpenSCAP 1.3.0\oscap.exe:     Can't open registry key 'SOFTWARE\Microsoft\AllUserInstallAgent': RegOpenKeyExW error: Отказано в доступе.
> 
> W: C:\Program Files (x86)\OpenSCAP 1.3.0\oscap.exe:     Obtrusive data from probe! [C:\Program Files (x86)\OpenSCAP 1.3.0\oscap.exe(7980):unknown(70c):c:\projects\openscap\src\oval\oval_probe_ext.c:1001:oval_probe_ext_eval]
>  [C:\Program Files (x86)\OpenSCAP 1.3.0\oscap.exe(7980):unknown(2394):c:\projects\openscap\src\oval\probes\windows\registry_probe.c:446:registry_recurse_down]
> D: C:\Program Files (x86)\OpenSCAP 1.3.0\oscap.exe:     Can't open registry key 'SYSTEM\ControlSet001\Control\DeviceClasses\{53f5630d-b6bf-11d0-94f2-00a0c91efb8b}\##?#STORAGE#Volume#_??_USBSTOR#Disk&Ven_&Prod_USB_DISK_2.0&Rev_PMAP#900087C66E192F13&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}#{53f5630d-b6bf-11d0-94f2-00a0c91efb8b}\#\Properties': RegOpenKeyExW error: Отказано в доступе.


I use ^ as it shown in tutorial, it should prevent interpreter from walking through all registry. And for OVALdi that was it. But here it is walks through all folders in HKLM hive and even goes inside (DRIVERS\DriverDatabase\DriverPackages) which will never be the right answer for regex since the line already not starts with SOFTWARE.
