### ISSUE TITLE
oscap checks on registry fails for case sensitivity 

### ISSUE THREAD

**Issue by treyperrone** [OpenSCAP/openscap#1395]
#### Description of Problem:
Running DISA provided XML for STIG against Windows Server 2016 fails on several registry keys due to case-sensitivity. 

Reg key names are not sensitive, thus the scanner should likely account for this particular scenario.

#### OpenSCAP Version:
1.3.0

#### Operating System & Version:
Win10 pro x64 and Win2016 std x64

#### Steps to Reproduce:

1. spin up win10 or server 2016
2. Verify a key such as HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa!everyoneincludesanonymous which is lowercase by default OOBE from Microsoft
3. Ensure data is set to decimal 0 which should pass evaluation
4. & 'C:\Program Files (x86)\OpenSCAP 1.3.0\oscap.exe' xccdf eval --rule xccdf_mil.disa.stig_rule_SV-88337r1_rule E:\win2016\U_MS_Windows_Server_2016_V1R10_STIG_SCAP_1-2_Benchmark.xml
4. `Title   Windows Server 2016 must be configured to prevent anonymous users from having the same permissions as the Everyo
ne group.
Rule    xccdf_mil.disa.stig_rule_SV-88337r1_rule
Ident   CCE-46412-3
Ident   CCI-000366
W: C:\Program Files (x86)\OpenSCAP 1.3.0\oscap.exe:     OVAL object not supported.
W: C:\Program Files (x86)\OpenSCAP 1.3.0\oscap.exe:     OVAL object not supported.
W: C:\Program Files (x86)\OpenSCAP 1.3.0\oscap.exe:     OVAL object not supported.
W: C:\Program Files (x86)\OpenSCAP 1.3.0\oscap.exe:     OVAL object not supported.
W: C:\Program Files (x86)\OpenSCAP 1.3.0\oscap.exe:     OVAL object not supported.
W: C:\Program Files (x86)\OpenSCAP 1.3.0\oscap.exe:     OVAL object not supported.
W: C:\Program Files (x86)\OpenSCAP 1.3.0\oscap.exe:     OVAL object not supported.
W: C:\Program Files (x86)\OpenSCAP 1.3.0\oscap.exe:     OVAL object not supported.
W: C:\Program Files (x86)\OpenSCAP 1.3.0\oscap.exe:     OVAL object not supported.
W: C:\Program Files (x86)\OpenSCAP 1.3.0\oscap.exe:     OVAL object not supported.
W: C:\Program Files (x86)\OpenSCAP 1.3.0\oscap.exe:     OVAL object not supported.
Result  fail`
5. Rename the key to alternate name, then rename to proper case defined in STIG xml (you cannot rename the key with proper case, regedit see the key as same and errors)
6. `Title   Windows Server 2016 must be configured to prevent anonymous users from having the same permissions as the Everyo
ne group.
Rule    xccdf_mil.disa.stig_rule_SV-88337r1_rule
Ident   CCE-46412-3
Ident   CCI-000366
W: C:\Program Files (x86)\OpenSCAP 1.3.0\oscap.exe:     OVAL object not supported.
W: C:\Program Files (x86)\OpenSCAP 1.3.0\oscap.exe:     OVAL object not supported.
W: C:\Program Files (x86)\OpenSCAP 1.3.0\oscap.exe:     OVAL object not supported.
W: C:\Program Files (x86)\OpenSCAP 1.3.0\oscap.exe:     OVAL object not supported.
W: C:\Program Files (x86)\OpenSCAP 1.3.0\oscap.exe:     OVAL object not supported.
W: C:\Program Files (x86)\OpenSCAP 1.3.0\oscap.exe:     OVAL object not supported.
W: C:\Program Files (x86)\OpenSCAP 1.3.0\oscap.exe:     OVAL object not supported.
W: C:\Program Files (x86)\OpenSCAP 1.3.0\oscap.exe:     OVAL object not supported.
W: C:\Program Files (x86)\OpenSCAP 1.3.0\oscap.exe:     OVAL object not supported.
W: C:\Program Files (x86)\OpenSCAP 1.3.0\oscap.exe:     OVAL object not supported.
W: C:\Program Files (x86)\OpenSCAP 1.3.0\oscap.exe:     OVAL object not supported.
Result  pass`

#### Actual Results:
oscap.exe fails the test because case

#### Expected Results:
oscap should not match case for key names, unless this is something that is defined in the XML itself in which case a submission to DISA might takes years to fix.

**Comment by redhatrises** [comment]
@treyperrone looks like either:

1. There is a bug in the OVAL spec that needs to be updated to handle case insensitivity https://oval-community-guidelines.readthedocs.io/en/latest/oval-schema-documentation/windows-definitions-schema.html?highlight=registry_object#registry-object
2. The XML file will have to be updated to use case insensitive regex using ```(?i)```

**Comment by treyperrone** [comment]
fair point, the file should handle this. guess need to tell disa to fix their files. have a feeling their feedback on website will not be easy like a github issue here...
