### ISSUE TITLE
Does openscap processes Cisco IOS OVAL schemes?

### ISSUE THREAD

**Issue by DenisNovac** [OpenSCAP/openscap#1399]
Hi. It seems that oscap-ssh does not support Cisco devices (it tries to create folders like it is on Linux after connection). But does OpenSCAP processes oval definitions (i see the schemes for ios and iosxe in OpenSCAP OVAL folder) for it at all? What if i find a way to give oscap-ssh right config from Cisco IOS device (like for command "show running-config")?

**Comment by jan-cerny** [comment]
Hi @DenisNovac,

OpenSCAP can't process CISCO definitions, they won't be evaluated.

The problem with `oscap-ssh` is that it requires OpenSCAP to be installed on the target, and I think there is no build of OpenSCAP for CISCO.

I don't understand your point about giving `oscap-ssh` "right config from Cisco IOS device". Could you explain it more?

**Comment by DenisNovac** [comment]
Thank you @jan-cerny. I know that OpenSCAP needs to be installed on target so i wanted to somehow just process the output of the target (like manually write in Cisco console "show running-config" and then put its output in openscap). But it is pointless since there is no interpreter for this definitions at all.
And i wonder is there a list of supported platforms somewhere? I really can not find it...

**Comment by jan-cerny** [comment]
Officially it's only Linux. We have a limited implementation for Windows. I recall in past there were people running it on Solaris and AIX, but I don't know if it's still the case.
