### ISSUE TITLE
debian_evr_string wrong compare operation

### ISSUE THREAD

**Issue by Sep0lkit** [OpenSCAP/openscap#1400]
#### Description of Problem:
i test oscap oval with com.ubuntu.bionic.cve.oval.xml from ubuntu official.

there always be false while the installed dpkg version is less than the version defined in oval.

when i change the state from  3.22.0-1ubuntu0.1  to 0:3.22.0-1ubuntu0.1 (add default epoch 0:). it works.

#### OpenSCAP Version:
1.3.2 

#### Operating System & Version:
ubuntu-bionic

#### Steps to Reproduce:

1.  dpkg installed is  3.22.1-1ubuntu0.1
2. oval define id oval:com.ubuntu.bionic:def:201999370000000 less than 3.22.1-1ubuntu0.1 is vulnerable, I change it to  3.22.2-1ubuntu0.1
3. result always be false.
4. but when i chage 3.22.2-1ubuntu0.1 to 0:3.22.2-1ubuntu0.1 , it works 

i think oscap not handle the empty epoch version.

**Comment by dodys** [comment]
I believe this issue was already fixed since then by both PRs #1662 #1901 
At the time of this bug, openscap still wasn't using the dpkg comparison algorithm.
I believe we can close this one @evgenyz
