### ISSUE TITLE
Pipeline scanning with Github Actions

### ISSUE THREAD

**Issue by hazcod** [OpenSCAP/openscap#1421]
#### Description of Problem:
Github Actions provides a free CI/CD pipeline for open source projects, many of which are container images that can be scanned with openscap for compliance scoring.

#### Steps to Reproduce:

1.  Create a github action (e.g. shell script, docker container)
2.  Build the container image
3.  Scan the container image
4.  Report any compliance failures

#### Actual Results:
I see no relevant example for scanning docker images in a pipeline.

#### Additional Information / Debugging Steps:
e.g. how I scan for vulnerabilities: https://github.com/ironPeakServices/iron-redis/blob/master/.github/workflows/pr.yaml#L44

**Comment by candrews** [comment]
@hazcod I've documented how to accomplish this goal at https://candrews.integralblue.com/2023/09/scap-security-and-compliance-scanning-of-docker-images-in-github-actions-and-gitlab-ci/

I hope that's helpful for you and anyone else who seeks to do the same.
