### ISSUE TITLE
Which compliance standards are supported on OpenSCAP Windows? 

### ISSUE THREAD

**Issue by RedCedarForge** [OpenSCAP/openscap#1425]
Hello everyone.
I'm doing a report on compliance scanning and I can't find anything in the documentation about exactly which compliance standards are currently supported by OpenSCAP on Windows. (Ex. DISA STIG, PCI-DSS, CIS, various NISTs, etc.) 

I'm aware that DISA STIG is available, are there any others currently supported?

**Comment by jan-cerny** [comment]
Hi @RedCedarForge,

There are 2 aspects of compliance standard support: scanner tool (OpenSCAP) and the security policy in SCAP format.

Regarding the scanner tool, OpenSCAP can run on Windows. But it has implemented only a subset of OVAL Windows tests, which means it can evaluate only some of the checks used in the security policies. Specifically, from [OVAL Windows Definitions Schema](https://oval.mitre.org/language/version5.10/ovaldefinition/documentation/windows-definitions-schema.html) we have implemented accesstoken_test, registry_test and wmi57_test. Also, OpenSCAP for Windows is an experimental project. It isn't supported by Red Hat customer support. We don't actively work on Windows version anymore. But we welcome any code contributions.

The second part are the policies in SCAP format. Our other project [ComplianceAsCode](https://github.com/ComplianceAsCode/content/) doesn't contain Windows policies. But you can find SCAP files for various Windows versions in  [NIST National Checklist program](https://nvd.nist.gov/ncp/repository?keyword=Microsoft+Windows&startIndex=0).

**Comment by RedCedarForge** [comment]
@jan-cerny  Thanks!
