### ISSUE TITLE
Some variables for offline scanning are not used in openscap code

### ISSUE THREAD

**Issue by matusmarhefka** [OpenSCAP/openscap#1427]
#### Description of Problem:
I have reviewed openscap C code and most of the variables which are exported in the `oscap-chroot`, `oscap-docker` or `oscap-podman` are not used in any way by the openscap C code. List of such variables:
* `OSCAP_PROBE_OS_NAME`
* `OSCAP_PROBE_OS_VERSION`
* `OSCAP_PROBE_ARCHITECTURE`

The variable `OSCAP_PROBE_RPMDB_PATH` is also a candidate for removal as I cannot find how it is utilized in the C code.

**Comment by jan-cerny** [comment]
Hi, these variables were used in system info probe, but we stopped to use them in https://github.com/OpenSCAP/openscap/pull/559. I think you can remove them.
