### ISSUE TITLE
test_probes_environmentvariable58 broken for unprivileged user with chroot capability.

### ISSUE THREAD

**Issue by matejak** [OpenSCAP/openscap#1429]
If the `oscap` binary has the `cap_sys_chroot` capability, the `test_probes_environmentvariable58` test executed under normal user fails. This is reliably reproducible on Fedora as well as RHELs.
There is this output:

```
129: TEST: test_probes_environmentvariable58                                                                           
129: W: oscap:     Entity has no value!                                                                                
129: E: oscap:     Can't open "/proc/24972/environ": errno=13, Permission denied.
129: W: oscap:     Entity has no value!                                                                                
129: E: oscap:     Can't open "/proc/24972/environ": errno=13, Permission denied.
129: W: oscap:     Entity has no value!                    
129: E: oscap:     Can't open "/proc/24972/environ": errno=13, Permission denied.                                      
129: W: oscap:     Entity has no value!                                                                                
129: E: oscap:     Can't open "/proc/24972/environ": errno=13, Permission denied.
129: W: oscap:     Entity has no value!   
129: E: oscap:     Can't open "/proc/24972/environ": errno=13, Permission denied.                                                                                                                                                             
...
129: W: oscap:     Entity has no value!
129: E: oscap:     Can't open "/proc/24972/environ": errno=13, Permission denied.
129: Definition oval:1:def:1: error
129: Evaluation done.
129: Result of oval:1:def:1 should be TRUE and is ERROR
129: RESULT: FAILED
```

where the offending process (in this case PID 24972) is the actual scan.
If the test suite is run by unprivileged user and `oscap` doesn't have the `cap_sys_chroot` capability, the test outputs all those `W: oscap:     Entity has no value!` warnings, but the test otherwise passes.
The same happens if the test is executed under root.

**Comment by evgenyz** [comment]
Is there any point in scanning own environment?

**Comment by evgenyz** [comment]
The owner of the environ in the process is root:root. No wonder it is not allowed to read it. It is definitely connected to the way how capability-dumb binaries are working. Not sure how to workaround it yet.

**Comment by evgenyz** [comment]
Well, looks like it's a bummer: https://www.spinics.net/lists/linux-fsdevel/msg108657.html

**Comment by matejak** [comment]
Good investigation, we have to address this in the upstream test suite.

**Comment by matejak** [comment]
As @evgenyz has discovered, this is not a bug, but a side-effect of the process security model. The #1428 has worked around this issue in a backward-compatible way, hence I am closing it as resolved.
