### ISSUE TITLE
Incorrect 'ansible_distribution' set in generated playbook

### ISSUE THREAD

**Issue by XanderCrews66** [OpenSCAP/openscap#1445]
### Description of Problem:
Applying a generated playbook from `oscap` on an Amazon Linux 2 server fails on a conditional check. The playbook is trying to match the `ansible_distribution` with `Redhat`,`Centos`, or `yum_config_file.stat.exists`. Ansible sets this this to `Amazon`, and therefore none of the conditions are matched.

#### OpenSCAP Version:
1.2.17

#### Operating System & Version:
Amazon Linux 2 (ami id: ami-7c2bc80d)

#### Steps to Reproduce:

1. Launch and Amazon Linux 2 instance (ami id: ami-7c2bc80d)
2. ssh and install OSCAP and Ansible 
    `sudo yum -y install openscap-scanner scap-security-guide`
   `sudo amazon-linux-extras install ansible2`
2. generate a fix playbook using the Amazon Linux 2 C2S profile
    `oscap xccdf generate fix --fix-type ansible --profile C2S --output amzn2-c2s-profile.yml /usr/share/xml/scap/ssg/content/ssg-amzn2-ds.xml`

3. apply the generated playbook with Ansible
    ` ansible-playbook -i "localhost", --connection=local -b amzn2-c2s-profile.yml`

#### Actual Results:
```
TASK [Security patches are up to date] *********************************************************************************
ok: [localhost]

TASK [Check existence of yum on Fedora] ********************************************************************************
skipping: [localhost]

TASK [Ensure GPG check is globally activated (yum)] ********************************************************************
fatal: [localhost]: FAILED! => {"msg": "The conditional check 'ansible_distribution == \"RedHat\" or ansible_distribution == \"CentOS\" or yum_config_file.stat.exists' failed. The error was: error while evaluating conditional (ansible_distribution == \"RedHat\" or ansible_distribution == \"CentOS\" or yum_config_file.stat.exists): 'dict object' has no attribute 'stat'\n\nThe error appears to be in '/home/ec2-user/amzn2-c2s-profile.yml': line 1299, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Ensure GPG check is globally activated (yum)\n      ^ here\n"}

PLAY RECAP *************************************************************************************************************
localhost                  : ok=70   changed=0    unreachable=0    failed=1    skipped=2    rescued=0    ignored=0
```

#### Expected Results:
All items in the playbook applied successfully 

#### Additional Information / Debugging Steps:
```
ec2-user@ip-172-31-1-226 ~]$ ansible all -i "localhost", --connection=local -m setup | grep '"ansible_distribution"'
"ansible_distribution": "Amazon",
```

As the error message says, the Conditonal is on line 1299 of the generated playbook, with the 'yum_config_file' variable being generated on line 1293. 

I did not test any of the other 'fix' types (e.g. Shell), but a similar situation likely exists.

**Comment by redhatrises** [comment]
@pczinser please contact Amazon to fix this issue. We don't have any sort of C2S for Amazon Linux in our content repos.

**Comment by jan-cerny** [comment]
Yes, there is nothing in OpenSCAP that generates this, it's a bug in SCAP content provided by Amazon.
