### ISSUE TITLE
Virus warning when copying DMG file?

### ISSUE THREAD

**Issue by degthat8412** [OpenSCAP/openscap#1446]
I go this when I tried to move the dmg file I downloaded from your site.   

![image](https://user-images.githubusercontent.com/41908967/71691938-a1132a00-2d76-11ea-94bf-ef57571dcf45.png)

**Comment by redhatrises** [comment]
This looks like a false positive to me. `scap-workbench-1.2.0.dmg` isn't masquerading as an Adobe Flash Installer... and scap-workbench doesn't use Java.

**Comment by evgenyz** [comment]
We use Travis infrastructure to build MacOS packages. There are no other evidences of the fact that build was compromised. For example: https://www.virustotal.com/gui/url/92df561ee62b88f86ad23806ddb4e46627e7b7ff575b4cb821979a75c27e7ef6/detection
