### ISSUE TITLE
OpenSCAP Validation Error

### ISSUE THREAD

**Issue by redhatrises** [OpenSCAP/openscap#1497]
#### Description of Problem:

It seems as OpenSCAP expects a certain order when evaluation `<Rule/>` and `<Group/>` elements. This was quite an unexpected behavior when building content.

Here is the error on content build:

````
File 'build/fedora/xccdf-unlinked-resolved.xml' line 10788: Element '{http://checklists.nist.gov/xccdf/1.1}platform': This element is not expected. 
Expected is one of ( {http://checklists.nist.gov/xccdf/1.1}conflicts, {http://checklists.nist.gov/xccdf/1.1}Value, {http://checklists.nist.gov/xccdf/1.1}Group, {http://checklists.nist.gov/xccdf/1.1}Rule, {http://checklists.nist.gov/xccdf/1.1}signature ).
OpenSCAP Error: Invalid XCCDF Checklist (1.1) content in build/fedora/xccdf-unlinked-resolved.xml. [/builddir/build/BUILD/openscap-1.3.2/src/source/oscap_source.c:346]
````

Had to re-order the elements in [shared_shorthand2xccdf.xslt](https://github.com/ComplianceAsCode/content/blob/master/shared/transforms/shared_shorthand2xccdf.xslt) to pass OpenSCAP validation. See https://github.com/ComplianceAsCode/content/pull/5281/commits/dcb982ce007a0be08c8d2a911c4b90de3abc2ad5 for some of the order changes. Apparently, we have had this problem already.
Can this be fixed? I don't think that ordering of elements matters in the XCCDF spec. If I am wrong, please let me know. It's a big usability problem for anyone that validates SCAP against the spec.

#### OpenSCAP Version:
all

**Comment by jan-cerny** [comment]
The definitions of types for `Rule` and `Group` elements in XCCDF XML schema (XSD retreived from https://csrc.nist.gov/schema/xccdf/1.2/xccdf_1.2.xsd) include their child elements in a `xsd:sequence` element. The `xsd:sequence` element means that child elements can only appear in the given order. So the ordering of the elements matters in this case.

**Comment by redhatrises** [comment]
Thanks @jan-cerny . This was very insightful and very helpful! Much appreciated.
