### ISSUE TITLE
In reports produced as HTML, links opened in new tabs are opened as duplicates

### ISSUE THREAD

**Issue by Ricky-Tigg** [OpenSCAP/openscap#1503]
#### Description of Problem:
In reports produced as HTML –`--report /tmp/report.html `–, links opened in new tabs are opened as duplicates. Though when links are opened in same tab, they are opened as intended as linked pages. 

_Illustration in Firefox:_

![openscap_1:1 3 2_report](https://user-images.githubusercontent.com/26058215/78008227-15df0b80-7348-11ea-8a13-374707666cce.png)

#### OpenSCAP / Operating System Versions:
openscap.x86_64 1:1.3.2-4.fc32 @fedora

**Comment by evgenyz** [comment]
It would be nice if report could open the details window when loaded with like `...report.html#rule-detail-idmXXXXXXXXXXXXXX`.
