### ISSUE TITLE
Getting error while evaluating STIG 

### ISSUE THREAD

**Issue by vivekhegde7** [OpenSCAP/openscap#1504]
#### Steps to Reproduce:

1. oscap xccdf eval --results test.xml --report test.html C:\U_MS_Windows_Server_2019_V1R1_STIG_SCAP_1-2_Benchmark.xml
2. 
3. 

#### Actual Results: OpenSCAP Error: Schema file not found when trying to validate 'C:\U_MS_Windows_Server_2019_V1R1_STIG_SCAP_1-2_Benchmark.xml' [C:\devel\openscap\src\source\validate.c:260]
Invalid SCAP Source Datastream (1.0) content in C:\U_MS_Windows_Server_2019_V1R1_STIG_SCAP_1-2_Benchmark.xml. [C:\devel\openscap\src\source\oscap_source.c:346]
Invalid SCAP Source Datastream (1.0) content in C:\U_MS_Windows_Server_2019_V1R1_STIG_SCAP_1-2_Benchmark.xml [C:\devel\openscap\src\XCCDF\xccdf_session.c:729]

**Comment by evgenyz** [comment]
I wonder where did you get OpenSCAP 1.4.0?

**Comment by yuumasato** [comment]
> I wonder where did you get OpenSCAP 1.4.0?

I think it is from master branch...

**Comment by yuumasato** [comment]
@vivekhegde7 for some reason OpenSCAP doesn't have SCAP 1.0 schemas, try scanning using `--skip-valid`.

A maybe non-safe compliant way is to change `schematron-version="`1.0"` to `1.2`. This made the xml pass the validation for me.

**Comment by vivekhegde7** [comment]
Yes, it is Master branch..
