### ISSUE TITLE
Amazon Linux 2 not considered certified?

### ISSUE THREAD

**Issue by jclark42796** [OpenSCAP/openscap#1509]
#### Description of Problem:
Rule xccdf_org.ssgproject.content_rule_installed_OS_is_certified fails on Amazon Linux 2.

Running:
Title: DISA STIG for Amazon Linux 2
				Id: xccdf_org.ssgproject.content_profile_stig-rhel7-disa

#### OpenSCAP Version:
OpenSCAP command line tool (oscap) 1.2.17

#### Operating System & Version:
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"

#### Steps to Reproduce:

$ oscap xccdf eval --report report.html --profile xccdf_org.ssgproject.content_profile_stig-rhel7-disa --rule xccdf_org.ssgproject.content_rule_installed_OS_is_certified /usr/share/xml/scap/ssg/content/ssg-amzn2-ds.xml
WARNING: This content points out to the remote resources. Use `--fetch-remote-resources' option to download them.
WARNING: Skipping https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL7.xml.bz2 file which is referenced from XCCDF content
Title   The Installed Operating System Is Vendor Supported and Certified
Rule    xccdf_org.ssgproject.content_rule_installed_OS_is_certified
Result  fail

#### Actual Results:
Fail

#### Expected Results:
Pass

**Comment by redhatrises** [comment]
This is expected. There is no STIG for Amazon Linux.

**Comment by jclark42796** [comment]
Thanks for the response.  I guess I misunderstood what was meant by the profile title: "DISA STIG for Amazon Linux 2".

**Comment by redhatrises** [comment]
Yup. The problem with Amazon and CentOS is they sed replace Red Hat Enterprise Linux with their own distro name without verifying and checking that the actual government profile actually is created or exists which leads to inaccurate statements and customer confusion that said product is certified or has gone through the government process to create these profiles.

**Comment by shawndwells** [comment]
Perhaps the check could be broken out?

Amazon Linux is supported by Amazon, but not certified by the US Government.

**Comment by evgenyz** [comment]
Is it actually related to the scanner itself? Shouldn't it be transferred to the CaC project (or reopened there if needed)?

**Comment by jan-cerny** [comment]
@evgenyz yes, this is content issue

**Comment by evgenyz** [comment]
Okay, there is no way of transferring this issue to [CaC](https://github.com/ComplianceAsCode/content/) repo. Please reopen it there if you have additional questions to discuss.
