### ISSUE TITLE
Requested offline mode is not supported by probe_uname

### ISSUE THREAD

**Issue by Gafera** [OpenSCAP/openscap#1510]
Hello, I'm experiencing a problem.

When rotating:

`./oscap-docker image-cve ubuntu --report report.html`

I only get unknown results:

`Definition oval:com.redhat.rhsa:def:20201429: unknown`
`Definition oval:com.redhat.rhsa:def:20201420: unknown`
`Definition oval:com.redhat.rhsa:def:20201406: unknown`
`Definition oval:com.redhat.rhsa:def:20201403: unknown`
`[...]`

In the middle of the analysis I get this:

`W: probe_uname: Requested offline mode is not supported by probe_uname.`

Could you help me solve this problem?

**Comment by jan-cerny** [comment]
@Gafera 
`oscap-docker image-cve` command doesn't work with Ubuntu images. From the output you can see that it tries to apply Red Hat definitions, which aren't applicable on Ubuntu images. However, it shouldn't do that, it should terminate with an error message "image is not based on RHEL". This somehow got broken. I can try to find a workaround. Which version of OpenSCAP do you use? And which operating system do you use?

**Comment by Gafera** [comment]
Hi, @jan-cerny . Alright?
I thank you for your attention.

I am currently using the operating system Ubuntu: 18.04 LTE and the OpenScap at version 1.2.15.
