### ISSUE TITLE
Some DISA-STIG rules are not behaving as expected for Windows

### ISSUE THREAD

**Issue by me-shubh** [OpenSCAP/openscap#1515]
#### Steps to Reproduce:

1. oscap xccdf eval --profile xccdf_mil.disa.stig_profile_MAC-1_Public --results results.xml --skip-valid U_MS_Windows_Server_2019_V1R2_STIG_SCAP_1-2_Benchmark.xml

#### Additional Information / Debugging Steps: While evaluating the file I removed all other rules as I wanted to focus just on 1 rule. I'm adding the result after step 1 that I have mentioned.
[1.txt](https://github.com/OpenSCAP/openscap/files/4508106/1.txt)
I am also attaching the XML file that I am evaluating 
[xml.zip](https://github.com/OpenSCAP/openscap/files/4508193/xml.zip)

**Comment by evgenyz** [comment]
Hey, @me-shubh, thank you for your report.

Could you please also collect verbose logs from the run, like `oscap xccdf eval --verbose DEVEL --profile xccdf_mil.disa.stig_profile_MAC-1_Public --results results.xml --skip-valid U_MS_Windows_Server_2019_V1R2_STIG_SCAP_1-2_Benchmark.xml` (note the **--verbose DEVEL** part)?

**Comment by me-shubh** [comment]
> Hey, @me-shubh, thank you for your report.
> 
> Could you please also collect verbose logs from the run, like `oscap xccdf eval --verbose DEVEL --profile xccdf_mil.disa.stig_profile_MAC-1_Public --results results.xml --skip-valid U_MS_Windows_Server_2019_V1R2_STIG_SCAP_1-2_Benchmark.xml` (note the **--verbose DEVEL** part)?

I executed this command - 
**oscap xccdf eval --verbose DEVEL --verbose-log-file log.txt --profile xccdf_mil.disa.stig_profile_MAC-1_Public --results results.xml --skip-valid U_MS_Windows_Server_2019_V1R2_STIG_SCAP_1-2_Benchmark.xml** 
 and the verbose log file 
[log.txt](https://github.com/OpenSCAP/openscap/files/4510307/log.txt)

**Comment by evgenyz** [comment]
@me-shubh Great! Thank you, I'll look into this.

**Comment by evgenyz** [comment]
There are no apparent error related to `accesstoken_probe`. Can you please add the XCCDF (xml) and HTML (report) results?

Also, are you sure that there are no users on your machine that have rights (backup not in admins group), which would violate the rule in question?

**Comment by me-shubh** [comment]
Yes, I have checked there are no other users on my machine for the stated rule except admin. I will attach the screenshot for it. 
![Screenshot (28)](https://user-images.githubusercontent.com/46965942/80078528-aafeaa00-856c-11ea-97d7-214c53333fdb.png)

The XML file is attached previously in the issue when it was commented.

The report generated : 
[report.txt](https://github.com/OpenSCAP/openscap/files/4521308/report.txt)

And this rule access not only accesstoken but also registry probe also right?

**Comment by evgenyz** [comment]
Mmm, no this rule uses only accesstoken test:
```xml
        <accesstoken_test xmlns="http://oval.mitre.org/XMLSchema/oval-definitions-5#windows" id="oval:mil.disa.stig.windows:tst:123900" version="1" check="all" comment="Back up files and directories - Administrators">
          <object object_ref="oval:mil.disa.stig.windows:obj:123900" />
          <state state_ref="oval:mil.disa.stig.windows:ste:123900" />
        </accesstoken_test>
```

```xml
        <accesstoken_state xmlns="http://oval.mitre.org/XMLSchema/oval-definitions-5#windows" id="oval:mil.disa.stig.windows:ste:123900" version="1" comment="Back up files and directories">
          <sebackupprivilege datatype="boolean" operation="equals">0</sebackupprivilege>
        </accesstoken_state>
```

```xml
        <accesstoken_object xmlns="http://oval.mitre.org/XMLSchema/oval-definitions-5#windows" id="oval:mil.disa.stig.windows:obj:123900" version="1" comment="Filter for Administrators">
          <set xmlns="http://oval.mitre.org/XMLSchema/oval-definitions-5" set_operator="UNION">
            <object_reference>oval:mil.disa.stig.windows:obj:123901</object_reference>
            <filter>oval:mil.disa.stig.windows:ste:123901</filter>
          </set>
        </accesstoken_object>
        <accesstoken_object xmlns="http://oval.mitre.org/XMLSchema/oval-definitions-5#windows" id="oval:mil.disa.stig.windows:obj:123901" version="1" comment="All security principles">
          <security_principle datatype="string" operation="pattern match">.*</security_principle>
        </accesstoken_object>
```

By the way, @jan-cerny and @yuumasato, `Obtrusive data` and set in `accesstoken_object`!

**Comment by evgenyz** [comment]
I guess I know what the problem is. Here is the filter for Administrators group:
```xml
        <accesstoken_state xmlns="http://oval.mitre.org/XMLSchema/oval-definitions-5#windows" id="oval:mil.disa.stig.windows:ste:124001" version="1" comment="Administrators">
          <security_principle datatype="string" operation="equals">Administrators</security_principle>
        </accesstoken_state>
```
Here is the collected entity:

(("windows:accesstoken_item" ":id" "11036431" )
**("security_principle" "BUILTIN\Administrators" )** ("seassignprimarytokenprivilege" #F ) ("seauditprivilege" #F ) ("sebackupprivilege" #T ) ("sechangenotifyprivilege" #T ) ("secreateglobalprivilege" #T ) ("secreatepagefileprivilege" #T ) ("
secreatepermanentprivilege" #F ) ("secreatesymboliclinkprivilege" #T ) ("secreatetokenprivilege" #F ) ("sedebugprivilege" #T ) ("seenabledelegationprivilege" #F ) ("seimpersonateprivilege" #T ) ("seincreasebasepriorityprivilege" #T ) ("se
increasequotaprivilege" #T ) ("seincreaseworkingsetprivilege" #F ) ("seloaddriverprivilege" #T ) ("selockmemoryprivilege" #F ) ("semachineaccountprivilege" #F ) ("semanagevolumeprivilege" #T ) ("seprofilesingleprocessprivilege" #T ) ("ser
elabelprivilege" #F ) ("seremoteshutdownprivilege" #T ) ("serestoreprivilege" #T ) ("sesecurityprivilege" #T ) ("seshutdownprivilege" #T ) ("sesyncagentprivilege" #F ) ("sesystemenvironmentprivilege" #T ) ("sesystemprofileprivilege" #T )
("sesystemtimeprivilege" #T ) ("setakeownershipprivilege" #T ) ("setcbprivilege" #F ) ("setimezoneprivilege" #T ) ("seundockprivilege" #T ) ("seunsolicitedinputprivilege" #F ) ("sebatchlogonright" #T ) ("seinteractivelogonrightsenetworklo
gonright" #F ) ("seremoteinteractivelogonright" #T ) ("seservicelogonright" #F ) ("sedenybatchlogonright" #F ) ("sedenyinteractivelogonright" #F ) ("sedenynetworklogonright" #F ) ("sedenyremoteinteractivelogonright" #F ) ("sedenyservicelo
gonright" #F ) ("setrustedcredmanaccessprivilege" #F ))

BUILTIN\Administrators != Administrators.

**Comment by evgenyz** [comment]
From [OVAL definition](https://oval.mitre.org/language/version5.10/ovaldefinition/documentation/windows-definitions-schema.html#accesstoken_object): `In a domain environment, security principles should be identified in the form: "domain\trustee name". For local security principles use: "computer name\trustee name". For built-in accounts on the system, use the trustee name without a domain.`

**Comment by evgenyz** [comment]
Does it mean that the probe should remove the prefix `BUILTIN`?

**Comment by evgenyz** [comment]
Inviting @jan-cerny as the author. Meanwhile switching to bug, feel free to revert.

**Comment by me-shubh** [comment]
> Mmm, no this rule uses only accesstoken test:
> 
> ```
>         <definition id="oval:mil.disa.stig.windows:def:1239" version="1" class="compliance">
>           <metadata>
>             <title>WN16-UR-000070</title>
>             <affected family="windows">
>               <platform>Microsoft Windows Server 2016</platform>
>             </affected>
>             <reference source="DISA" ref_id="73743" ref_url="http://iase.disa.mil/stigs/SRR/index.html" />
>             <reference ref_url="http://cce.mitre.org" source="CCE" ref_id="CCE-44987-6" />
>             <description>The Back up files and directories user right must only be assigned to the Administrators group.</description>
>           </metadata>
>           <criteria operator="AND">
>             <criterion test_ref="oval:mil.disa.stig.windows:tst:123900" comment="Back up files and directories - Administrators" />
>           </criteria>
>         </definition>
> ```
> 
> ```
>         <accesstoken_test xmlns="http://oval.mitre.org/XMLSchema/oval-definitions-5#windows" id="oval:mil.disa.stig.windows:tst:123900" version="1" check="all" comment="Back up files and directories - Administrators">
>           <object object_ref="oval:mil.disa.stig.windows:obj:123900" />
>           <state state_ref="oval:mil.disa.stig.windows:ste:123900" />
>         </accesstoken_test>
> ```
> 
> ```
>         <accesstoken_state xmlns="http://oval.mitre.org/XMLSchema/oval-definitions-5#windows" id="oval:mil.disa.stig.windows:ste:123900" version="1" comment="Back up files and directories">
>           <sebackupprivilege datatype="boolean" operation="equals">0</sebackupprivilege>
>         </accesstoken_state>
> ```
> 
> ```
>         <accesstoken_object xmlns="http://oval.mitre.org/XMLSchema/oval-definitions-5#windows" id="oval:mil.disa.stig.windows:obj:123900" version="1" comment="Filter for Administrators">
>           <set xmlns="http://oval.mitre.org/XMLSchema/oval-definitions-5" set_operator="UNION">
>             <object_reference>oval:mil.disa.stig.windows:obj:123901</object_reference>
>             <filter>oval:mil.disa.stig.windows:ste:123901</filter>
>           </set>
>         </accesstoken_object>
>         <accesstoken_object xmlns="http://oval.mitre.org/XMLSchema/oval-definitions-5#windows" id="oval:mil.disa.stig.windows:obj:123901" version="1" comment="All security principles">
>           <security_principle datatype="string" operation="pattern match">.*</security_principle>
>         </accesstoken_object>
> ```
> 
> By the way, @jan-cerny and @yuumasato, `Obtrusive data` and set in `accesstoken_object`!

As I tried putting some prints in the probe code of registry as well as access token, and when I tried evaluating this particular rule it printed both the statements of registry and access token, so how is it only accessing access token?
