### ISSUE TITLE
Oval Object Not Supported

### ISSUE THREAD

**Issue by kh-34** [OpenSCAP/openscap#1528]
#### Description of Problem:
Oval Object not supported errors.  

#### OpenSCAP Version:
1.3.3 - OpenSCAP command line tool

#### Operating System & Version:
Window 10.0.10586

#### Steps to Reproduce:

1. oscap xccdf eval --check-engine-results U_MS_Windows_10_V1R17_STIG_SCAP_1-2_Benchmark.xml
2. 
3. 

#### Actual Results:
Getting Unknown on about 50 Checks.  Here is the beginning of the output.

W: C:\Program Files (x86)\OpenSCAP 1.3.3\oscap.exe:     OVAL object 'rpmverifyfile_object' is not supported.
W: C:\Program Files (x86)\OpenSCAP 1.3.3\oscap.exe:     OVAL object 'rpminfo_object' is not supported.
W: C:\Program Files (x86)\OpenSCAP 1.3.3\oscap.exe:     OVAL object 'rpminfo_object' is not supported.
W: C:\Program Files (x86)\OpenSCAP 1.3.3\oscap.exe:     OVAL object 'textfilecontent54_object' is not supported.
W: C:\Program Files (x86)\OpenSCAP 1.3.3\oscap.exe:     OVAL object 'rpminfo_object' is not supported.
W: C:\Program Files (x86)\OpenSCAP 1.3.3\oscap.exe:     OVAL object 'rpminfo_object' is not supported.
W: C:\Program Files (x86)\OpenSCAP 1.3.3\oscap.exe:     OVAL object 'rpminfo_object' is not supported.
W: C:\Program Files (x86)\OpenSCAP 1.3.3\oscap.exe:     OVAL object 'rpminfo_object' is not supported.
W: C:\Program Files (x86)\OpenSCAP 1.3.3\oscap.exe:     OVAL object 'rpminfo_object' is not supported.
W: C:\Program Files (x86)\OpenSCAP 1.3.3\oscap.exe:     OVAL object 'file_object' is not supported.
W: C:\Program Files (x86)\OpenSCAP 1.3.3\oscap.exe:     OVAL object 'textfilecontent54_object' is not supported.
W: C:\Program Files (x86)\OpenSCAP 1.3.3\oscap.exe:     OVAL object 'textfilecontent54_object' is not supported.
W: C:\Program Files (x86)\OpenSCAP 1.3.3\oscap.exe:       OVAL object 'wmi_object' is not supported.
#### Expected Results:
I was expecting a Pass/Fail for all checks.

**Comment by redhatrises** [comment]
@kh-34 can you provide some more info? The warnings that you are getting are expected when oval objects aren't currently supported. For example, `rpminfo_object` is not supported at all on a Windows system. However, this should affect the scan since you are using a Windows Benchmark.

**Comment by kh-34** [comment]
hi @redhatrises , 
Thanks for the fast reply. I was thinking that too, specifically for the rpminfo_object, but I am receiving warnings in the logs for that and a lot of other OVAL Object errors which had me confused.  I've attached the output from verbose loggings of Warnings for your review.  
[output.txt](https://github.com/OpenSCAP/openscap/files/4625238/output.txt)

Additionally, I've attached the Console text, if that helps.  
[Console.txt](https://github.com/OpenSCAP/openscap/files/4625260/Console.txt)

Let me know what else you might need!

**Comment by evgenyz** [comment]
Let's see what we have here.

```
OVAL object 'rpmverifyfile_object' is not supported.
OVAL object 'rpminfo_object' is not supported.
```
These two are linux-only objects, it is absolutely normal that Windows version of OpenSCAP does not support them. One might wonder why the scanner event attempt to query information from these probes (as there are, obviously, no such tests in `U_MS_Windows_10_V1R17_STIG_SCAP_1-2_Benchmark.xml`). The answer is simple: the scanner validates content applicability against CPE checks, where we have a bucket of tests related to non-windows systems. I wonder if it might make sense to not include Linux CPEs in Windows build (and vice-versa). @jan-cerny Any thoughts?

```
OVAL object 'textfilecontent54_object' is not supported.
```
This is strange, `textfilecontent54_object` is independent and should be present in Windows build. Might be a bug. Are you using the official build?

```
OVAL object 'file_object' is not supported.
```
There is no implementation for Window's version of this test in OpenSCAP (#1518).

```
OVAL object 'wmi_object' is not supported.
```
There is no implementation of deprecated version of this test in OpenSCAP. I would advise to update the content to include newer `wmi57_object` (https://oval.mitre.org/language/version5.11/ovaldefinition/documentation/windows-definitions-schema.html#wmi57_test).

```
OVAL object 'lockoutpolicy_object' is not supported.
OVAL object 'passwordpolicy_object' is not supported.
OVAL object 'auditeventpolicysubcategories_object' is not supported.
OVAL object 'fileeffectiverights53_object' is not supported.
OVAL object 'user_sid55_object' is not supported.
OVAL object 'sid_sid_object' is not supported.
```
There is no implementation for these objects in OpenSCAP. Help would be appreciated.

**Comment by evgenyz** [comment]
Adding `bug` because of `textfilecontent54_object`.

**Comment by jan-cerny** [comment]
@evgenyz 

Yes, I like your idea, including only Windows CPEs in Windows builds could fix the problem.

`textfilecontent54` is platform independent from the point of view of OVAL specification. However, our implementation of it, the textfilecontent54 probe, isn't platform independent, because it is written to be run on Linux. Therefore it's disabled when building on Windows. I assume there will be some changes needed in the textfilecontent54 probe code to make it working on Windows and also in oval_fts.c.
