### ISSUE TITLE
How to print some SEXP_t variable?

### ISSUE THREAD

**Issue by me-shubh** [OpenSCAP/openscap#1535]
#### Steps to Reproduce:
This is how my print statement looks like:
SEXP_t *probe_in = probe_ctx_getobject(ctx); //2nd line in windows registry probe main function
printf("S_TYPE = %s  S_VALP = %d ", (char*)((*probe_in).s_type), (*probe_in).s_valp); //this is what I want to print.

#### Actual Results:
                                       S_TYPE = (null)  S_VALP = 53441287
                                       S_TYPE = (null)  S_VALP = 53447559
This code is recurring two times so printing two times
Can you tell me am I printing these values correctly or is there any issue?

**Comment by jan-cerny** [comment]
I think you can try function `size_t SEXP_fprintfa (FILE *fp, const SEXP_t *s_exp);` from `sexp-output.h`, for example `SEXP_fprintfa(stdout, sexp)`. Or use `dO` macro from `common/debug_priv.h`, eg. `dO(OSCAP_DEBUGOBJ_SEXP, sexp)`.

**Comment by me-shubh** [comment]
Can you please tell me the exact statement to print it. The one I have mentioned above.
I want to print the values of probe_in variable which belongs to ctx structure.
so how exactly I use SEXP_fprintfa function. What should I put for file pointer? Can you explain these

**Comment by me-shubh** [comment]
Thank You @jan-cerny
