### ISSUE TITLE
Cause of false negatives in registry probe FOUND, might be a proposition to modify the windows probe code

### ISSUE THREAD

**Issue by me-shubh** [OpenSCAP/openscap#1536]
#### Description of Problem: 
The registry probe was giving a false negative result for several rules from the DISA STIG file - the cause of the same was that the name of the registry value being accessed by the probe was compared to the actual registry name in a case sensitive manner (eg. "**EveryoneIncludesAnonymous**" from the Stig file was being compared with "**everyoneincludesanonymous**" in the windows registry). When this name in the stig file was changed to (EveryoneIncludesAnonymous) match the name in the windows registry, the probe behaved properly. 

So, changing the way this name is being compared might resolve the issue - is this feasible?

Is there any way to compare the "name" of the registry value in a case insensitive manner?

Well, what I think is this can be done in the following manner:

```
if (probe_entobj_cmp(name_ent, tmp) != OVAL_RESULT_TRUE) {
		SEXP_free(tmp);
		free(value);
		free(name_wstr);
		free(name_str);
		return;
	}
```
This is an **if condition** in some function of registry probe which indirectly compares those string that I discussed in the description. The probe upon reaching this **if condition** returns a **false** result because the name doesn't match and the **probe_entobj_cmp** - returns **false** - which is not fair.

So what can be done is - the implementation of this **probe_entobj_cmp** can be changed in such a way that it compares the string in a case insensitive manner. Can it be done?

#### Additional Information / Debugging Steps:

For reference:
Rule: **Windows Server 2019 must be configured to prevent anonymous users from having the same permissions as the Everyone group**
Source: **U_MS_Windows_Server_2019_V1R2_STIG_SCAP_1-2_Benchmark.xml**

Hive: **HKEY_LOCAL_MACHINE**
Key: **SYSTEM\CurrentControlSet\Control\Lsa**
Name in the Registry: **everyoneincludesanonymous**
Name in the Stig file: **EveryoneIncludesAnonymous**

There are many other rules that were fixed by changing the case in Stig file.

**Comment by redhatrises** [comment]
@me-shubh if the issue is because of case insensitivity, this is probably more so a regex issue than a code issue. Modifying the regex to the following is more so the fix:

`(?i)EveryoneIncludesAnonymous(?-i)`

**Comment by evgenyz** [comment]
The Windows Registry is itself case-insensitive (in aspect of key names), but OVAL definition of registry test does not require to threat them in case-insensitive manner, so default rules to the content should apply.
