### ISSUE TITLE
Error viewing report in epiphany web browser

### ISSUE THREAD

**Issue by bkmgit** [OpenSCAP/openscap#1540]
#### Description of Problem:

Trouble viewing report in the broswer

#### OpenSCAP Version:

1.3.3
#### Operating System & Version:

Fedora 31

#### Steps to Reproduce:

1.  sudo dnf install openscap openscap-utils epiphany
2.  sudo oscap xccdf eval  --report report.html /usr/share/xml/scap/ssg/content/ssg-fedora-ds.xml
3.  epiphany report.html

#### Actual Results:

This page contains the following errors:
error on line 19 at column 40: xmlParseEntityRef: no name
Below is a rendering of the page up to the first error.

![Report rendering error in Epiphany](https://user-images.githubusercontent.com/1679477/84242304-5659c300-ab09-11ea-802d-7f406867d014.png)

#### Expected Results:

View of report. Report opens ok in Chromium web browser

#### Additional Information / Debugging Steps:

Think this is an HTML issue. Is it worth trying to submit a fix?

**Comment by evgenyz** [comment]
Hey, @bkmgit! Thank you for reporting the problem. It is of course worth submitting a fix. Even the description of the exact problem in HTML document could help.

**Comment by jan-cerny** [comment]
This error message seems to be caused by using not escaped `&` within `<script>` element. It looks like it has to be escaped in XHTML or we have to use "CDATA". https://stackoverflow.com/questions/1513871/xhtml-wont-validate-and-in-a-javascript-function. If I fix this, then other errors pop up, for example unpaired tags, which are not allowed in XHTML. I think we should run the validator on the generated report.

**Comment by bkmgit** [comment]
Ok. Ran the [W3C validator](https://validator.w3.org) on the generated report file. The output is below. Might it be worth adding some tests using w3c-markup-validator in Travis-CI? w3c-markup-validator is available in a number of packaged software repositories.

    Error: Attribute xmlns:arf not allowed here.

    From line 1, column 16; to line 1, column 135

    TYPE html><html xmlns="http://www.w3.org/1999/xhtml" xmlns:arf="http://scap.nist.gov/schema/asset-reporting-format/1.1" lang="en"><head>

    Warning: Attribute with the local name xmlns:arf is not serializable as XML 1.0.

    From line 1, column 16; to line 1, column 135

    TYPE html><html xmlns="http://www.w3.org/1999/xhtml" xmlns:arf="http://scap.nist.gov/schema/asset-reporting-format/1.1" lang="en"><head>

    Error: A document must not include both a meta element with an http-equiv attribute whose value is content-type, and a meta element with a charset attribute.

    From line 1, column 209; to line 1, column 230

    et=utf-8"><meta charset="utf-8"></meta

    Error: Stray end tag meta.

    From line 1, column 231; to line 1, column 237

    t="utf-8"></meta><meta 

    Error: Stray end tag meta.

    From line 1, column 291; to line 1, column 297

    "IE=edge"></meta><meta 

    Error: Stray end tag meta.

    From line 1, column 366; to line 1, column 372

    -scale=1"></meta><title

    Error: CSS: Deprecated media feature max-device-width. For guidance, see the Deprecated Media Features section in the current Media Queries specification.

    At line 1, column 0

    <!DOCTYPE html>

    Warning: The navigation role is unnecessary for element nav.

    From line 23, column 30126; to line 23, column 30178

    ead><body><nav class="navbar navbar-default" role="navigation"><div c

    Error: CSS: width: Too many values or values are not recognized.

    From line 66, column 197; to line 66, column 263

    account."><div class="progress-bar progress-bar-success" style="width: NaN%">0 pass

    Error: CSS: width: Too many values or values are not recognized.

    From line 67, column 19; to line 67, column 84

        </div><div class="progress-bar progress-bar-danger" style="width: NaN%">0 fail

    Error: CSS: width: Too many values or values are not recognized.

    From line 68, column 19; to line 68, column 85

        </div><div class="progress-bar progress-bar-warning" style="width: NaN%">0 othe

    Error: CSS: width: Too many values or values are not recognized.

    From line 69, column 212; to line 69, column 278

    d rules."><div class="progress-bar progress-bar-success" style="width: NaN%">0 othe

    Error: CSS: width: Too many values or values are not recognized.

    From line 70, column 19; to line 70, column 82

        </div><div class="progress-bar progress-bar-info" style="width: NaN%">0 low↩

    Error: CSS: width: Too many values or values are not recognized.

    From line 71, column 19; to line 71, column 85

        </div><div class="progress-bar progress-bar-warning" style="width: NaN%">0 medi

    Error: CSS: width: Too many values or values are not recognized.

    From line 72, column 19; to line 72, column 84

        </div><div class="progress-bar progress-bar-danger" style="width: NaN%">0 high

    Error: Stray end tag input.

    From line 73, column 971; to line 73, column 978

    ue="pass"></input>pass</

    Error: Stray end tag input.

    From line 73, column 1133; to line 73, column 1140

    e="fixed"></input>fixed<

    Error: Stray end tag input.

    From line 73, column 1304; to line 73, column 1311

    mational"></input>inform

    Error: Stray end tag input.

    From line 73, column 1529; to line 73, column 1536

    ue="fail"></input>fail</

    Error: Stray end tag input.

    From line 73, column 1691; to line 73, column 1698

    e="error"></input>error<

    Error: Stray end tag input.

    From line 73, column 1856; to line 73, column 1863

    "unknown"></input>unknow

    Error: Stray end tag input.

    From line 73, column 2080; to line 73, column 2087

    tchecked"></input>notche

    Error: Stray end tag input.

    From line 73, column 2256; to line 73, column 2263

    plicable"></input>notapp

    Error: Stray end tag input.

    From line 73, column 2472; to line 73, column 2479

    Search()"></input><div c

    Error: The element button must not appear as a descendant of the a element.

    From line 75, column 1080; to line 75, column 1135

    -details"><button type="button" class="btn btn-secondary noprint">Scroll
