### ISSUE TITLE
oscap build fails on Ubuntu 20.04 at oscap link step

### ISSUE THREAD

**Issue by GaryGapinski** [OpenSCAP/openscap#1541]
#### Description of Problem:

post-cmake make of openscap fails at oscap linking step with error

```
/usr/bin/ld: ../src/libopenscap.so.25.2.0: undefined reference to `MMap::MMap(FileFd&, unsigned long)'
collect2: error: ld returned 1 exit status
make[2]: *** [utils/CMakeFiles/oscap.dir/build.make:239: utils/oscap] Error 1
make[1]: *** [CMakeFiles/Makefile2:3226: utils/CMakeFiles/oscap.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
```

#### OpenSCAP Version:

origin/maint-1.3 from https://github.com/OpenSCAP/openscap

#### Operating System & Version:

Ubuntu 20.04 LTS

#### Steps to Reproduce:

1. Follow Ubuntu-related directions in https://github.com/OpenSCAP/openscap/blob/maint-1.3/docs/developer/developer.adoc
2. Run cmake ../ and make
3. Receive ld link error

#### Actual Results:

Incomplete build

#### Expected Results:

Completed build

#### Additional Information / Debugging Steps:

Terminal history follows. Note that cmake identifies some absent potential components which may or may not be pertinent at this stage of build [oscap-1.3.3-on-ubuntu-20.04-build.log](https://github.com/OpenSCAP/openscap/files/4768828/oscap-1.3.3-on-ubuntu-20.04-build.log).

```
gapinski@nuc7i7bnh-650ncr-com:~/Projects/github/OpenSCAP/openscap/build$ git status
On branch maint-1.3
Your branch is up to date with 'origin/maint-1.3'.

nothing to commit, working tree clean
gapinski@nuc7i7bnh-650ncr-com:~/Projects/github/OpenSCAP/openscap/build$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04 LTS"
gapinski@nuc7i7bnh-650ncr-com:~/Projects/github/OpenSCAP/openscap/build$ 

```

**Comment by evgenyz** [comment]
So, according to Ubuntu developers the function was intentionally excluded from the public API: https://bugs.launchpad.net/ubuntu/+source/apt/+bug/1883079

> MMap is an internal implementation detail that people have been using accidentally when they wanted to open the cache, where they should use pkgCacheFile for.

Can't help but wonder why it wasn't deprecated first and why it still present in public headers then?

**Comment by evgenyz** [comment]
If I understand correctly in the upstream `apt` this function is still part of the API/ABI: https://salsa.debian.org/apt-team/apt/-/blob/master/debian/libapt-pkg6.0.symbols#L346. Hmm.

**Comment by evgenyz** [comment]
@pschneiders another potential problem for you.

**Comment by GaryGapinski** [comment]
Removing the libapt-pkg-dev (`sudo apt remove libapt-pkg-dev`) and rebuilding allows the build to complete successfully.

(This excludes the dpkginfo probe but I can work around that until there is a resolution.)

**Comment by evgenyz** [comment]
Found out that in F32 we have the same problem. Gosh.
