### ISSUE TITLE
how Nanitor solution can use openscap ???

### ISSUE THREAD

**Issue by themeswordpress** [OpenSCAP/openscap#1553]
I have a question, how some solution can use the openscanp how they make the integration between the openscap & they solution and can make the scan remotely using lightweight agent installed on the target machine " ie central system that has different agents " 

For example nanitor system how it can use openscap ? for CIS & pci ?

**Comment by ggbecker** [comment]
That's a question that goes way beyond the purpose of this project. OpenSCAP is an open source project that provides an implementation of SCAP standards with its limitations.

To know how people integrate this project into their solution is a question for whom is developing this kind of integration. I believe none of us can answer this question.

The only thing OpenSCAP is able to perform is to scan remote machines over SSH (`oscap-ssh`), but the target machine also needs to have OpenSCAP installed.

**Comment by redhatrises** [comment]
@themeswordpress this is a question for Nanitor.... unless you work for Nanitor and are trying to integrate into your product.
