### ISSUE TITLE
Update Bootstrap

### ISSUE THREAD

**Issue by evgenyz** [OpenSCAP/openscap#1560]
As a follow-up of #1550, the remaining issue with HTML report:

`CSS: Deprecated media feature max-device-width.`

**Comment by jan-cerny** [comment]
This isn't just about the update, but then you have to make sure that everything still works. You have to check that the layout isn't broken, the generated documents are accessible for visually impaired, that it prints on paper and into PDF. Notice that it affects both HTML guides and HTML reports. We have done some modifications to the official bootstrap to achieve this. They aren't possible to apply to the latest versions as they are, you have to do it again.
