### ISSUE TITLE
Proposition to Modularize: A new windows probe 'sid_sid' implementation can have the same API used in accesstoken probe

### ISSUE THREAD

**Issue by McSohan** [OpenSCAP/openscap#1562]
#### Description:
The sid_sid object and accesstoken object both require trustee_name to be retrieved using an sid.
The function for this has already been implemented in the accesstoken probe.
Would it be right to move this and related common functionality to a new module which can be
common to the probes requiring sid related API calls?

#### OpenSCAP Version:
1.4.0 - OpenSCAP command-line tool

#### Operating System:
Windows

#### Path to the file:
openscap/src/OVAL/probes/windows/accesstoken_probe.c

#### Reference line number:
 **249 :**       _static WCHAR *sid_to_trustee_name(SID *sid)_

#### Extension:
The API called (_LookupAccountSidW_) via this function will also be required in the sid_sid probe. The function could be modified to return all the data obtained from the API via pointers. Would that be good or should the API be called
in the sid_sid probe - in a manner which is exclusive to that probe?

**Comment by evgenyz** [comment]
Yes, it totally makes sense to do so. There are, for example, RPM and DBus-based probes with a common module. Are you willing to create and donate the `sid_sid` probe to the project?

**Comment by evgenyz** [comment]
> Would that be good or should the API be called in the sid_sid probe - in a manner which is exclusive to that probe?

The function could be placed in a common `sid_helper.c` module and modified to be as generic as needed for all possible usage by all relevant probes.

**Comment by evgenyz** [comment]
Related issue: #1528.

**Comment by me-shubh** [comment]
> Yes, it totally makes sense to do so. There are, for example, RPM and DBus-based probes with a common module. Are you willing to create and donate the `sid_sid` probe to the project?

Yes, we have been trying to build and setup the project environment along with finding some errors in the existing probes. And yes we were successful in doing so. Now we are trying to build this new 'sid_sid' probe and contribute to the community. For doing so can we seek some help of you or your colleagues knowing about Windows internals?

**Comment by me-shubh** [comment]
> > Yes, it totally makes sense to do so. There are, for example, RPM and DBus-based probes with a common module. Are you willing to create and donate the `sid_sid` probe to the project?
> 
> Yes, we have been trying to build and setup the project environment along with finding some errors in the existing probes. And yes we were successful in doing so. Now we are trying to build this new 'sid_sid' probe and contribute to the community. For doing so can we seek some help of you or your colleagues knowing about Windows internals?

We have created a template for the probe and now we are implementing the suitable API for it. As we are students so we are not much thorough with Windows internals, we would love as much assistance as possible

**Comment by evgenyz** [comment]
Sure, you can reach us for assistance. But please keep in mind that the core of the OpenSCAP community members are not, by any means, Windows experts as well :).

**Comment by me-shubh** [comment]
> Sure, you can reach us for assistance. But please keep in mind that the core of the OpenSCAP community members are not, by any means, Windows experts as well :).

Oh okay. So shall we continue this process here on these threads or mailing would be better?

**Comment by evgenyz** [comment]
You might receive more advices regarding Windows on the mailing list, but any code you might have is better to be discussed in form of a PR. So, I would say go for both.

**Comment by me-shubh** [comment]
> You might receive more advices regarding Windows on the mailing list, but any code you might have is better to be discussed in form of a PR. So, I would say go for both.

I would be happy if you can share the contact details for the same :)

**Comment by McSohan** [comment]
> Yes, it totally makes sense to do so. There are, for example, RPM and DBus-based probes with a common module. Are you willing to create and donate the `sid_sid` probe to the project?

Yes we would be happy to do it.  Currently, we are trying to understand the approach with an aim of implementing windows probes to contribute.
