### ISSUE TITLE
Commands 

### ISSUE THREAD

**Issue by themeswordpress** [OpenSCAP/openscap#1589]
Hello Openscap team, 

Hope all is well, Can you help me for commands, I mean, where can I find the commands file, for example, if the tag is rpminfo_object so how the tool knows that this rpminfo_object should be applied this commands, for example, rpm -q packageName. 

Where are the file commands in openscap tool how openscap knows the commands ?

Best Regards,

**Comment by themeswordpress** [comment]
rpm just an example, so example this tag textfilecontent54_object how the openscap knows the commands

**Comment by evgenyz** [comment]
OpenSCAP does not use any "commands" at all. It does not spawn any processes (directly) to fetch the information.
