### ISSUE TITLE
Building from source as debian

### ISSUE THREAD

**Issue by kirotawa** [OpenSCAP/openscap#1598]
I have a newbie question, and sorry for noise,

I'm trying to build it as debian and i'm hitting the vendor_perl versus the perl5/5.30 issue. In CMakefile for swig/perl it uses vendor_perl instead what it used previously in version 1.2.17 : vendorarch="$( $PERL -e 'use Config; print $Config{vendorarch}' | sed "s|$($PERL -e 'use Config; print $Config{prefix}')||" )

My question is that was intentional? Is vendor_perl supposed to be resolved somehow by dh_help? Or is that bug? 

That is the issue msg:
dh_install: warning: Cannot find (any matches for) "usr/lib/x86_64-linux-gnu/perl5/5.30" (tried in ., debian/tmp)

dh_install: warning: libopenscap-perl missing files: usr/lib/x86_64-linux-gnu/perl5/5.30

And it happens because /debian/tmp/usr/lib/x86-64-linux-gnu/perl5 has /vendor_perl instead 5.30.

Thanks in advance

**Comment by evgenyz** [comment]
Debian builds are not really well-maintained at this moment. If you have a solution that won't break Ubuntu (or anything else) please propose a PR.

**Comment by kirotawa** [comment]
Yeah, I'm porting/building it from source to groovy in a first step (before test and so), but that issue is on my way. Hard coding perl version on it made it builds. Since i am newbie in cmake stuff, was looking for advice  in how to handle it properly without break any thing and was curious why the vendorarch is set on the fly in 1.2.17 and in 1.3.3 it's just vendor_perl. 
I'll keep digging on it.
Thanks!

**Comment by evgenyz** [comment]
@jan-cerny Any advice?

**Comment by jan-cerny** [comment]
I don't know, I only guess. We use CMake module FindPerlLibs to detect Perl libraries and their location. https://cmake.org/cmake/help/latest/module/FindPerlLibs.html. However, we hardcode the installation path for the Perl modules in swig/perl/CMakeLists.txt to `${CMAKE_INSTALL_LIBDIR}/perl5/vendor_perl`. Perhaps, this hardcoded path could be replaced by some of the variables provided by FindPerlLibs.

**Comment by kirotawa** [comment]
Nice tip @jan-cerny. I can confirm that using this [1] worked for it to build as debian pkg. Thanks!

[1]
```
diff  --git a/swig/perl/CMakeLists.txt b/swig/perl/CMakeLists.txt                                                                                                                        
index 0325919..be804a7 100644                                                                                                                                                           
--- a/swig/perl/CMakeLists.txt                                                                                                                                                          
+++ b/swig/perl/CMakeLists.txt                                                                                                                                                          
@@ -1,4 +1,5 @@                                                                                                                                                                         
 include(UseSWIG)                                                                                                                                                                       
+include(FindPerlLibs)                                                                                                                                                                  
                                                                                                                                                                                        
 set(CMAKE_SWIG_FLAGS "-module" "openscap_pm")                                                                                                                                          
 if (${CMAKE_VERSION} VERSION_LESS "3.8.0")                                                                                                                                             
@@ -13,6 +14,6 @@ if (${CMAKE_C_COMPILER_ID} STREQUAL "GNU" OR ${CMAKE_C_COMPILER_ID} STREQUAL "Cl                                                                                      
 endif()                                                                                                                                                                                
                                                                                                                                                                                        
 install(TARGETS ${SWIG_MODULE_openscap_pm_REAL_NAME}                                                                                                                                   
-       DESTINATION ${CMAKE_INSTALL_LIBDIR}/perl5/vendor_perl)                                                                                                                          
+        DESTINATION ${PERL_VENDORLIB})                                                                                                                                                 
 install(PROGRAMS ${CMAKE_CURRENT_BINARY_DIR}/openscap_pm.pm                                                                                                                            
-       DESTINATION ${CMAKE_INSTALL_DATADIR}/perl5/vendor_perl)                                                                                                                         
+        DESTINATION ${PERL_VENDORARCH})                                                                                                                                                
~                      
```

**Comment by kirotawa** [comment]
out of curiosity the openscap 1.3.3 attempt to build for ubuntu/groovy is in here: https://launchpad.net/~ubuntu-security/+archive/ubuntu/ubuntu-security-staging/+sourcepub/11580502/+listing-archive-extra

**Comment by kirotawa** [comment]
Using FindPerlLibs i also could built ok , openscap1.3.3. on fedora 32, but didn't test any hard there.

**Comment by evgenyz** [comment]
Nah, mention is related to Windows. Are you planning to create a PR with this change, by the way?

**Comment by kirotawa** [comment]
@evgenyz yep, if it sounds ok. But, you dropped that windows issue, so, not sure.

**Comment by evgenyz** [comment]
No we did not drop it, we just don't have resources to deal with it :( The change sounds OK, we can work on it in the PR if there would be any problems with CI.

**Comment by kirotawa** [comment]
okdokie, thanks.

**Comment by kirotawa** [comment]
Closing issue, as a merge that deal with this was already made. Thanks folks!
#1618
