### ISSUE TITLE
[minor] [doc] "compiling" link in docs/manual/manual.adoc outdated

### ISSUE THREAD

**Issue by pinkgothic** [OpenSCAP/openscap#1599]
#### Description of Problem:
The documentation at [docs/manual/manual.adoc](https://github.com/OpenSCAP/openscap/blob/maint-1.3/docs/manual/manual.adoc) contains the phrase _"for details please refer to the compiling section"_, with 'compiling' linking to an anchor in the same document that no longer exists.

#### OpenSCAP Version:
1.3

#### Operating System & Version:
None

#### Steps to Reproduce:
- navigate to [docs/manual/manual.adoc](https://github.com/OpenSCAP/openscap/blob/maint-1.3/docs/manual/manual.adoc)
- ctrl+f 'compiling'
- click link

#### Actual Results:
- nothing happens

#### Expected Results:
- link leads to compilation instructions (which are now at [docs/developer/developer.adoc](https://github.com/pinkgothic/openscap/blob/maint-1.3/docs/developer/developer.adoc))

#### Additional Information / Debugging Steps:
None

I tried to fork the repository to fix this myself, but to my great embarrassment, I'm apparently not clever enough to figure out how to put a relative link into the doc. My attempts to follow [these instructions](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-readmes#relative-links-and-image-paths-in-readme-files) did not work. I tried using the `{shorthand}[link text]` format and putting `:shorthand:` at the top of the file with a relative link, but that didn't work either - GitHub just didn't render the link in both scenarios.

Maybe someone more familiar with relative links in Markdown documents on GitHub can fix this.

**Comment by evgenyz** [comment]
Hey! Thanks for noticing and letting us know! 

The `<<../developer/developer.adoc#,Developer Documentation>>` combination should do the trick. I'll leave the honor of creation of the PR to you (if you're still up to it, of course) :)

**Comment by pinkgothic** [comment]
Magical, that works - thanks for your guidance! Is that documented anywhere that I could read up on to not make this class of mistake again? :)

In any case, I've created the PR. Thanks again!

**Comment by evgenyz** [comment]
> Magical, that works - thanks for your guidance! Is that documented anywhere that I could read up on to not make this class of mistake again? :)

Mmm, it is in the docs: https://asciidoctor.org/docs/user-manual/#navigating-between-source-files. You've been pretty close, maybe just forgot to add `#` or something.
