### ISSUE TITLE
Scans Fail on Debian10 

### ISSUE THREAD

**Issue by titoulevrai** [OpenSCAP/openscap#1606]
- Is this an issue with SCAP Workbench?
    No
- Is this an issue with SCAP Security Guide (i.e., related to the content of scans, not the scanner proper)?
    -I don't think so
- Is this an issue during the OS installation process?
   No

Thanks!

#### Description of Problem:

On a Deiban10 I tried to scan the OS with the profile xccdf_org.ssgproject.content_profile_anssi_np_nt28_high.
But at multiple time, some tests don't work.
It seems to have some missing Items when I search the cause in the oval details  : 
"package rsyslog is installed  failed because these items were missing:
Object oval:ssg-obj_test_service_rsyslog_package_rsyslog_installed:obj:1 of type dpkginfo_object"

#### OpenSCAP Version:

OpenSCAP command line tool (oscap) 1.2.16
Copyright 2009--2017 Red Hat Inc., Durham, North Carolina.

==== Supported specifications ====
XCCDF Version: 1.2
OVAL Version: 5.11.1
CPE Version: 2.3
CVSS Version: 2.0
CVE Version: 2.0
Asset Identification Version: 1.1
Asset Reporting Format Version: 1.1
CVRF Version: 1.1

#### Operating System & Version:
Debian10 
Debian 4.19.132-1
#### Steps to Reproduce:

1. Install debian10 
2. Install libopenscap8
3. run the command as root : oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_anssi_np_nt28_high ssg-debian10-ds-1.2.xml 

#### Actual Results:

OpenSCAP Error: Probe with PID=2250 has been killed with signal 11 [../../../../../src/OVAL/probes/SEAP/sch_pipe.c:178]
Item corresponding to object 'oval:ssg-obj_test_package_rsyslog_installed:obj:1' from test 'oval:ssg-test_package_rsyslog_installed:tst:1' has an unknown flag. This may indicate a bug in OpenSCAP. [../../../../src/OVAL/results/oval_resultTest.c:914]
Probe with PID=2332 has been killed with signal 11 [../../../../../src/OVAL/probes/SEAP/sch_pipe.c:178]
Item corresponding to object 'oval:ssg-obj_test_service_rsyslog_package_rsyslog_installed:obj:1' from test 'oval:ssg-test_service_rsyslog_package_rsyslog_installed:tst:1' has an unknown flag. This may indicate a bug in OpenSCAP. [../../../../src/OVAL/results/oval_resultTest.c:914]
Probe with PID=2349 has been killed with signal 11 [../../../../../src/OVAL/probes/SEAP/sch_pipe.c:178]
Item corresponding to object 'oval:ssg-obj_test_package_cron_installed:obj:1' from test 'oval:ssg-test_package_cron_installed:tst:1' has an unknown flag. This may indicate a bug in OpenSCAP. [../../../../src/OVAL/results/oval_resultTest.c:914]
Probe with PID=2378 has been killed with signal 11 [../../../../../src/OVAL/probes/SEAP/sch_pipe.c:178]
Item corresponding to object 'oval:ssg-obj_test_package_openssh-server_removed:obj:1' from test 'oval:ssg-test_package_openssh-server_removed:tst:1' has an unknown flag. This may indicate a bug in OpenSCAP. [../../../../src/OVAL/results/oval_resultTest.c:914]
Probe with PID=2413 has been killed with signal 11 [../../../../../src/OVAL/probes/SEAP/sch_pipe.c:178]
Item corresponding to object 'oval:ssg-obj_test_package_openssh-server_installed:obj:1' from test 'oval:ssg-test_package_openssh-server_installed:tst:1' has an unknown flag. This may indicate a bug in OpenSCAP. [../../../../src/OVAL/results/oval_resultTest.c:914]
Probe with PID=2419 has been killed with signal 11 [../../../../../src/OVAL/probes/SEAP/sch_pipe.c:178]
Item corresponding to object 'oval:ssg-obj_openssh-server_version:obj:1' from test 'oval:ssg-test_openssh-server_version:tst:1' has an unknown flag. This may indicate a bug in OpenSCAP. [../../../../src/OVAL/results/oval_resultTest.c:914]

#### Expected Results:
The test must be fail or pass but not error

#### Additional Information / Debugging Steps:
Debian just installed with openssh and libopensca8

**Comment by evgenyz** [comment]
The `1.2.16` version of the scanner, which is packaged for Debian, is very old and behaves badly with contemporary security content and OS components. Please, contact the package maintainer regarding package upgrade.

Alternatively, you could try building it (`1.3.3`) yourself from the source code.
