### ISSUE TITLE
Issues with OVAL test results details in the HTML report

### ISSUE THREAD

**Issue by jnmatlock** [OpenSCAP/openscap#1633]
#### Description of Problem:
OVAL test results showing incorrect value (false/fail) for the following Rule IDs after running rhel8-playbook-stig.yml.

1. Rule ID: xccdf_org.ssgproject.content_rule_banner_etc_issue
OVAL Definition ID:	oval:ssg-banner_etc_issue:def:1
Modify the System Login Banner

2. Rule ID: xccdf_org.ssgproject.content_rule_configure_openssl_crypto_policy
OVAL Definition ID:	oval:ssg-configure_openssl_crypto_policy:def:1
Configure OpenSSL library to use System Crypto Policy

3. Rule ID: xccdf_org.ssgproject.content_rule_audit_ospp_general
OVAL Definition ID:	oval:ssg-audit_ospp_general:def:1
Perform general configuration of Audit for OSPP

#### OpenSCAP Version:
1.3.2

#### Operating System & Version:
RHEL 8.2 with Draft DISA STIG

#### Steps to Reproduce:

1. Download scap-security-guide package
2. Run rhel8-playbook-stig.yml
3. Run oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_stig --report /tmp/oscap-report.html --fetch-remote-resources /usr/share/xml/scap/ssg/content/ssg-rhel8-ds.xml

Note: Also ran playbooks individually, still receiving the same results in the HTML report 

#### Actual Results:

Modify the System Login Banner

![login_banner_oval_test_html](https://user-images.githubusercontent.com/44849530/98964854-535b6800-24d7-11eb-8e40-4485548c5951.png)

![login_banner_etc_issue](https://user-images.githubusercontent.com/44849530/98964873-56eeef00-24d7-11eb-9e2c-c72244d72ff7.png)

Configure OpenSSL library to use System Crypto Policy

![openssl_crypto_policy_oval_test_html](https://user-images.githubusercontent.com/44849530/98965051-91588c00-24d7-11eb-8c9a-a35fd5ac3ddb.png)

![openssl_crypto_policy_issue](https://user-images.githubusercontent.com/44849530/98965056-93224f80-24d7-11eb-98af-59101ff079a8.png)

Perform general configuration of Audit for OSPP

![audit_ospp_general_oval_test_html](https://user-images.githubusercontent.com/44849530/98965115-a7fee300-24d7-11eb-8e9e-4849eb4a9659.png)

![audit_ospp_general_oval_test_html_2](https://user-images.githubusercontent.com/44849530/98965126-ab926a00-24d7-11eb-8db1-bb7118468558.png)

![audit_ospp_general_issue](https://user-images.githubusercontent.com/44849530/98965146-b0efb480-24d7-11eb-976c-f7b7eef81696.png)

#### Expected Results:

Each of the following should show up with status pass.

1. Rule ID: xccdf_org.ssgproject.content_rule_banner_etc_issue
OVAL Definition ID:	oval:ssg-banner_etc_issue:def:1
Modify the System Login Banner

2. Rule ID: xccdf_org.ssgproject.content_rule_configure_openssl_crypto_policy
OVAL Definition ID:	oval:ssg-configure_openssl_crypto_policy:def:1
Configure OpenSSL library to use System Crypto Policy

3. Rule ID: xccdf_org.ssgproject.content_rule_audit_ospp_general
OVAL Definition ID:	oval:ssg-audit_ospp_general:def:1
Perform general configuration of Audit for OSPP

#### Additional Information / Debugging Steps:

The STIG playbook and the recommended remediation playbook run with no issues.

**Comment by evgenyz** [comment]
@jan-cerny, @yuumasato, @ggbecker My first impression is that is belongs to CaC.
