### ISSUE TITLE
[SCAP.R.2850] XML namespace isn't ignored

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/openscap#1638]
#### Description of Problem:

When evaluating r2850-rhel-datastream.xml from [SCAP 1.3 validation test suite](https://csrc.nist.gov/CSRC/media/Projects/scap-validation-program/documents/SCAP1.3ValidationTestContent_1-3.0.0.0.zip) I get unexpected results. All rules are evaluated as notapplicable by OpenSCAP. The CPE checks from this datastream are evaluated as not applicable. They consist of xmlfilecontent tests. The items described by xmlfilecontent_objects are not found. It's because the xmlfilecontent_objects contain simple XPath expressions without namespace, but the scanned XML file has a namespace. The test suite expects that the XPath expressions will be evaluated ignoring the namespace.

#### OpenSCAP Version:
1.3.4

#### Operating System & Version:
f32

#### Steps to Reproduce:

1.  cd requirements/R2850
2. cd configuration_scripts/
3. sudo python3 r2850_rhel_config_1.py
 (this script will copy the XML files gov.nist.secauto-scapval-1.3.2.swidtag from this directory to /scap_validation_content/R2850 that will be scanned by oscap in the next step, so you can review them here as well)
4. cd ..
5. oscap xccdf eval --results-arf results_arf.xml --profile xccdf_gov.nist.validation_profile_r2850-rhel r2850-rhel-datastream.xml

#### Actual Results:
xccdf_gov.nist.validation.r2850-rhel_rule_100 notapplicable
xccdf_gov.nist.validation.r2850-rhel_rule_200 notapplicable
xccdf_gov.nist.validation.r2850-rhel_rule_300 notapplicable

#### Expected Results:
xccdf_gov.nist.validation.r2850-rhel_rule_100 pass
xccdf_gov.nist.validation.r2850-rhel_rule_200 fail
xccdf_gov.nist.validation.r2850-rhel_rule_300 notapplicable

#### Additional Information / Debugging Steps:

There are elements like `<xpath>/SoftwareIdentity/@name</xpath>` in the datastream. They don't contain namespace. 

The file `requirements/R2850/configuration_scripts/gov.nist.secauto-scapval-1.3.2.swidtag` has an xmlns in the root element.
```
<SoftwareIdentity 
  xmlns="http://standards.iso.org/iso/19770/-2/2015/schema.xsd" 
  xml:lang="en-US" 
  name="SCAP Validation Tool" 
  tagId="gov.nist.secauto-scapval-1.3.2" 
  tagVersion="1" 
  version="1.3.2"
  versionScheme="multipartnumeric"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://standards.iso.org/iso/19770/-2/2015/schema.xsd
  http://standards.iso.org/iso/19770/-2/2015-current/schema.xsd
  http://tagvault.org/xsd/swid-extensions-2015.xsd swid-2015-extensions-1.0.xsd">
```

Changing every xpath query in the datastream to use `local-name()` function , for example `<xpath>/*[local-name()="SoftwareIdentity"]/@name</xpath>` changes the rule results to expected results. Based on that I think that it's expected that the xpath queries will match the elements, for example `SoftwareIdentity`.

However I'm not sure if the expected behavior is correct or if the current behavior is correct as well. I haven't found anything in OVAL specification about it.

**Comment by jan-cerny** [comment]
In my opinion the current behaviour is correct because it should be an XPath 1.0 expression and in XPath the namespaces matter.

**Comment by evgenyz** [comment]
Well, if we are going to stick with this broken implementation the only other option is to prepend node names with a wild card in the xpath itself (it is not supported in xpath 1.0 AFAIK, but we use xpath 1.1+ for this probe).

**Comment by jan-cerny** [comment]
Read this mailing list thread: https://lists.cisecurity.org/empathy/thread/ZEJKSY7QMLVXNZ7QRQ555N7W2T2SDNTO
