### ISSUE TITLE
[SCAP.R.3010] suspicious warning when evaluating a valid ds

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/openscap#1642]
#### Description of Problem:
When evaluating r3010-datastream.xml from
[SCAP 1.3 validation test suite](https://csrc.nist.gov/CSRC/media/Projects/scap-validation-program/documents/SCAP1.3ValidationTestContent_1-3.0.0.0.zip) I get a warning that a component has been already registered.

#### OpenSCAP Version:
1.3.4

#### Operating System & Version:
f32

#### Steps to Reproduce:

1. oscap xccdf eval --results-arf arf.xml requirements/R3010/r3010-datastream.xml
2. 
3. 

#### Actual Results:
W: oscap: File r3010-cpe-oval has already been registered in Source DataStream session: requirements/R3010/r3010-datastream.xml

#### Expected Results:
no warning or a better warning

#### Additional Information / Debugging Steps:

We need to investigate what that warning means and ideally improve or change or remove the warning.

**Comment by evgenyz** [comment]
@jan-cerny 

There is a story behind it :) #545. (Commit: https://github.com/OpenSCAP/openscap/commit/1f2d82a245869df5af1effdf6030b34e6bb31937)

The code in question: https://github.com/OpenSCAP/openscap/blob/27211fa7b3cb1a83a5e8d1b31c1aab9695240391/src/DS/ds_sds_session.c#L270

Now, as far as I understand there would be no harm if we will just ignore the fact that some source was referenced twice. It'd end up in the same hashmap anyway. My suggestion: move the message to the INFO level, just in case it is harmful for a very obscure DS.
