### ISSUE TITLE
"Official" docker image is old and doesn't contain some tools

### ISSUE THREAD

**Issue by tculp** [OpenSCAP/openscap#1643]
The official image located at https://hub.docker.com/r/openscap/openscap is now 3 years old. Also, it doesn't contain the oscap-docker tool. Is this image still maintained?

**Comment by tculp** [comment]
Given that the image is now 6 years old since the last update, I'll assume it is not still maintained

**Comment by evgenyz** [comment]
We got rid of these repos.
