### ISSUE TITLE
Generated report shows different results based on multi-check being true of false

### ISSUE THREAD

**Issue by jtrollin** [OpenSCAP/openscap#1647]
#### Description of Problem:
When I run the test tool on RHEL 7 using `oscap xccdf eval --fetch-remote-resources --profile xccdf_org.ssgproject.content_profile_stig --results-arf arf.xml --report report.html /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml` the generated HTML shows a different result for xccdf_org.ssgproject.content_rule_security_patches_up_to_date 

When multi-check is set to true the test shows as passed even though some of the child tests failed, when set to false it shows the test as being failed. 

#### OpenSCAP Version:
1.2.17

#### Operating System & Version:
ed Hat Enterprise Linux Server release 7.9 (Maipo)

#### Steps to Reproduce:

1.  Run oscap and generate the HTML report
2.  chance multi-check to false in /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml
3. Run oscap again and generate the HTML report
4. You will see the first report showing it as passed and the second report showing it as failed (which is correct)

**Comment by jan-cerny** [comment]
I think this was fixed by https://github.com/OpenSCAP/openscap/pull/1426

**Comment by evgenyz** [comment]
> I think this was fixed by #1426

Yeah, but we are not going to back-port it to `1.2.x`, right? And even if we are, we won't release it for RHEL7.
