### ISSUE TITLE
Remove internal CPE dictionary

### ISSUE THREAD

**Issue by evgenyz** [OpenSCAP/openscap#1683]
According to the SCAP standard scanner does not have to provide inbuilt CPE dictionary. We see more harm than good from having it. It will be removed (emptied) in the next API-breaking version.

We will however retain the functionality, so that a package maintainer or the end user could be able to customize the workflow.

**Comment by jan-cerny** [comment]
This looks like a clever idea: we won't have to maintain it, and people will still be able to provide their own dictionaries. It shouldn't affect common use cases because the SCAP source data streams contain their own built-in dictionaries.
