### ISSUE TITLE
out of memory probe_rpmverify

### ISSUE THREAD

**Issue by jingnanj** [OpenSCAP/openscap#1685]
#### Description of Problem:
My Centos7 Linux server is down for Memory Leak, and when I restart my server, the log shows that Openscap made it out of memory
Out of memory: Kill process 230642 (probe_rpmverify) score 529 or sacrifice child

#### OpenSCAP Version:
openscap 1.3.4

#### Operating System & Version:
Centos7

#### Steps to Reproduce:

1. oscap xccdf eval --result cis.html --profile xccdf_org.ssgproject.content_profile_cis /content/build/ssg-centos7-ds.xml

#### Actual Results:
Out of memory

#### Expected Results:
No Memory Leak

**Comment by evgenyz** [comment]
OpenSCAP 1.3+ does use threads instead of child processes. Are you sure that you're running the latest version of the scanner? Can you please also provide the whole output of the `oscap --version` command.
