### ISSUE TITLE
Ansible calls to "replace" module no longer support follow: true

### ISSUE THREAD

**Issue by parkerbp** [OpenSCAP/openscap#1694]
- Is this an issue with SCAP Workbench?
    - If so, report it here: https://github.com/OpenSCAP/scap-workbench/issues
- Is this an issue with SCAP Security Guide (i.e., related to the content of scans, not the scanner proper)?
    - If so, report it here: https://github.com/OpenSCAP/scap-security-guide/issues
- Is this an issue during the OS installation process?
    - If so, report it here: https://github.com/OpenSCAP/oscap-anaconda-addon/issues

Thanks!

#### Description of Problem:
After generating an ansible file to remediate issues, the created file contains calls to the replace module with the " follow: true" parameter. This is no longer valid post ansible 2.5

#### OpenSCAP Version:
OpenSCAP command line tool (oscap) 1.2.17

#### Operating System & Version:
OEL 7.9

#### Steps to Reproduce:

1. Generate ansible output from any 7.9 OEL server build
2. Execute ansible playbook
3. 

#### Actual Results:
    - name: Do not allow users to reuse recent passwords - system-auth (add)
      replace:
        dest: /etc/pam.d/system-auth
        follow: true
        regexp: ^password\s+sufficient\s+pam_unix\.so\s(?!.*remember\s*=\s*).*$
        replace: \g<0> remember={{ var_password_pam_unix_remember }}
      when: '"pam" in ansible_facts.packages'

fatal: [10.64.160.105]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (replace) module: follow Supported parameters include: after, attributes, backup, before, encoding, group, mode, owner, path, regexp, replace, selevel, serole, setype, seuser, unsafe_writes, validate"}

**Comment by matejak** [comment]
This is a content issue - scanner just extract the respective snippet from the datastream, and it basically doesn't "understand" Ansible at all. Please copy-paste this issue to the [ComplianceAsCode/content](https://github.com/ComplianceAsCode/content) project, as the issue can't be transferred there by us.

**Comment by matejak** [comment]
and I have just checked that project, and there seems to be no content like this any more - the issue has been fixed already upstream, so I am closing this one.

**Comment by yuumasato** [comment]
Was fixed in https://github.com/ComplianceAsCode/content/pull/6139
