### ISSUE TITLE
oscap-docker complains about docker module

### ISSUE THREAD

**Issue by mooseDecoder** [OpenSCAP/openscap#1695]
#### Description of Problem:

I am unable to run the oscap-docker example. I used RH provided guide, which I followed to the T, located here https://www.open-scap.org/resources/documentation/security-compliance-of-rhel7-docker-containers/

I have done some research into the issue, and have noted some are saying it is due to a python issue. The guide should be updated to reflect that if that is the case, but I am still not able to get the desired results regardless of having installed python3 among other recommendations.

#### OpenSCAP Version:
1.2.17

#### Operating System & Version:
RHEL7 Server, rhel7 docker image

#### Steps to Reproduce:

https://www.open-scap.org/resources/documentation/security-compliance-of-rhel7-docker-containers/

#### Actual Results:

<img width="974" alt="image" src="https://user-images.githubusercontent.com/17228578/108243327-f3024500-711b-11eb-916d-5329382acf5d.png">

#### Expected Results:

See guide.

**Comment by jan-cerny** [comment]
Hi @mooseDecoder , try to check if you have installed these packages:
* atomic
* openscap-containers
* docker
* python-docker-py

**Comment by mooseDecoder** [comment]
Thanks very much @jan-cerny  -- was missing atomic and python-docker-py -- but will still note the documentation makes no mention of the need to install these dependencies.

**Comment by jan-cerny** [comment]
OK, that page wasn't great. I have improved it.

**Comment by jan-cerny** [comment]
I wondered why atomic isn't installed automatically. Fortunately, it's a known issue: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/7.3_release_notes/known_issues_security . The reason seems to be that atomic package is in the extras repository but openscap packages are shipped in base OS.
