### ISSUE TITLE
Openscap performance problem

### ISSUE THREAD

**Issue by jingnanj** [OpenSCAP/openscap#1698]
#### Description of Problem:
hey guys, Is there have any way to limit CPU  when Openscap starts tasks? 

#### OpenSCAP Version:
Openscap 1.3.2

#### Operating System & Version:
centos7

#### Steps to Reproduce:

1. oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_cis  ssg-centos7-ds.xml

#### Actual Results:
it will use 100% CPU when working on a task for few minutes

#### Expected Results:
Keep CPU utilization under 50%, it's ok to take more time on each scan task.

**Comment by evgenyz** [comment]
Usual `nice`, `cpulimit` and control groups should do the trick. The OpenSCAP itself does not have such a control available.
