### ISSUE TITLE
Failure while evaluating Ubuntu 16.04 using DISA STIG

### ISSUE THREAD

**Issue by compete2cooperate** [OpenSCAP/openscap#1716]
We are trying to evaluate Ubuntu 16.04 using openscap with DISA STIG as reference/benchmark (downloaded from https://dl.dod.cyber.mil/wp-content/uploads/stigs/zip/U_CAN_Ubuntu_16-04_LTS_V2R2_STIG.zip) but we are getting all result as "**notchecked**" . Not sure if we are missing anything. Any help is highly appreciated.

Thanks!

#### Steps to Reproduce:

1. We executed `oscap xccdf eval --profile MAC-1_Classified --report /tmp/report.html --cpe /usr/share/scap-security-guide/ssg-ubuntu1604-cpe-dictionary.xml U_CAN_Ubuntu_16-04_LTS_STIG_V2R2_Manual-xccdf.xml`
2. But all of the results are "notchecked"

#### Actual Results:
> Title   The Ubuntu operating system must disable all wireless network adapters.
> Rule    SV-219346r610963_rule
> Ident   SV-110017
> Ident   V-100913
> Ident   CCI-002418
> Result  notchecked
> 
> Title   The Ubuntu operating system must be configured so that remote X connections are disabled, unless to fulfill documented and validated mission requirements.
> Rule    SV-233779r610963_rule
> Ident   CCI-000366
> Result  notchecked
> 
> Title   The Ubuntu operating system SSH daemon must prevent remote hosts from connecting to the proxy display.
> Rule    SV-233780r610963_rule
> Ident   CCI-000366
> Result  notchecked

**Comment by evgenyz** [comment]
Please run it in debugging mode and attach the resulting log.

`oscap xccdf eval --verbose DEVEL --profile MAC-1_Classified --report /tmp/report.html --cpe /usr/share/scap-security-guide/ssg-ubuntu1604-cpe-dictionary.xml U_CAN_Ubuntu_16-04_LTS_STIG_V2R2_Manual-xccdf.xml`

**Comment by compete2cooperate** [comment]
Hi @evgenyz 
Thanks for such a quick response

We issued following command
`oscap xccdf eval --verbose DEVEL --verbose-log-file /tmp/xccdf.log --profile MAC-1_Classified --report /tmp/report.html --cpe /usr/share/scap-security-guide/ssg-ubuntu1604-cpe-dictionary.xml U_CAN_Ubuntu_16-04_LTS_STIG_V2R2_Manual-xccdf.xml`

Please find the xccdf.log as verbose-log-file
[xccdf.log](https://github.com/OpenSCAP/openscap/files/6195454/xccdf.log)

**Comment by ggbecker** [comment]
> Hi @evgenyz
> Thanks for such a quick response
> 
> We issued following command
> `oscap xccdf eval --verbose DEVEL --verbose-log-file /tmp/xccdf.log --profile MAC-1_Classified --report /tmp/report.html --cpe /usr/share/scap-security-guide/ssg-ubuntu1604-cpe-dictionary.xml U_CAN_Ubuntu_16-04_LTS_STIG_V2R2_Manual-xccdf.xml`
> 
> Please find the xccdf.log as verbose-log-file
> [xccdf.log](https://github.com/OpenSCAP/openscap/files/6195454/xccdf.log)

The file `U_CAN_Ubuntu_16-04_LTS_STIG_V2R2_Manual-xccdf.xml` is a manual benchmark checklist and does not contain any automated content that can be consumed by the scanner.

Please refer to SCAP content provided by DISA here: https://public.cyber.mil/stigs/scap/

In your case it should be this file: https://dl.dod.cyber.mil/wp-content/uploads/stigs/zip/U_CAN_Ubuntu_16-04_LTS_V2R2_STIG_SCAP_1-2_Benchmark.zip

I'm going to close the since it doesn't seem to be related to a problem with the scanner itself.
