### ISSUE TITLE
using of customization file has no effect

### ISSUE THREAD

**Issue by markmal** [OpenSCAP/openscap#1718]
#### Description of Problem:

using of customization file has no effect

#### OpenSCAP Version:

OpenSCAP command line tool (oscap) 1.3.4

#### Operating System & Version:

Debian 10

#### Steps to Reproduce:

1. Using oscap-workbench open /usr/share/xml/scap/ssg/content/ssg-debian10-ds.xml, profile xccdf_org.ssgproject.content_profile_standard. 
2. Disable rule xccdf_org.ssgproject.content_rule_sshd_disable_root_login. 
3. Save customization into file ssg-debian10-ds-tailoring.xml
4. Run oscap
`oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_standard --tailoring-file ssg-debian10-ds-tailoring.xml /usr/share/xml/scap/ssg/content/ssg-debian10-ds.xml`

#### Actual Results:
...
Title   Disable SSH Root Login
Rule    xccdf_org.ssgproject.content_rule_sshd_disable_root_login
Result  fail
...

#### Expected Results:
Should not check this rule

#### Additional Information / Debugging Steps:
ssg-debian10-ds-tailoring.xml
`<?xml version="1.0" encoding="UTF-8"?>
<xccdf:Tailoring xmlns:xccdf="http://checklists.nist.gov/xccdf/1.2" id="xccdf_scap-workbench_tailoring_default">
  <xccdf:benchmark href="/tmp/scap-workbench-zMYYyh/ssg-debian10-ds.xml"/>
  <xccdf:version time="2021-03-30T09:24:01">1</xccdf:version>
  <xccdf:Profile id="xccdf_org.ssgproject.content_profile_standard_customized_TC" extends="xccdf_org.ssgproject.content_profile_standard">
    <xccdf:title xmlns:xhtml="http://www.w3.org/1999/xhtml" xml:lang="en-US" override="true">Standard System Security Profile for Debian 10 [CUSTOMIZED]</xccdf:title>
    <xccdf:description xmlns:xhtml="http://www.w3.org/1999/xhtml" xml:lang="en-US" override="true">This profile contains rules to ensure standard security baseline
of a Debian 10 system. Regardless of your system's workload
all of these checks should pass.</xccdf:description>
    <xccdf:select idref="xccdf_org.ssgproject.content_rule_sshd_disable_root_login" selected="false"/>
  </xccdf:Profile>
</xccdf:Tailoring>`

**Comment by jan-cerny** [comment]
@markmal Do you use the correct profile ID? If you want to use the customized profile you have to pass to `oscap` the ID of the customized profile` instead of the ID of the original profile. In your example it should be `--profile xccdf_org.ssgproject.content_profile_standard_customized_TC`.

**Comment by markmal** [comment]
Yes, this works!
THANK YOU!
