### ISSUE TITLE
Running a custom remediation script results into artificial double quotes to be inserted around the inserted value

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/openscap#174]
Description of problem:
------------------------------

Use the following remediation script (for testing purpose can be used on some artificially failing rule):
```
# platform = Red Hat Enterprise Linux 7
. /usr/share/scap-security-guide/remediation_functions

# Install required packages
package_command install esc
package_command install pam_pkcs11

# Define constants to be reused below
SP="[[:space:]]"
PAM_PKCS11_CONF="/etc/pam_pkcs11/pam_pkcs11.conf"

# Ensure OCSP is turned on in $PAM_PKCS11_CONF
# 1) First replace any occurrence of 'none' value of 'cert_policy' key setting with the correct configuration
sed -i "s/^${SP}*cert_policy${SP}=${SP}none;/cert_policy = ca, ocsp_on, signature;/g" "$PAM_PKCS11_CONF"
# 2) Then append 'ocsp_on' value setting to each 'cert_policy' key in $PAM_PKCS11_CONF configuration line,
# which does not contain it yet
sed -i "/^${SP}*cert_policy${SP}=.*;/ {/ocsp_on/! s/^${SP}*cert_policy${SP}=${SP}\(.*\);/cert_policy = \1, ocsp_on;/}" "$PAM_PKCS11_CONF"

# Enable smartcard authentication (but allow also other ways
# to login not to possibly cut off the system in question)
authconfig --enablesmartcard --updateall
```

<b>Note:</b> Normally this remediation script is present for the ```smartcard_auth``` rule of the PCI-DSS profile of scap-security-guide content for RHEL-7 system.

The sed command snippet at line 17 of the aforementioned remediation script:
```
17 sed -i "/^${SP}*cert_policy${SP}=.*;/ {/ocsp_on/! s/^${SP}*cert_policy${SP}=${SP}\(.*\);/cert_policy = \1, ocsp_on;/}" "$PAM_PKCS11_CONF"
```
should append ```ocsp_on``` value to each row in the ```cert_policy``` row of the ```/etc/pam_pkcs11/pam_pkcs11.conf``` configuration file, if the ```oscp_on``` is not present on that ```cert_policy``` row yet. Example:
```
cert_policy = ca, signature;
```
should be turned into
```
cert_policy = ca, signature, ocsp_on;
```

Running the above remediation script directly in Bash actually performs, what's expected above.

But using it as a remediation script for some XCCDF rule and running it (after failing rule check) within the remediation procedure results into the following line to be created:
```
cert_policy = ca, signature, "ocsp_on";
```

Yes, only the double quotes placed around the ```ocsp_on``` value being, what's the difference.

Though I understand this is very seldom corner case (we will probably rewrite that remediation script itself for the purpose of the scap-security-guide project it to behave as expected), the reasons for this behaviour should be inspected. Initial assumption being if the remediation spawns another child process, double quotes are placed around arguments of that child process. But this might be completely wrong assumption, and the reason for this behavior might be completely different.

Thank you for the research, Jan.

**Comment by mpreisler** [comment]
I recall @iankko mentioning that this is *most likely* related to something in the environment. Running the script with `bash --norc` reproduces the behavior outside `oscap`.

I will leave this open until @iankko confirms but this seems to be a bug in the remediation script.

**Comment by iankko** [comment]
@mpreisler 
> I recall @iankko mentioning that this is most likely related to something in the environment. Running the script with bash --norc reproduces the behavior outside oscap.
> I will leave this open until @iankko confirms but this seems to be a bug in the remediation script.

Have investigated further and got a more detailed / concrete reproducer. The issue doesn't happen when ```authconfig --enablesmartcard --updateall``` command isn't run within that remediation script (in that case 'ocps_on' is appended correctly -- without quotes into all ```cert_policy``` rows of ```/etc/pam_pkcs11/pam_pkcs11.conf``` configuration file).

But it is present when:
* first that sed script is run within remediation, and also
* ```authconfig --enablesmartcard --updateall``` command is run within that remediation.

So instead of openscap issue, this rather seems to be problem of authconfig command. Will report the bug against the authconfig component (feel free to ignore this report as it's not fault of openscap).
