### ISSUE TITLE
Centos stopped working. no dictionary file. this did work on early releases of centos7 but no longer working in the current releases.

### ISSUE THREAD

**Issue by jalbrizio** [OpenSCAP/openscap#1750]
- Is this an issue with SCAP Workbench?
    - If so, report it here: https://github.com/OpenSCAP/scap-workbench/issues
- Is this an issue with SCAP Security Guide (i.e., related to the content of scans, not the scanner proper)?
    - If so, report it here: https://github.com/OpenSCAP/scap-security-guide/issues
- Is this an issue during the OS installation process?
    - If so, report it here: https://github.com/OpenSCAP/oscap-anaconda-addon/issues

Thanks!

#### Description of Problem:

Centos stopped working. no dictionary file. this did work on early releases of centos7 but no longer working in the current releases

#### OpenSCAP Version:
latest 

#### Operating System & Version:
Centos7 and 8

#### Steps to Reproduce:

oscap xccdf eval --profile stig --results ./oscap-results-2021.html --cpe  /root/openscap/cpe/openscap-cpe-dict.xml /usr/share/xml/scap/ssg/content/ssg-rhel7-xccdf.xml

or git pull the latest from github

oscap xccdf eval --profile stig --results ./oscap-results-2021.html --cpe  /root/openscap/cpe/openscap-cpe-dict.xml /usr/share/xml/scap/ssg/content/ssg-rhel7-xccdf.xml

usr/share/xml/scap/ssg/content/ no longer has centos files. niether does the latest release from github

#### Actual Results:
all items have Result  notapplicable

#### Expected Results:
Pass or fail items

**Comment by marcin-sowa** [comment]
We have the same issue. CentOS dict/profiles are missing now. What happen?

**Comment by ggbecker** [comment]
We have recently added a piece of code in RHEL spec files that will re-enable the centos files in /usr/share/xml/scap/ssg/content/. Please check: https://git.centos.org/rpms/scap-security-guide/pull-request/1#comment-806

**Comment by marcin-sowa** [comment]
@jalbrizio, You can use this to fix existing RedHat dictionaries, so they can work on CentOS.

```
sudo sed -i \
  -e 's|idref="cpe:/o:redhat:enterprise_linux|idref="cpe:/o:centos:centos|g' \
  -e 's|ref_id="cpe:/o:redhat:enterprise_linux|ref_id="cpe:/o:centos:centos|g' \
  /usr/share/xml/scap/ssg/content/ssg-rhel*.xml
```

**Comment by evgenyz** [comment]
Dictionaries belong to the content, we are getting rid of them in OpenSCAP.
