### ISSUE TITLE
Not applicable not counted in results top bar

### ISSUE THREAD

**Issue by cipherboy** [OpenSCAP/openscap#1751]
#### Description of Problem:

Consider two different versions of content, where some rules are not applicable:

![Screenshot from 2021-05-10 09-33-41](https://user-images.githubusercontent.com/914030/117667433-df8ed500-b172-11eb-88a2-b3402a303e58.png)

![Screenshot from 2021-05-10 09-33-57](https://user-images.githubusercontent.com/914030/117667435-e0276b80-b172-11eb-8def-55b2e01eb831.png)

In particular, both had 283 rules according to `scap-workbench`. However, because 9 rules were marked not applicable, it _looks_ like the first one only had 274 (by adding 186+55+33). Additionally, the second run had 1 rule marked not applicable, which shows the resulting count at 282.

#### OpenSCAP Version:

```
root@ubuntu-2004-base:~# apt show libopenscap8
Package: libopenscap8
Version: 1.2.16-2ubuntu3.2
Priority: extra
Section: universe/libs
Source: openscap
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Pierre Chifflier <pollux@debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 66.2 MB
Depends: libapt-pkg6.0 (>= 1.9~), libbz2-1.0, libc6 (>= 2.17), libcap2 (>= 1:2.10), libcurl4 (>= 7.16.2), libdbus-1-3 (>= 1.9.14), libgcc-s1 (>= 3.0), libgcrypt20 (>= 1.8.0), libldap-2.4-2 (>= 2.4.7), libpcre3, libselinux1 (>= 1.32), libstdc++6 (>= 5.2), libxml2 (>= 2.7.4), libxslt1.1 (>= 1.1.25)
Conflicts: libopenscap0, libopenscap1, libopenscap3
Replaces: libopenscap0, libopenscap1, libopenscap3
Homepage: http://www.open-scap.org/
Download-Size: 2,483 kB
APT-Manual-Installed: yes
APT-Sources: http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages
Description: Set of libraries enabling integration of the SCAP line of standards
 OpenSCAP is a set of open source libraries providing an easier path
 for integration of the SCAP line of standards. SCAP is a line of
 standards managed by NIST with the goal of providing a standard language
 for the expression of Computer Network Defense related information.
 .
 The intended scope of this project is to implement working interface
 wrappers for parsing and querying SCAP content including:
  * Common Vulnerabilities and Exposures (CVE)
  * Common Configuration Enumeration (CCE)
  * Common Platform Enumeration (CPE)
  * Common Vulnerability Scoring System (CVSS)
  * Extensible Configuration Checklist Description Format (XCCDF)
  * Open Vulnerability and Assessment Language (OVAL)
```

#### Operating System & Version:

Ubuntu LTS 20.04

#### Steps to Reproduce:

1. Create a profile with some not applicable results
2. Scan a system which triggers not applicable
3. Compare bars

#### Actual Results:

Counts don't match profile total

#### Expected Results:

Expected either a separate n/a section or n/a rules to be included in "other".

----

Let me know if this has been fixed in 1.3, but I couldn't find any issues/PRs related to it. I'm assuming it is in openscap's xslt content.

**Comment by jan-cerny** [comment]
I think that this issue is still present in 1.3. I suspect this line: https://github.com/OpenSCAP/openscap/blob/maint-1.3/xsl/xccdf-report-impl.xsl#L225 where notapplicable results are added to "ignored". The logic behind it is perhaps this: If they're notapplicable, they aren't evaluated so it's like they aren't selected. This used to make sense in past, but now when we use granular CPEs in SCAP content I agree with your proposal to have a separate section for them.
