### ISSUE TITLE
Incorrect report?

### ISSUE THREAD

**Issue by scrouet-neocase** [OpenSCAP/openscap#1759]
#### Description of Problem:
The system configuration for the Windows Server is correct but the OpenSCAP check reports 'false' rules.

#### OpenSCAP Version:
1.3.4

#### Operating System & Version:
Windows Server 2016

#### Steps to Reproduce:

Run ```
oscap.exe xccdf eval --profile xccdf_mil.disa.stig_profile_CAT_I_Only --results results.xml --report 
 report.html U_MS_Windows_Server_2016_V1R13_STIG_SCAP_1-2_Benchmark
```

#### Actual Results:
The report is generated correctly, but some rules are still 'false' while the system configuration via GPO is correct.

#### Expected Results:
No 'false' rules.

#### Additional Information / Debugging Steps:

**Comment by CheeseyJake** [comment]
I had a similar issue in Windows 10. The issue that I saw was that it appears that Windows' registry value names are case insensitive while OpenSCAP is case sensitive. Changing the registry value name to match the expected casing seems to have helped a bit.
