### ISSUE TITLE
OpenSCAP build error

### ISSUE THREAD

**Issue by paxtsuchi** [OpenSCAP/openscap#1763]
#### Description of Problem:
CMake Error Could not find a pacakge configuration file provided by "pthread" 
(purpose : Building OpenSCAP on Windows using Visual Studio)

#### OpenSCAP Version:
* Master

#### Operating System & Version:
* Windows 10(x64)

#### Steps to Reproduce:

1.  I tried "Building OpenSCAP on Windows using Visual Studio"  

2.  cmake -D ENABLE_PYTHON3=FALSE -D CMAKE_TOOLCHAIN_FILE=c:/devel/vcpkg/scripts/buildsystems/vcpkg.cmake ..

3.  but, step 2 is error
-- Could NOT find DBUS (missing: DBUS_INCLUDE_DIRS DBUS_LIBRARIES)
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
CMake Error at C:/Program Files/CMake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find PCRE (missing: PCRE_LIBRARY PCRE_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindPCRE.cmake:26 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  C:/devel/vcpkg/scripts/buildsystems/vcpkg.cmake:772 (_find_package)
  CMakeLists.txt:109 (find_package)

4. cmake -D ENABLE_PYTHON3=FALSE -D CMAKE_TOOLCHAIN_FILE=c:/devel/vcpkg/scripts/buildsystems/vcpkg.cmake -D PCRE_LIBRARY=C:\devel\vcpkg\packages\pcre_x86-windows\lib\pcre.lib -D PCRE_INCLUDE_DIR=C:\devel\vcpkg\packages\pcre_x86-windows\lib -D LIBXML2_LIBRARY=C:\devel\vcpkg\packages\libxml2_x86-windows\lib\libxml2.lib -D LIBXML2_INCLUDE_DIR=C:\devel\vcpkg\packages\libxml2_x86-windows\lib -D LIBXSLT_LIBRARIES=C:\devel\vcpkg\packages\libxslt_x86-windows\lib -D LIBXSLT_INCLUDE_DIR=C:\devel\vcpkg\packages\libxslt_x86-windows\lib -D ZLIB_LIBRARY=C:\devel\vcpkg\packages\zlib_x86-windows\lib\zlib.lib -D ZLIB_INCLUDE_DIR=C:\devel\vcpkg\packages\zlib_x86-windows\lib -D BZIP2_LIBRARIES=C:\devel\vcpkg\packages\bzip2_x86-windows\lib\bz2.lib -D BZIP2_INCLUDE_DIR=C:\devel\vcpkg\packages\bzip2_x86-windows\lib ..

5. but, step 4 is error
CMake Error at C:/devel/vcpkg/scripts/buildsystems/vcpkg.cmake:772 (_find_package):
  Could not find a package configuration file provided by "pthread" with any
  of the following names:

    pthreadConfig.cmake
    pthread-config.cmake

  Add the installation prefix of "pthread" to CMAKE_PREFIX_PATH or set
  "pthread_DIR" to a directory containing one of the above files.  If
  "pthread" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:151 (find_package)

**Comment by evgenyz** [comment]
This is how we build on Windows in our CI. I hope it could help figuring out the problem: https://ci.appveyor.com/project/OpenSCAP/openscap/builds/39604211

**Comment by paxtsuchi** [comment]
Thask for your help.

I share how to solve above issue.

## Causes
.vcpkg downloads libraries default 32bit. (.\vcpkg install curl libxml2 libxslt bzip2 pcre pthreads getopt-win32)
my system enviroment windows(x64) So, CMake tried to generate windows x64 solution.
but Not Exist x64 libaries 


## Solutions
case 1 build x86 windows from command line with cmake(option:-A Win32)
```
ex]
cmake -D ENABLE_PYTHON3=FALSE -A Win32 -D CMAKE_TOOLCHAIN_FILE=c:/devel/vcpkg/scripts/buildsystems/vcpkg.cmake ..
```
case 2. Download 64bit libraries Using vcpkg(option:x64-windows)
```
ex]
.\vcpkg install curl:x64-windows libxml2:x64-windows libxslt:x64-windows bzip2:x64-windows pcre:x64-windows pthreads:x64-windows getopt-win32:x64-windows
```

**Comment by cyungmann** [comment]
It appears that instead of specifying the platform for each vcpkg package individually, you can simply pass `--triplet x64-windows`, e.g.

`.\vcpkg install --triplet x64-windows curl libxml2 libxslt bzip2 pcre pthreads getopt-win32`

Note also that starting with the September 2023 vcpkg release, the default triplet will change from x86-windows to the detected host triplet. See https://devblogs.microsoft.com/cppblog/vcpkg-2023-02-24-release-default-triplet-changes-risc-v-support-bug-fixes-and-more/#upcoming-default-triplet-changes
