### ISSUE TITLE
Single rule evaluation doesn't work when the rule `requires` another one

### ISSUE THREAD

**Issue by yuumasato** [OpenSCAP/openscap#1814]
#### Description of Problem:

The `--rule` mode doesn't work as expected when the rule has an `xccdf:requires`.

#### OpenSCAP Version:
1.3.5 

#### Operating System & Version:
Fedora/RHEL

#### Steps to Reproduce:

1. Get RHEL-8 Cac/content from 0.1.58
2. On a RHEL-8 machine
3. `oscap xccdf eval --profile ospp --rule xccdf_org.ssgproject.content_rule_sshd_set_idle_timeout ssg-rhel8-ds.xml `

#### Actual Results:
Nothing was evaluated, no warning no error:
```console
$ oscap xccdf eval --profile ospp --rule xccdf_org.ssgproject.content_rule_sshd_set_idle_timeout ssg-rhel8-ds.xml 
WARNING: Datastream component 'scap_org.open-scap_cref_security-data-oval-com.redhat.rhsa-RHEL8.xml' points out to the remote 'https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL8.xml'. Use '--fetch-remote-resources' option to download it.
WARNING: Skipping 'https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL8.xml' file which is referenced from datastream
WARNING: Skipping ./security-data-oval-com.redhat.rhsa-RHEL8.xml file which is referenced from XCCDF content
```

#### Expected Results:
Either:
1) `oscap` warns that the rule has a `xccdf:requires` that was not satisfied, thus the target `--rule` was not evaluated. And provide an option to force selection of the required rules. (But in `--rule` mode any `xccdf:requires` is not satisfied by definition).
2) (Prefered by me) `oscap` identifies the `xccdf:requires` and selects it together with the target `--rule`, and the logs register that additional rules were selected to satisfy the target `--rule`.

#### Additional Information / Debugging Steps:
The `xccdf:conflicts` should not be a problem for `--rule` mode, but should get a log entry when a conflict causes a rule to be unselected.

**Comment by jan-cerny** [comment]
@yuumasato 

I have discovered that openscap in the single rule mode can evaluate rule that require other rule, but only if the required rule is also a part of the currently evaluated profile. If the required rule isn't a part of the evaluated profile, it doesn't work. 

There is a workaround: use `--profile '(all)'` instead of  `--profile ospp`.

**Comment by jan-cerny** [comment]
@yuumasato amazing!
Actually, there are 2 similar rules in our content: sshd_set_keepalive and sshd_set_keepalive_0, the question is which of them should be in the requires field and selected in the profile.
