### ISSUE TITLE
Every other unselect argument in autotailor is ignored.

### ISSUE THREAD

**Issue by watsonjm** [OpenSCAP/openscap#1817]
#### Description of Problem:
I'm using autotailor to remove a few rules for scanning some containers using oscap-podman. It appears that every other (2/4/6) rule is skipped. 

#### OpenSCAP Version:
OpenSCAP command line tool (oscap) 1.3.4,

#### Operating System & Version:
RHEL 8.4 on an Azure VM

#### Steps to Reproduce:
1. `autotailor -u package_usbguard_installed -u network_configure_name_resolution -u no_files_unowned_by_user -u configure_usbguard_auditbackend -u package_rng-tools_installed -u ssh_client_rekey_limit -p stig_tailored -o tailoring.xml /usr/share/xml/scap/ssg/content/ssg-rhel8-ds-1.2.xml xccdf_org.ssgproject.content_profile_stig`
2.  `sudo oscap-podman <IMAGE ID> xccdf eval --fetch-remote-resources --profile xccdf_org.ssgproject.content_profile_stig_tailored --results results.xml --report report.html --tailoring-file tailoring.xml /usr/share/xml/scap/ssg/content/ssg-rhel8-ds-1.2.xml`

#### Actual Results:
network_configure_name_resolution, configure_usbguard_auditbackend, ssh_client_rekey_limit will all be ignored and still checked in the rules. If you swap all of the even & odd rules in your autotailor command, those 3 will be checked and the new odd-numbered rules will be ignored and still checked. 

#### Expected Results:
All rules should be unselected instead of only odd-numbered ones.

#### Additional Information / Debugging Steps:
You can use this command for autotailor to compare your results:
`autotailor -u network_configure_name_resolution -u no_files_unowned_by_user -u configure_usbguard_auditbackend -u package_rng-tools_installed -u ssh_client_rekey_limit -u package_usbguard_installed -p stig_tailored -o tailoring.xml /usr/share/xml/scap/ssg/content/ssg-rhel8-ds-1.2.xml xccdf_org.ssgproject.content_profile_stig`

**Comment by watsonjm** [comment]
It looks like running the autotailor output through xmllint fixes the issue
`xmllint --format tailoring.xml > tailoring_linted.xml`
and then using that in the eval command:
`sudo oscap-podman <IMAGE ID> xccdf eval --fetch-remote-resources --profile xccdf_org.ssgproject.content_profile_stig_tailored --results results.xml --report report.html --tailoring-file tailoring_linted.xml /usr/share/xml/scap/ssg/content/ssg-rhel8-ds-1.2.xml`

**Comment by evgenyz** [comment]
Autotailor bug has been fixed here: https://github.com/OpenSCAP/openscap/pull/1987.
