### ISSUE TITLE
xpath missing in during install on Debian 11 bullseye

### ISSUE THREAD

**Issue by egberts** [OpenSCAP/openscap#1819]
#### Description of Problem:

attempted source install on Debian 11 (bullseye) using `git clone` from here.

#### OpenSCAP Version:

default branch is refs/heads/maint-1.3

#### Operating System & Version:

Debian 11 (bullseye)

#### Steps to Reproduce:

1.  Follow install instructions for source-based cmake.
2. run ctest -V
2. 
3. 

#### Actual Results:

`I require xpath tool but it is not installed. Aborting.`

All of some 29 test failed.

#### Expected Results:

pass at least 1 test.

#### Additional Information / Debugging Steps:

Debian 11 workaround is to run:

    apt install libxml-xpath-perl

Tested, passed all tested, reesolved.

**Comment by evgenyz** [comment]
Err, `libxml-xpath-perl` or `perl-XML-XPath` in case of Fedora is the build-time or devel dependency. It is used in tests, which are obviously not part of the binary package. If you want to develop openscap (and run tests), install build-time dependencies.
