### ISSUE TITLE
yaml-filter_object not found

### ISSUE THREAD

**Issue by egberts** [OpenSCAP/openscap#1822]
#### Description of Problem:

yaml-filter module not found.

#### OpenSCAP Version:

master branch 

#### Operating System & Version:

Debian 11

#### Steps to Reproduce:

1. git —recurse-submodules clone https//github.com/OpenSCAP/openscap
2. cd openscap
3. cd build
4. cmake ,,/
5. make 
6. # changed my mind, want latest stuff
7. cd ..
3. git status. # see that `maint-1.3` tag/branch is the HEAD
4. `git checkout master`
5. cd build
6. cmake ../

#### Actual Results:

yaml-filter_object not found
define SOURCES …

#### Expected Results:

build without error after changing Git branch/tag with respect to yam-filter module

**Comment by evgenyz** [comment]
Well, yeah, CMake is not really that bullet-proof. If you encounter it again and could be able to provide more information about reasons for CMake to behave in that weird way feel free to reopen this bug.
