### ISSUE TITLE
 notchecked results

### ISSUE THREAD

**Issue by ionutstoican** [OpenSCAP/openscap#1834]
Hi,
 I have an Oracle Linux 8 system where I want to run some security checks.  The following openscap packages are installed:

  rpm -qa|grep scap
  openscap-scanner-1.3.4-6.0.1.el8_4.x86_64
  openscap-1.3.4-6.0.1.el8_4.x86_64
  scap-security-guide-0.1.57-3.0.1.el8_4.noarch

Then, run oscap scan:

oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_hipaa ssg-ol8-ds.xml

The results are pass/fail, as expected. But for some of rules the result is not checked, as below: 

Title Encrypt Partitions
Rule  xccdf_org.ssgproject.content_rule_encrypt_partitions
Result        notchecked

Do you have any suggestion? Is there any xml file that is missing from my system?

ls -al|grep ol8
-rw-r--r-- 1 root root     6341 Nov  2 20:01 ssg-ol8-cpe-dictionary.xml
-rw-r--r-- 1 root root   107649 Nov  2 20:01 ssg-ol8-cpe-oval.xml
-rw-r--r-- 1 root root 14254589 Nov  2 20:01 ssg-ol8-ds-1.2.xml
-rw-r--r-- 1 root root 14254903 Nov  2 20:01 ssg-ol8-ds.xml
-rw-r--r-- 1 root root  1033869 Nov  2 20:01 ssg-ol8-ocil.xml
-rw-r--r-- 1 root root  2991843 Nov  2 20:01 ssg-ol8-oval.xml
-rw-r--r-- 1 root root  9018941 Nov  2 20:01 ssg-ol8-xccdf.xml

**Comment by ggbecker** [comment]
That's because the rule has no automated check, it only has the rule description and how to check manually: https://github.com/ComplianceAsCode/content/tree/master/linux_os/guide/system/software/disk_partitioning/encrypt_partitions
