### ISSUE TITLE
Rule from `requires` element is not evaluated during `oscap xccdf eval --rule ...` scan

### ISSUE THREAD

**Issue by mildas** [OpenSCAP/openscap#1854]
#### Description of Problem:
During `sshd_set_idle_timeout` rule scan, I have noticed that `sshd_set_keepalive_0` is not evaluated.

The `sshd_set_idle_timeout` rule check `ClientAliveInterval` value in `/etc/ssh/sshd_config` file. The rule requires `sshd_set_keepalive_0` rule, see [sshd_set_idle_timeout rule.yml](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/services/ssh/ssh_server/sshd_set_idle_timeout/rule.yml#L68) - if `ClientAliveCountMax` value is `0`.

#### OpenSCAP Version:
openscap-1.3.5-10.el8.x86_64

#### scap-security-guide Version:
a8eee3a

#### Operating System & Version:
RHEL 8

#### Steps to Reproduce:

1. Update `/etc/ssh/sshd_config` to include:
```
# Correct value according to sshd_set_idle_timeout
ClientAliveInterval 10
# Bad value according to sshd_set_keepalive_0. It must be 0
ClientAliveCountMax 100
``` 
2. `# oscap xccdf eval --profile '(all)' --rule xccdf_org.ssgproject.content_rule_sshd_set_idle_timeout --results-arf arf-result.xml ssg-rhel8-ds.xml`

#### Actual Results:
```
Title   Set SSH Idle Timeout Interval
Rule    xccdf_org.ssgproject.content_rule_sshd_set_idle_timeout
Ident   CCE-80906-1
Result  pass
```

#### Expected Results:
```
Title   Set SSH Idle Timeout Interval
Rule    xccdf_org.ssgproject.content_rule_sshd_set_idle_timeout
Ident   CCE-80906-1
Result  fail
```

#### Additional Information / Debugging Steps:
In the datastream, I see `<xccdf-1.2:requires idref="xccdf_org.ssgproject.content_rule_sshd_set_keepalive_0"/>` element under `sshd_set_idle_timeout` rule. Thus, I would expect `sshd_set_keepalive_0` to be part of the `sshd_set_idle_timeout` check. It is not there, see graph from `arf-to-graph`:

![image](https://user-images.githubusercontent.com/18598137/161949330-df847dd7-049d-46e5-84fb-2188236b202c.png)

In #1814, `--profile '(all)'` was recommended. It doesn't work with it.
Previously, `extend_definition` was part of the rule check. But it got [removed recently](https://github.com/ComplianceAsCode/content/pull/8338/commits/130fb8a3424945b14fc559dfe358e5b3140311e4) and `ClientAliveCountMax` is not taken into account.

**Comment by jan-cerny** [comment]
@mildas Hi Milan. 

You have used the `--rule` option. The `--rule` option always evaluates a single rule. Don't expect that it will evaluate multiple rules.

Recently (in OpenSCAP 1.3.6) the `--rule` option has been improved and it was clarified in the man page, so I will cite the updated version:

 --rule RULE
Select a particular rule from XCCDF document. Only this rule will be evaluated. Any other rules required by this rule won't be evaluated. Rule will use values according to the selected profile. If no  profile  is selected, default values are used. This option can be used multiple times to specify multiple rules at once.

The `--profile '(all)'` was a workaround for a situation when the rule required by the rule specified by the `--rule` option wasn't part of the evaluated profile which caused that the rule specified by the `--rule` option isn't evaluated.

I think that you might miss the purpose of `<xccdf:requires>` elements. They don't extend the rules with additional checks. Instead, they serve as safeguards for rule selection in profiles. If you create a profile that contains a rule 1 which requires a rule 2 which isn't selected in your profile then the rule 1 will be skipped. They have a nice example of it in section 7.2.3.3.2 in XCCDF specification.

So the "Expected results" can't be achieved using `xccdf:requires` elements, instead, you probably want the OVAL check to use an extend_definition.

**Comment by mildas** [comment]
Thank you @jan-cerny for the explanation. I get it now. Makes sense and it is not issue on openscap side, thus closing this issue.
