### ISSUE TITLE
RFE: provide ./configure --disable-docs

### ISSUE THREAD

**Issue by isimluk** [OpenSCAP/openscap#186]
It would allow us to run `make distcheck` without doxygen and asciidoctor.

When I grab rhel7 test machine, I always swear on missing asciidoctor.

**Comment by mpreisler** [comment]
Do we actually run asciidoctor as part of the build? I doubt that.

**Comment by isimluk** [comment]
Not sure about the build, but description mentions `make distcheck`. :)

**Comment by isimluk** [comment]
Anyway, I no longer experience the bug. It can be closed. 🍰

**Comment by mpreisler** [comment]
@isimluk is correct, we do run it as part of dist-hook.

```
dist-hook: ChangeLog
	cd $(distdir)/docs && doxygen Doxyfile
	cd $(distdir)/docs/manual && asciidoctor -b html5 manual.adoc
```

**Comment by redhatrises** [comment]
@jan-cerny has this been fixed? I vaguely remember you working on this for CMake.

**Comment by jan-cerny** [comment]
@redhatrises 
On `maint-1.2` which uses autotools the `dist-hook` still depends on `doxygen` and `asciidoctor`.

However, you're correct that in CMake in `maint-1.3` this was fixed. There is an option `ENABLE_DOCS` in CMake which turns the docs build on or off. By default it is set to `FALSE`, so the docs doesn't slow down every build. Moreover, CMake checks at the configure time if `asciidoc` and `doxygen` is available on the machine. I think we can close this issue. The fix has been done in https://github.com/OpenSCAP/openscap/pull/1169/files
