### ISSUE TITLE
1.3.6 + master (bd41965d): test suite is failing

### ISSUE THREAD

**Issue by kloczek** [OpenSCAP/openscap#1865]
#### Description of Problem:
Looks like cmake test suite is failing in several units

#### OpenSCAP Version:
1.3.6 + master up to bd41965d.

#### Operating System & Version:
Linux x86/64

#### Steps to Reproduce:
1.  build openscap
2.  execute `ctest -vv`

#### Expected Results:
Test suite should not fail

#### Additional Information / Debugging Steps:
cmake setup
<details>

```console
[tkloczko@devel-g2v x86_64-redhat-linux-gnu]$ cmake -L
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.


CMake Error: The source directory "/home/tkloczko/rpmbuild/BUILD/openscap-1.3.6/x86_64-redhat-linux-gnu" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
-- Cache values
ASCIIDOC_EXECUTABLE:FILEPATH=/usr/bin/asciidoc
CMAKE_BUILD_TYPE:STRING=RelWithDebInfo
CMAKE_INSTALL_PREFIX:PATH=/usr
ENABLE_DOCS:BOOL=ON
ENABLE_MITRE:BOOL=OFF
ENABLE_OSCAP_UTIL:BOOL=ON
ENABLE_OSCAP_UTIL_AS_RPM:BOOL=ON
ENABLE_OSCAP_UTIL_AUTOTAILOR:BOOL=ON
ENABLE_OSCAP_UTIL_CHROOT:BOOL=ON
ENABLE_OSCAP_UTIL_DOCKER:BOOL=ON
ENABLE_OSCAP_UTIL_PODMAN:BOOL=ON
ENABLE_OSCAP_UTIL_SSH:BOOL=ON
ENABLE_OSCAP_UTIL_VM:BOOL=ON
ENABLE_PROBES:BOOL=ON
ENABLE_PROBES_INDEPENDENT:BOOL=ON
ENABLE_PROBES_LINUX:BOOL=ON
ENABLE_PROBES_SOLARIS:BOOL=OFF
ENABLE_PROBES_UNIX:BOOL=ON
ENABLE_PROBES_WINDOWS:BOOL=OFF
ENABLE_PYTHON3:BOOL=ON
ENABLE_SCE:BOOL=ON
ENABLE_TESTS:BOOL=ON
ENABLE_VALGRIND:BOOL=OFF
ENV_PRESENT:FILEPATH=/usr/bin/env
GCONF_INCLUDE_DIR:PATH=GCONF_INCLUDE_DIR-NOTFOUND
GCONF_LIBRARY:FILEPATH=
GIT_EXECUTABLE:FILEPATH=/usr/bin/git
LIBXSLT_EXSLT_INCLUDE_DIR:PATH=/usr/include
LIBXSLT_LIBRARY:FILEPATH=/usr/lib64/libxslt.so
OPENDBX_INCLUDE_DIR:PATH=OPENDBX_INCLUDE_DIR-NOTFOUND
OPENDBX_LIBRARY:FILEPATH=OPENDBX_LIBRARY-NOTFOUND
OPENSCAP_ENABLE_MD5:BOOL=ON
OPENSCAP_ENABLE_SHA1:BOOL=ON
OPENSCAP_PROBE_INDEPENDENT_ENVIRONMENTVARIABLE:BOOL=ON
OPENSCAP_PROBE_INDEPENDENT_ENVIRONMENTVARIABLE58:BOOL=ON
OPENSCAP_PROBE_INDEPENDENT_FAMILY:BOOL=ON
OPENSCAP_PROBE_INDEPENDENT_FILEHASH:BOOL=ON
OPENSCAP_PROBE_INDEPENDENT_FILEHASH58:BOOL=ON
OPENSCAP_PROBE_INDEPENDENT_SYSTEM_INFO:BOOL=ON
OPENSCAP_PROBE_INDEPENDENT_TEXTFILECONTENT:BOOL=ON
OPENSCAP_PROBE_INDEPENDENT_TEXTFILECONTENT54:BOOL=ON
OPENSCAP_PROBE_INDEPENDENT_VARIABLE:BOOL=ON
OPENSCAP_PROBE_INDEPENDENT_XMLFILECONTENT:BOOL=ON
OPENSCAP_PROBE_LINUX_IFLISTENERS:BOOL=ON
OPENSCAP_PROBE_LINUX_INETLISTENINGSERVERS:BOOL=ON
OPENSCAP_PROBE_LINUX_PARTITION:BOOL=ON
OPENSCAP_PROBE_LINUX_RPMINFO:BOOL=ON
OPENSCAP_PROBE_LINUX_RPMVERIFY:BOOL=ON
OPENSCAP_PROBE_LINUX_RPMVERIFYFILE:BOOL=ON
OPENSCAP_PROBE_LINUX_RPMVERIFYPACKAGE:BOOL=ON
OPENSCAP_PROBE_LINUX_SELINUXBOOLEAN:BOOL=ON
OPENSCAP_PROBE_LINUX_SELINUXSECURITYCONTEXT:BOOL=ON
OPENSCAP_PROBE_LINUX_SYSTEMDUNITDEPENDENCY:BOOL=ON
OPENSCAP_PROBE_LINUX_SYSTEMDUNITPROPERTY:BOOL=ON
OPENSCAP_PROBE_UNIX_DNSCACHE:BOOL=ON
OPENSCAP_PROBE_UNIX_FILE:BOOL=ON
OPENSCAP_PROBE_UNIX_FILEEXTENDEDATTRIBUTE:BOOL=ON
OPENSCAP_PROBE_UNIX_INTERFACE:BOOL=ON
OPENSCAP_PROBE_UNIX_PASSWORD:BOOL=ON
OPENSCAP_PROBE_UNIX_PROCESS:BOOL=ON
OPENSCAP_PROBE_UNIX_PROCESS58:BOOL=ON
OPENSCAP_PROBE_UNIX_ROUTINGTABLE:BOOL=ON
OPENSCAP_PROBE_UNIX_RUNLEVEL:BOOL=ON
OPENSCAP_PROBE_UNIX_SHADOW:BOOL=ON
OPENSCAP_PROBE_UNIX_SYMLINK:BOOL=ON
OPENSCAP_PROBE_UNIX_SYSCTL:BOOL=ON
OPENSCAP_PROBE_UNIX_UNAME:BOOL=ON
OPENSCAP_PROBE_UNIX_XINETD:BOOL=ON
OSCAP_DOCKER_PYTHON:STRING=/usr/bin/python3
OSCAP_TEMP_DIR:STRING=/tmp
PROCPS_INCLUDE_DIR:PATH=PROCPS_INCLUDE_DIR-NOTFOUND
PROCPS_LIBRARY:FILEPATH=PROCPS_LIBRARY-NOTFOUND
SEAP_MSGID_BITS:STRING=32
SED_EXECUTABLE:FILEPATH=/usr/bin/sed
VALGRIND_PRESENT:FILEPATH=/usr/bin/valgrind
WANT_BASE64:BOOL=TRUE
WANT_XBASE64:BOOL=FALSE
WITH_CRYPTO:STRING=gcrypt
```
</details>

**Comment by evgenyz** [comment]
Hey, you have to be a bit more specific than `Linux x86/64` about the OS version you're running.

**Comment by evgenyz** [comment]
> Looking on the code I was not able to find anything kernel version specific .. nevertheless I'm using kernel version 5.17.8.

Please, provide content of `/etc/os-release`.

**Comment by kloczek** [comment]
I'm using my own distribution and I'm packaging for it OpenSCAP.
If you want me to perform some diagnostics please let me know.

**Comment by evgenyz** [comment]
Well, you have some configuration problems with systemd, SELinux and, probably, libxml (not sure here) in you distribution.

**Comment by kloczek** [comment]
systemd and libxml2? .. highly unlikely as none of other my packages have any issues with those two
```console
[tkloczko@devel-g2v SPECS]$ grep BuildRequires:.*systemd *.spec -l | wc -l
178
[tkloczko@devel-g2v SPECS]$ grep BuildRequires:.*libxml-2.0 *.spec -l | wc -l
163
[tkloczko@devel-g2v SPECS]$ grep BuildRequires:.*libxml2-devel *.spec -l | wc -l
30
```
SELinux is messy as always however none of the test suites of other packages which depends on SELinux are failing.

Nevertheless would be really appreciated more details than only vectors ..
FYI: test suite is executed on system with enabled SELinux and it uses btrfs.

**Comment by kloczek** [comment]
gentle ping .. 🤔

**Comment by evgenyz** [comment]
Our CI builds and tests in Ubuntu and Fedora (multiple versions). The scanner works as intended there (more or less). If you can identify specific problem in the code or build system, which is specific to other distros, we can try and fix it.

We are not going to debug OpenSCAP on the platforms we have no access to.

**Comment by kloczek** [comment]
> Our CI builds and tests in Ubuntu and Fedora (multiple versions). The scanner works as intended there (more or less). If you can identify specific problem in the code or build system, which is specific to other distros, we can try and fix it.

How you are testing that on Fedora?
Are you doing that on Fedora system image using custom set of settings/compile and link time flags instead what is implemented in fedora spec file?
If yes you are not testing Fedora build procedure but your own version of that procedure.
In such scenario you are not been able to reproduce what I'm doing.

> We are not going to debug OpenSCAP on the platforms we have no access to.

I've did not ask to debug anything.
If you have any suggestions what I can try to do to diagnose this fail please let me know what exactly you want me to do.

**Comment by evgenyz** [comment]
> How you are testing that on Fedora? Are you doing that on Fedora system image using custom set of settings/compile and link time flags instead what is implemented in fedora spec file? If yes you are not testing Fedora build procedure but your own version of that procedure. In such scenario you are not been able to reproduce what I'm doing.

That's how:
- https://github.com/OpenSCAP/openscap/actions/runs/7845898940/job/21411366888
- https://github.com/OpenSCAP/openscap/pull/2081/checks?check_run_id=21406366348

With this spec file: https://github.com/OpenSCAP/openscap/blob/maint-1.3/openscap.spec

> > We are not going to debug OpenSCAP on the platforms we have no access to.
> 
> I've did not ask to debug anything. If you have any suggestions what I can try to do to diagnose this fail please let me know what exactly you want me to do.

- Use latest version of `maint-1.3` branch.
- Understand how `--verbose=` flag works.
- Find differences in the behavior of the scanner based on the logs and/or use `gdb` if necessary.
- Open issues case-by-case, with cmake configure and build logs, isolated DEVEL logs of the problematic session (keep it as simple as possible) and a description of behavior discrepancy.

It might or might not allow us to understand and fix portability problems.
