### ISSUE TITLE
Provide full names of SCAP Security Guides

### ISSUE THREAD

**Issue by Ricky-Tigg** [OpenSCAP/openscap#1888]
#### Description of problem: 
Hello. An attempt to reveal the full names of SCAP Security Guides in command-line reveals not to be achievable. At best, file names, which are coded, can be obtained, yet involving non-built command functions; illustration in **RPM** systems:
```
$ rpm -ql scap-security-guide | grep '\-ds.xml$' | sed 's+^/usr/share/xml/scap/ssg/content/ssg-++g' | sed 's/-ds.xml$//g' | column
alinux2		debian11	macos1015	rhel7		ubuntu1604
alinux3		debian9		ocp4		rhel8		ubuntu1804
centos7		eks		ol7		rhel9		ubuntu2004
centos8		fedora		ol8		rhv4		ubuntu2204
chromium	firefox		ol9		sl7		uos20
cs9		fuse6		opensuse	sle12		vsel
debian10	jre		rhcos4		sle15
```
Nevertheless for some of them, the product they refer to cannot be determined

#### OpenSCAP Version:
1.3.6

#### Suggestion:
Addition of a new built-in function aimed to display the list of full names of SCAP Security Guides.

_Note_: by accident i discovered [here](https://static.open-scap.org/), then outside the `oscap` function, that those full names were listed. At last this allow to **guess** for some coded names, the full names they mightt be referring to. But that's a guess.

An ideal function would return full names along with files names that deal accordingly with the product, which respective files are in directory /usr/share/xml/scap/ssg/content/, as follows:
```
$ oscap <new command>
Alibaba Cloud Linux 2 (ssg-alinux2-ds.xml)
(...)
```

**Comment by evgenyz** [comment]
The `scap-security-guide` package is an independent entity. The naming is unfortunate but it's legacy stuff. I'd suggest opening an issue in https://github.com/ComplianceAsCode/content/issues. The proposal could be to add autogenerated list of profiles to the description of the package in spec file.

**Comment by jan-cerny** [comment]
@Ricky-Tigg  @evgenyz you can also run `man scap-security-guide` where you have a list of all products and profiles with descriptions and files names.

**Comment by Ricky-Tigg** [comment]
Thank you; i was aware of `man scap-security-guide`'s content. Reported at that ComplianceAsCode/content/issues as 9648.
