### ISSUE TITLE
HTML Guide does not contain profile/description?

### ISSUE THREAD

**Issue by isimluk** [OpenSCAP/openscap#189]
This is quite confusing. For example I go through the policies at http://static.open-scap.org/ssg-guides/ssg-rhel6-guide-index.html and there is missing the highlevel description of what I am looking at.

I think this is high priority for us to fix this.

**Comment by mpreisler** [comment]
How do you envision the fixed guide to look like? Should we show the benchmark desc and then profile desc?

**Comment by isimluk** [comment]
I don't know for sure, however I imagine having greater emphasis on the 'profile description'. If you see the current texts in SSG, we can print profile _before_ the benchmark.

**Comment by mpreisler** [comment]
Done in 461ecf9552c3312e4a455340621eb3ce918a7105

![image](https://cloud.githubusercontent.com/assets/753153/11304545/cf9ca376-8fa8-11e5-8eaa-b02de535db77.png)
