### ISSUE TITLE
Test tests/probes/process58/command_line_extra.sh hangs infinitely

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/openscap#1897]
#### Description of Problem:
During review of the PR https://github.com/OpenSCAP/openscap/pull/1891 we have experienced issues with testing-farm jobs. There were initially some infrastructure problems, but after the infrastructure was fixed and the jobs were rerun, we have discovered that the test fail because of timeout. However, the timeout is very generous - it's 3 hours. So the test didn't finish in time. 

I have executed the test suite locally and I reproduced the issue, the tests were taking huge amount of time. They were stuck at 
tests/probes/process58/command_line_extra.sh for more than 30 minutes. This test never completed.

#### OpenSCAP Version:
current upstream maint-1.3 branch as of 2022-11-25 as of HEAD d10c40e43e1c627912374b8fbdfa1a84967fcc92

#### Operating System & Version:
F36, F 37

#### Steps to Reproduce:

1. cd build
2. cmake .. && make
3. ctest --verbose -R probes/process58/command_line_extra.sh

#### Actual Results:
the test is stuck and never finishes

see the full output with `set -x` at this link: https://pastebin.com/m6Y79Kcr

#### Expected Results:
the test passes and is completed in a finite time

#### Additional Information / Debugging Steps:
It's stuck in the `clean_processes` function which is a cleanup function executed in `trap` call when the test script process exits.

When the `trap` is commented out, it's stuck in the `exit` call.

**Comment by evgenyz** [comment]
It is reproducible only on F37?

**Comment by jan-cerny** [comment]
I have tried only F 37 but from the testing farm results in PR #1891 we can see that now it happens also on F 36 and rawhide systems.

**Comment by jan-cerny** [comment]
I have successfully reproduced this on F 36 virtual machine. I have updated the issue description, I also added there a link to the output of `set -x` and I have also add the second additional information to the "Additional Information / Debugging Steps" section.

**Comment by jan-cerny** [comment]
It reminds me this famous commit :smiley: https://github.com/openscap/openscap/commit/07bd511cc86c66c857b7379933e7c9d2515feded

**Comment by jan-cerny** [comment]
> I wonder if we could instead of juggling zombies use the OpenSCAP process itself for testing command line.

I think the point of the test is to verify whether oscap correctly handles the special case of zombie process.

https://github.com/OpenSCAP/openscap/pull/102/files#diff-01e7af4655d4f0f836fae2fb1a8a3b96b7ab26ccc50b6c9bac20a1e2c035543dR505

**Comment by jan-cerny** [comment]
There is a problem that the test prints out:

`Failed: expected command-line of process with PID=36090 is '\[bash]\ <defunct>' but real is: '[sleep] <defunct>'`

This process with this PID is supposed to be the zombie process. But the zombie shouldn't be a `sleep` command, but it should be a `bash` process, because the zombie is created this way:

`( SHELL_PID=$BASHPID && ( kill -STOP $SHELL_PID && sleep 1 ) ) &`

**Comment by jan-cerny** [comment]
I have discovered that there is a difference in the zombie process command line between F 37 and RHEL 8.6:

RHEL 8.6:

```
[root@ci-vm-10-0-138-73 ~]# ( SHELL_PID=$BASHPID && ( kill -STOP $SHELL_PID && sleep 1 ) ) &
[2] 5281
[root@ci-vm-10-0-138-73 ~]# echo $!
5281

[2]+  Stopped                 ( SHELL_PID=$BASHPID && ( kill -STOP $SHELL_PID && sleep 1 ) )
[root@ci-vm-10-0-138-73 ~]# ps -ostate,pid,cmd --ppid 5281
S     PID CMD
Z    5282 [bash] <defunct>
[root@ci-vm-10-0-138-73 ~]# 
```

Fedora 37:

```
[jcerny@thinkpad openscap{maint-1.3}]$ ( SHELL_PID=$BASHPID && ( kill -STOP $SHELL_PID && sleep 1 ) ) &
[3] 45020

[3]+  Stopped                 ( SHELL_PID=$BASHPID && ( kill -STOP $SHELL_PID && sleep 1 ) )
[jcerny@thinkpad openscap{maint-1.3}]$ echo $!
45020
[jcerny@thinkpad openscap{maint-1.3}]$ ps -ostate,pid,cmd --ppid 45020
S     PID CMD
Z   45022 [sleep] <defunct>
[jcerny@thinkpad openscap{maint-1.3}]$ 
```
