### ISSUE TITLE
xmlcontent_probe not reporting objects without a xpath match causes false positives

### ISSUE THREAD

**Issue by marcusburghardt** [OpenSCAP/openscap#1923]
#### Description of Problem:

During some productization tests it was detected an issue where the OVAL result was invalid when a XML file doesn't match a `xpath`. This issue is better described in #1890 .

In short it was caused because without a `xpath` match it was not possible to determine the correct `datatype`. Previously, the object was reported with an empty `datatype`, like `datatype=""`, which consequently caused an invalid OVAL result.

The patch was introduced by #1891 and the solution there was to not report the object if there was no `xpath` match.

However, this approach revealed another issue.
For example, the `firewalld_sshd_port_enabled` rule needs to ensure the all the custom zone files (the files in `/etc/firewalld/zones`) are indeed allowing `ssh` service. This is checked by searching the following xpath:
`<ind:xpath>/zone/service[@name='ssh']</ind:xpath>`

If the `xpath` is not found in the zone file, it means the service is not allowed and the system should be remediated.
After the #1891 the non-compliant file is ignored and the scanner report a false positive. Consequently the system is not remediated.

#### OpenSCAP Version:

openscap-1.3.7-1 from [1.3.7](https://github.com/OpenSCAP/openscap/releases/tag/1.3.7) release

#### Operating System & Version:

RHEL8 and RHEL9

#### Steps to Reproduce:

This should be better reproduced by executing an automatus test from ComplianceAsCode/content project.

1. ./build_product rhel8
2. ./tests/automatus.py rule --libvirt qemu:///session <vm name> --datastream build/ssg-rhel8-ds.xml --dontclean --remediate-using bash --debug firewalld_sshd_port_enabled

#### Actual Results:

The following test scenarios are expected to fail but are passing during the initial stage:
- customized_zone_without_ssh.fail.sh
- new_zone_without_ssh.fail.sh
- only_nics_configured.fail.sh

In a real environment, the non-compliant system will report a false positive and won't be remediated.

#### Expected Results:

The non-compliant files are reported and remediated.

**Comment by marcusburghardt** [comment]
What would be the impact of setting eg `datatype=string` when `xpath` is not found instead of ignoring the object?

I believe this would be an acceptable option to resolve the invalid OVAL result issue without impacting cases like this with `firewalld`. More cases besides `firewalld` may appear in the future.

**Comment by evgenyz** [comment]
We are talking about this test?

```
    <ind:xmlfilecontent_test id="test_firewalld_sshd_port_enabled_zone_ssh_enabled_etc"
        check="all" check_existence="at_least_one_exists" version="1"
        comment="SSH service is defined in all zones created or modified by the administrator">
      <ind:object object_ref="object_firewalld_sshd_port_enabled_zone_files_etc"/>
      <ind:state state_ref="state_firewalld_sshd_port_enabled_zone_files_etc"/>
    </ind:xmlfilecontent_test>
    
    <ind:xmlfilecontent_object id="object_firewalld_sshd_port_enabled_zone_files_etc" version="1">
      <ind:path>/etc/firewalld/zones</ind:path>
      <ind:filename operation="pattern match">^.*\.xml$</ind:filename>
      <ind:xpath>/zone/service[@name='ssh']</ind:xpath>
    </ind:xmlfilecontent_object>

    <ind:xmlfilecontent_state id="state_firewalld_sshd_port_enabled_zone_files_etc" version="1">
      <ind:xpath>/zone/service[@name='ssh']</ind:xpath>
    </ind:xmlfilecontent_state>
```

**Comment by jan-cerny** [comment]
@marcusburghardt
I think that producing an item when the node specified by XPath doesn't exist would be inconsistent with behavior of all other probes. For example, in textfilecontent54_test, if the given regular expression doesn't match anything the probe doesn't produce any item as well.

Would changing the check_existence to all_exist help here?

**Comment by marcusburghardt** [comment]
Unfortunately changing to `all_exist` doesn't help because the non-compliant file will be ignored anyways. It doesn't appear in the objects list if it is non-compliant.

**Comment by jan-cerny** [comment]
@marcusburghardt thanks

the problem  feels to me similar to the rule uefi_no_removable_media

We want to check whether each zone contains an ssh. So we can check whether the count of nodes matching the `/zone` xpath is equal to count of nodes matching the `/zone/service[@name='ssh']`

**Comment by jan-cerny** [comment]
> What would be the impact of setting eg datatype=string when xpath is not found instead of ignoring the object?

I think that would mean we won't be able to distnighuish between "node doesn't exist" and "node exists and contains an empty string".

**Comment by marcusburghardt** [comment]
> > What would be the impact of setting eg datatype=string when xpath is not found instead of ignoring the object?
> 
> I think that would mean we won't be able to distnighuish between "node doesn't exist" and "node exists and contains an empty string".

I see. Yes, this is another valid case prone to false positives. We are discussing options to workaround this behavior change in the content side. There are some ideas we need to test but if can solve on the content side I believe it would be faster for now.

I am not sure on the impact on other cases similar to `firewalld`, but for the moment the existing rules which use `xmlcontent_probe` are only related to `firewalld`.

**Comment by evgenyz** [comment]
Can we close this bug or it is waiting to be formally closed by a PR in CaC?

**Comment by marcusburghardt** [comment]
The issue was already fixed by changing the OVAL check for this rule in CaC: https://github.com/ComplianceAsCode/content/pull/10162

We can close the issue here.
