### ISSUE TITLE
SARIF report output

### ISSUE THREAD

**Issue by candrews** [OpenSCAP/openscap#1940]
#### Description of Problem:
It would be great if  `openscap` could output `SARIF` formatted reports.

There are many services that can consume SARIF, including [GitHub SARIF support for code scanning](https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning) which would enable easy use of openscap in GitHub Actions as requested in https://github.com/OpenSCAP/openscap/issues/1421.

SARIF can also be converted to many other formats, providing a gateway for easy openscap use in many scenarios.

#### OpenSCAP Version:
1.3.7

#### Operating System & Version:
Linux

#### Steps to Reproduce:
`oscap xccdf eval --datastream-id ds.xml --xccdf-id xccdf.xml  --sarif report.sarif --results xccdf-results.xml scap-ds.xml`

#### Actual Results:
There is no `--sarif` support right now :-)

#### Expected Results:
`report.sarif` contains a SARIF 2.1 JSON file.

**Comment by candrews** [comment]
It would a lot easier if openscap directly output SARIF, but until then, there is a way to convert openscap's XCCDF output to SARIF by using [Mitre’s SAF](https://www.npmjs.com/package/@mitre/saf) then [Microsoft’s SARIF Multitool](https://www.npmjs.com/package/@microsoft/sarif-multitool). I documented this approach at https://candrews.integralblue.com/2023/09/scap-security-and-compliance-scanning-of-docker-images-in-github-actions-and-gitlab-ci/

**Comment by evgenyz** [comment]
Highly unlikely any OpenSCAP developer would work on this. Mostly because it is pretty much entirely out of scope.

But if they do, they will be able to re-open the bug.
