### ISSUE TITLE
enable test_memusage only if OS_LINUX is defined

### ISSUE THREAD

**Issue by orcl-jlana** [OpenSCAP/openscap#1945]
#### Description of Problem:

The tests test_memusage.c uses [read_common_sizet(...)](https://github.com/OpenSCAP/openscap/blob/c8d3c87b49c5e90dbf9b087514e5a1f895d5a287/tests/API/probes/test_memusage.c#L16), but the method is available only [if OS_LINUX is defined](https://github.com/OpenSCAP/openscap/blob/c8d3c87b49c5e90dbf9b087514e5a1f895d5a287/src/common/memusage.c#L59) Otherwise the compilation of the test fails.

#### Actual Results: 

```
...
[ 84%] Linking C executable test_memusage
ld: warning: file /usr/lib/amd64/libexslt.so: attempted multiple inclusion of file
ld: warning: file /usr/lib/64/libpcre.so: attempted multiple inclusion of file
ld: warning: file /usr/lib/64/libcurl.so: attempted multiple inclusion of file
Undefined                       first referenced
 symbol                             in file
read_common_sizet                   CMakeFiles/test_memusage.dir/test_memusage.c.o
ld: fatal: symbol referencing errors
collect2: error: ld returned 1 exit status
*** Error code 1
```

**Comment by evgenyz** [comment]
Actually this should be fixed in a different way, by adding if defined (OS_SOLARIS) to the internal implementation of the function. See: https://github.com/OpenSCAP/openscap/pull/1941.

**Comment by evgenyz** [comment]
Sorry for the noise.
