### ISSUE TITLE
oscap-docker: command not found in Ubuntu pre-compiled binary

### ISSUE THREAD

**Issue by mdforbes500** [OpenSCAP/openscap#1951]
- Is this an issue with SCAP Workbench?
    - If so, report it here: https://github.com/OpenSCAP/scap-workbench/issues
- Is this an issue with SCAP Security Guide (i.e., related to the content of scans, not the scanner proper)?
    - If so, report it here: https://github.com/OpenSCAP/scap-security-guide/issues
- Is this an issue during the OS installation process?
    - If so, report it here: https://github.com/OpenSCAP/oscap-anaconda-addon/issues

Thanks!

#### Description of Problem:
After installing openscap using apt-get (with `apt-get install libopenscap8`) on Ubuntu 20.04-LTS, the oscap-docker command is not found.

#### OpenSCAP Version:
1.2.26

#### Operating System & Version:
Ubuntu 20.04

#### Steps to Reproduce:

1. install openscap via apt-get (`apt-get install libopenscap8`)
2. run `oscap-docker` on any image/container

#### Actual Results:
```
oscap-docker: command not found
```

#### Expected Results:
It runs a scan and generates an output.

**Comment by evgenyz** [comment]
I believe this issue belong to the downstream package's tracker. The upstream project has little influence over how the scanner is being packaged in various distros. Moreover, the 1.2 version is technically obsolete and not supported.
