### ISSUE TITLE
SCAP file in xml format for Open-SCAP Windows 10 pro-

### ISSUE THREAD

**Issue by Raumin05** [OpenSCAP/openscap#1958]
Hi,

Do you know where i can find SCAP files configuration in xml format for windows 10 pro ?
And in particular to control GPO and Service.

Thank you 

Have a good day

**Comment by evgenyz** [comment]
Hey! No, we do not know.

**Comment by Raumin05** [comment]
Seriously ?  
You can make an effort anyway it's not a complicated question.  
Where is the problem ?
