### ISSUE TITLE
Archive of oscap ZIP

### ISSUE THREAD

**Issue by Raumin05** [OpenSCAP/openscap#1964]
Hello, 

I would need a ZIP archive of Oscap.

Do you know where I can find it ? Is it possible to use it without installing it ? 

I mean to execute Oscap commands without installing Oscap just from the archive.

Thank you for yout help.

Have a good day

VALADE Raumin

**Comment by evgenyz** [comment]
No, it is not possible and we are not planning to produce such binaries.
