### ISSUE TITLE
OpenSCAP Shell

### ISSUE THREAD

**Issue by isimluk** [OpenSCAP/openscap#199]
Rationale: The rationale is to avoid copying and pasting a set of parameters and values and file paths and to be able to share and track a configuration file that captures specific tailoring files or xsl sheets more easily among individuals.

̈́Deliverable: Similarly as there is a lvm shell or virsh, we could build a shell like capability.

This is a big idea.

**Comment by electrosenpai** [comment]
Do you mind if the code is generate by Flex and bison or you prefer "pur code" ?

I don't know virsh and lvm (I'm gonna check it) , but I think it's look like Metasploit console right ?

**Comment by isimluk** [comment]
@electrosenpai, I think bison and flex might be actually preferred! :-)

I am sorry for a delayed answer.

**Comment by electrosenpai** [comment]
@isimluk no worries
can't start this week I'm busy , I will start next week :-)

**Comment by jan-cerny** [comment]
This idea can be replaced by improving the `oscap` cmdline interface and providing an `-i` option.
It is also possible to use OpenSCAP daemon.

It is not clear how the use case would look like.
