### ISSUE TITLE
Func question 

### ISSUE THREAD

**Issue by Sirdorblu** [OpenSCAP/openscap#1998]
Is there a func to scan a one file or it will be? like:
oscap oval eval --report vulnerability.html rhel-8.oval.xml test.0:12.0-1.rpm

**Comment by evgenyz** [comment]
There is an option to validate a single OVAL definition from a Data Stream, like `oscap oval eval --id oval:ssg-installed_OS_is_fedora:def:1 ssg-fedora-ds.xml`. That's pretty much how selective OVAL standard could be.

**Comment by evgenyz** [comment]
If your Data Stream (rhel-8.oval.xml) has a test definition for each file (package), then it is probably what you're looking for.

**Comment by Sirdorblu** [comment]
> There is an option to validate a single OVAL definition from a Data Stream, like `oscap oval eval --id oval:ssg-installed_OS_is_fedora:def:1 ssg-fedora-ds.xml`. That's pretty much how selective OVAL standard could be.

but its for installed pkgs, if i have a list of noninstalled pkgs?
