### ISSUE TITLE
OpenSCAP segfaults with fetch remote resources

### ISSUE THREAD

**Issue by mpreisler** [OpenSCAP/openscap#200]
SCAP Workbench 1.1.1 with OpenSCAP 1.2.5 with fetch remote resources - RHEL5 USGCB content works fine.

SCAP Workbench 1.1.1 with OpenSCAP 1.2.6 with fetch remote resources - RHEL5 USGCB content causes a segfault.

This looks like a regression in 1.2.6!

**Comment by jan-cerny** [comment]
I can reproduce this on my machine. I will investigate it more.

**Comment by jan-cerny** [comment]
I can reproduce segfault with oscap with remote resources and USGCB by this command:
`oscap xccdf eval --results /tmp/results --profile united_states_government_configuration_baseline --oval-results --fetch-remote-resources ../usgcb-rhel5desktop-xccdf.xml`
It has same backtrace as Issue #191 .

**Comment by jan-cerny** [comment]
After merging #207 it doesn't happen anymore. Closing.
