### ISSUE TITLE
Raspberry pi ubuntu server 22.04 results all not applicable

### ISSUE THREAD

**Issue by big-yellow-duck** [OpenSCAP/openscap#2018]
#### Description of Problem:
I am trying to run openscap on my raspberry pi4 running ubuntu 22.04 server. I've built openscap in my raspberry pi and run the benchmark: CIS for ubuntu server 22.04 level 1 server. but all the sections are not applicable. 

#### OpenSCAP Version:
built version: 1.2.17

#### Operating System & Version:
Ubuntu 22.04 server for Raspberry Pi

#### Steps to Reproduce:

1.  built openscap following the guide provided for ubuntu 22.04
2.   run the benchmark using:
```
oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_cis_level1_workstation --results scan_results.xml --report report.html  ssg-ubuntu2204-xccdf.xml
```

#### Actual Results:
```
Title   Do Not Allow SSH Environment Options
Rule    xccdf_org.ssgproject.content_rule_sshd_do_not_permit_user_env
Result  notapplicable

Title   Enable PAM
Rule    xccdf_org.ssgproject.content_rule_sshd_enable_pam
Result  notapplicable
```
#### Expected Results:

should be fail or pass for the tests

**Comment by evgenyz** [comment]
Most likely it happened because the content is not compatible with OpenSCAP 1.2.x. Try using 1.3.x.

**Comment by crouth-redge** [comment]
What is the most sensible path for 1.3.x on Ubuntu 22.04? 22.04 ships with `1.2.17`  - there are no newer versions available for that release of Ubuntu and 1.3.x is only being included in 23.x and 24.x ubuntu repos. 

I've been searching for a PPA, deb release or even a solid guide on getting 1.3.7 installed from source on Ubuntu and coming up empty.

Making the CIS Benchmark for Ubuntu 22.04 based on a version that's not available on it was an interesting choice. I guess another option is to install openscap in a docker container and use it to perform a remote scan over ssh...

**Comment by evgenyz** [comment]
If you take a look at the github actions here in the repo you will find how the scanner could be manually built in a deb-based system. There are just couple of commands really, and all the deps are listed.

The 1.3.x version is 5+ years old, I have no idea as to why Ubuntu/Debian ignored it.

**Comment by crouth-redge** [comment]
Thanks, I'll check that.

Just as an alternative option, are there any maintained openscap docker images out there that can be leveraged? This would remove the need to build manually as I could use the oscap-ssh tool from a CI job.

I can make my own based on 23.04 and get 1.3.x that way, just wondering if I missed official containers being moved from Dockerhub > something as the ones on dockerhub are 6 years old.

**Comment by evgenyz** [comment]
None I know of.

**Comment by crouth-redge** [comment]
Bah, sadly the `oscap-ssh` method is still reliant on the version of libopenscap on the target, So need to at least get a newer version of that into the targets.

**Comment by crouth-redge** [comment]
Aha! 

Ok so for a 22.04 scan the best route is oscap-ssh from a 23.04 host, and on the targets install `libopenscap25` and `openscap-scanner` from universe - THESE bring in 1.3.7 when done this way. `libopenscap8` brings in 1.2.17

**Comment by big-yellow-duck** [comment]
I've managed to built OpenSCAP on my raspberry pi! I thought it was stuck halfway but it took around 4 hours to build. then running audits on it works just fine! following the docs to install the dependencies to build it properly took some time.

Thank you for the help!!

I think this is actually quite a good idea as it can save space if you're on a small emmc.

> Aha!
> 
> Ok so for a 22.04 scan the best route is oscap-ssh from a 23.04 host, and on the targets install `libopenscap25` and `openscap-scanner` from universe - THESE bring in 1.3.7 when done this way. `libopenscap8` brings in 1.2.17

**Comment by crouth-redge** [comment]
Damn, I installed  `libopenscap25` and `openscap-scanner` from universe a couple of weeks ago and successfully got a clean scan with 1.3.7, however - these are now _gone_ from the 22.04 universe.. and I can only install 1.2.17 again. 

This is damned frustrating. Why would the security benchmarks for 22.04 be written for 1.3+ when Ubuntu is only consitently shipping 1.2.17 in the repos for 22.04? This is a royal PITA.
