### ISSUE TITLE
OpenSCAP segfault (xslt)

### ISSUE THREAD

**Issue by ybznek** [OpenSCAP/openscap#202]
when you run
```
cd tests/oval_details
oscap xccdf eval --results  `mktemp` --oval-results --report `mktemp` ./rpminfo.xccdf.xml
```
It can have three different (random) results
- Some error message
```
runtime error: file /home/zmoravec/gitRepos/openscap/xsl/xccdf-report-oval-details.xsl line 44 element key
Failed to evaluate the 'match' expression.
```
- Segmentation fault [gdb.txt](https://github.com/OpenSCAP/openscap/files/25185/gdb.txt)
- don't exit

It seems to be ok, when I revert 6b278aad5943249dbc871ccca710306be4b76db2.
But this is probably not caused by wrong content.

**Comment by isimluk** [comment]
It is very weird that a simple XPath change makes a segfault. However, I think best way would be to revert the XPath change asap. And only then try to find better way for this xpath.

**Comment by isimluk** [comment]
Closing this. We do not have resources to optimize the xpath query.
