### ISSUE TITLE
Removed symbol from openscap_sce.so

### ISSUE THREAD

**Issue by havardAasen** [OpenSCAP/openscap#2025]
#### Description of Problem:
A library symbol, `oscap_get_substrings`, has been removed from `openscap_sce.so`.

#### OpenSCAP Version:
It was removed between 1.3.8 and 1.3.9, in f653e07627eea34de72ce6315af571ec4c54f10a

#### Steps to Reproduce:

1.  Compile library for version 1.3.8
2.  Compile library for version 1.3.9
3.  Compare exported symbols

#### Actual Results:
A library symbol has been removed, which seems to be an ABI break.

#### Expected Results:
No removed symbol, or SONAME bump.

**Comment by evgenyz** [comment]
Well, technically, yes. But this lib is not part of the public API, and the symbol in question should not have been there in the first place.

**Comment by havardAasen** [comment]
Are you saying that the entire script check engine is only meant for internal usage by openscap? In `openscap.spec`, this library is in it's own package, the header file is also split out.

If this symbol wasn't supposed to be exposed, are more symbols that shouldn't be exposed by the library?

While it might not have been intentional, the symbol was still exposed, and then removed. Intentional or not, it is an ABI breakage and warrants a SONAME bump.

**Comment by evgenyz** [comment]
> Are you saying that the entire script check engine is only meant for internal usage by openscap? In `openscap.spec`, this library is in it's own package, the header file is also split out.

Yes. It is an internal plugin library, it is not meant to be used directly. All functionality is exposed via oscap and libopenscap.so.

**Comment by havardAasen** [comment]
> > Are you saying that the entire script check engine is only meant for internal usage by openscap? In `openscap.spec`, this library is in it's own package, the header file is also split out.
> 
> Yes. It is an internal plugin library, it is not meant to be used directly. All functionality is exposed via oscap and libopenscap.so.

Ok, thanks for the clarification.

Out of curiosity, why are the header file `sce_engine_api.h` being shipped into it's own package, or shipped at all for that matter? This seems unnecessary if one is not supposed to develop against the library.

**Comment by evgenyz** [comment]
> Out of curiosity, why are the header file `sce_engine_api.h` being shipped into it's own package, or shipped at all for that matter? This seems unnecessary if one is not supposed to develop against the library.

Probably it happened when sce plugin got separated. There are a lot of sub-optimal stuff accumulated over the years.
