### ISSUE TITLE
help with OpenScap Daemon installation 

### ISSUE THREAD

**Issue by Mettthew** [OpenSCAP/openscap#2031]
hello everyone,

i know this question would not fit in this section, but i checked the section for "openscap daemon" and it is closed and does not give me a chance to post the problem there.

I am trying to download "openscap daemon" into my Kali Linux virtual machine, but I am not very familiar with these things and am finding it difficult to install.

Is there by any chance a step by step guide for installation? I have already checked in the github repository of Openscap Daemon, but I am struggling to understand what I should do to install it

**Comment by evgenyz** [comment]
The OpenSCAP Daemon is an obsolete project that is no longer developed or supported. Why do you want to use it anyway?

**Comment by Mettthew** [comment]
thank you very much for your answer,

I was looking for open source vulnerability scanners for my university thesis that supported APIs to be able to scan directly from scripts in python and I noticed that through OpenScap Daemon one could connect to a rest server that would allow this

Do you know if OpenScap offers something similar?

**Comment by evgenyz** [comment]
OpenSCAP is not a very good tool for vul. scanning (and at some point it might just stop doing it altogether). There are plenty of other opensource tools that do a better job in that regard.

If you want to check your system for compliance with DISA STIG or CIS gudelines (for example), that's another story. But it hardly requires a daemon (the reason it actually got retired).

**Comment by Mettthew** [comment]
thanks again,
I'm fairly new to the vulnerability world but unfortunately I'm having a hard time finding what I need, I've only found OpenVAS which supports the API and has a free version that supports it, but I would need to find at least 2 more 😭

I was hoping to have found another one with OpenScap, but it will mean that I will continue my search
