### ISSUE TITLE
Sysctl element kernel.sched_energy_aware cause test fail on Rawhide

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/openscap#2049]
#### Description of Problem:
The test `test_sysctl_probe_all.sh` fails on Rawhide

#### OpenSCAP Version:
current upstream maint-1.3 branch as of 2023-11-07 as of HEAD 30c8c395e547fa44a44080fa209ce4d27d3c3f95

#### Operating System & Version:
Fedora Rawhide as of 2023-11-07

#### Steps to Reproduce:

1.  run our ctest tests

#### Actual Results:
```
238/277 Test #238: probes/sysctl/test_sysctl_probe_all.sh .............................................***Failed    0.29 sec
Result file: test_sysctl_probe_all.res.out.5fl6Id
Our names file: test_sysctl_probe_all.our.out.nnyTvH
Sysctl names file: test_sysctl_probe_all.sysctl.out.bTJnYG
Errors file: test_sysctl_probe_all.err.out.Ygjjz9
Diff (sysctlNames / ourNames): ------
152d151
< kernel.sched_energy_aware
```

#### Expected Results:
passed test

#### Additional Information / Debugging Steps:
Manifests also in Testing farm, eg. https://artifacts.dev.testing-farm.io/472eea03-0b74-4043-87cf-d0628926f355/

Most likely the kernel.sched_energy_aware needs to be added on a special list in the systemctl probe.

**Comment by evgenyz** [comment]
Last time it happened I was considering making the list dynamic somehow. Maybe now it is time to do so, as it happens more and more often.
