### ISSUE TITLE
Verbose feature: Improve include header dependencies

### ISSUE THREAD

**Issue by isimluk** [OpenSCAP/openscap#205]
@jan-cerny, you have recently added `include public/oscap_debug.h` to `src/common/util.h`. This fixes the build, however it is not 100% technically accurate. The util.h does not depend on oscap_debug.h. In perfect world we should include `oscap_debug.h` only from files that require something from it.

A motivation behind this is that, in general, having clear dependencies makes future refactoring much easier. I have learned this last year, when I tried to devouple `src/OVAL/results/` folder. There were cyclic dependencies that were not needed that make my job harder. Further the util.h file is already quite complex (ifdefs) so having one less include here makes sense to me.

So what need to be done:
 (1) remove that include
 (2) try to include oscap_debug.h from other files

I think there will be not many files affected by this (since everyone affected should already include `oscap_debug.h`, but I may be wrong. If you find you would need to modify each file, please feel free to close this as WONTFIX.

This is very minor issue, @jan-cerny. However, I still feel it makes sense to fix it. It can be postponed to 1.2.8+.

**Comment by jan-cerny** [comment]
Thanks for pointing this out. Dependencies are sometimes tricky :-) I agree with you.

**Comment by jan-cerny** [comment]
Fixed in 0cc192d7e354519d83c57eb09ee9dd1f22ff65ce
