### ISSUE TITLE
Verbose feature: Improve error messages:

### ISSUE THREAD

**Issue by isimluk** [OpenSCAP/openscap#206]
(1) One error message reads: "Log file is not specified!". Can you please include advise for the user what he/she needs to do? Something like: "Please provide --verbose-log-file FILE option together with --verbose"

(2) Another message reads: " Inavlid verbosity level!" Please advise user what are the verbosity levels here.

Low priority, moving to 1.2.8.

**Comment by jan-cerny** [comment]
Thanks for these useful ideas. Although everything is described in man page, it is definitely more comfortable when an user doesn't have to read the manual.

**Comment by jan-cerny** [comment]
Fixed in 385cad4fbda4cc11e4c710c871ea7a2ed59773e7
