### ISSUE TITLE
support a tool for `dpkg list` or `rpm -qa --qf` command result to system-characteristics.xml

### ISSUE THREAD

**Issue by beruhan** [OpenSCAP/openscap#2064]
I has a ubuntu 18.04 which has not install openscap tool,and then I want to use `dpkg list` commond get the software as installed_packages.txt,and then use a tool or script convert installed_packages.txt to system-characteristics.xml. Finally I upload system-characteristics.xml to a server which installed oscap, use  `oscap oval analyse ` and `oscap oval generate report` command get report .xml. Is there a way to do like this?

**Comment by evgenyz** [comment]
Not that we aware of.
