### ISSUE TITLE
SELinux prevents access to faillock.conf - prevents login

### ISSUE THREAD

**Issue by biffsocko** [OpenSCAP/openscap#2101]
- Is this an issue with SCAP Workbench?
    - If so, report it here: https://github.com/OpenSCAP/scap-workbench/issues
- Is this an issue with SCAP Security Guide (i.e., related to the content of scans, not the scanner proper)?
    - If so, report it here: https://github.com/OpenSCAP/scap-security-guide/issues
- Is this an issue during the OS installation process?
    - If so, report it here: https://github.com/OpenSCAP/oscap-anaconda-addon/issues

Thanks!

#### Description of Problem:
selinux prevents access to faillock.conf

#### OpenSCAP Version:
1.3.8

#### Operating System & Version:
RHEL8

#### Steps to Reproduce:
enable selinux + add faillock controls.  

#### Actual Results:
can't log in, have to boot into single usermode

#### Expected Results:
can log in

**Comment by evgenyz** [comment]
If the content came from `scap-security-guide` package, then the right place to file an issue is: https://github.com/ComplianceAsCode/content.

If not — ask your content provider.
