### ISSUE TITLE
oscap-ssh does not support --stig-viewer option

### ISSUE THREAD

**Issue by jlk6wu** [OpenSCAP/openscap#2107]
#### Description of Problem: 
oscap-ssh does not support --stig-viewer option. When using this option to perform a remote scan of a system, it does not appear to produce a STIGViewer-compatible .xml output file, even when that output is specified. 

#### OpenSCAP Version: 
OpenSCAP command line tool (oscap) 1.2.17

#### Operating System & Version:
Red Hat Enterprise Linux 7.9, Red Hat Enterprise Linux 8.9

#### Steps to Reproduce:

1. Run oscap-ssh with --stig-viewer option:  

> sudo oscap-ssh root@X.X.X.X 22 xccdf eval --profile xccdf_org.ssgproject.content_profile_stig --stig-viewer oscap-report.xml /usr/share/xml/scap/ssg/content/ssg-rhel8-ds.xml
2. Search file systems of source and target system for STIGViewer-compatible file

> sudo find / -name oscap-report.xml

**Comment by avalanchein** [comment]
Proposed solution attached - summary of additions below: 
line 215:
STIG_RESULTS=""

line 226-229:
("--stig-viewer")
		STIG_RESULTS=${oscap_args[j]}
		oscap_args[j]="$REMOTE_TEMP_DIR/stig_results.xml"
	  ;;

line 325-327:
if [ "$STIG_RESULTS" != "" ]; then
    scp_retreive_from_temp_dir stig_results.xml "$STIG_RESULTS" || die "Failed to copy the STIG results file back to local machine!"
fi


[oscap-ssh.txt](https://github.com/OpenSCAP/openscap/files/15478125/oscap-ssh.txt)

**Comment by jlk6wu** [comment]
Solution was merged.

**Comment by bwilkinscloud** [comment]
@jlk6wu What version was this fixed merged?
