### ISSUE TITLE
Unable to create ansible fix with custom xccdf

### ISSUE THREAD

**Issue by pvcasillasg** [OpenSCAP/openscap#2109]
#### Description of Problem:

When im trying to create a fix with oscap I provide a custom profile, but every single time I try to run the command I got the same exact error

command im using:

`oscap xccdf generate fix --profile xccdf_org.ssgproject.content_profile_ospp_RedHat9_Custom --fix-type ansible /usr/share/xml/scap/ssg/content/ssg-RedHat9-ds-custom.xml > /tmp/2024-05-21-192.168.1.104-rh-oscap-5-reporte.yml`

`No profile matching suffix "xccdf_org.ssgproject.content_profile_ospp_RedHat9_Custom" was found. Get available profiles using:
$ oscap info "/usr/share/xml/scap/ssg/content/ssg-RedHat9-ds-custom.xml"`

The output of the Oscap info is: 

> 
> [root@rh-oscap-5 ~]# oscap info "/usr/share/xml/scap/ssg/content/ssg-RedHat9-ds-custom.xml"
> Document type: XCCDF Tailoring
> Imported: 2024-05-21T12:05:44
> Benchmark Hint: /usr/share/xml/scap/ssg/content/ssg-RedHat9-ds.xml
> Profiles:
> 	Title: Protection Profile for General Purpose Operating Systems [CUSTOMIZED]
> 		Id: xccdf_org.ssgproject.content_profile_ospp_RedHat9_Custom
> 
> 

#### OpenSCAP Version:

OpenSCAP command line tool (oscap) 1.3.10

#### Operating System & Version:
RedHat 9.4

#### Steps to Reproduce:

oscap xccdf generate fix --profile xccdf_org.ssgproject.content_profile_ospp_RedHatd9_custom --fix-type ansible /usr/share/xml/scap/ssg/content/ssg-RedHat9-ds-Custom.xml-sd-Custom > /tmp/2024-05-21-192.168.1.104-rh-oscap-5-reporte.yml
 

#### Actual Results:

OpenSCAP Error: Unable to open file: '/usr/share/xml/scap/ssg/content/ssg-RedHat9-ds-Custom.xml-sd-Custom' [/builddir/build/BUILD/openscap-1.3.10/src/source/oscap_source.c:298]
Unable to open file: '/usr/share/xml/scap/ssg/content/ssg-RedHat9-ds-Custom.xml-sd-Custom' [/builddir/build/BUILD/openscap-1.3.10/src/source/oscap_source.c:298]

#### Expected Results:

Ansible generated

**Comment by evgenyz** [comment]
You should use `--tailoring-file /usr/share/xml/scap/ssg/content/ssg-RedHat9-ds-custom.xml` with the DS you've made the tailoring out of.

**Comment by pvcasillasg** [comment]
Thanks, that was exactly my issue.
