### ISSUE TITLE
Weird non-UTF characters in OVAL results

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/openscap#212]
When I run
`oscap oval eval --id "oval:ssg:def:445" --results oval-results.xml /usr/share/xml/scap/ssg/content/ssg-fedora-oval.xml`
I get not deterministic results. In the OVAL results file, sometimes I get 5 `//lin-sys:rpmverifyfile_item/lin-sys:name[text()="ca-certificates"]` elements, but sometimes I got 6 of them. The sixth rpmverifyfile_item contains weird non-utf8 characters inside `filepath` element.

See line 7570 in this file
[wrong_utf8_oval_results.txt](https://github.com/OpenSCAP/openscap/files/31847/wrong_utf8_oval_results.txt) (GitHub can't upload *.xml, it's just renamed)

This causes that a report can't be generated and it seems to me it is  a reason of https://bugzilla.redhat.com/show_bug.cgi?id=1277291

I am using OpenSCAP 1.2.6 and SSG 0.1.25 on Fedora 22 Workstation.

**Comment by jan-cerny** [comment]
I can't reproduce this on current maint-1.2

**Comment by isimluk** [comment]
weird

**Comment by isimluk** [comment]
Especially, the part, that you can no longer reproduce this thing.

**Comment by jan-cerny** [comment]
Yes, I agree that this is really weird, because it doesn'ŧ happen always. Moreover, there is no change in rpmverifyfile probe after 1.2.6 release, so I can't see the reason.  However it is reproducible when I do git checkout 69d29ad (release commit).  Moreover, if I compile that with `./configure --enable-debug`, it freezes and rpmverifyfile probe takes 100% of processor.

**Comment by dkopecek** [comment]
@jan-cerny Hey Jan, can you provide your version of the /usr/share/xml/scap/ssg/content/ssg-fedora-oval.xml  please? Thanks.

**Comment by jan-cerny** [comment]
@dkopecek Yes, I can (just remove the .txt extension, github doesn't allow to upload xml files)
[ssg-fedora-oval.xml.txt](https://github.com/OpenSCAP/openscap/files/33016/ssg-fedora-oval.xml.txt)

**Comment by jan-cerny** [comment]
I have browsed through old issues and I have discovered that this is very similar to this issue: https://github.com/OpenSCAP/openscap/issues/65

**Comment by jan-cerny** [comment]
@ybznek @msrubar @isimluk @dkopecek   Hey guys, are there any ideas how to solve this? I spent a lot of time with this issue a week ago, but I didn't find anything. It's not-deterministic behavior of the probe. I think it might affects many users in future. Does somebody have an experience with programming RPM? Any suggestion is welcome! Thank you very much.

**Comment by ybznek** [comment]
Sorry, I have no experience.

**Comment by dkopecek** [comment]
@jan-cerny *strdup()*ing the strings that RPM API returns isn't enough to fix this?

**Comment by jan-cerny** [comment]
@dkopecek No, it isn't. I have tried that, it fixes the valgrind messages, but it doesn't fix UTF-8 errors and it doesn't fix freezing with `./configure --enable-debug`

**Comment by dkopecek** [comment]
@jan-cerny is your fix for the valgrind-detectable issues already upstreamed?

**Comment by jan-cerny** [comment]
@dkopecek No, it isn't. Should I do it even if we know that it doesn't fix the reason?

**Comment by dkopecek** [comment]
@jan-cerny Well, I guess there aren't any advantages in having known invalid memory reads and writes in a probe, what do you think?

**Comment by jan-cerny** [comment]
OK, so I will make a pull request.

**Comment by mpreisler** [comment]
Discussed this today with @jan-cerny @isimluk and @ybznek . The `valgrind warning` fix is very likely a fix to this issue. That valgrind warning shows that we are relying on undefined behavior and *most likely* that's why we have weird non-UTF8 characters in the files and occasional segfaults.

I have merged the PR from @jan-cerny , so this is most likely already fixed. @jan-cerny will verify that hypothesis tomorrow.

**Comment by dkopecek** [comment]
@jan-cerny What about the other rpm* probes, have you checked that there isn't the same problem?

**Comment by jan-cerny** [comment]
@dkopecek  Not yet, thanks for your suggestion.

**Comment by jan-cerny** [comment]
@mpreisler I have tried to verify whether my patch 67a234fd8ce53d995088ffb9b8d62ed43e709bbb fixes this issue. I have cherry-picked this patch into current maint-1.2. I have run that command 20 times, and the issue haven't appeared. It seemed to my that it is OK.

But the problem is that I have run the same command on maint-1.2 compiled WITHOUT the patch. I have run it more than 20 times and the issue haven't appeared. I wasn't able to reproduce this issue today. I am not able to tell you whether the patch is a proper fix, because the issue is no longer reproducible on my machine without the patch.

**Comment by jan-cerny** [comment]
With the patch `valgrind --trace-children=yes` doesn't report any memory problems on my machine

**Comment by mpreisler** [comment]
> @jan-cerny What about the other rpm* probes, have you checked that there isn't the same problem?

^ Check the other RPM probes, then I think we can close this.

**Comment by jan-cerny** [comment]
I have checked other rpm* probes - rpmverify.c and rpminfo.c. I can't find anything similar to this. The rpmverify.c has very similar code, but it already uses `strdup()` on return value of `rpmfiFN(fi)`.
