### ISSUE TITLE
Test fails

### ISSUE THREAD

**Issue by Sangeetha-E** [OpenSCAP/openscap#2120]
#### Description of Problem:
I am evaluating built-in ds.xml file for testing. But it failed.

https://github.com/OpenSCAP/openscap/blob/main/tests/report/ds.xml

#### OpenSCAP Version:
1.3.10

#### Operating System & Version:
Ubuntu-20.04.1

#### Steps to Reproduce:

1. cd openscap-1.3.10/tests/report
2. oscap xccdf eval --report report.html ds.xml

#### Actual Results:
# 
oscap xccdf eval --report report.html ds.xml
--- Starting Evaluation ---

Title   Simple rule
Rule    xccdf_moc.elpmaxe.www_rule_1
Result  fail

# 

#### Expected Results:
# 
oscap xccdf eval --report report.html ds.xml
--- Starting Evaluation ---

Title   Simple rule
Rule    xccdf_moc.elpmaxe.www_rule_1
Result  pass

# 

#### Additional Information / Debugging Steps:
# 
 oscap xccdf eval --verbose INFO --report report.html ds.xml
I: oscap: Using environment variables:
I: oscap: OSCAP_CHECK_ENGINE_PLUGIN_DIR=''
I: oscap: OSCAP_CONTAINER_VARS=''
I: oscap: OSCAP_EVALUATION_TARGET=''
I: oscap: OSCAP_FULL_VALIDATION=''
I: oscap: OSCAP_OVAL_COMMAND_OPTIONS=''
I: oscap: OSCAP_PCRE_EXEC_RECURSION_LIMIT=''
I: oscap: OSCAP_PROBE_ROOT=''
I: oscap: SEXP_VALIDATE_DISABLE=''
I: oscap: SOURCE_DATE_EPOCH=''
I: oscap: OSCAP_PROBE_MEMORY_USAGE_RATIO=''
I: oscap: OSCAP_PROBE_MAX_COLLECTED_ITEMS=''
I: oscap: OSCAP_PROBE_IGNORE_PATHS=''
I: oscap: Identified document type: data-stream-collection
I: oscap: Created a new XCCDF session from a SCAP Source Datastream 'ds.xml'.
I: oscap: Validating XML signature.
I: oscap: Signature node not found
I: oscap: Identified document type: Benchmark
I: oscap: Started new OVAL agent variable.oval.xml.
I: oscap: Querying system information.
I: oscap: Starting probe on URI 'queue://system_info'.
I: oscap: I will run system_info_probe_main:
--- Starting Evaluation ---

I: oscap: Evaluating a XCCDF policy with selected 'default-profile' profile.
Title   Simple rule
Rule    xccdf_moc.elpmaxe.www_rule_1
I: oscap: Evaluating XCCDF rule 'xccdf_moc.elpmaxe.www_rule_1'.
I: oscap: Evaluating definition 'oval:x:def:1': x.
I: oscap: Evaluating variable test 'oval:x:tst:1': oval:x:var:1 should equals 24.
I: oscap: Querying variable object 'oval:x:obj:1', flags: 0.
I: oscap: Creating new syschar for variable_object 'oval:x:obj:1'.
I: oscap: Starting probe on URI 'queue://variable'.
I: oscap: Querying variable 'oval:x:var:1'.
I: oscap: Variable 'oval:x:var:1' is not local, skipping.
I: oscap: Variable 'oval:x:var:1' has values "42".
I: oscap: I will run variable_probe_main:
I: oscap: State 'oval:x:ste:1' references constant_variable 'oval:x:var:2'.
I: oscap: Querying variable 'oval:x:var:2'.
I: oscap: Variable 'oval:x:var:2' is not local, skipping.
I: oscap: Variable 'oval:x:var:2' has values "24".
I: oscap: Test 'oval:x:tst:1' requires that at least one object defined by 'oval:x:obj:1' exists on the system.
I: oscap: 1 objects defined by 'oval:x:obj:1' exist on the system.
I: oscap: All items matching object 'oval:x:obj:1' were collected. (flag=complete)
I: oscap: In test 'oval:x:tst:1' all of the collected items must satisfy these states: 'oval:x:ste:1'.
I: oscap: Item '1023532' compared to state 'oval:x:ste:1' with result false.
I: oscap: Test 'oval:x:tst:1' evaluated as false.
I: oscap: Definition 'oval:x:def:1' evaluated as false.
Result  fail

#

**Comment by evgenyz** [comment]
What is the result of
```
cd build
ctest -V -R report/
```
? Does it pass?

**Comment by Sangeetha-E** [comment]
The result of `ctest -V -R report/`:
```
100% of tests passed.
```
Does this mean that the above one is the **expected failure**?

It checks if the return value is 2.
https://github.com/OpenSCAP/openscap/blob/main/tests/report/report.sh#L11

**Comment by evgenyz** [comment]
Yep.
