### ISSUE TITLE
How to Use OpenSCAP Without Installing it on the Remote Machine?

### ISSUE THREAD

**Issue by hdby99** [OpenSCAP/openscap#2140]
**Description:**
I am developing a product that requires running vulnerability assessments on a client's operating system and database. Due to certain constraints, I cannot install OpenSCAP directly on the client's systems. Instead, I need to perform the vulnerability assessments from a backend server that can simulate the client's environment.

**Steps Taken:**
**Chroot Environment**: Attempted to create a chroot environment to simulate the client's file system.
**Remote Assessment**: Discovered the oscap-ssh command for remote scanning, but it requires OpenSCAP to be installed on the client system, which is not feasible in my case.

Is there a way to use oscap-ssh or a similar tool without requiring OpenSCAP to be installed on the remote system?

**Comment by evgenyz** [comment]
Unfortunately there is no way to do that.
