### ISSUE TITLE
This needs to be appended to the installation command in Ubuntu.

### ISSUE THREAD

**Issue by silverskyvicto** [OpenSCAP/openscap#2149]
#### Description of Problem:

When using the latest version of Ubuntu, the installation cannot be performed using the commands listed in the documentation.

https://github.com/OpenSCAP/openscap/blob/da1d1bd4659928e5621a6a0790d4cfb8341863cd/docs/manual/manual.adoc?plain=1#L108

#### OpenSCAP Version:
- 1.3.9

#### Operating System & Version:
- Ubuntu 24.04 LTS

#### Steps to Reproduce:

1. Log in to Ubuntu Server
2. Update package repository
    ```sh
    $ sudo apt update
    ```
3. Execute command below
    ```sh
    $ sudo apt install libopenscap8 
    ```

#### Actual Results:
```sh
$ sudo apt install libopenscap8
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package libopenscap8 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  openscap-common libopenscap25t64

E: Package 'libopenscap8' has no installation candidate
```

#### Expected Results:
OpenSCAP successfully installed.

#### Additional Information / Debugging Steps:
The installation was successful when the following command was executed
```
$ sudo apt install openscap-scanner
```

A search for packages shows that the packages have changed in the latest version of Ubuntu.
- [Package search results](https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=openscap&searchon=names)

**Comment by jan-cerny** [comment]
This has been fixed by https://github.com/OpenSCAP/openscap/pull/2143
