### ISSUE TITLE
Library issue with OpenSCAP 1.4.0

### ISSUE THREAD

**Issue by provensen** [OpenSCAP/openscap#2161]
#### Description of Problem:
I installed OpenSCAP on my RHEL9 server that is already STIGGED. I installed the OpenSCAP from the libopenscap library and the oscap tool from the source code, and I am getting:
**/opt/openscap/build/utils/oscap: error while loading shared libraries: libopenscap.so.33: cannot open shared object file: No such file or directory**
Why am I getting this?
With it already being STIGGED, I only can install OpenSCAP in /opt. No other directory will allow me to execute openscap_wrapper

#### OpenSCAP Version:
1.4.0

#### Operating System & Version:
RHEL9.4

#### Steps to Reproduce:

1. dnf install cmake dbus-devel libacl-devel libblkid-devel libcap-devel libcurl-devel libgcrypt-devel libselinux-devel libxml2-devel libxslt-devel libattr-devel make openldap-devel pcre2-devel perl-XML-Parser perl-XML-XPath perl-devel python3-devel rpm-devel swig bzip2-devel gcc-c++ libyaml-devel xmlsec1-devel xmlsec1-openssl-devel -y
2. wget https://github.com/OpenSCAP/openscap/releases/download/1.4.0/openscap-1.4.0.tar.gz
3. tar -xzpf openscap-1.4.0.tar.gz -C /opt
4. cd /opt/openscap-1.4.0
5. mkdir -p build
6. cd build/
7. cmake ../
8. make
9. ./oscap_wrapper -V

#### Actual Results:
**/opt/openscap/build/utils/oscap: error while loading shared libraries: libopenscap.so.33: cannot open shared object file: No such file or directory**

#### Expected Results:
OpenSCAP command line tool (oscap) 1.4.0......

**Comment by provensen** [comment]
```
#!/bin/bash -
# openscap 'run' programs locally script
# Copyright (C) 2011-2019 Red Hat Inc.
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

#----------------------------------------------------------------------

# With this script you can run oscap without needing to
# install the utility first.  You just have to do for example:
#
#   ./oscap_wrapper [oscap args ...]

#----------------------------------------------------------------------
# Build directory
b=/opt/openscap-1.4.0/build

"$b/run" "$b/utils/oscap" "$@"
```
The oscap_wrapper script works before I perform the remediation script, but once I run the remediation script I still get the following:
`/opt/openscap-1.4.0/build/utils/oscap: error while loading shared libraries: libopenscap.so.33: cannot open shared object file: No such file or directory`
The remediation script hardens the RHEL9.4 system with Disa STIG. Yes, libopenscap.so.33 is located in `/opt/openscap-1.4.0/build/src/`
Why is the oscap_wrapper script trying to find libopenscap.so.33 in `/opt/openscap-1.4.0/build/utils/oscap`?

**Comment by evgenyz** [comment]
> Why is the oscap_wrapper script trying to find libopenscap.so.33 in `/opt/openscap-1.4.0/build/utils/oscap`

Because this is what the script does (it is there for development debugging purposes):
```
# With this script you can run oscap without needing to
# install the utility first.  You just have to do for example:
#
#   ./oscap_wrapper [oscap args ...]
```

I'm not sure what are you trying to do, but I would recommend building and installing the package instead of messing with local build, especially in a restricted environment.

**Comment by provensen** [comment]
I believe the STIG remediation script I am using changes the permission for a library directory. Something libopenscap.so.33 relies on. What are libopenscap.so.33's dependents?

**Comment by evgenyz** [comment]
> I believe the STIG remediation script I am using changes the permission for a library directory. Something libopenscap.so.33 relies on. What are libopenscap.so.33's dependents?

The tool `./utils/oscap` depends on the library. What library itself depends on you can check with `ldd libopenscap.so.33`.
