### ISSUE TITLE
User Manual: Debugging instructions are outdated by --verbose mode

### ISSUE THREAD

**Issue by isimluk** [OpenSCAP/openscap#238]
@jan-cerny can You please take a look at https://github.com/OpenSCAP/openscap/blob/maint-1.2/docs/manual/manual.adoc#debugging

These are the debugging instructions that apply to openscap-1.2.6-. You have greatly improved debugging experience in 1.2.7+, but the instructions are now outdated. Can you please briefly describe the new debugging mode?

Thanks!

**Comment by jan-cerny** [comment]
Yes, I agree it should be mentioned in the user manual.

**Comment by jan-cerny** [comment]
Done.
