### ISSUE TITLE
Feature request: HTML guide -- consider ability to filter the list of displayed rules per requirement

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/openscap#247]
HTML report in current OpenSCAP can filter out the displayed rules depending on the result (PASS, FAIL, NOTCHECKED) and display only rules having one concrete result.

It would be nice (RFE) if the generated HTML guide for particular profile and benchmark could also filter out only rules e.g.:
- per concrete PCI DSS identifier, DISA STIG / NIST identifier etc.

Example use case: Show me only rules in the guide mapping to PCI DSS Req #5.

The author of this idea is Zbynek (proper attribution is important). I just formatted the idea into a ticket.

Thank you for your consideration, Jan.

**Comment by shawndwells** [comment]
On 12/1/15 5:40 AM, iankko wrote:
>
> HTML report in current OpenSCAP can filter out the displayed rules 
> depending on the result (PASS, FAIL, NOTCHECKED) and display only 
> rules having one concrete result.
>
> It would be nice (RFE) if the generated HTML guide for particular 
> profile and benchmark could also filter out only rules e.g.:
>
>   * per concrete PCI DSS identifier, DISA STIG / NIST identifier etc.
>
> Example use case: Show me only rules in the guide mapping to PCI DSS 
> Req #5 <https://github.com/OpenSCAP/openscap/pull/5>.
>
> The author of this idea is Zbynek (proper attribution is important). I 
> just formatted the idea into a ticket.
>
> Thank you for your consideration, Jan.
>
+1. Having a simpler table, e.g. like below, would be great!

CCE | NIST Refs | XCCDF Rule Title | Pass/Fail

**Comment by mpreisler** [comment]
Implemented in #188, fixed in #357

If you don't agree please reopen.
