### ISSUE TITLE
Feature request: Consider the ability to reshuffle HTML guide's content

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/openscap#248]
The currently generated HTML guide for benchmarks / profiles from SSG always follows the very same structure:
* Introduction
* System settings
  * Installing Software section etc.
* Services

It would be nice if the HTML guide could support providing the very same content, but having the particular sections reshuffled according to the preferences of the user.

Concrete Use Case:

Consider the PCI DSS v3 standard form. Let's suppose the use would want to have a HTML guide in the form of:
  * Display sections / rules for "Req #1 first",
  * Display sections / rules for "Req #2",
  * ... Display sections / rules for "Req #12"

Thank you for your consideration, Jan.

**Comment by mpreisler** [comment]
We decided to solve this by transforming the SCAP content instead.

https://github.com/OpenSCAP/scap-security-guide/pull/1241
