### ISSUE TITLE
Docs: User manual should be installed by `make install`

### ISSUE THREAD

**Issue by isimluk** [OpenSCAP/openscap#250]
@msrubar, could you please look into this?

**Comment by msrubar** [comment]
Yes, I'll resolve this issue.

**Comment by jan-cerny** [comment]
@redhatrises Yes, it's there:
https://github.com/OpenSCAP/openscap/blob/900295ef58d121b15533fcd8736d3950417134b0/docs/CMakeLists.txt#L45-L47

Fixed in https://github.com/OpenSCAP/openscap/pull/1109
