### ISSUE TITLE
Setting the XCCDF rule, role attribute to unscored is not working in openscap1.2.6

### ISSUE THREAD

**Issue by jacobvar** [OpenSCAP/openscap#272]
Setting the XCCDF rule, role attribute to unscored is not working in openscap 1.2.6. This
was working earlier in openscap 1.2.3.

**Comment by jan-cerny** [comment]
I can reproduce this issue. I am going to make a fix.

**Comment by jacobvar** [comment]
On 12/16/15 07:21 AM, Jan Černý wrote:
>
> I can reproduce this issue. I am going to make a fix.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/OpenSCAP/openscap/issues/272#issuecomment-165139323>.
>
Thanks a lot Jan. Much appreciated. You are awesome!
Jacob.
