### ISSUE TITLE
Can't execute sce from Datastream

### ISSUE THREAD

**Issue by xCXDx** [OpenSCAP/openscap#295]
I'm using openscap.x86_64 1.2.7-0.3.el7.centos on Centos 7.2 and I want to execute a Datastream witch includes OVAL and SCE. When I execute this with the command

    oscap xccdf eval datastream.xml

i get the error

    OpenSCAP Error: SCE couldn't find script file 'sce_true.sh'. Expected location: './sce_true.sh'. [sce_engine.c:329]

When I copy the script I use, manually to this location, it works, but thats not the way Datastream should work. I tried also the Version openscap.x86_64 1.0.10-3.el6.centos on Centos 6.7 and Ubuntu 14.04 and there it works the way it should work. openScap extracts the scripts there from datastream and executes them.

The configuration is similar on both hosts.

Does anybody have a solution for sce in datastream with openscap 1.2?

**Comment by isimluk** [comment]
Thanks for reporting this. I have found that we do not have tests for this. We will need to look further into this.

**Comment by ybznek** [comment]
I confirm the issue, with maint-1.0 is it ok, but with maint-1.2 doesn't work

Error message
```
OpenSCAP Error: Error while creating script component (id='scap_org.open-scap_ecomp_services--obsolete--disable_nfs_exports.sh') to file '/tmp/oscap.2PicNM/././services/obsolete/disable_nfs_exports.sh'. [sds.c:165]
SCE couldn't find script file 'services/obsolete/disable_nfs_exports.sh'. Expected location: './services/obsolete/disable_nfs_exports.sh'. [sce_engine.c:329]
```
