### ISSUE TITLE
Run SCE tests during make distcheck

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/openscap#300]
Make distcheck involves `./configure`, but without `--enable-sce`, which means that tests from `tests/sce` directory are not run during `make distcheck`, and therefore they are not run on Jenkins.

I think we should run these tests regularly, because the SCE is part of distributed software,

**Comment by isimluk** [comment]
Related to #255. (Can be fixed by fixing #255).

**Comment by evgenyz** [comment]
So, I guess it was fixed in https://github.com/OpenSCAP/openscap/commit/7bf437c4a392d7ba3d511674f71cd0d608a5c4c5. Closing.
