### ISSUE TITLE
openscap-containers should depend on atomic

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/openscap#302]
Hello!
I am have installed openscap-containers-1.2.8-1.fc23.noarch on Fedora 23 minimal with Python 3. I can't run the `oscap-docker` command. It requires atomic, but the package does not depend on it. Please see this example of command that I am running:
```
[root@localhost ~]# oscap-docker
Failed to import "Atomic.mount.DockerMount". It seems Atomic has not been installed.
````
It seems to me that the spec file should be amended that openscap-containers package should depend on atomic package.

**Comment by jan-cerny** [comment]
```
[root@localhost ~]# rpm -qpR openscap-containers-1.2.8-1.fc23.noarch.rpm
/usr/bin/python3
openscap = 1.2.8-1.fc23
openscap-scanner
python(abi) = 3.4
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PartialHardlinkSets) <= 4.0.4-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1
```

**Comment by jan-cerny** [comment]
discussed this with @isimluk. I understand that this is a noarch package which should not depend on package which is available ONLY on certain architectures, but not at all of them.

**Comment by isimluk** [comment]
The openscap-containers is a downstream "thing" (fedora's openscap.spec file to be specific).

There is nothing we can do about this in upstream. :-)
