### ISSUE TITLE
oscap-docker gives a weird message on vulenrability scan

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/openscap#304]
I have openscap-contaners 1.2.8 on Fedora 23 minimal with Python3.
I have run the vulnerability scan of Fedora container. I am aware of fact it does not make nay sense to run vulnerability scan of Fedora for RHEL 7 vulnerabilitites. However, I am surprised with a weird error message at the end of the output. 

Please see the last line:

```
[root@localhost ~]# docker run -d fedora sleep 3600
c47eb2130910301e577e5c9758c1546eb83c2c4bac0a6b157b4671c58e18846f
Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
[root@localhost ~]# oscap-docker container-cve c47eb2130910301e577e5c9758c1546eb83c2c4bac0a6b157b4671c58e18846f
Definition oval:com.redhat.rhsa:def:20160071: false

[ .................................................. ]

Definition oval:com.redhat.rhsa:def:20140675: false
Evaluation done.
Response header of HTTP doesn't contain"last-modified" field. Cannot determine version of remote file "https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL7.xml.bz2"[root@localhost ~]# 
````
It seems to me an error of communication with rhsa server.

**Comment by jan-cerny** [comment]
Hello! I have pulled the RHEL7 container and I experience the same message also for scanning the image.
Steps to reproduce:
1) docker pull rhel7
2) oscap-docker image-cve rhel7

The vulnerability scan works OK, return code is 0, but the suspicious message is here again: 
```
Response header of HTTP doesn't contain"last-modified" field. Cannot determine version of remote file "https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL7.xml.bz2"
```

**Comment by isimluk** [comment]
I think @baude and @mpreisler have seen the "last-modified" field missing previously.

Do you now for sure this is not just a warning? Does the scan compelete or not? If this is harmless, does it make sense to include `Warning: ` at the start of the message?

**Comment by mpreisler** [comment]
Last time we've seen this the https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL7.xml.bz2 regressed by not sending the headers. Could be that the same situation is happening again... :-(

I did some digging to confirm and it seems the header is there. See
```
$ curl -i -X HEAD https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL7.xml.bz2
HTTP/1.1 200 OK
Server: Apache
Last-Modified: Thu, 28 Jan 2016 13:31:51 GMT
ETag: "1277-3bd13-52a64f0f15fc0"
Accept-Ranges: bytes
Content-Length: 245011
Content-Type: application/x-bzip2
Date: Thu, 28 Jan 2016 15:14:44 GMT
Connection: keep-alive
X-N: S
```

Could it be a case sensitivity issue?

**Comment by jan-cerny** [comment]
@mpreisler Yes, it is a case sensitivity issue. 

https://github.com/OpenSCAP/openscap/blob/maint-1.2/utils/oscap_docker_python/get_cve_input.py#L81

The HTTP headers are here converted to a dictionary. In this dictionary the keys are names of Headers. However in Python the dictionary keys are case sensitive. We use `'last-modified'` as a key, but I verified that currently the server gives `'Last-Modified'`

Here is my quick attempt:

```
Python 3.4.3 (default, Jun 29 2015, 12:16:01) 
[GCC 5.1.1 20150618 (Red Hat 5.1.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib.request
>>> r = urllib.request.urlopen("https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL7.xml.bz2")
>>> d = dict(r.info())
>>> d
{'Last-Modified': 'Thu, 28 Jan 2016 16:19:49 GMT', 'Accept-Ranges': 'bytes', 'Server': 'Apache', 'ETag': '"259f-3be0a-52a6749a37340"', 'Date': 'Mon, 01 Feb 2016 07:52:53 GMT', 'Content-Type': 'application/x-bzip2', 'Connection': 'close', 'Content-Length': '245258'}
>>> d['last-modified']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'last-modified'
>>> d['Last-Modified']
'Thu, 28 Jan 2016 16:19:49 GMT'
>>> 
```

**Comment by mpreisler** [comment]
@jan-cerny Do you have plans to fix this? I volunteer to review.

**Comment by mpreisler** [comment]
Discussed this with @ybznek just now. The good news is that this is just a message. The scan will still work. The bad news is that caching the content locally is broken since the hosting changed from lowercase last-modified headers to `Last-Modified`. We need to fix this in OpenSCAP.

**Comment by ybznek** [comment]
I will fix it.

**Comment by jan-cerny** [comment]
Fixed in https://github.com/OpenSCAP/openscap/pull/308
