### ISSUE TITLE
HTML report says the target was host even if I scan VM or container

### ISSUE THREAD

**Issue by mpreisler** [OpenSCAP/openscap#305]
Seems to be related to offline scanning.

I will add more details later.

**Comment by ybznek** [comment]
If I understood well, reproducer can be
```
oscap-docker image fedora:23 xccdf eval --report /tmp/report.html  /usr/share/xml/scap/ssg/content/ssg-fedora-xccdf.xml 
```
And this is result what we don't want:
![screenshot_2016-04-07_12-39-40](https://cloud.githubusercontent.com/assets/2564361/14348594/d3861594-fcbd-11e5-834b-0761e75c2b6b.png)
(zmoravec-thinkpad is machine where docker is running)

@mpreisler What result do you expect for vm/container/chroot? Get hostname from target, or something like "Target image: fedora:23" ?

**Comment by mpreisler** [comment]
@ybznek I will defer to you with that decision. There are pros and cons to both approaches.

**Comment by mpreisler** [comment]
@rsprudencio Wasn't this fixed by your system_info patches?

**Comment by rsprudencio** [comment]
@mpreisler It work in any chroot'ed scan, but I'm not sure about container because we rely on /boot/grub2/ files and AFAIK containers doesn't have anything in /boot, I'll test it and update this with more info.

**Comment by mpreisler** [comment]
Discussed this today, this is still reproducible according to @yuumasato.

We want something like: `Target: image asdfasdfasdf on zmoravec-thinkpad`. Not sure how to get it there though.

**Comment by jan-cerny** [comment]
I think this is very visible issue
