### ISSUE TITLE
Build Fails 

### ISSUE THREAD

**Issue by princeriley** [OpenSCAP/openscap#306]
➜  openscap git:(maint-1.2) ✗ make check
Making check in lib
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-recursive
make[3]: Nothing to be done for `check-am'.
Making check in src
Making check in common
  CC       liboscapcommon_la-debug.lo
debug.c:166:40: error: use of undeclared identifier
      'program_invocation_short_name'
        fprintf(__debuglog_fp, "%c: %s: ", l, program_invocation_short_name);
                                              ^
debug.c:178:3: error: use of undeclared identifier
      'program_invocation_short_name'
                program_invocation_short_name, (long) getpid(), thread_name,
                ^
2 errors generated.
make[2]: *** [liboscapcommon_la-debug.lo] Error 1
make[1]: *** [check-recursive] Error 1
make: *** [check-recursive] Error 1

**Comment by isimluk** [comment]
Not true. Build runs just fine for me. :-)

Perhaps it only fails with your compiler on your system. Altough, I cannot tell, further from this info.

Please note, there are instructions to build OpenSCAP for windows in user manual. https://github.com/OpenSCAP/openscap/blob/master/docs/manual/manual.adoc#building-openscap-on-windows 

@mpreisler has been able to build openscap on macosx and include it into our scap-workbench macosx binary.

**Comment by mpreisler** [comment]
I have not run the test suite on MacOSX and Windows. Most likely you can get it to work but it will require some effort.

**Comment by jan-cerny** [comment]
I have found out that program_invocation_short_name is a GNU extension.
See http://linux.die.net/man/3/program_invocation_short_name.
The purpose of this variable here is to display name of the program which generated the message in verbose log. 

I think we should use there conditional compiling (`#ifdef ...`)

**Comment by princeriley** [comment]
Could you please provide mor specific details on how To build on MacOSX
including the build script

Thanks

Prince

**Comment by mpreisler** [comment]
@princeriley Hi, the biggest pain is installing the dependencies. I did that using macports. Then I did:

```
./configure --disable-probes --disable-python --disable-util-oscap-docker
make -j 4
```

Keep in mind that this will yield an openscap that cannot scan the local machine! It is only useful for tools that manipulate SCAP content, such as SCAP Workbench. It is quite possible that openscap would build even with the probes but that hasn't been tested and isn't supported.

**Comment by princeriley** [comment]
Hello

I appreciate the advice and the suggestions

I'm going to commit to making MacOSX a full fledged platform for OpenSCAP
as I believe there shouldn't be any barriers to entry for people using sCAP
on Mac OSX

I'll start with Maverick and by the end of this summer I should have a
Yosemite version of scripts ready to post

If you don't object I'll fork off this effort and send you weekly update on
my plans and progress

Prince Riley

**Comment by mpreisler** [comment]
That sounds excellent! I recommend working on the `master` branch because there are already some Windows and MacOSX portability patches there.

We are always delighted about forks and patches :-)

**Comment by princeriley** [comment]
I have two issues with MacPorts the first is I appreciate their fine work
on ports of the Linux and Unix tools and libraries but they seldom do
enough quality assurance on their builds to meet Apple standards That's not
a criticism of them or third work But I want Appke to adopt OpenSCAP next
year

Prince

**Comment by princeriley** [comment]
Thanks

I need to put the porting plan together and delve into the code base in
more detail so I can lay out a development roadmap

I'll take on Windows 7 and MacOSX Mavetick

Need to set up quality checks through a few other people to check and
validate my works with a alpha beta gamma release staging ( need to discuss
release tests at these quality gates)

Prince

**Comment by princeriley** [comment]
Eventually I want to put our docker containers for SCAP and a Apple
Developer approved DMG

**Comment by princeriley** [comment]
I'm not sure the link you provided to me in your last email about building
on MaCOSX was very helpful since it is more specific to Windows than MacOSX

My initial review of the build log indicates theres no missing libraries or
a flag setting that could be tripping things up

Prince

**Comment by princeriley** [comment]
If you don't mind

Could you rebuild it again on your MacOSX platform bit pipe the output to a
file and email it to me

That way I can do the same at my end and check the builds in each file to
figure out where the problem is coming from and how to fix it

Thanks

Prince

**Comment by mpreisler** [comment]
I don't have a MacOS X machine available right now, sorry.

**Comment by princeriley** [comment]
Understood

Where can I get my hands on all the Python OpenSCAP programs and Libraries

Prince
