### ISSUE TITLE
[RFE] oscap ds sds-compose: Allow @use-case attribute to be set / specified to something else than just "OTHER"

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/openscap#330]
```oscap``` right now does not allow to specify value of the ```@use-case```  when composing DataStream. There's this hard-coded "OTHER" value:
&nbsp; &nbsp; [1] https://github.com/OpenSCAP/openscap/blob/maint-1.2/src/DS/sds.c#L999

But there might be cases when specific value of ```@use-case``` attribute is required, e.g. (output from SCAP NIST content validation testsuite when validation DS produced by openscap) -- mentioning just row / error message in question:
```
324-1 	1
(of 1) 	ERROR 	SCHEMATRON
	scap_org.open-scap_datastream_from_xccdf_ssg-rhel6-xccdf-1.2.xml - The @use-case 
attribute in the <ds:data-stream> element MUST be set to "CONFIGURATION", "VULNERABILITY", 
"INVENTORY" or "OVAL_ONLY" 	/*:data-stream-collection[namespace-uri()='http://scap.nist.gov
/schema/scap/source/1.2'][1]/*:data-stream[namespace-uri()='http://scap.nist.gov/schema
/scap/source/1.2'][1] 	matches(@use-
case,'^(CONFIGURATION|VULNERABILITY|INVENTORY|OVAL_ONLY)$')
```

from e.g. ( https://jlieskov.fedorapeople.org/scap-scapversion-1.2-validation-result.html )

Obviously the "OTHER" ```@use-case``` value being the only hard-coded, right now it's not possible to meet the aforementioned requirement using just solely ```oscap ds sds-compose``` CLI.

Maybe some of the future versions could add support for new command line argument, e.g. something like:

```oscap ds sds-compose --use-case=CONFIGURATION```

Thank you for consideration, Jan.

**Comment by mpreisler** [comment]
This is odd, I vaguely remember writing this code and I think `OTHER` was a valid allowed option.

I don't see how to choose the right `@use-case` automatically so probably we will have to add a command line option to both `sds-compose` and `sds-add`.

**Comment by iankko** [comment]
Ad ```OTHER``` being valid option, you are correct. Seems: 
* [draft-SP800-126r2.pdf](http://www.thecre.com/fisma/wp-content/uploads/2011/07/draft-SP800-126r2.pdf) allowed just ```CONFIGURATION```, ```VULNERABILITY```, ```OVAL_ONLY```, or 
```INVENTORY``` (page #19) . But then final r2 introduced also ```OTHER``` option: 

* [nistspecialpublication800-126r2.pdf]( http://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-126r2.pdf) => ```The value MUST be one of the following: CONFIGURATION, VULNERABILITY, INVENTORY , or OTHER``` (page #21)

> I don't see how to choose the right @use-case automatically so probably we will have to add a command line option to both sds-compose and sds-add.

Yes. This would be appreciated. Thanks.

**Comment by mpreisler** [comment]
@iankko, since SSG does both vulnerability and configuration in one XCCDF we probably can use the `OTHER` option just fine. We just need to figure out how to get the schematron fixed up so that it allows `OTHER` as an option.

**Comment by iankko** [comment]
@mpreisler 
While I agree with the above, a bit afraid when proposing this they might come with argument both the ```CONFIGURATION | VULNERABILITY``` to be more specific for the particular use case than ```OTHER```.

But that shouldn't be blocker you to try this.

Thanks! Jan.

**Comment by mpreisler** [comment]
Hi @iankko!

Dragos confirmed that this is a bug in SCAPVal on the scap-dev list:

> Hello Mr. Preisler,
> 
>    Thank you for bringing this issue to our attention. SCAPVal's team was aware of this issue and already corrected it. The fix will be available in the next release. I'll retest it using your content to make sure it works properly.
> 
> We appreciate your email and look forward to the opportunity to provide additional support if needed.
> 
> Respectfully,
>  Dragos Prisaca 
>  NVLAP Technical Expert
 > NIST SCAP Validation Program | NIST ITL/CSD support

As far as I can tell you don't have to make any changes to SCAP Security Guide regarding this, just ignore the error. I will keep this open as a feature request for use-case attribute change using the command-line.

**Comment by isimluk** [comment]
I am ok, to close this issue if others agree. :)

**Comment by iankko** [comment]
@mpreisler 
> Dragos confirmed that this is a bug in SCAPVal on the scap-dev list:

Thanks, Martin! Asked them to clarify the date of the future SCAPVal release if possible yet.
..
> As far as I can tell you don't have to make any changes to SCAP Security Guide regarding this, just ignore the error. 

Right (will keep it as is so we verify the issue in upstream testsuite is fixed :)).

> I will keep this open as a feature request for use-case attribute change using the command-line.

Of course it would be better to have this feature implemented. But it's truly sole RFE now (feel free to close it should you got an opinion there isn't high chance someone else would want it too).

Thanks.

**Comment by mpreisler** [comment]
OK, closing then. Let's see if somebody requests this again.
