### ISSUE TITLE
The group-by feature in HTML report should sort the references by ID

### ISSUE THREAD

**Issue by mpreisler** [OpenSCAP/openscap#342]
Else it's very hard to find the requirement ID I am looking for. See attached screenshot.

The order seems implementation defined or undefined.

![image](https://cloud.githubusercontent.com/assets/753153/13613237/4a7f5d5a-e539-11e5-87c7-526fe199c83a.png)

Please consider sorting in a way that makes sense for most of the IDs. Most of the IDs are sets of numbers delimited by some delimiter. Just sorting them as strings will not provide the best results. Splitting the IDs by known delimiters and then sorting the lists will work better.

**Comment by jan-cerny** [comment]
@mpreisler Thanks for bringing this up. I am looking into it now. I found that sorting for PCI-DSS IDs has been already implemented before, but that time we did not have the granularity (eg. 10.5.2). I would like to implement it in a more robust way.

**Comment by jan-cerny** [comment]
Fixed in https://github.com/OpenSCAP/openscap/pull/357
