### ISSUE TITLE
partition-probe offline scan

### ISSUE THREAD

**Issue by ybznek** [OpenSCAP/openscap#343]
To scan partitions of container we need to have access to `/proc/mounts` of container.
Current implementation of atomic mount doesn't provide access to the **/proc/mounts**.
https://github.com/projectatomic/atomic/issues/310

We can gain access to the file using bash (or appropriate C functions), but we need PID of container

```
pid=$(sudo docker inspect -f "{{.State.Pid}}" 6aefb3ccf384)
sudo cat /proc/$pid/mounts
or
sudo nsenter -t $pid -m -p cat /proc/mounts 
```

```
```

**Comment by matusmarhefka** [comment]
We agreed to close this as `atomic scan` is working with mounted container images, these images are not run during the scan.
