### ISSUE TITLE
password/shadow-probe offline-scan

### ISSUE THREAD

**Issue by ybznek** [OpenSCAP/openscap#344]
It seems, that support of offline for these probes is primitive. but passwords aren't stored only in /etc/passwd, but can be provided by LDAP server and other sources.

Thes command get password from configured sources (or similar C function).
```
$ getent passwd
```

Choosing of source of passwords,... is provided by Name Service Switch (NSS)
```
$ cat /etc/nsswitch.conf
```

Main problems are:
- We cannot get passwords from LDAP in offline container, because it can need running ```nslcd``` daemon to do LDAP queries. If the daemon is not available, we get only some of passwords and (un)availability of LDAP database is unknown for us. So we don't know that we don't have whole password database
- We can check if container use only local password database (/etc/passwd) and do evaluation and return "not checked" if container tries to use other type of database. BUT there is no standard way to determine, what database container uses, 2 possible, but BAD solutions of this problems:
  - we can parse /etc/nsswitch.conf in openscap
  - use code from "/usr/src/debug/glibc-2.21/nss/nsswitch.h" - not public API

Only good solution is to enforce somebody to provide us public API to get possible sources of password and determine to scan or not depending of these sources.

**Comment by ybznek** [comment]
I will close this issues. Currently there is no clean way to fix it. Reference to this issue is in commit message of probe.

**Comment by praving55** [comment]
Hi @ybznek,
I was thinking that it is better to have something than nothing. For containers, password and shadow test could be based out of files. Do you want to discuss this?

Thanks and regards,
Pravin Goyal

**Comment by ybznek** [comment]
Hi @praving55,
I am not sure whether possibly wrong results are better than no results. As far as I know, we are not able to show some VISIBLE warning that scan might not read all usernames/passwords.

Cannot you use e.g. textfilecontent probe?

We could discuss it on openscap mailing list, it will be more visible for community than this issue.

**Comment by praving55** [comment]
You are right. We can live with alternatives.
