### ISSUE TITLE
Improve behavior of OSCAP_PROBE_ROOT_* behavior

### ISSUE THREAD

**Issue by ybznek** [OpenSCAP/openscap#346]
In SSG, these probes are in "top" list:
- partition_object  
- sysctl_object  
- selinuxsecuritycontext_object 

All these probes need access to **/proc** filesystem, but we cannot provide it to probe.
There are more probes, like process58 which will became available offline with /proc/

I would like to add some next **OSCAP_PROBE_**\* environment variable (OSCAP_PROBE_PID_CONTEXT) and enable 3rd type of OFFLINE_MODE to probe.

If this variable is specified, our probe will do something like _nsenter_ (probably setns() function) and became able to scan /proc filesystem

It needs to be discussed.

Possible results:
- more offline probes available - but only for running systems/containers
- need to solve situation, when namespace is shared between host and container - we can accidentally scan host, instead of container
- currently we don't have required atomic/oscap-docker

related info: https://github.com/OpenSCAP/openscap/issues/343

**Comment by matusmarhefka** [comment]
None of the probes are applicable for container scanning and we agreed to support offline scanning of VMs the same way as for containers, thus closing this.
