### ISSUE TITLE
Suspicious error messages with chroot

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/openscap#368]
When testing #361 I have discovered that running a scan with chroot to a directory where can emit suspicious error messages on stderr.
```
[root@thinkpad openscap]# utils/oscap-chroot /tmp oval eval cpe/openscap-cpe-oval.xml
error: Failed to initialize NSS library
Definition oval:org.open-scap.cpe.rhel:def:7: not applicable
Definition oval:org.open-scap.cpe.rhel:def:6: not applicable
error: Failed to initialize NSS library
Definition oval:org.open-scap.cpe.rhel:def:5: not applicable
Definition oval:org.open-scap.cpe.rhel:def:1: not applicable
Definition oval:org.open-scap.cpe.fedora:def:25: not applicable
Definition oval:org.open-scap.cpe.fedora:def:24: not applicable
Definition oval:org.open-scap.cpe.fedora:def:23: not applicable
Definition oval:org.open-scap.cpe.fedora:def:22: not applicable
Definition oval:org.open-scap.cpe.fedora:def:21: not applicable
Definition oval:org.open-scap.cpe.fedora:def:20: not applicable
Definition oval:org.open-scap.cpe.fedora:def:19: not applicable
Definition oval:org.open-scap.cpe.fedora:def:18: not applicable
Definition oval:org.open-scap.cpe.fedora:def:17: not applicable
Definition oval:org.open-scap.cpe.fedora:def:16: not applicable
Evaluation done.
libgcc_s.so.1 must be installed for pthread_cancel to work
libgcc_s.so.1 must be installed for pthread_cancel to work
libgcc_s.so.1 must be installed for pthread_cancel to work
```

I think that these messages were hidden before, because probes used to have redirected stderr to /dev/null. I have removed this recently in https://github.com/OpenSCAP/openscap/pull/365, so these error messages came into light.

**Comment by jan-cerny** [comment]
Actually @isimluk has predicted future. 
> Removal of that dup2 in NDEBUG has potential to give us some surprises in future. However, I am ok accepting the risk.

**Comment by ybznek** [comment]
I've successfully handled
```error: Failed to initialize NSS library``` I will add it do ***dI*** output

**Comment by ybznek** [comment]
```
libgcc_s.so.1 must be installed for pthread_cancel to work
```

Is really caused by missing "libgcc_s.so.1". It will chroot to directory, ..., tries to call pthread_cancel - this tries to load "libgcc_s.so.1" from chrooted root.

As our offline mode works, we probably aren't able to fix that issues. The most what we can do is try to hide the error message.

**Comment by jan-cerny** [comment]
@ybznek What is the impact of this message? How does this issue affect the scan? Does it cause some unexpected result or false positives? If yes, we should not hide the message.

**Comment by ybznek** [comment]
I have done some workaround https://github.com/OpenSCAP/openscap/pull/386. This issue it should fix, but another dynamic library can be loaded in similar way and write error too.

**Comment by jan-cerny** [comment]
@ybznek Should we close this issue now?
