### ISSUE TITLE
Missing xccdf:TestResult/test-system attribute

### ISSUE THREAD

**Issue by isimluk** [OpenSCAP/openscap#372]
We do not export this attribute when creating xccdf:TestResult.

We should not always export our version, we need to parse it from the input and hold in a structure, if we process TestResult from other product.

**Comment by isimluk** [comment]
Credits: This has been first reported by Dragos Prisaca.

**Comment by jan-cerny** [comment]
Fixed in https://github.com/OpenSCAP/openscap/pull/457
