### ISSUE TITLE
Refactor rpm* probes

### ISSUE THREAD

**Issue by ybznek** [OpenSCAP/openscap#379]
We definitely should refactor these probes. There is lot of common code copied/pasted in these four probes. 

Currently, every fix we need to repeat four times.
- rpminfo
- rpmverify
- rpmverifyfile
- rpmverifypackage

**Comment by jan-cerny** [comment]
This is a really good task to get into the OpenSCAP code base to learn a lot about them. @ybznek has already re-factored some of it, but there is much more to re-factor in the rpm probes.
