### ISSUE TITLE
probe_rpmverify does not compile on RHEL5 and SLES11

### ISSUE THREAD

**Issue by AndreasKrause** [OpenSCAP/openscap#393]
Anticipating a future release of openscap-1.2.9 I tried to compile a current snapshot of maint-1.2. On this occasion I stumbled upon problems compiling probe_rpmverify on RHEL5 and SLES11. Guess it's somehow related to the version of rpmlib on these systems. Any chance to fix that before 1.2.9 is released?

    creating probe_rpmverify
    if gcc -DHAVE_CONFIG_H -I. -I. -I../../..     -O2 -g -m64 -mtune=generic -pipe -std=c99 -W -Wall -Wnonnull -Wshadow -Wformat -Wundef -Wno-unused-parameter -Wmissing-prototypes -Wno-unknown-pragmas -D_GNU_SOURCE -DOSCAP_THREAD_SAFE -D_POSIX_C_SOURCE=200112L -Wno-unused-function -I/usr/include/libxml2   -DOSCAP_THREAD_SAFE -D_REENTRANT -D_POSIX_PTHREAD_SEMANTICS -DTHREAD_SAFE -DSEAP_THREAD_SAFE -I../../../src -I../../../src/common -I../../../src/common/public -I../../../src/source/public -I../../../src/OVAL -I../../../src/OVAL/public -I../../../src/OVAL/probes/public -I../../../src/OVAL/probes/SEAP/public -I../../../lib -MT probe_rpmverifyfile-rpmverifyfile.o -MD -MP -MF ".deps/probe_rpmverifyfile-rpmverifyfile.Tpo" -c -o probe_rpmverifyfile-rpmverifyfile.o `test -f 'unix/linux/rpmverifyfile.c' || echo './'`unix/linux/rpmverifyfile.c; \
    	then mv -f ".deps/probe_rpmverifyfile-rpmverifyfile.Tpo" ".deps/probe_rpmverifyfile-rpmverifyfile.Po"; else rm -f ".deps/probe_rpmverifyfile-rpmverifyfile.Tpo"; exit 1; fi
    unix/linux/rpmverifyfile.c: In function 'rpmverify_additem':
    unix/linux/rpmverifyfile.c:366: error: 'RPMVERIFY_FILEDIGEST' undeclared (first use in this function)
    unix/linux/rpmverifyfile.c:366: error: (Each undeclared identifier is reported only once
    unix/linux/rpmverifyfile.c:366: error: for each function it appears in.)
    unix/linux/rpmverifyfile.c: At top level:
    unix/linux/rpmverifyfile.c:401: error: 'VERIFY_FILEDIGEST' undeclared here (not in a function)
    unix/linux/rpmverifyfile.c:401: warning: missing initializer
    unix/linux/rpmverifyfile.c:401: warning: (near initialization for 'rpmverifyfile_bhmap[10].a_flag')
    unix/linux/rpmverifyfile.c:402: error: 'VERIFY_CAPS' undeclared here (not in a function)
    unix/linux/rpmverifyfile.c:402: warning: missing initializer
    unix/linux/rpmverifyfile.c:402: warning: (near initialization for 'rpmverifyfile_bhmap[11].a_flag')
    make[3]: *** [probe_rpmverifyfile-rpmverifyfile.o] Error 1
    make[3]: Leaving directory `/usr/src/redhat/BUILD/openscap-maint-1.2/src/OVAL/probes'
    make[2]: *** [all-recursive] Error 1
    make[2]: Leaving directory `/usr/src/redhat/BUILD/openscap-maint-1.2/src/OVAL/probes'
    make[1]: *** [all-recursive] Error 1
    make[1]: Leaving directory `/usr/src/redhat/BUILD/openscap-maint-1.2'
    make: *** [all] Error 2
    error: Bad exit status from /var/tmp/rpm-tmp.71732 (%build)
    
    
    RPM build errors:
        Bad exit status from /var/tmp/rpm-tmp.71732 (%build)

**Comment by praving5** [comment]
@AndreasKrause which SLES 11 version? I am using SLES 11 SP3 and rpmverify works great there. I am using OpenSCAP 1.2.5 though and have installed it from [here](http://download.opensuse.org/repositories/security/SLE_11_SP3/x86_64/)

**Comment by AndreasKrause** [comment]
It's SLES11 SP4 . With openscap 1.2.5 it compiles fine, too. But it fails for the pre-1.2.9 version.

**Comment by jan-cerny** [comment]
Fixed in https://github.com/OpenSCAP/openscap/pull/452
