### ISSUE TITLE
SCE results aren't embedded in XCCDF reports

### ISSUE THREAD

**Issue by AndreasKrause** [OpenSCAP/openscap#394]
When evaluating xccdf with `--oval-results` OVAL result files (`*-oval.xml.result.xml`) are generated in current work dir. Similarily, when called with `--check-engine-results` SCE result files (`*.-sce.sh.result.xml`) appear.

However, when finally generating XCCDF reports, OVAL results are embedded in the HTML report file while SCE results aren't. This is reproducable on RHEL5+6, SLES11+12 (all with openscap-1.2.5).

**Comment by mpreisler** [comment]
Are you using the <check-import> feature in the SCE checks? See https://www.open-scap.org/features/other-standards/sce/

**Comment by AndreasKrause** [comment]
No, I'm referring to

> 2. use SCE result file
> In case there is no  <check-import import-name=”stdout” />  in the
> XCCDF (or the XSLT can’t find it for whatever reason), it will try to look for
> SCE result files and get their stdout element content.

Can't test with < check-import > right now since I'm on vacation, but I think I tested this as well and the result wasn't embedded either.

**Comment by jan-cerny** [comment]
I confirm this issue still persists on current maint-1.2.
When I run it in two steps,
```
oscap xccdf eval --profile default --check-engine-results --results results.xml  sce_xccdf.xml
oscap xccdf generate report results.xml > report.html
```
 the SCE results are missing, as reported.

However, When I generate report directly during XCCDF evaluation, the SCE results are shown in report. Try this:
````
oscap xccdf eval --profile default --check-engine-results --results results.xml  --report report.html sce_xccdf.xml
```
The SCE results are there.

My opinion is that there is a bug in generating HTML reports from XCCDF in `oscap xccdf generate report` command. I think that it simply does not try to find whether `*.result.xml` files are available.

**Comment by jan-cerny** [comment]
@AndreasKrause 
Does
`oscap xccdf generate report --sce-template "%.result.xml" results.xml > report.html`
work for you?

**Comment by AndreasKrause** [comment]
@jan-cerny 
Ahoj, Jan! Strangely enough, this also only embeds oval results, no sce results. The Option --sce-template works for me as a synonym for --oval-template.

**Comment by jan-cerny** [comment]
Hello, patches proposed in pull request https://github.com/OpenSCAP/openscap/pull/414 should fix this issue.

**Comment by jan-cerny** [comment]
Fixed in https://github.com/OpenSCAP/openscap/pull/414
