### ISSUE TITLE
Update openscap/xsl/xccdf_1.1_to_1.2.xsl to include profile

### ISSUE THREAD

**Issue by praving5** [OpenSCAP/openscap#399]
Hi,
Would it make sense to enhance  `openscap/xsl/xccdf_1.1_to_1.2.xsl` to have '`profile`' element added as well? We are already generating rule IDs. So, just make a default profile out of those rule IDs. This will save quite a bit of manual effort to add profile information later on.

Thanks and regards,
Pravin Goyal

**Comment by mpreisler** [comment]
I don't understand this request. XCCDF 1.1 to 1.2 is a conversion XSLT that converts XCCDF 1.1.x to 1.2. What exactly should we be adding? AFAIK the `(default)` profile concept stays the same between both of those versions of XCCDF.

**Comment by praving5** [comment]
Thanks Martin for looking at this. 

I was suggesting to add a specific profile instead of `(default)` profile concept. Most of the XCCDF documents have that and it would be good to be consistent. After using that XSLT, I had to then manually create  a profile section for all the rules. I feel this can be avoided and can be a great value add to complete the XCCDF 1.2 form.

**Comment by mpreisler** [comment]
I still don't understand, if the original XCCDF 1.1 had the profiles, the new XCCDF 1.2 will have them too. If the original didn't have profiles, the new converted XCCDF won't have them as well.

**Comment by praving5** [comment]
That's exactly my point. We use Simons's oval-to-xccdf xslt to get a xccdf 1.1 document directly from oval. Oval does not have profiles.So, the generated xccdf 1.1 document does not have profiles. And then I use xccdf 1.1 to xccdf 1.2 xslt. It is worth to address this use case.

**Comment by mpreisler** [comment]
That doesn't make sense to me, the transformation converts xccdf 1.1 to 1.2, it isn't meant to create any profiles...

**Comment by mpreisler** [comment]
what you could do is change oval-to-xccdf transform to have select="true" on all generated Rules. then use `(default)` profile.

**Comment by praving5** [comment]
Ok, Thanks.
