### ISSUE TITLE
Question: Is there a python library for openscap?

### ISSUE THREAD

**Issue by avb76** [OpenSCAP/openscap#400]
I didn't know where to put this question. Sorry if this isn't the right place.

Is there a python library that can offer the functionalities that oscap tool offers?

Thanks!

**Comment by iankko** [comment]
@avb76 
Check out the possibilities the openscap-python* Python language bindings provide:
```
$ dnf search openscap-python
====================================================================
N/S Matched: openscap-python 
=====================================================================
openscap-python.x86_64 : Python 2 bindings for openscap
openscap-python3.x86_64 : Python 3 bindings for openscap
```

HTH, Jan
(should you need some specific examples how to use certain functionality, let us know)

**Comment by avb76** [comment]
Thanks, @iankko!

**Comment by avb76** [comment]
@iankko, is there a github repo for `openscap-python`? I couldn't find one. I have the rpm already, but it would be nice to see what can I do with it. I usually look over the libraries code to understand better how to use them. Thanks!

**Comment by iankko** [comment]
@avb76 
> @iankko, is there a github repo for openscap-python? I couldn't find one. I have the rpm already, but it would be nice to see what can I do with it. I usually look over the libraries code in order to understand better how to use them. Thanks!

No, there isn't one (the Python bindings are generated automatically during the openscap pkg build process using the Swig tool). But having the ```openscap-python``` package installed and issuing query like:
```
$ for i in $(find -name '*.py'); do grep 'def oscap' $i >> /tmp/openscap-python; done
```
produces /tmp/openscap-python file with the following content for me:
```
def oscap_init():
def oscap_cleanup():
def oscap_get_version():
def oscap_document_type_to_string(type):
def oscap_validate_document(xmlfile, doctype, version, reporter, arg):
def oscap_schematron_validate_document(xmlfile, doctype, version, outfile):
def oscap_apply_xslt(xmlfile, xsltfile, outfile, params):
def oscap_path_to_schemas():
def oscap_path_to_schematron():
def oscap_path_to_cpe():
def oscap_determine_document_type(document, doc_type):
def oscap_clearerr():
def oscap_err():
def oscap_err_family():
def oscap_err_desc():
def oscap_err_get_full_error():
def oscap_text_new():
...
```
HTH

**Comment by avb76** [comment]
Thanks again, @iankko!

**Comment by mpreisler** [comment]
@avb76 I recommend using python's capabilities to figure out which functions are available. Especially `dir(..)`.

**Comment by avb76** [comment]
@mpreisler, thanks! I'll let you know if I run into any problems.
