### ISSUE TITLE
Guess OSCAP_PROBE_OS_VERSION when omitted

### ISSUE THREAD

**Issue by enoodle** [OpenSCAP/openscap#402]
When using the probe chroot mode it is often difficult to calculate the OS version without actually changing root and it seems like OpenSCAP could do that easily.

from: https://github.com/simon3z/image-inspector/pull/3#discussion_r59254319

**Comment by isimluk** [comment]
I think we should be able to guess all four OSCAP_PROBE_* variables at https://github.com/OpenSCAP/openscap/blob/28f52f56ecf2fb9399dd3036fed7a9f442fe9677/src/OVAL/probes/independent/system_info.c#L362

**Comment by jan-cerny** [comment]
@isimluk @enoodle Is this still actual? What source of values is expected for those variables?

**Comment by iankko** [comment]
@jan-cerny 
> @isimluk @enoodle Is this still actual? What source of values is expected for those variables?

IMHO if we are on Unix system && uname probe has been enabled / compiled, the ```os_name``` and ```os_version``` could be retrieved from the ```uname(&buf)``` call. Uname probe is already doing this:
    https://github.com/OpenSCAP/openscap/blob/maint-1.2/src/OVAL/probes/unix/uname.c#L70

For ```architecture``` (```OS_PROBE_ARCHITECTURE```) that info should be reachable via ```uname``` too. For ```hname``` (```OS_PROBE_PRIMARY_HOST_NAME```) we could use ```uname -n``` if first part of the hostname would be sufficient. Should this be set to FQDN, we would need to use different means of course.

On other platforms I would say there are also means how to retrieve this information.

Just my 2c.

**Comment by ybznek** [comment]
I think https://github.com/OpenSCAP/openscap/issues/305 could be "similar" issue.

**Comment by matejak** [comment]
We have reviewed this issue, and we couldn't figure out what is the use case behind it. Could you help us to understand why this feature is needed?

**Comment by isimluk** [comment]
Please be mindful that `uname` syscall may actually give you parameters of host system not guest container. So this may need some proper testing.

**Comment by evgenyz** [comment]
#998 is related issue.

**Comment by evgenyz** [comment]
I guess this could be closed by #1505.
