### ISSUE TITLE
[openscap-containers] [RFE] Introduce oscap-rkt (to inspect both vuln assessment and compliance) of images / containers build on top of rkt application container runtime

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/openscap#403]
The rkt package has been approved for Fedora 24+:
- https://bugzilla.redhat.com/show_bug.cgi?id=1169966#c52
- https://bugzilla.redhat.com/show_bug.cgi?id=1169966#c53
- https://admin.fedoraproject.org/pkgdb/package/rpms/rkt/
- https://trello.com/c/7fiOTmCZ/12-5-rkt-get-rkt-packaged-into-fedora-rawhide-and-f23-container-formats-bz-1169966
- https://github.com/coreos/rkt

We should create corresponding `oscap-rkt` utility to scan both cold rkt images and running containers.

**Comment by evgenyz** [comment]
Closing this because of existence of `oscap-podman` and lack of any activity.
