### ISSUE TITLE
oscap-docker - python2, ignore parameters, print always help

### ISSUE THREAD

**Issue by ybznek** [OpenSCAP/openscap#419]
I've just tried oscap-docker on RHEL7.3 (Python 2.7.5)

It ignore every parameters and print help always.

It is broken due to this change
https://github.com/OpenSCAP/openscap/commit/c00f3c44b7a64b814e765265fe6941c3f6f90cf5
but it doesn't seem that problem is in python/strange python API.

Before any deeper investigation; quick fix could be - run this line only with python3 and not with python2.

**We should also check why we haven't noticed it earlier.**

**Comment by dahaic** [comment]
Hello, the reason is change of defaults priority in python during 2.7 evolution :)

https://bugzilla.redhat.com/show_bug.cgi?id=1340036

**Comment by ybznek** [comment]
@dahaic Ah, thank you :)

**Comment by ybznek** [comment]
Fixed by https://github.com/OpenSCAP/openscap/commit/fa334865b1eb24c6eabfe4c80a339c84ffc2d250
