### ISSUE TITLE
declaration of ‘time’ shadows a global declaration

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/openscap#42]
Making all in XCCDF
make[3]: Entering directory `/var/www/html/openscap/src/XCCDF'
  CC     libxccdf_la-benchmark.lo
  CC     libxccdf_la-elements.lo
  CC     libxccdf_la-item.lo
  CC     libxccdf_la-profile.lo
  CC     libxccdf_la-value.lo
  CC     libxccdf_la-resolve.lo
  CC     libxccdf_la-result.lo
result.c: In function ‘xccdf_rule_result_override’:
result.c:1157: warning: declaration of ‘time’ shadows a global declaration
/usr/include/time.h:186: warning: shadowed declaration is here
  CC     libxccdf_la-result_scoring.lo
  CC     libxccdf_la-rule.lo
  CC     libxccdf_la-tailoring.lo
  CC     libxccdf_la-xccdf_session.lo

**Comment by isimluk** [comment]
Fixed in 404e2e3aec451ca5958591a81af12dd9e96a6133.

Thank You for the report!

Next time please consider creating ticket at https://fedorahosted.org/openscap/newticket
