### ISSUE TITLE
file probe - recurse_file_system="local" doesn't scan

### ISSUE THREAD

**Issue by ybznek** [OpenSCAP/openscap#429]
From openscap upstream tests:

```
    <file_object version="1" id="oval:1:obj:6" xmlns="http://oval.mitre.org/XMLSchema/oval-definitions-5#unix">
      <behaviors max_depth="2" recurse="directories" recurse_direction="down" recurse_file_system="local"   />
      <path>/</path>
      <filename xsi:nil="true"/>
      <filter action="exclude" xmlns="http://oval.mitre.org/XMLSchema/oval-definitions-5">oval:1:ste:5</filter>
    </file_object>

  </objects>
```

When `recurse_file_system="local"` is used during offline scan, it doesn't scan expected files.

https://github.com/OpenSCAP/openscap/blob/maint-1.2/src/OVAL/probes/oval_fts.c

**Comment by jan-cerny** [comment]
This error lies probably on line 159 in src/OVAL/probes/fsdev.c. There is a call of `setmntent()` that returns NULL. This functions that tries to open `/etc/mtab`. However, `/etc/mtab` is a symlink to `/proc/self/mounts`. We can't access /proc of mounted containers in offline scan. Therefore we got error "No such file or directory" when trying to open `/etc/mtab`.

**Comment by jan-cerny** [comment]
Question: What is the expected meaning of recurse_file_system="local" for scanning containers?
The OVAL specification defines this attribute as:
> The value of 'local' limits the search scope to local file systems (as opposed to file systems mounted from an external system). 

If this means for containers that we scan only root filesystem of the container, then I think that we could fix this issue by skipping ignoring the "behaviors" element for offline scans.

@ybznek @mpreisler Any suggestions are appreciated.

**Comment by ybznek** [comment]
Yes, missing /proc doesn't let us do many operations.

I don't think that we can cat the information about file systems in different way.

Skipping of "local" for offline mode can be solution, but I think we should return some message, that we ignore this option.

**Comment by mpreisler** [comment]
> Skipping of "local" for offline mode can be solution, but I think we should return some message, that we ignore this option.

agreed
