### ISSUE TITLE
Coverity scan TOCTOU failure in sysctl probe

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/openscap#430]
Performing a CoverityScan on OpenSCAP-1.2.9 returns the following TOCTOU check warning:

```
46. openscap-1.2.9/src/OVAL/probes/unix/sysctl.c:158: toctou: Calling function "fopen" that
uses "mibpath" after a check function. This can cause a time-of-check, time-of-use race
condition. 
```

When reading sysctl value, after fopen() we should add stat() call to ensure we are reading the sysctl value truly from the file, that got opened before.

**Comment by matejak** [comment]
It is still reported by Coverity for maint-1.2 1.2.17.
