### ISSUE TITLE
[RFE] Consider providing Windows binaries as part of OpenSCAP release process

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/openscap#434]
According to:
  [1] https://martin.preisler.me/2015/03/openscap-and-scap-workbench-on-windows-part-2/
it's possible to build OpenSCAP on Windows.

Maybe we could create `make windows` upstream Makefile target, that would ask for the location of the dependencies, and build Windows binaries?

Or if custom Win binaries build would be too challenging for common users, maybe we could provide pre-compiled Windows binaries with every OpenSCAP release on GitHub?

**Comment by mpreisler** [comment]
The Windows binaries of OpenSCAP would only be suitable for parsing the SCAP data formats. That's why we only build it for SCAP Workbench and nothing else.

We could provide oscap.exe that could do `oscap info`. The tool would also be able to validate contents, etc... But it wouldn't be able to scan.

Given the above I do not think there is enough value in the binaries to build them for every release.

**Comment by mpreisler** [comment]
@jan-cerny This is probably fixed for 1.3.0, right?

**Comment by jan-cerny** [comment]
@mpreisler This is not fixed at all. I would like to have it fixed, though. What are your suggestions?

My long-term idea was to provide a OpenSCAP for Windows Installer to be able to be downloaded for our users. This would enable the users to download and install OpenSCAP on Windows. Also, we should put a link to the Download page on our OpenSCAP portal. The Windows Installer will be of course marked as a technical preview and there must be a big disclaimer that it does not work as expected.

@mpreisler What is your opinion on this topic?

**Comment by mpreisler** [comment]
@jan-cerny my suggestion is to add creating an installer to the upstream release guide for master and then this can be closed IMO.

**Comment by evgenyz** [comment]
@jan-cerny @matejak The #1106 states that it fixes this bug. But it is still open. Can we close it?

**Comment by jan-cerny** [comment]
@evgenyz Yes, we publish Windows builds as a part of release process. We attach them to the GitHub release page, eg. https://github.com/OpenSCAP/openscap/releases/tag/1.3.1 contains a link to MSI installer. The process is described in https://github.com/OpenSCAP/openscap/blob/maint-1.3/release_tools/README.adoc. However, in practice, we don't build the binaries locally, but we build them in AppVeyor.
