### ISSUE TITLE
Tests for github issues

### ISSUE THREAD

**Issue by ybznek** [OpenSCAP/openscap#435]
When we report some bug, it is quite complicated to upload reproducer to github issue, especially when it needs more files. And it is a bit "complicated" to rerun the reproducer. 

We could have some upstream folder of not passing tests - the tests would not be launched during make dist(check), but they could be in same format - after fix, we could move them to classic test folder.

Side effect of this solution could be higher number of tests.

What do you think?

**Comment by iankko** [comment]
>  When we report some bug, it is quite complicated to upload reproducer to github issue, especially when it needs more files. And it is a bit "complicated" to rerun the reproducer.

Actually the need to attach a more complex reproducer is easier to achieve - GitHub support *.zip archive format. Though sharing the *.zip archive might be a bit inconvenient for the developer working on the fix due the need to expand it first.

The situation gets slightly more complicated when the reproducer is easy (IOW when it's just simple *-oval.xml file). In that case it's not easy to share it directly. Of course it can be workarounded by attaching *.txt form of that file. But again it might not be immediately obvious to the developer, the attached file should be converted back to *.xml to run it (not speaking about corner cases when the reproducer would contain some XML entities - the need to convert them back and fort).

> We could have some upstream folder of not passing tests - the tests would not be launched during make dist(check), but they could be in same format - after fix, we could move them to classic test folder.

How this folder would solve the situation with sharing the tests / reproducers?

> Side effect of this solution could be higher number of tests.
> 
> What do you think?

**Comment by ybznek** [comment]
I though that these tests will not be only archive with set of files.

Reproducers could be be in easy test format (openscap upstream test compatible) - so issue finder will
- create test files from template
- attach content
- add line with "oscap <parameters>"
- add greps
- push it to openscap

A bug solver can then
- run code immediately
- his PR with fix will contain - bugfix + move of tests to our normal test directory (+improve tests)

My opinion is that lot of issues consist of 
- environment - files on FS, ..
- content - xml file
- oscap parameters
- expected results - grep

And the "human readable" of this is quite similar to "machine readable form".

**Comment by iankko** [comment]
Thanks for clarification. This makes sense to me.

But IMHO rather than uses being able to push to openscap directly, I would probably recommend a separate repository where such tests would be stored. This will avoid the need to solve the issue how to give the access to users only to part of the git repository subtree, but forbid to push elsewhere.
