### ISSUE TITLE
Fix fileextendedattribute test

### ISSUE THREAD

**Issue by ybznek** [OpenSCAP/openscap#436]
https://github.com/OpenSCAP/openscap/issues/424

It was strange to my, when the probe doesn't work despite existing test.
- Remove https://github.com/OpenSCAP/openscap/blob/maint-1.2/tests/probes/fileextendedattribute/test_probes_fileextendedattribute.sh#L11 - xattr support of filesystem is possible to check using exit value of (setfattr/getfattr)
- https://github.com/OpenSCAP/openscap/blob/maint-1.2/tests/probes/fileextendedattribute/test_probes_fileextendedattribute.sh#L15 - is useless, probecheck do it
- don't create files in /tmp, but rather in current directory - my tmpfs doesn't support xattr, but classic filesystem (ext4,..) should support it

**Comment by matusmarhefka** [comment]
This is still valid.
