### ISSUE TITLE
get unknow result in centOS 5.11

### ISSUE THREAD

**Issue by wiseking1984** [OpenSCAP/openscap#437]
I downloaded openscap-maint-1.2,and compile it in centOS 5.11, install with: make install exec_prefix="/home/appweb/openscap".and "export OVAL_PROBE_DIR=/home/appweb/openscap/libexec/openscap/"
then I try oscap command, found that all the result are "unknow". can you explain why?
I try the same things in CentOS 6.7, which results are normal.

 ./oscap oval eval --skip-valid --result centos.linux.5.result.xml centos.linux.5.xml
 Definition oval:org.mitre.oval:def:10009: unknown
Definition oval:org.mitre.oval:def:10005: unknown
Definition oval:org.mitre.oval:def:10004: unknown
Definition oval:org.mitre.oval:def:10002: unknown
Definition oval:org.mitre.oval:def:10001: unknown
Definition oval:org.mitre.oval:def:10000: unknown
Evaluation done.

**Comment by mpreisler** [comment]
Please provide `oscap --v` and what you used as configure options.

**Comment by wiseking1984** [comment]
[root@localhost bin]# ./oscap --v
OpenSCAP command line tool (oscap) 1.0.8
Copyright 2009--2016 Red Hat Inc., Durham, North Carolina.

==== Supported specifications ====
XCCDF Version: 1.2
OVAL Version: 5.10.1
CPE Version: 2.3
CVSS Version: 2.0
CVE Version: 2.0
Asset Identification Version: 1.1
Asset Reporting Format Version: 1.1

==== Capabilities added by auto-loaded plugins ====
No plugins have been auto-loaded...

==== Paths ====
Schema files: /usr/share/openscap/schemas
Default CPE files: /usr/share/openscap/cpe
Probes: /usr/libexec/openscap

==== Inbuilt CPE names ====
./oscap: symbol lookup error: ./oscap: undefined symbol: oscap_source_new_from_file

**Comment by wiseking1984** [comment]
output in centOS 6.7

[appweb@web-49-206-hzifc bin]$ ./oscap --v
OpenSCAP command line tool (oscap) 1.2.10
Copyright 2009--2016 Red Hat Inc., Durham, North Carolina.

==== Supported specifications ====
XCCDF Version: 1.2
OVAL Version: 5.11.1
CPE Version: 2.3
CVSS Version: 2.0
CVE Version: 2.0
Asset Identification Version: 1.1
Asset Reporting Format Version: 1.1

==== Capabilities added by auto-loaded plugins ====
No plugins have been auto-loaded...

==== Paths ====
Schema files: /usr/local/share/openscap/schemas
Default CPE files: /usr/local/share/openscap/cpe
Probes: /usr/local/libexec/openscap

==== Inbuilt CPE names ====

==== Supported OVAL objects and associated OpenSCAP probes ====

**Comment by mpreisler** [comment]
```
./oscap: symbol lookup error: ./oscap: undefined symbol: oscap_source_new_from_file
```

You seem to have a mismatch between the `oscap` binary and the shared library. Wipe all instances of openscap from your system and install one version of it. Make sure you don't have multiple versions in /usr/lib(64) and /usr/local/lib(64).
