### ISSUE TITLE
[RFE] Performing a vulnerability scan of a machine - allow the result to contain only CVEs / RHSAs of selected importance

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/openscap#438]
Right now it's possible to perform a vulnerability (CVE) scan of a specific machine:
- https://www.open-scap.org/resources/documentation/perform-vulnerability-scan-of-rhel-6-machine/

It would be great if OpenSCAP could somehow allow the report to contain only CVEs / RHSAs of selected importance. For example suppose the case customer would want to scan only for critical flaws. It should be possible to specify the severity of the flaw, that should be scanned.
## Additional information:

Of course it's possible to reach this outside changing OpenSCAP code (modify the OVAL content to contain just records for critical CVEs). But to be able to do this, this requires additional knowledge of OVAL (be familiar with the syntax to know which items to delete still to keep valid OVAL file). IMHO it would be convenient for the users if OpenSCAP by performing CVE scan could filter entries based on severity.

**Comment by shawndwells** [comment]
It'd be great if this spanned XCCDF and OVAL content (e.g. use the XCCDF severity tags). For example, when doing DoD STIG scans, sometimes people want to quickly vet they have no CAT I (severity=high) findings.

**Comment by matusmarhefka** [comment]
This should be solved by refactoring OVAL report  interface to match the XCCDF report interface. The OVAL report is severely outdated.
