### ISSUE TITLE
RFE: Add support for 'prohibitChanges="true"' attribute value

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/openscap#444]
Per [XCCDF specification](https://scap.nist.gov/specifications/xccdf/xccdf_element_dictionary.html)

```
prohibitChanges     xsd:boolean     (optional -- default='false')   

If benchmark producers should prohibit changes to this item during tailoring.
An author should use this when they do not want to allow end users to change the item. 
```

From the above implies if the benchmark author would want to have e.g. xccdf:Value in form of a constant (not-editable / read-only), they could specify `prohibitChanges="true"` attribute value for that XCCDF item.

This should instruct the benchmark producer to mark this value as unmodifiable during tailoring (e.g. display its value, but don't allow to modify it).

Currently the `prohibitChanges` attribute is NOT supported by OpenSCAP (even when specified doesn't cause a difference when dealing with specific XCCDF item, since it's still possible to change it's value during tailoring).

How reproducible:
Always

Steps to reproduce:
- Use `shared/xccdf/remediation_functions.xml` implementation from PR:
  https://github.com/OpenSCAP/scap-security-guide/pull/1299
- Build and load the benchmark
- In the customization dialog of SCAP Workbench change the value of `Remediation function to replace configuration setting in config file or add the configuration setting if it does not exist yet` from the current value (actual implementation of `replace_or_append()` remediation function) to e.g. "This is an example value"
- Select e.g. `Ensure SELinux State is Enforcing` rule
- Change the `/etc/selinux/config` `SELINUX` setting from `enforcing` to `permissive` (so the specific system property will fail)
- Scan the system against that rule and apply online remediation in SCAP Workbench

Current result:
## 

SCAP-Workbench will report `error` since remediation failed (value of above xccdf:Value got overwritten with junk).

Expected result:
## 

SCAP-Workbench will report `fixed` state (value of above xccdf:Value is not overwritten since its marked as not possible to modify during tailoring).

**Comment by dahaic** [comment]
Currently, there is no known request for this feature, but it can prove useful as we create new SSG content.
