### ISSUE TITLE
RFE: Add support for 'hidden="true"' attribute value

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/openscap#445]
Per [XCCDF specification](https://scap.nist.gov/specifications/xccdf/xccdf_element_dictionary.html):

```
hidden  xsd:boolean     (optional -- default='false') 

If this item should be excluded from any generated documents although it may
still be used during assessments. 
```

From the above implies (if I read it correctly) when an XCCDF item is marked with `hidden="true"` attribute, it should not be visible in the (HTML form) or XML form of the benchmark. But despite of that it could be used during assessments. Basically it would be some internal XCCDF item, not visible to be present in the benchmark, but still usable during the assessments.

Currently using the `hidden="true"` value for some XCCDF item doesn't seem to have an effect for benchmarks produced by OpenSCAP. E.g. xccdf:Value marked as `hidden="true"` is still visible in the benchmark.

How reproducible:
Always

Steps to reproduce:
- Consider the `shared/xccdf/remediation_functions.xml` implementation from https://github.com/OpenSCAP/scap-security-guide/pull/1299 (those xccdf:Values should be not visible in the benchmark [or at least not visible in the HTML report], but still usable during system assessment).

Current result:
XCCDF items equipped with `hidden="true"` are still visible in the benchmark.

Expected result:
XCCDF items using `hidden="true"` aren't visible in the benchmark, but still can be used during systems' assessment (IOW those items would be benchmark specific internal items).

**Comment by dahaic** [comment]
Currently, there is no known request for this feature, but it can prove useful as we create new SSG content.
