### ISSUE TITLE
PKG_CHECK_MODULES macros ignore package version on RHEL7

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/openscap#453]
On RHEL7.2 we have seen that autoconf macros like
`PKG_CHECK_MODULES([rpm], [rpm >= 4.18],[],[])`
gets evaluated to true everytime, regardless to the version of respective package installed.

Currently I am not able to say whether it is an issue in our build system or an issue in the toolset.

**Comment by ybznek** [comment]
I had this issue too, `pkg-config` worked as expected, but the macro didn't work on my rhel instance, too.

**Comment by matejak** [comment]
This may depend on version of system's `pkg-config`. The `autoconf` macro is used correctly and it translate e.g. in

```
pkg-config --exists --print-errors "rpm >= 4.18"
```

This works on Fedora 28, but it may fail on other systems if there is a bug in `pkg-config` or in the underlying `glib`.

There was an issue on RHEL6, where the same target of the check screwed up other checks. Target of all checks was `rpm`, so I have changed that in #1170.

Reopen this if you can come with a reproducer after the PR is merged.
