### ISSUE TITLE
Add test: file probe & unicode filenames

### ISSUE THREAD

**Issue by ybznek** [OpenSCAP/openscap#467]
I would like to see behavior of file probe/sexp/oscap with very crazy filenames touch `"$(echo -e '\x01\x20')"`.

Linux filesystems allow usage of almost every filename (except \0,...).

We should create these files during test, I don't know if git can handle them.

Maybe it isn't too important to can work with such files, but oscap should crash during their processing.

https://github.com/OpenSCAP/openscap/issues/447#issuecomment-229316426

**Comment by jan-cerny** [comment]
Test was introduced in https://github.com/OpenSCAP/openscap/pull/468/commits/2bd56625acdc6ef5ae431b84b722d18c2370b01a
