### ISSUE TITLE
Getting "Unable to open file: '–profile'"  error while evaluating

### ISSUE THREAD

**Issue by parveenksofc** [OpenSCAP/openscap#472]
Hi All,

I'm new to openscap and using centos7 and while executing the oscap evaluation by following the [Getting started guide](https://www.open-scap.org/getting-started/) , I am getting below mentioned error.

[root@mc1 content]# oscap xccdf eval –profile pci-dss -results-arf arf.xml -report report.html /usr/share/xml/scap/ssg/content/ssg-centos7-xccdf.xml
OpenSCAP Error: Unable to open file: '–profile' [oscap_source.c:264]
[root@mc1 content]#
[root@mc1 content]#
[root@mc1 content]#
[root@mc1 content]#
[root@mc1 content]# oscap xccdf eval –-profile pci-dss --results-arf arf.xml --report report.html /usr/share/xml/scap/ssg/content/ssg-centos7-xccdf.xml
OpenSCAP Error: Unable to open file: '–-profile' [oscap_source.c:264]
[root@mc1 content]#

# ****More Details:**** 

**openscap rpms:**
[root@mc1 content]# rpm -qa | grep -i scap
openscap-1.2.9-5.el7_2.x86_64
openscap-utils-1.2.9-5.el7_2.x86_64
scap-workbench-1.0.2-2.el7.x86_64
scap-security-guide-0.1.25-3.el7.centos.0.1.noarch
perl-Pod-Escapes-1.04-286.el7.noarch
openscap-scanner-1.2.9-5.el7_2.x86_64
[root@mc1 content]#

**OS details:**
[root@mc1 content]# cat /etc/*release*
CentOS Linux release 7.2.1511 (Core)
Derived from Red Hat Enterprise Linux 7.2 (Source)
cat: /etc/lsb-release.d: Is a directory
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.2.1511 (Core)
CentOS Linux release 7.2.1511 (Core)
cpe:/o:centos:centos:7
[root@mc1 content]#

**oscap details:**
[root@mc1 content]# oscap -V
OpenSCAP command line tool (oscap) 1.2.9
Copyright 2009--2016 Red Hat Inc., Durham, North Carolina.

==== Supported specifications ====
XCCDF Version: 1.2
OVAL Version: 5.11.1
CPE Version: 2.3
CVSS Version: 2.0
CVE Version: 2.0
Asset Identification Version: 1.1
Asset Reporting Format Version: 1.1

==== Capabilities added by auto-loaded plugins ====
No plugins have been auto-loaded...

==== Paths ====
Schema files: /usr/share/openscap/schemas
Default CPE files: /usr/share/openscap/cpe
Probes: /usr/libexec/openscap

==== Inbuilt CPE names ====
Red Hat Enterprise Linux - cpe:/o:redhat:enterprise_linux
Red Hat Enterprise Linux 5 - cpe:/o:redhat:enterprise_linux:5
Red Hat Enterprise Linux 6 - cpe:/o:redhat:enterprise_linux:6
Red Hat Enterprise Linux 7 - cpe:/o:redhat:enterprise_linux:7
Community Enterprise Operating System 5 - cpe:/o:centos:centos:5
Community Enterprise Operating System 6 - cpe:/o:centos:centos:6
Community Enterprise Operating System 7 - cpe:/o:centos:centos:7
Scientific Linux 5 - cpe:/o:scientificlinux:scientificlinux:5
Scientific Linux 6 - cpe:/o:scientificlinux:scientificlinux:6
Scientific Linux 7 - cpe:/o:scientificlinux:scientificlinux:7
Fedora 16 - cpe:/o:fedoraproject:fedora:16
Fedora 17 - cpe:/o:fedoraproject:fedora:17
Fedora 18 - cpe:/o:fedoraproject:fedora:18
Fedora 19 - cpe:/o:fedoraproject:fedora:19
Fedora 20 - cpe:/o:fedoraproject:fedora:20
Fedora 21 - cpe:/o:fedoraproject:fedora:21
Fedora 22 - cpe:/o:fedoraproject:fedora:22
Fedora 23 - cpe:/o:fedoraproject:fedora:23
Fedora 24 - cpe:/o:fedoraproject:fedora:24
Fedora 25 - cpe:/o:fedoraproject:fedora:25
SUSE Linux Enterprise all versions - cpe:/o:suse:sle
SUSE Linux Enterprise Server 10 - cpe:/o:suse:sles:10
SUSE Linux Enterprise Desktop 10 - cpe:/o:suse:sled:10
SUSE Linux Enterprise Server 11 - cpe:/o:suse:sles:11
SUSE Linux Enterprise Desktop 11 - cpe:/o:suse:sled:11
SUSE Linux Enterprise Server 12 - cpe:/o:suse:sles:12
SUSE Linux Enterprise Desktop 12 - cpe:/o:suse:sled:12
openSUSE 11.4 - cpe:/o:opensuse:opensuse:11.4
openSUSE 13.1 - cpe:/o:opensuse:opensuse:13.1
openSUSE 13.2 - cpe:/o:opensuse:opensuse:13.2
openSUSE All Versions - cpe:/o:opensuse:opensuse
Red Hat Enterprise Linux Optional Productivity Applications - cpe:/a:redhat:rhel_productivity
Red Hat Enterprise Linux Optional Productivity Applications 5 - cpe:/a:redhat:rhel_productivity:5

==== Supported OVAL objects and associated OpenSCAP probes ====
system_info                  probe_system_info
family                       probe_family
filehash                     probe_filehash
environmentvariable          probe_environmentvariable
textfilecontent54            probe_textfilecontent54
textfilecontent              probe_textfilecontent
variable                     probe_variable
xmlfilecontent               probe_xmlfilecontent
environmentvariable58        probe_environmentvariable58
filehash58                   probe_filehash58
inetlisteningservers         probe_inetlisteningservers
rpminfo                      probe_rpminfo
partition                    probe_partition
iflisteners                  probe_iflisteners
rpmverify                    probe_rpmverify
rpmverifyfile                probe_rpmverifyfile
rpmverifypackage             probe_rpmverifypackage
selinuxboolean               probe_selinuxboolean
selinuxsecuritycontext       probe_selinuxsecuritycontext
systemdunitproperty          probe_systemdunitproperty
systemdunitdependency        probe_systemdunitdependency
file                         probe_file
interface                    probe_interface
password                     probe_password
process                      probe_process
runlevel                     probe_runlevel
shadow                       probe_shadow
uname                        probe_uname
xinetd                       probe_xinetd
sysctl                       probe_sysctl
process58                    probe_process58
fileextendedattribute        probe_fileextendedattribute
routingtable                 probe_routingtable
symlink                      probe_symlink
[root@mc1 content]#

-
Parveen Kumar Sharma

**Comment by jan-cerny** [comment]
Hi, thank you very much for reporting this.

There should be two short dashes `--`, like every other unix command line utility is using.

This is an issue in the getting started guide, most likely caused by some automatic conversion in WordPress.

**Comment by parveenksofc** [comment]
Hi jan-cerny,

Thanks for quick response.

I tried with both the way as mentioned in the original case. 

**## With one "-" :**
`[root@mc1 content]# oscap xccdf eval –profile pci-dss -results-arf arf.xml -report report.html /usr/share/xml/scap/ssg/content/ssg-centos7-xccdf.xml
OpenSCAP Error: Unable to open file: '–profile' [oscap_source.c:264]
[root@mc1 content]#`

**## With two "-" :**
`[root@mc1 content]# oscap xccdf eval –-profile pci-dss --results-arf arf.xml --report report.html /usr/share/xml/scap/ssg/content/ssg-centos7-xccdf.xml
OpenSCAP Error: Unable to open file: '–-profile' [oscap_source.c:264]
[root@mc1 content]#`



-
Parveen Kumar Sharma

**Comment by jan-cerny** [comment]
@parveenksofc you have there one long and one short "-" 

Meanwhile I have fixed the getting started guide.

**Comment by parveenksofc** [comment]
Thanks @jan-cerny for quickly fixing the [getting started guide](https://www.open-scap.org/getting-started/).

The issue I was facing was fixed by removing the some ASCII character while copied form the html page somehow. Manually inserting the complete command did the charm for me. 👍 


Thanks for quick help.


-
Parveen Kumar Sharma
