### ISSUE TITLE
valgrind-check - tests/DS/rds_split_simple

### ISSUE THREAD

**Issue by ybznek** [OpenSCAP/openscap#479]
https://jenkins.open-scap.org/job/openscap-maint-valgrind-check/58/consoleFull
Not initialized memory was used
```
+ rds_split_simple                                            FAIL test_ds.sh (exit status: 1)
```
Valgrind set not initialized memory to "UUU"  and we can see it in `name="UUUUUUU"`
```
<           </target-facts>
---
>           </target-facts><target-id-ref system="http://scap.nist.gov/schema/asset-identification/1.1" name="UUUUUUU" href=""/>
```

**Comment by jan-cerny** [comment]
@ybznek Can we close this? Is there something missing?

**Comment by ybznek** [comment]
I think, we can.
