### ISSUE TITLE
sds-add of tailoring file fails

### ISSUE THREAD

**Issue by ybznek** [OpenSCAP/openscap#490]
We are not able to add tailoring file to datastream

tests/API/XCCDF/tailoring

```
$ oscap ds sds-compose ./simple-xccdf.xml ds.xml
$ oscap ds sds-add ./simple-oval.xml ds.xml
$ oscap ds sds-add ./simple-tailoring.xml ds.xml
OpenSCAP Error: Failed to add component-ref/@id='scap_org.open-scap_cref_.--simple-tailoring.xml' to the DataStream. [sds.c:916]
```

@mpreisler  I have found your article https://martin.preisler.me/2016/05/combine-scap-tailoring-file-and-datastream-into-a-single-file/ Do you know this issue, or you have another reasons to merge it using script?

**Comment by iankko** [comment]
@ybznek 
IMHO this is a known issue (functionality to be implemented yet). See https://bugzilla.redhat.com/show_bug.cgi?id=1306643 for details (to me these two are equivalent).

**Comment by ybznek** [comment]
@iankko thank you. It seems that they are equivalent. We will track it here too. It is easier to see.

**Comment by mpreisler** [comment]
> @mpreisler I have found your article https://martin.preisler.me/2016/05/combine-scap-tailoring-file-and-datastream-into-a-single-file/ Do you know this issue, or you have another reasons to merge it using script?

I know about this issue.
