### ISSUE TITLE
oscap cannot eval usgcb windows 7 content

### ISSUE THREAD

**Issue by ybznek** [OpenSCAP/openscap#502]
https://usgcb.nist.gov/usgcb/content/scap/oval510/Win7-2.0.5.1.zip

```
oscap xccdf eval --profile xccdf_gov.nist_profile_united_states_government_configuration_baseline_version_2.0.5.1 --results /dev/stdout ./scap_gov.nist_USGCB-Windows-7.xml 
OpenSCAP Error: Unknown test type oval:gov.nist.usgcb.windowsseven:tst:30. [oval_test.c:402]
Failed to create OVAL definition model from: 'USGCB-Windows-7-2.0.5.1-oval.xml'. [xccdf_session.c:787]
```

**Comment by ybznek** [comment]
```All the applicable USGCB source data streams published to http://usgcb.nist.gov SHALL be
used for testing this requirement.```


It could be 'not applicable' for test, but I think we shouldn't crash on any content.

**Comment by mpreisler** [comment]
@ybznek Could you check this with the `master` branch? I have added support for Windows content there in the past.

**Comment by ybznek** [comment]
@mpreisler 
With master I get `notapplicable`, so it seems to be ok there.
Can we close this issue?

**Comment by jan-cerny** [comment]
@mpreisler Are we sure that the certification lab will not try to run content for other platforms with expectation that they will get a result of `not applicable`? @ybznek Could you have a look at the certification requirements again to clarify this? If it is OK to get an error here, we could close this issue. Otherwise we will have to backport that from master branch.

**Comment by mpreisler** [comment]
@jan-cerny I am not sure.

**Comment by ybznek** [comment]
I have already quoted https://github.com/OpenSCAP/openscap/issues/502#issuecomment-235563642.
I don't think we should deal with it for certification - especially when it is already fixed (in maint-1.3)

I am going to look into documentation again, but it will not probably change my mind.

**Comment by ybznek** [comment]
According to previous discussion i will remove "certification_block" label.

**Comment by jan-cerny** [comment]
@ybznek I think we can close this issue because it is working OK with master. What do you think?

**Comment by ybznek** [comment]
@jan-cerny Do we have reason to don't backport it?

**Comment by mpreisler** [comment]
@ybznek If I recall correctly I had to add a bunch of enums and new structs to support the Windows content. I don't think it would be worth it to backport it.

**Comment by jan-cerny** [comment]
@mpreisler Ok, then I suggest closing this,
