### ISSUE TITLE
HTML guide for lower screen resolution

### ISSUE THREAD

**Issue by ybznek** [OpenSCAP/openscap#504]
When we open guide with lower resolution than full HD, horizontal scrollbar occurs, because content isn't resized properly.

We should reduce `<table>` size if user has lower resolution.

Please ensure, that inner content like remediation scripts is readable.

![image](https://cloud.githubusercontent.com/assets/2564361/17546301/c2fcfedc-5ee1-11e6-99c7-e08c0443e6fb.png)

**Comment by mpreisler** [comment]
The issue is not in `<table>` size but with the preformatted `<pre>` contents of remediations and descriptions. We need to wrap them in a container that is `overflow: auto`. It's tricky to do this right though.
