### ISSUE TITLE
Hard-coded colors in terminal output

### ISSUE THREAD

**Issue by ybznek** [OpenSCAP/openscap#512]
If somebody use white terminal, he will not see some output texts, because they have same color.

https://github.com/OpenSCAP/openscap/blob/maint-1.2/utils/oscap-xccdf.c#L297

I wanted to fix it, but we use all - grey/white/bold formats.

If I replace white/gray by "default", all these texts will be visually same.

We could use [italic]not applicable[/italic], but e.g. my terminal cannot display italic.
If we use [bold]not applicable[/bold] it will have same style as rule title.

Any tips how to don't use hard-coded colors and don't break much current styles?

**Comment by shawndwells** [comment]
On 8/24/16 8:01 AM, Zbyněk Moravec wrote:
>
> If somebody use white terminal, he will not see some output texts,
> because they have same color.
>
> https://github.com/OpenSCAP/openscap/blob/maint-1.2/utils/oscap-xccdf.c#L297
>
> I wanted to fix it, but we use all - grey/white/bold formats.
>
> If I replace white/gray by "default", all these texts will be visually
> same.
>
> We could use [italic]not applicable[/italic], but e.g. my terminal
> cannot display italic.
> If we use [bold]not applicable[/bold] it will have same style as rule
> title.
>
> Any tips how to don't use hard-coded colors and don't break much
> current styles?
>

Pass:        Green
Fail:          Red
notapplicable:    Black (no action or concern needed)
notchecked:        Yellow. Maybe orange.

A good thought process on color selection:
http://www.neurotriggersagency.com/wp-content/uploads/2015/04/image2-northamericanculture.jpg

(while it says "North American Culture," I wager this is more international)
