### ISSUE TITLE
Manual.adoc - change links to updated guides/results/...

### ISSUE THREAD

**Issue by ybznek** [OpenSCAP/openscap#513]
https://github.com/OpenSCAP/openscap/blob/maint-1.2/docs/manual/manual.adoc#34-content-transformation

I think we could use some newer examples in the documentation.

**Comment by jan-cerny** [comment]
Fixed in https://github.com/jan-cerny/openscap/commit/d4fb56e40cbc7877e121c2b585233064bbf3a516
New examples stored on static.open-scap.org.
