### ISSUE TITLE
RHEL7 O-SCAP needs to check /etc/security/pwquality.conf

### ISSUE THREAD

**Issue by BisuDagger** [OpenSCAP/openscap#52]
I'm hoping I'm putting this in the correct forum. 
First issue:
-Basically, all password SCAP checks (lcredit/ocredit/reuse etc.) result in errors or false. The issue is that RHEL7 O-SCAP needs to check /etc/security/pwquality.conf instead of /etc/pam.d/{system-auth, password-auth}. Is there any way this fix can be added in?

Additional Issues on this Topic:
-Password Parameters (such as minimum age/min length etc.) do not pass SCAP. this issue is harder to identify and lies within /etc/login.defs

**Comment by isimluk** [comment]
Hello Bisu, Thanks for the report. It should have been reported against scap-security-guide sub project, that holds all the SCAP content.

I have reported the issue for you at OpenSCAP/scap-security-guide#446.

Thanks!
