### ISSUE TITLE
verbose mode with oscap xccdf remediate doesn't work

### ISSUE THREAD

**Issue by ybznek** [OpenSCAP/openscap#520]
Version:
latest oscap version in Fedora24 & latest upstream maint-1.2

`oscap xccdf remediate  --verbose INFO --verbose-log-file /tmp/verbose.xml --report /tmp/rep.xml  /tmp/res.xml`

`--verbose` parameters are correctly validated, but verbose mode doesn't print anything.

/tmp/verbose.xml doesn't exist after command run, so it seems that verbose mode doesn't work completely for this use case.

**Comment by ybznek** [comment]
@jan-cerny I haven't already checked the code. Should it work for such use cases?

**Comment by jan-cerny** [comment]
@ybznek Verbose mode works only with "oval eval", "oval collect" and "xccdf eval commands". Verbose mode is not allowed together with remediation now. I think it can be implemented easily by enabling those 2 options in appropriate oscap submodule.

**Comment by mpreisler** [comment]
@jan-cerny I am confused, are you saying that this is or isn't a bug? Looks like a bug to me if the options are accepted but don't enable verbose mode.

**Comment by mpreisler** [comment]
@jan-cerny Could you please take a look at this one for `1.2.13`? Looks like an easy fix.

**Comment by rsprudencio** [comment]
Please take #603 into consideration. :smile:
