### ISSUE TITLE
<Rule> with <refine-rule role="unchecked"> gets checked

### ISSUE THREAD

**Issue by GaryGapinski** [OpenSCAP/openscap#54]
Tested with oscap version 1.0.8.

A `<refine-rule>` element specifying `role="unchecked"` does not prevent the target `<Rule>` from undergoing evaluation.

I have specifically tested this using a `<Rule selected="false">` , a `<select selected="true">`, and a `<refine-rule role="unchecked">`.

I also tested with a `<Rule role="unchecked">` and found the check also occurs.

**Comment by mpreisler** [comment]
Hi Gary, thanks for your report.

@ybznek is working on this AFAIK.

**Comment by ybznek** [comment]
Hi @GaryGapinski, fix has been merged about 1-2 days ago. It should be released with next version.

**Comment by mpreisler** [comment]
It was https://github.com/OpenSCAP/openscap/pull/119
