### ISSUE TITLE
Add 'complexity', 'disruption', 'reboot', and 'strategy' to --report if the attributes exist

### ISSUE THREAD

**Issue by redhatrises** [OpenSCAP/openscap#541]
With https://github.com/OpenSCAP/scap-security-guide/issues/790 now merged in SSG, we should add 'complexity', 'disruption', 'reboot', and 'strategy', if the attributes exist, to the --report generation

**Comment by jan-cerny** [comment]
Fixed in https://github.com/OpenSCAP/openscap/pull/548
