### ISSUE TITLE
Migrate the OpenSCAP build tooling from autotools to CMAKE

### ISSUE THREAD

**Issue by redhatrises** [OpenSCAP/openscap#542]
With scap-workbench building with CMAKE and scap-security-guide building soon with CMAKE, OpenSCAP should also migrate its build infrastructure to CMAKE as well. There are numerous advantageous to CMAKE especially when it comes to compiling on different operating systems.

**Comment by jan-cerny** [comment]
@redhatrises Cmake will be really great in OpenSCAP. It'd make my life much easier :smiley: . I think we're all disappointed with autotools and its complexity. I'm giving +100 for this proposal.

**Comment by mpreisler** [comment]
+1

It is a ton of pain to convert it though. I know from experience ;-)

**Comment by mpreisler** [comment]
@jan-cerny has done this but hasn't updated the ticket. Closing. See #890
