### ISSUE TITLE
Make it easier to add support for new CPE to OpenSCAP

### ISSUE THREAD

**Issue by redhatrises** [OpenSCAP/openscap#543]
PR https://github.com/OpenSCAP/openscap/pull/539 shows how complicated it is to add or enable a new product in OpenSCAP. This should be a simpler process.

**Comment by mpreisler** [comment]
I think there is no way to make it noticeably simpler. You have to add a CPE item, you have to add CPE OVAL for it and you have to add specific implementation to runlevel probe if necessary.

What exactly do you have in mind to make this simpler? This will depend on the particular OS being added, there is almost zero actual boilerplate that needs to be copied to add support for a new OS to OpenSCAP.

**Comment by shawndwells** [comment]
On 9/27/16 6:08 PM, Martin Preisler wrote:
>
> I think there is no way to make it noticeably simpler. You have to add
> a CPE item, you have to add CPE OVAL for it and you have to add
> specific implementation to runlevel probe if necessary.
>
> What exactly do you have in mind to make this simpler? This will
> depend on the particular OS being added, there is almost zero actual
> boilerplate that needs to be copied to add support for a new OS to
> OpenSCAP.
>

Documentation :) I had to code walk to figure out where to put things. A
"add your CPEs here, update probes over here, see if it compiles" would
have been really helpful.

**Comment by mpreisler** [comment]
Ah, OK. That makes sense.

**Comment by redhatrises** [comment]
Or if there was some way to do some sort of script for inserting a new product.... but documentation works as well.

**Comment by mpreisler** [comment]
This can't be done with a script. There is no generic way to add CPE OVAL and there is no generic way to add support to the runlevel probe. Somebody always needs to look at that and think.

**Comment by radzy** [comment]
It could be *PARTIALLY* done with a script.

If the script would generate FIXME lines for the CPE OVAL to indicate "here's where you need to think", it would be helpful.  And I think that would be better than nothing at all.  This would be somewhere between a full-docs solution and the (impossible) full-automation solution.  (And, frankly, probably closer to the full-docs solution.)

I'm not saying that's the best option.  For example, one result would be that people adding new product would only think where indicated and not everywhere, but you really do need to think everywhere.  But for a beginner just getting started, figuring it all out at the same time is a very very steep learning curve.
