### ISSUE TITLE
User manual contains wrong date of the last update

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/openscap#557]
When I go to:
http://static.open-scap.org/openscap-1.2/oscap_user_manual.html

I see this:

OpenSCAP User Manual
Michal Šrubař msrubar@redhat.com version 1.0, 2015-31-08

The date and version here is obviously wrong, because it has been updated many times since August 2015. I think that the date of last update should be there. I think that this can give an impression that we didn't touch it for more than a year.

**Comment by mpreisler** [comment]
Fixed in 63b6cf585037bbf417fba68686c9b7dbe5a7b556
