### ISSUE TITLE
Question: Oscap return code

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/openscap#562]
The oscap(8) manual page says:

```
EXIT STATUS
       Normally, the exit status is 0 when operation finished successfully and 1 otherwise. In  cases
       when  oscap performs evaluation of the system it may return 2 indicating success of the opera‐
       tion but incompliance of the assessed system.
```

But there are also other possibilities, eg. if user specifies a wrong parameter, oscap returns 100, 101, etc.
For example:

```
[jcerny@thinkpad ~]$ oscap xccdf --eval xccdf.xml
No such module: --eval
[jcerny@thinkpad ~]$ echo $?
101
```

Should these cases been mentioned in the manual page as well?

**Comment by radzy** [comment]
My take, as a maximalist: the manpage should mention all arguments and all return codes, except when there is a clear reason for an exception (such as when the command is a front-end for plugins or equivalent, such as ssh's sub-feature and some git sub-commands, and only then when the plugins/equiv are documented in separate manpages).

**Comment by evgenyz** [comment]
@jan-cerny Were you satisfied by the answer? :)
