### ISSUE TITLE
Unlocking mutex before returning

### ISSUE THREAD

**Issue by yuumasato** [OpenSCAP/openscap#570]
Coverity reported that there is a missing unlock at src/OVAL/probes/probe/icache.c:385

```
 9. openscap-1.2.11/src/OVAL/probes/probe/icache.c:385: missing_unlock: Returning without unlocking "cache->queue_mutex".
383|                   dE("An error ocured while signaling the `notempty' condition: %u, %s",
384|                      errno, strerror(errno));
385|->                 return (-1);
386|           }
387|   
```
I also noticed that there are other places that return without unlocking a locked mutex, like in function probe_icache_nop() in the same file.

**Comment by mpreisler** [comment]
Moving to 1.2, 1.0 was deprecated.
