### ISSUE TITLE
Atomicity defect reported by Coverity scan

### ISSUE THREAD

**Issue by yuumasato** [OpenSCAP/openscap#571]
Coverity scan reported that there is an ATOMICITY defect, see log below:

`
openscap-1.2.11/src/OVAL/probes/probe/icache.c:220: use: Using an unreliable value of "*__errno_location()" inside the second locked section. If the data that "*__errno_location()" depends on was changed by another thread, this use might be incorrect.`

It is probably a false positive, as `errno` is used in the same way in many other locations in `icache.c`, but none of them are in a complex place like line 220. It is in a nested loop which locks and unlocks a mutex many times.

**Comment by rsprudencio** [comment]
AFAIK errno is thread-safe, so this should not be a problem.

**Comment by jan-cerny** [comment]
Yeah, I agree. `man 3 errno` says
> errno is thread-local; setting it in one thread does not affect its value in any other thread.

I close this as a false positive.
