### ISSUE TITLE
Why is there a \r (^M) in stdout and usage and xccdf output

### ISSUE THREAD

**Issue by darrenmoffat** [OpenSCAP/openscap#579]
I've noticed that the format strings for displaying the human readable progress output (when _not_ passing --progress) have a \r in them that results in a ^M in the output. 

This is a pattern also used in the usage output.  For the usage it seems to result in missing output when using gnome-terminal (at least for me), but not for xterm.

eg:

$ oscap xccdf -h  
oscap -> xccdf

eXtensible Configuration Checklist Description Format

Usage: oscap [options] xccdf command [command-specific-options]

Commands:
                                 - Perform evaluation driven by XCCDF file and use OVAL as checking engine
                                 - Resolve an XCCDF document
                                 - Validate XCCDF XML content
                                 - Validate XCCDF XML content
                                 - Export XCCDF values as OVAL external-variables document(s)
                                 - Convert XCCDF Benchmark to other formats
                                 - Perform remediation driven by XCCDF TestResult file or ARF.

but it should look like this (but without the ^M), the output below was generated by piping to less.

oscap -> xccdf

eXtensible Configuration Checklist Description Format

Usage: oscap [options] xccdf command [command-specific-options]

Commands:
    eval^M                               - Perform evaluation driven by XCCDF file and use OVAL as checking engine
    resolve^M                            - Resolve an XCCDF document
    validate^M                           - Validate XCCDF XML content
    validate-xml^M                               - Validate XCCDF XML content
    export-oval-variables^M                              - Export XCCDF values as OVAL external-variables document(s)
    generate^M                           - Convert XCCDF Benchmark to other formats
    remediate^M                          - Perform remediation driven by XCCDF TestRe

**Comment by jan-cerny** [comment]
Hi, for me it works in GNOME Terminal. I am using gnome-terminal-3.20.3-1.fc24.x86_64 and I don't notice anything missing.

I think that \r (carriage return) there is a hack to align all the options - to have all the bullets on the same collumn in order to look better.

However I agree that this looks ugly when you are not in terminal but you redirect the output afterwards. We also need to remove those \r characters in oscap-docker etc.

I think that something like aligning function like Python has would be benficial for handling this.

**Comment by mpreisler** [comment]
Fixed by @jan-cerny in 6c19c67beab5f323384b58c2a49fd7b8d0de9c69
