### ISSUE TITLE
Add shellcommand_* extensions from CIS benchmarks?

### ISSUE THREAD

**Issue by tyrken** [OpenSCAP/openscap#606]
Recent CIS benchmarks such as CIS_Ubuntu_Linux_16.04_LTS_Benchmark_v1.0.0-oval.xml include extensions to vanilla 5.11 OVAL in the http://oval.mitre.org/XMLSchema/oval-definitions-5#cmd namespace (e.g. shellcommand_test, shellcommand_object, shellcommand_state).  These cause a validation error that stops openscap using them, and it still errors if I manually import the extra schemas in /usr/share/openscap/schemas/oval/5.11/.

Would it be appropriate for the OpenSCAP project to extend to support the same extension, e.g. as jOVAL did in https://github.com/joval/jOVAL/commit/c62183dad1032ba02e04153c21986947f12a4702 ?

Related to https://github.com/CISecurity/OVALRepo/issues/434

**Comment by mpreisler** [comment]
Hi Tristan,

this extension was proposed to the OVAL board and was rejected. Therefore I think it doesn't make sense to implement it in OpenSCAP. It's not just a question of effort, adding a shell test to OVAL opens up a big attack surface. All the tests in OVAL are read-only and can't affect the system unless there is a bug in the interpreter. The `shellcommand_t` changes that.

If people need shell commands for checking engines they should use SCE. The SCE standard is implemented by multiple vendors and is much older than the shellcommand_test extension in OVAL. On top of that it's a separate checking engine so it's easy to distinguish read-only and potentially harmful checks.

I really wish CIS hadn't reinvented the wheel with this one :-(

**Comment by tyrken** [comment]
OK - thanks for the full answer!

**Comment by demurgos** [comment]
For reference, I believe that this the proposal mentioned above: https://github.com/OVALProject/Sandbox/pull/145.
