### ISSUE TITLE
RFE: add "hide all result details" to bottom of HTML report

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/openscap#620]
Add a "hide all result details" button to bottom of HTML report so users don't have to endlessly scroll back up to hide the noise

**Comment by mpreisler** [comment]
Frankly, I don't see the use-case for this. Is it common for users to click `show all result details`, then scroll down and then suddenly want the results to disappear? You can use the rule overview regardless of whether the rule details are shown or not.

**Comment by shawndwells** [comment]
Hiding extended details: HTML report is 27 pages
![image](https://cloud.githubusercontent.com/assets/5713754/21447465/01b3650a-c8a3-11e6-831d-ff047d64530b.png)


Showing extended details: 215 pages
![image](https://cloud.githubusercontent.com/assets/5713754/21447474/1afe4f16-c8a3-11e6-957a-d325fa2dac73.png)

Once I scroll down through the extended details, I have to scroll back up 200 pages. Kind of a pain. Or we could put a "hide details" button on the bottom of the HTML report

**Comment by mpreisler** [comment]
I see, I made a slightly different solution to avoid introducing complex hide/show javascript logic. I think it fulfills this requirement, please check it out. #651
