### ISSUE TITLE
duplicate elements in "group rules by" in HTML report

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/openscap#621]
On the HTML report, we can "Group rules by" identifiers. I believe this comes from
``openscap/xsl/xccdf-resources/openscap.js``:

`````
146 var KeysEnum = {
147     DEFAULT: "default",
148     SEVERITY: "severity",
149     RESULT: "result",
150     NIST: "NIST SP 800-53 ID",
151     DISA: "DISA ID",
152     PCI_DSS: "PCI DSS Requirement",
153     CIS: "CIS Recommendation"
154 };
`````

But when I expand the "Group rules by," some of them are repeated:
![image](https://cloud.githubusercontent.com/assets/5713754/21447546/fb13c176-c8a3-11e6-9501-e503fa043dbb.png)

I can't figure out why this is happening... issue in SSG? somewhere in the javascript?

**Comment by shawndwells** [comment]
note the duplicate "DISA IDs" in the drop down

**Comment by shawndwells** [comment]
$ rpm -qv openscap-utils
openscap-utils-1.2.10-2.el7.x86_64

**Comment by mpreisler** [comment]
Looks like a duplicate of #601

**Comment by shawndwells** [comment]
dupe of https://github.com/OpenSCAP/openscap/issues/601, closing
