### ISSUE TITLE
RFE: Add output for failed checks in the reports

### ISSUE THREAD

**Issue by redhatrises** [OpenSCAP/openscap#632]
Looking at the failures in a html report, I was thinking that it would be nice to know why a check failed when looking at the reports. Was it because a service was enabled for startup at boot time but currently not running? Did I have one file out of many that the permissions were not changed? Did I configure something in runtime but configure it persistently?

Adding a collapsible table called "Output", "Reason for Failure", or whatever that shows the reason why a check failed (service enabled at boot, service is running, these files have wrong permissions, password length is 14 or comment out, etc.) would be very helpful for hardening a system, generating a waiver, validating a waiver, etc.

**Comment by jan-cerny** [comment]
@redhatrises Thanks for the RFE. Do you want the table to replace the current section "Items (not) found violating (satisfying)" in the report? It is generated when `oscap` is invoked with `--oval-results`. I think it is very similar to what you suggest.

**Comment by redhatrises** [comment]
Thanks @jan-cerny! I apparently went on the Christmas break and came back forgetting how to scan with oscap. Even though `--oval-results` is a little rough with some of the output, closing as the functionality exists. Thanks again @jan-cerny
