### ISSUE TITLE
Coverity issues in runlevel probe

### ISSUE THREAD

**Issue by mpreisler** [OpenSCAP/openscap#634]
```
3. openscap-1.2.13/src/OVAL/probes/unix/runlevel.c:312: check_return: Calling "fgetc(osrelease)" without checking return value. This library function may fail and return an error code.
```

**Comment by yuumasato** [comment]
A  possible fix is commented out in the source itself.
`/*const char c = */fgetc(osrelease);`

Did you have intentions of using the char?

**Comment by mpreisler** [comment]
@yuumasato I added that there because of the compiler warning but I am not the author of this code. I was just fixing some issues and doing refactoring.
