### ISSUE TITLE
system_info resource leaks

### ISSUE THREAD

**Issue by mpreisler** [OpenSCAP/openscap#636]
```
1. Defect type: RESOURCE_LEAK 
21. openscap-1.2.13/src/OVAL/probes/independent/system_info.c:702: leaked_storage: Variable "os_name" going out of scope leaks the storage it points to.
Expand
2. Defect type: RESOURCE_LEAK 
19. openscap-1.2.13/src/OVAL/probes/independent/system_info.c:702: leaked_storage: Variable "hname" going out of scope leaks the storage it points to.
Expand
3. Defect type: RESOURCE_LEAK 
19. openscap-1.2.13/src/OVAL/probes/independent/system_info.c:702: leaked_storage: Variable "architecture" going out of scope leaks the storage it points to.
Expand
4. Defect type: RESOURCE_LEAK 
20. openscap-1.2.13/src/OVAL/probes/independent/system_info.c:697: leaked_storage: Variable "os_name" going out of scope leaks the storage it points to.
Expand
5. Defect type: RESOURCE_LEAK 
18. openscap-1.2.13/src/OVAL/probes/independent/system_info.c:697: leaked_storage: Variable "hname" going out of scope leaks the storage it points to.
Expand
6. Defect type: RESOURCE_LEAK 
18. openscap-1.2.13/src/OVAL/probes/independent/system_info.c:697: leaked_storage: Variable "architecture" going out of scope leaks the storage it points to.
```

**Comment by rsprudencio** [comment]
Pretty sure it's false positive

**Comment by yuumasato** [comment]
@rsprudencio A leak might occur when condition on line [system_info.c#L644](https://github.com/OpenSCAP/openscap/blob/maint-1.2/src/OVAL/probes/independent/system_info.c#L644) happens to be false.
When this happens, variables `os_name`, `hname` and `architecture` will be `strdup()`ed, and as `offline_mode` is `PROBE_OFFLINE_NONE`, [this](https://github.com/OpenSCAP/openscap/blob/maint-1.2/src/OVAL/probes/independent/system_info.c#L686) condition is false and leak occurs.

I think that explicitly comparing with `PROBE_OFFLINE_NONE`, which is `0x00`, will help avoid confusion.

**Comment by rsprudencio** [comment]
@yuumasato I missed that, good catch!

I made a PR with a proposal to fix that issue, I strduped everything so we won't need any of that logic anymore. Also initialized item.

If item is NULL it will fail to add to collection as it expected, but it still returns 0. It will fail later on @mpreisler? Should we make it something like return probe_item_collect();?
