### ISSUE TITLE
Include schema in supported OVAL objects list of `oscap --version`

### ISSUE THREAD

**Issue by dahaic** [OpenSCAP/openscap#650]
When printing capabilities of oscap, all OVAL objects are printed as names, without schema prefix. This is fine for experienced user, but for newcomer, who want to write some rule, full name would be easier to find in documentation.

Example:
Instead of `selinuxboolean`, `linux:selinuxboolean` would be printed.

**Comment by mpreisler** [comment]
Makes sense.
