### ISSUE TITLE
Generating HTML guide with a nonexisting profile should fail

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/openscap#656]
When I try to generate a HTML guide and I specify a profile that does not exist in the given datastream, the HTML guide is generated. 
[guide.tar.gz](https://github.com/OpenSCAP/openscap/files/714065/guide.tar.gz)

```
[jcerny@thinkpad content]$ oscap xccdf generate guide --profile ijklmnop --output /tmp/guide.html ssg-fedora-ds.xml
[jcerny@thinkpad content]$ echo $?
0
```
The resulting HTML guide contains no rules. I think that an error message should be displayed instead, and no guide should be generated.

I think my situation is similar to a situation when an user wants to scan his system and he specifies wrong profile.  But in that case he will get error:

```
[jcerny@thinkpad content]$  oscap xccdf eval --profile ijklmnop ssg-fedora-ds.xml 
Profile "ijklmnop" was not found. Get available profiles using:
$ oscap info "ssg-fedora-ds.xml"
```

I think that fixing this issue would help to avoid mistakes when generating guides.

**Comment by rsprudencio** [comment]
Github closed this automatically because it was liked to #671. Reopened as it was only partially fixed.

**Comment by jan-cerny** [comment]
Rest of the issue is reported in https://github.com/OpenSCAP/openscap/issues/814
