### ISSUE TITLE
Probe environmentvariable58 failing to find oscap PID

### ISSUE THREAD

**Issue by rsprudencio** [OpenSCAP/openscap#658]
For some reason environmentvariable58 probe is failing to get probe PID during the scan, so it's not getting the environment when OVAL object has <ind-def:pid xsi:nil="true" datatype="int"/>, which makes it points to it's own PID.

Error in result:
<message level="error">Can't find process with requested PID.</message>

**Comment by mpreisler** [comment]
Attach a reproducer OVAL please.

**Comment by mpreisler** [comment]
Were you doing an online scan or offline scan?

**Comment by mpreisler** [comment]
@rsprudencio Could you please check this ticket? I think you might have been scanning in offline mode. It that use-case the results are expected.

**Comment by rsprudencio** [comment]
I tried to remember how I triggered this, but it wasn't they way I thought it was, so I think we can close this ticket, I'll reopen if I stumble upon this again.
