### ISSUE TITLE
Refactor probe system to unify all probe binaries

### ISSUE THREAD

**Issue by rsprudencio** [OpenSCAP/openscap#672]
Our probe system relies on several probes which makes it harder to maintain/deploy and it's not needed at all in Windows environment.

Per request, this should also affect Linux probes so we have a whole new probe system with unique binary for object collecting.

The fix for this issue should enable this behavior for openscap as a whole, not only for Windows or Linux.

**Comment by mpreisler** [comment]
@jan-cerny please update this with status

**Comment by jan-cerny** [comment]
We have decided to NOT create your unified probe interface. Instead, we merged all the probes to a single process. This change happened in master branch in https://github.com/OpenSCAP/openscap/pull/981. Therefore, this request is no longer applicable. Closing. Thank you very much.
