### ISSUE TITLE
[oscap-docker] image-cve centos:7

### ISSUE THREAD

**Issue by adrianovieira** [OpenSCAP/openscap#676]
a sample run of `oscap-docker image-cve centos:7` occurs error **(centos:7 is not based on RHEL)** when I try to run on a CEntOS-7 image, but for `oscap-docker image-cve registry.access.redhat.com/rhel7` returns the list of status definition
```
...
Definition oval:com.redhat.rhsa:def:20170238: false
Definition oval:com.redhat.rhsa:def:20170225: false
...
```

PS: host is a centos-7.3.1611 with openscap-1.2.10-2.el7.x86_64, openscap-utils-1.2.10-2.el7.x86_64, atomic-1.14.1-5.el7.x86_64, docker-1.12.5-14.el7.centos.x86_64

Are there someway to run oscap-docker on centos:7 based images and take reports?

**Comment by mpreisler** [comment]
You cannot use the RHEL7 CVE OVALs for CentOS, the packages are not the same and are not signed by Red Hat.

The error message `entos:7 is not based on RHEL` is a bit unfortunate, it means the image is not RHEL based, not that CentOS is not RHEL based. Hope this makes sense.

**Comment by adrianovieira** [comment]
Thank you by your response.

I notice that CentOS is not a RHEL based image.

I haven't realize or find on oscap-docker manpage how to use a oscap-docker with a centos based image.

What I'd like to know is how I can use a centos OVAL with oscap-docker to check a centos based image.

Can you point me a doc or something like that which I can use/read how do a scap check of a centos image?

Thanks in advance.

**Comment by mpreisler** [comment]
> What I'd like to know is how I can use a centos OVAL with oscap-docker to check a centos based image.

I do not know of any good source for CentOS CVE OVAL. If you already have the file you can use:

```
oscap-docker image $IMAGE oval eval $YOUR_CVE_OVAL_FILE
```

**Comment by adrianovieira** [comment]
Thanks by your answer.

May be you know why the command below don't generate a html report.

```
oscap-docker image <registry.access.redhat.com/rhel7 || centos:7> \
  oval eval /usr/share/xml/scap/ssg/content/ssg-rhel7-oval.xml \
  --results result.xml --report report.html

...
Definition oval:ssg-accounts_logon_fail_delay:def:1: false
Definition oval:ssg-account_unique_name:def:1: true
Definition oval:ssg-account_disable_post_pw_expiration:def:1: false
Evaluation done.
```

is it by definition or I'm doing something wrong?
