### ISSUE TITLE
Check for fcntl() return value

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/openscap#681]
In `src/SCE/sce_engine.c` on lines 564 and 565 we should check for return value of `fcntl(stdout_pipefd[0], F_SETFL, flag_stdout | O_NONBLOCK);` to ensure flag was set correctly on the file descriptor.

**Comment by mpreisler** [comment]
http://man7.org/linux/man-pages/man2/fcntl.2.html

We need to check whether the return value is different from 0. If it is we should abort and print an error.

**Comment by rsprudencio** [comment]
Fixed in #688
