### ISSUE TITLE
cygwin build instructions and autogen/autoreconf issues

### ISSUE THREAD

**Issue by joshualubell** [OpenSCAP/openscap#682]
The instructions in section 5.4 of the User Manual have the following issues:
1. git and libxslt should be added to the package requirements
2. libgcrypt is misspelled

Additionally, running autogen.sh produces the following errors:
$ ./autogen.sh
'.toreconf-2.69: unrecognized option '-
autoreconf-2.69: Try '/usr/bin/autoreconf-2.69 --help' for more information.

If I instead execute the autogen.sh instructions as commands - one line at a time - I get the following:
$ mkdir -p m4

lubell@CEPHEUS ~/openscap/openscap
$ mkdir -p config/

lubell@CEPHEUS ~/openscap/openscap
$ touch config/config.rpath

lubell@CEPHEUS ~/openscap/openscap
$ autoreconf -i -s
sh: $'\r': command not found
sh: -c: line 1: syntax error near unexpected token `$'do\r''
sh: -c: line 1: `      for gl_file in  canonicalize-lgpl.c close.c closedir.c dirfd.c dup2.c fchdir.c fcntl.c float.c itold.c flock.c fstat.c getcwd-lgpl.c getdelim.c getdtablesize.c gethostname.c getline.c getlogin.c gettimeofday.c inet_pton.c lstat.c malloc.c memchr.c mkdtemp.c mkstemp.c msvc-inval.c msvc-nothrow.c open.c opendir.c pthread_sigmask.c raise.c random.c random_r.c readdir.c readlink.c realloc.c secure_getenv.c sigprocmask.c stat.c stpcpy.c strcasecmp.c strncasecmp.c strdup.c strerror-override.c strerror_r.c strptime.c strsep.c time_r.c uname.c vasnprintf.c printf-args.c printf-parse.c asnprintf.c vasprintf.c asprintf.' ; do
configure.ac:26: error: expected source file, required through AC_LIBSOURCES, not found
m4/gnulib-comp.m4:160: gl_INIT is expanded from...
configure.ac:26: the top level
autom4te-2.69: /usr/bin/m4 failed with exit status: 1
aclocal-1.14: error: echo failed with exit status: 1
autoreconf-2.69: aclocal failed with exit status: 1

**Comment by mpreisler** [comment]
Please check out our master branch. We have native support for MSVC and Windows now. cmake is used as the configure system.

**Comment by tresf** [comment]
Sorry for bumping an old thread, the fix for the error is to run `dos2unix` on the files e.g.  `find . -name \*.sh|xargs dos2unix`, `find . -name \*.am|xargs dos2unix`, etc.

Since OpenSCAP has switched CMake, it no longer suffers from these issues so this fix is irrelevant to this project but I wanted to offer this advice for those stumbling here from search engines, I hope that's OK. 🍻
