### ISSUE TITLE
Add Fedora 26 and 27 CPE

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/openscap#692]
Fedora 26 was branched from Rawhide on 1st March 2017.  Rawhide will be now f27.
We are still missing f26 CPE.

We have to add Fedora 26 and 27 CPE in our CPE dictionary.

See https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/EPPCFXYZJIKV3UTQAOGKEALBY5W2TBHK/

**Comment by mpreisler** [comment]
https://github.com/OpenSCAP/openscap/pull/698

merged.

**Comment by mpreisler** [comment]
`maint-1.2 milestone`: 1.2.14
