### ISSUE TITLE
openscap-python3 bindings for RHEL 7

### ISSUE THREAD

**Issue by lehuff** [OpenSCAP/openscap#694]
Hopefully this is the right place to ask this, but right now openscap-python is available on RHEL 7, but openscap-python3 is not. Only way to get this is to compile the entire project from source, which is less than ideal. Is there any way to get this package/rpm available for RHEL7 sans building everything from source on the local system?

**Comment by mpreisler** [comment]
I wonder how to solve this for RHEL7 because python3 is not in the base channel. Perhaps we could add openscap-python3 to the software collection that you get python3 from. Would that be valuable?

**Comment by lehuff** [comment]
Yes, absolutely! It's already available in newer Fedora repo's I believe.

**Comment by lehuff** [comment]
Any updates on this?

**Comment by mpreisler** [comment]
@lehuff I have created a downstream bug, see https://bugzilla.redhat.com/show_bug.cgi?id=1435798

**Comment by mpreisler** [comment]
Closing this because upstream has python3 bindings, we need to track this downstream for RHEL7.
