### ISSUE TITLE
probe_systemdunitdependency fails when running online inside container

### ISSUE THREAD

**Issue by rsprudencio** [OpenSCAP/openscap#700]
How to reproduce:
Running oscap directly from a container
$ oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_pci-dss /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml

Note: this is NOT offline scanning

`OpenSCAP Error: Probe at sd=8 (systemdunitdependency) reported an error: Unknown error [oval_probe_ext.c:393]
Unable to receive a message from probe [oval_probe_ext.c:579]
Invalid oval result type: -1. [oval_resultTest.c:179]
Probe at sd=8 (systemdunitdependency) reported an error: Unknown error [oval_probe_ext.c:393]
Unable to receive a message from probe [oval_probe_ext.c:579]
Invalid oval result type: -1. [oval_resultTest.c:179]
Probe at sd=8 (systemdunitdependency) reported an error: Unknown error [oval_probe_ext.c:393]
Unable to receive a message from probe [oval_probe_ext.c:579]
Invalid oval result type: -1. [oval_resultTest.c:179]
Probe at sd=8 (systemdunitdependency) reported an error: Unknown error [oval_probe_ext.c:393]
Unable to receive a message from probe [oval_probe_ext.c:579]
Invalid oval result type: -1. [oval_resultTest.c:179]
Probe at sd=6 (systemdunitdependency) reported an error: Unknown error [oval_probe_ext.c:393]
Unable to receive a message from probe [oval_probe_ext.c:579]
Invalid oval result type: -1. [oval_resultTest.c:179]
Probe at sd=6 (systemdunitdependency) reported an error: Unknown error [oval_probe_ext.c:393]
Unable to receive a message from probe [oval_probe_ext.c:579]
Invalid oval result type: -1. [oval_resultTest.c:179]
Probe at sd=6 (systemdunitdependency) reported an error: Unknown error [oval_probe_ext.c:393]
Unable to receive a message from probe [oval_probe_ext.c:579]
Invalid oval result type: -1. [oval_resultTest.c:179]`

**Comment by jan-cerny** [comment]
Also reported on https://bugzilla.redhat.com/show_bug.cgi?id=1431186

**Comment by jan-cerny** [comment]
A fix is proposed in https://github.com/OpenSCAP/openscap/pull/708

**Comment by jan-cerny** [comment]
Fixed in #708.
