### ISSUE TITLE
fedora hosting no more present

### ISSUE THREAD

**Issue by praving55** [OpenSCAP/openscap#709]
It looks like fedora hosting is gone.

I can no longer access [https://fedorahosted.org/releases/o/p/openscap/openscap-1.2.13.tar.gz](https://fedorahosted.org/releases/o/p/openscap/openscap-1.2.13.tar.gz)

**Comment by mpreisler** [comment]
We had to move to github hosting, see https://github.com/OpenSCAP/openscap/releases/tag/1.2.13

**Comment by praving55** [comment]
Hi @mpreisler,
Thanks for replying. We should probably change the landing page [https://github.com/OpenSCAP/openscap](https://github.com/OpenSCAP/openscap). Option 1a in the compilation process still refers to fedora hosting.

Thanks and regards,
Pravin Goyal

**Comment by mpreisler** [comment]
@praving55 Done in https://github.com/OpenSCAP/openscap/commit/daf505a1242d7b72a9cfa438e9dad1b9105840d4

Thx for notifying us!
