### ISSUE TITLE
oscap-docker doesn't warn user about need of --fetch-remote-resources

### ISSUE THREAD

**Issue by yuumasato** [OpenSCAP/openscap#713]
oscap-docker doesn't warn the user when remote resources are needed and '--fetch-remote-resources' was not provided.

How to reproduce:
- scan a container image with a profile that fetches remote content, like pci-dss.
`sudo oscap-docker image 41a4953dbf95 xccdf eval --profile xccdf_org.ssgproject.content_profile_pci-dss --results results.xml --report report.hml ssg-rhel7-ds.xml`

Actual output:
No warnings, and rule `security_patches_up_to_date` is simply marked as notchecked.
```
Title   Ensure Software Patches Installed
Rule    xccdf_org.ssgproject.content_rule_security_patches_up_to_date
Ident   CCE-26895-3
Result  notchecked
```

Expected output:
Warning like the one `oscap` outputs:
```
WARNING: This content points out to the remote resources. Use `--fetch-remote-resources' option to download them.
WARNING: Skipping https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL7.xml.bz2 file which is referenced from XCCDF content
```

**Comment by yuumasato** [comment]
Just found out that `openscap-docker` from `openscap-utils-1.2.10` shows the warning but version `openscap-utils-1.2.13` doesn't.

Output from version 1.2.10:
```
[root@rhel7_vm ~]# oscap-docker image 41a4953dbf95 xccdf eval --profile xccdf_org.ssgproject.content_profile_pci-dss --results results.xml --report report.hml /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xmlxccdf_org.ssgproject.content_profile_pci-dss /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml
This content points out to the remote resources. Use `--fetch-remote-resources' option to download them.
```

**Comment by jan-cerny** [comment]
I think that we moved this message from the stdout to stderr because we wanted that Workbench can cosume it and display it, because it reads stderr. On the other hand, oscap-docker prints out stderr only if scan failed. So we made it visible in Workbench while we hide it in oscap-docker 😬 😬 

I suggest oscap-docker copying oscap stderr to its stderr.

**Comment by jan-cerny** [comment]
Fixed in https://github.com/OpenSCAP/openscap/pull/718
