### ISSUE TITLE
OVAL details in HTML report could have bigger boxes or smaller font

### ISSUE THREAD

**Issue by rsprudencio** [OpenSCAP/openscap#738]
![image](https://cloud.githubusercontent.com/assets/753153/25542080/07f6d9a8-2c1f-11e7-8979-7474693e9a72.png)

The font is bigger than the boxes, but it's a minor detail just to make report looks better. Maybe we should try to make those boxes bigger to match the font size or decrease font size.

Related to #728

**Comment by jan-cerny** [comment]
The headings look like a sentence, but the boxes look like isolated, separated labels. I would try to not use boxes at all, only emphasise the "failed", and make it a whole sentence that has a beginning and end. 
![html_report_oval_details](https://cloud.githubusercontent.com/assets/9050916/26775026/62650064-49d3-11e7-8dc4-864cff244ef8.png)

**Comment by jan-cerny** [comment]
@mpreisler @rsprudencio What are your opinions? Changing this would be easy, but we need to find a solution that would look well.

**Comment by mpreisler** [comment]
@jan-cerny I like the boxes because they immediately focus my attention to the two fields that matter. On the other hand your solution fixes this problem and both fields are still highlighted.

I will defer to your judgement here.

**Comment by shawndwells** [comment]
Many community members monitor the mailing lists and not GitHub. Maybe shoot a message asking for people to sound off? Even a few replies from the community is more than we have now :)

**Comment by jan-cerny** [comment]
This is really an easy fix and should be done before 1.2.15 release coming mid July.
