### ISSUE TITLE
<Rule> with <refine-rule> loses <Rule>-specific severity attribute during evaluation

### ISSUE THREAD

**Issue by GaryGapinski** [OpenSCAP/openscap#739]
Using oscap 1.2.10 on RHEL 7.3.

When a `<refine-rule>` which cites only the idref and role attributes is present in a `<Profile>` for evaluation, the severity attribute of the target `<Rule>` is not propagated to the corresponding evaluation `<rule-result>` element. The neglected attribute appears as lacking severity in the evaluation report.

**Comment by mpreisler** [comment]
Hi @GaryGapinski , thanks for the report.

Could you please attach SCAP XMLs that we can reproduce this with?

**Comment by GaryGapinski** [comment]
Hello, @mpreisler — the attached was used with profile «xccdf_org.ssgproject.content_profile_nasa-rhel7-workstation».

[nasa-rhel7-ds.zip](https://github.com/OpenSCAP/openscap/files/991073/nasa-rhel7-ds.zip)
