### ISSUE TITLE
Is it possible to scan all Linux images with OpenSCAP or just RHEL based images

### ISSUE THREAD

**Issue by mylespollie** [OpenSCAP/openscap#749]
I'm looking for a way to scan my OpenShift registry which contains images based on many different Linux distributions.  I read this on the Red Hat site:

Note: The OpenSCAP CVE scan only works on RHEL based containers and images because it relies on CVE input that no other distribution is currently creating.
https://developers.redhat.com/blog/2016/05/02/introducing-atomic-scan-container-vulnerability-detection/

**Comment by mpreisler** [comment]
You need to differentiate various tools and contents. If the question is vague it gets difficult to answer.

1) atomic scan only supports RHEL at this point
2) oscap-docker supports anything you have content for, including Debian, Ubuntu, SUSE, ... They all provide CVE OVAL feeds

You have a couple of options. Probably the best is to patch openscap-daemon to support CVE OVAL feeds other than just the RHEL one. openscap-daemon is the tech that powers atomic scan.

See https://github.com/OpenSCAP/openscap-daemon/blob/master/openscap_daemon/cve_feed_manager.py
The code is already more or less prepared for something like this.

Use `oscapd-evaluate scan` for testing.

https://www.debian.org/security/oval/
https://people.canonical.com/~ubuntu-security/oval/
https://support.novell.com/security/oval/

**Comment by mylespollie** [comment]
Thanks for the response.
