### ISSUE TITLE
No scap-workbench package in yakkety

### ISSUE THREAD

**Issue by djmoore711** [OpenSCAP/openscap#750]
apt-get does not seem to find the package for scap-workbench in Ubuntu yakkety. I looked it up and it is not the official repository. I am having some major issues building it from source, as well. Any guidance?

**Comment by jan-cerny** [comment]
@djmoore711 
Hi, SCAP Workbench was introduced in Ubuntu 17.04 Zesty Zapus, it's not available in Ubuntu 16.10 Yakkety Yak.

Could you attach the build log? Maybe you're missing some of the dependencies. Double check the Readme. https://github.com/OpenSCAP/scap-workbench/blob/v1-1/README.md Unfortunately it's written for Fedora, and the names of some packages are different in Ubuntu.

**Comment by djmoore711** [comment]
Thanks for the quick reply. I spoke with a friend and he suggested I just bite the bullet and upgrade to Zesty Zapus. I just did and the distribution upgrade went smoothly. I will be installing it from the repositories now. Thank you!

**Comment by djmoore711** [comment]
Worked flawlessly since the distribution upgrade! Thanks.
