### ISSUE TITLE
Explore ways to convert list whitelisting to be value based instead of regex

### ISSUE THREAD

**Issue by dahaic** [OpenSCAP/openscap#759]
Example being ```rule_sshd_use_approved_ciphers```. There is no way for user to make this rule more strict right now, which would be useful.

**Comment by jan-cerny** [comment]
XCCDF has a complex-value element, but I'm not sure how it can be used in an OVAL check.

In general I think it's good idea to use values instead of hard-coding some constants into the OVAL files, because then users can easily customize the benchmark in SCAP Workbench.

**Comment by jan-cerny** [comment]
OVAL experts, do you have any idea if the list of values can be used in rules like `sshd_use_approved_ciphers` instead of a regular expression? @shawndwells @isimluk @redhatrises ?

**Comment by isimluk** [comment]
There are some provisions for multival in OVAL. IIRC, the bind of such values from XCCDF to OVAL is not possible (or not specified clearly).

Well, it's been while. I barely remember. And I have been wrong before. 🐫 

If you could post some code snippets (examples what's wrong) and how it should look, it could help my memory.

**Comment by jan-cerny** [comment]
@isimluk 
For example, this OVAL is ugly:
https://github.com/OpenSCAP/scap-security-guide/blob/master/shared/templates/static/oval/sshd_use_approved_ciphers.xml

Specifically, I don't like the regular expression on line 28:
```
^[\s]*(?i)Ciphers(?-i)[\s]+((aes128-ctr|aes192-ctr|aes256-ctr|aes128-cbc|aes192-cbc|aes256-cbc|3des-cbc|rijndael-cbc@lysator\.liu\.se),?)+[\s]*(?:|(?:#.*))?$
```

It checks if only ciphers form the given list are present in /etc/sshd_config, and no other cipher is there.

The regex works fine, but it has several problems:
* the regular expression is hard to read
* values are hard-coded
* It's not possible to customize the rule using SCAP Workbench or using an XCCDF tailoring file. What if somebody wants to forbid eg. aes128-ctr?

We have so-called "values" in XCCDF. Here we would need that a value being actually a list of values. Lists of values exists in XCDDF, but I can't find how to use it in OVAL then.

**Comment by yuumasato** [comment]
@jan-cerny Maybe this reference helps: https://oval.mitre.org/language/version5.10/ovaldefinition/documentation/oval-definitions-schema.html#variable

This example from reference is enlightening, I think
> For example, if an entity 'size' with an operation of 'less than' references a variable that returns five different integers, and the var_check attribute has a value of 'all', then the 'size' entity returns true only if the actual size is less than each of the five integers defined by the variable.

So, the oval might work if
- regex you mentioned is changed to only check that ciphers from the variable is present.
- and another check is added that verifies that no other strange cipher exists, using another list with all approved ones.
