### ISSUE TITLE
how to build statically ? [HELP ME]

### ISSUE THREAD

**Issue by raphaell** [OpenSCAP/openscap#763]
Hello.

I have some question. 
I wan to build openscap statically in fedora 25 with oscap and probe*
How to do that ?  It doesn't support static link in building. isn't it? 
below is my config option. 

./configure --prefix=/tmp/bu --disable-util-oscap-docker --disable-shared --enable-static --with-crypto=nss3 CFLAGS="-DCURRENT_DIR -m64" LDFLAGS="-static -L/usr/lib64" CFLAGS="-I/usr/include -I/usr/include/nss3 -I/usr/include/nspr4"

in making... 
  CCLD     probe_system_info
  CC       family.o
  CCLD     probe_family
  CC       variable.o
  CCLD     probe_variable
  CC       filehash.o
  CCLD     probe_filehash
/usr/bin/ld: crapi/.libs/libcrapi.a(libcrapi_la-md5.o): undefined reference to symbol 'HASH_Create@@NSS_3.4'
/usr/lib64/libnss3.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:1721: recipe for target 'probe_filehash' failed
make[3]: *** [probe_filehash] Error 1
make[3]: Leaving directory '/root/workspace/openscap-1.2.14/src/OVAL/probes'
Makefile:2710: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/root/workspace/openscap-1.2.14/src/OVAL/probes'
Makefile:1282: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/workspace/openscap-1.2.14'
Makefile:1091: recipe for target 'all' failed
make: *** [all] Error 2

How to resolve that problem? 

Thank you for reading.

**Comment by mpreisler** [comment]
We don't support static linking in libopenscap. It probably wouldn't be that much effort though, patches would be most welcome!

**Comment by raphaell** [comment]
Okay. 
Is there any place to ask something ? :)  or any doubt  about SCAP workbench or openscap.
This place is for bug-report I think.

**Comment by mpreisler** [comment]
@raphaell https://www.open-scap.org/resources/support/
