### ISSUE TITLE
Configure script fails on debian 8

### ISSUE THREAD

**Issue by weaseal** [OpenSCAP/openscap#765]
I tried to compile on debian 8 but it errors out with:

```
configure: error: in `/home/me/openscap-1.2.14':
configure: error: libcurl devel support is missing
See `config.log' for more details
```

But libcurl-devel is installed:
```
$ sudo dpkg --get-selections | grep libcurl
libcurl3:amd64					install
libcurl3-gnutls:amd64				install
libcurl4-openssl-dev:amd64			install
```

I tried playing with some configure flags such as --libdir and --libexecdir but had no luck in getting it to proceed.

config.log attached as config.zip
[config.zip](https://github.com/OpenSCAP/openscap/files/1106684/config.zip)

**Comment by mpreisler** [comment]
```
configure:24385: checking for pkg-config
configure:24418: result: no
```

Install pkg-config.

**Comment by weaseal** [comment]
Aha, right you are! But then the configure script should probably die there instead of going further and dying on a red-herring.

**Comment by mpreisler** [comment]
Yup. A patch would be most welcome :-)
