### ISSUE TITLE
Alert user to proprietary extensions in SCAP content

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/openscap#768]
Sometimes certain content providers use their own proprietary extension (instead of standard
OVAL), you can tell that from content by seeing something along the lines of

    <xccdf:check system="http://cisecurity.org/check">

Perhaps, we can make OpenSCAP report this ^ element to the user. OpenSCAP could output something like:

~Warning: Skipping rule {#X} that requires proprietary extension to evaluate. Please ask you content vendor to provide SCAP/OVAL instead.~

    Warning: Skipping rule {#X} that requires a non-standard extension to evaluate. Please ask you content vendor to provide SCAP/OVAL instead.

(An idea from @isimluk, I'm only capturing it here as an RFE)

**Comment by jan-cerny** [comment]
Thanks @isimluk for the idea. Thanks @shawndwells for reporting.
