### ISSUE TITLE
5.11.2 schemas missing

### ISSUE THREAD

**Issue by Back-N-Black** [OpenSCAP/openscap#783]
I hope I'm in the right place, correct me if I'm wrong.

I am using openscap-1.2.13-2.el6.x86_64 on a Centos 6.8 system
Oval definitions file(centos_linux_6.xml) aquired from https://oval.cisecurity.org/repository/download (v5.11.2/patch/Centos 6)

It complains 

`OpenSCAP Error: Schema file not found when trying to validate '/share/ia/openscap/mitre/centos_linux_6.xml' [validate.c:243]`
`Invalid OVAL Definition (5.11.2) content in /share/ia/openscap/mitre/centos_linux_6.xml. [oscap_source.c:324]`

I have searched through the installed schemas(xsd files) and there is no /usr/share/openscap/schemas/oval/5.11.2 directory.

Looking through this repository I see that it is indeed the case.

Is the answer simply that a Oval definition was provided for which there is no support yet?

**Comment by mpreisler** [comment]
OpenSCAP does not support OVAL 5.11.2 yet but this should be fairly easy for us to fix. We'll take a look at that for 1.2.15. Just adding the files should be enough for partial support.

Until this is fixed you can try using `--skip-valid` as a temporary workaround.

**Comment by Back-N-Black** [comment]
Thanks!
