### ISSUE TITLE
Automated fixing

### ISSUE THREAD

**Issue by yonas** [OpenSCAP/openscap#785]
Are there any tools within OpenSCAP that can automatically fix security issues, or is this purely a scanning/reporting tool?

**Comment by shawndwells** [comment]
On 7/21/17 8:08 PM, Yonas Yanfa wrote:
> Are there any tools within OpenSCAP that can automatically fix
> security issues, or is this purely a scanning/reporting tool?

Hi Yonas,

    OpenSCAP does have remediation capabilities, if your content
supports it. Here are the docs:
https://static.open-scap.org/openscap-1.0/oscap_user_manual.html#_remediate_system

    SCAP Security Guide content does include bash remediations, and
Ansible content is under development.

-Shawn

**Comment by yonas** [comment]
Thanks Shawn!
