### ISSUE TITLE
oscap remediation behavior

### ISSUE THREAD

**Issue by shawndwells** [OpenSCAP/openscap#791]
Using --remediate on rhel 7.4, the system scans and then remediates. 

A few of the rules, like ``xccdf_org.ssgproject.content_rule_audit_rules_execution_restorecon`` show as fixed even though the evaluation message shows errors during remediation. 

Should the behavior of oscap --remediate be updated to scan-->remediate-->rescan?

**Comment by evgenyz** [comment]
Why running another scan session (with another invocation of the scanner) after remediation is not enough? Also, there are remediations, which require system reboot to be properly propagated.
