### ISSUE TITLE
oscap xccdf generate guide --profile does not fail when profile not found

### ISSUE THREAD

**Issue by dahaic** [OpenSCAP/openscap#814]
Summary sums it, basically. You can `cd` into `tests/API/XCCDF/guide/` and reproduce issue there:

```
> oscap xccdf generate guide --profile "notfound" content-profile-xccdf11.xml
Profile "notfound" was not found. Get available profiles using "oscap info".
> echo $?
0
```

**Comment by mpreisler** [comment]
See https://github.com/OpenSCAP/openscap/pull/671#issue-205385735

**Comment by jan-cerny** [comment]
It's probably already fixed. The issue is not reproducible with openscap-1.3.0-3.fc29.x86_64. 
@dahaic I think we need a test case for this.
