### ISSUE TITLE
./src/OVAL/probes/fsdev.c solaris specific code for __fsdev_init function issues

### ISSUE THREAD

**Issue by jlcharton** [OpenSCAP/openscap#817]
Hi,

I think that the code is broken in several places.

line 246:
`struct mnttab *ment;`

But ment is never allocated before being used later on lines 271 and 284.
So maybe line 246 could be fixed like this:
`struct mnttab mentbuf, *ment = &mentbuf;`

lines 271 and 284:
`while ((getmntent(fp, ment)) != 0) {`

But according to solaris man pages for getmntent:

> RETURN VALUES
  getmntent() and getmntany()
     If the next entry is successfully read by getmntent()  or  a
     match  is  found with getmntany(), 0 is returned.  If an EOF
     is encountered on reading, these functions return -1. If  an
     error  is  encountered,  a value greater than 0 is returned.
     The following error values are defined in <sys/mnttab.h>:
     MNT_TOOLONG     A line in the  file  exceeded  the  internal
                     buffer size of MNT_LINE_MAX.
     MNT_TOOMANY     A line in the file contains too many fields.
     MNT_TOOFEW      A line in the file contains too few fields.

So getmntent() is supposed to return 0 on success and the test should probably be:
`while ((getmntent(fp, ment)) == 0) {`

Best Regards,

Jean-Louis Charton

**Comment by mpreisler** [comment]
Hi @jlcharton

could you please submit these changes as a pull request?

**Comment by matusmarhefka** [comment]
@mpreisler @jlcharton Can we close this issue? It looks like it was resolved by commit https://github.com/OpenSCAP/openscap/commit/78291468df36ea0e29755608e6bbd8dcd30f1537

**Comment by jan-cerny** [comment]
Fixed in https://github.com/OpenSCAP/openscap/commit/78291468df36ea0e29755608e6bbd8dcd30f1537
