### ISSUE TITLE
./src/OVAL/adt/oval_collection.c code understanding and portability

### ISSUE THREAD

**Issue by jlcharton** [OpenSCAP/openscap#818]
Hi,

Oracle Developer Studio 12.5 C compiler issues the following error on Solaris:

> CC       libovaladt_la-oval_collection.lo
"oval_collection.c", line 60: zero or negative subscript

line 60 is: `static struct oval_iterator *_debugStack[0];`

As far as I know, zero length array is GCC specific feature not standard C.
So I wanted to slightly modify this to make the code portable but looking closer to the code I got confused.
Firstly because _debugStack is never allocated to a non zero size in the code.
Secondly because _debugStack seems to be accessed with negative indices in several places.
For example in the block starting line 129:
`if ((iterator_count++) < 0) {`
`    _debugStack[iterator_count - 1] = iterator;`
`    dW("iterator_count: %d.", iterator_count);`
`}`

Clearly, when this if statement is true,it means that iterator_count is AT MOST 0 within the { } block of code. And so iterator_count - 1 is <= -1. So _debugStack[iterator_count - 1] = iterator statement looks weird to me. And there are several other places in the code with such if statements.

Is there something I don't understand well?
Any suggestion to make this code portable is welcome.
Thanks,

Jean-Louis Charton

**Comment by jlcharton** [comment]
Can anyone help me on this?
Thanks in advance.

J-L

**Comment by jan-cerny** [comment]
Hi @jlcharton . In my opinion this code doesn't make any sense and doesn't do anything. Most likely it is a remainder from debugging. You can remove this array and all its usages completely.

**Comment by jan-cerny** [comment]
Fixed in https://github.com/OpenSCAP/openscap/pull/830
