### ISSUE TITLE
./src/OVAL/probes/unix/process.c Solaris read_process() issues

### ISSUE THREAD

**Issue by jlcharton** [OpenSCAP/openscap#828]
Hi,

lines 421-422:
`r.scheduling_class = malloc(PRCLSZ);`
`strncpy(r.scheduling_class, (psinfo->pr_lwp).pr_clname, sizeof(r.scheduling_class));`

In my opinion this piece of code has 3 problems:
- The call to strncpy is wrong since r.scheduling_class is a const char *.
- The third parameter to strncpy (i.e. sizeof(r.scheduling_class)) is incorrect and should be PRCLSZ, Lukily PRCLSZ is defined as 8 in sys/procfs.h which equals sizeof(pointer) on _LP64. However, it's wrong on non _LP64 environments.
- r.scheduling_class is never freed thus resulting in a memory leak.

So the question here is why not just write the code this way:
`r.scheduling_class = (psinfo->pr_lwp).pr_clname;`?

Jean-Louis

**Comment by jan-cerny** [comment]
It looks to me that you can do it that way.

**Comment by jlcharton** [comment]
Ouch! While modifying the code I found at least 2 more problems in this function line 454:
`r.tty = oscap_sprintf("%s", psinfo->pr_ttydev);`

- r.tty is allocate but never freed. Okay, this one is easy to fix.
- psinfo->pr_ttydev is a dev_t so the "%s" pattern in this context is buggy. The fix here is probably less trivial since I doubt the function dev_to_tty implemented in process58-devname.c works on Solaris (it seems to be Linux specific code).

**Comment by jlcharton** [comment]
Well, Solaris (at least 10 and 11) has an undocumented function `char *_ttyname_dev(dev_t devno, char *tty, size_t ttylen);` that determines the tty name corresponding to devno.
This makes it relatively easy to provide a dev_to_tty() implementation for Solaris.
However, relying on an undocumented feature is pretty bad practice...

**Comment by jan-cerny** [comment]
Is it possible to solve it without using the undocumented function?

**Comment by jlcharton** [comment]
Certainly yes. One can take a look at _ttyname_dev implementation from OpenSolaris here [http://src.illumos.org/source/xref/illumos-gate/usr/src/lib/libc/port/gen/ttyname.c](http://src.illumos.org/source/xref/illumos-gate/usr/src/lib/libc/port/gen/ttyname.c). It should be a good place to start writing a port of dev_to_tty function for Solaris.
