### ISSUE TITLE
Pre POSIX.1-2008 realpath

### ISSUE THREAD

**Issue by jlcharton** [OpenSCAP/openscap#833]
realpath is called with NULL as second argument in the following files:
./src/OVAL/probes/unix/symlink.c => line 87
./src/common/oscap_acquire.c => lines 207 and 212.

However, this way to call realpath introduced by POSIX.1-2008 is not supported on some plateforms (for instance Solaris 10, AIX 6.1). On such plateforms, realpath(path, NULL) returns NULL and so openscap is broken.

So would you agree to provide in openscap an oscap_realpath() implementation of the realpath function that follows POSIX.1-2008 for plateforms that lack this feature?

That is something like this:

```
#include <config.h> /* For HAVE_POSIX_2008_REALPATH */
#include <limits.h> /* For PATH_MAX */

char *oscap_realpath(const char *restrict path, char *restrict resolved_name)
{
#ifdef HAVE_POSIX_2008_REALPATH
    return realpath(path, resolved_name);

#else /* !HAVE_POSIX_2008_REALPATH */
    char *retval;

    if (resolved_name != NULL)
        retval = realpath(path, resolved_name);
    else {
        char resolved_buf[PATH_MAX];

        retval = realpath(path, resolved_buf);
        if (retval != NULL)
            retval = strdup(retval);
    }

    return retval;
#endif /* !HAVE_POSIX_2008_REALPATH */
}
```

And where HAVE_POSIX_2008_REALPATH would be determined by configure.

If you're okay with this suggestion, in which openscap .c file should I add this function (i.e. what is the better place for such a function) and in which .h file should I declare its prototype?

**Comment by jan-cerny** [comment]
Good catch.

We used to have many custom functions like "oscap_free", "oscap_alloc", "oscap_strcmp", etc. We removed them recently, because they weren't much useful, but they made our code more confusing.

What about fixing it by allocating a buffer explicitly at all places where realpath is called?

**Comment by jlcharton** [comment]
Ok, I'm going to fix it the way you prefer.

**Comment by matusmarhefka** [comment]
Fixed by PR https://github.com/OpenSCAP/openscap/pull/834
Thank you @jlcharton
