### ISSUE TITLE
Code portability question

### ISSUE THREAD

**Issue by jlcharton** [OpenSCAP/openscap#847]
Hi,
There are several places in the code that use GCC specific pragmas or \_\_attribute\_\_ that make other C99 compilers complain. One example of this is in ./src/common/util.h:
```
#define OSCAP_HIDDEN_START _Pragma("GCC visibility push(hidden)")
#define OSCAP_HIDDEN_END _Pragma("GCC visibility pop")
```
IBM XLC/C++ generates tons of warnings "1506-224 (I) Incorrect pragma ignored" for such pragmas.
Moreover, these defines are used with a trailing ';' everywhere in the code. That is like this:
```
OSCAP_HIDDEN_START;
...
OSCAP_HIDDEN_END;
```
However, this is not ISO C compliant. The trailing ';' should not be there. Both Oracle Dev Studio C and GCC (with -pedantic turned on) complain:
Oracle C: warning: syntax error:  empty declaration
GCC -pedantic: ISO C does not allow extra ';' outside of a function.

So my question is: would you agree to remove the trailing ',' everywhere in the code and also to define GCC specific pragrams enclosed with a #ifdef \_\_GNUC\_\_ ... #endif like this:
```
#ifdef __GNUC__
#define OSCAP_HIDDEN_START _Pragma("GCC visibility push(hidden)")
#else
#define OSCAP_HIDDEN_START
#endif
```
This would make the compilation much more quiet (I don't like having tons of minor compiler warnings that may mask a much more significant one).
Thanks.

**Comment by jlcharton** [comment]
Any feedback?

**Comment by matusmarhefka** [comment]
@jlcharton Can't we break something for other compilers if we just enclose all the GCC specific pragmas with #ifdef __GNUC__ ...? I mean yes, we will compile the code with other compilers without warnings but will we produce the same thing as with GCC?

**Comment by jan-cerny** [comment]
@matusmarhefka Yes, they will produce a different thing, but the question is if it will break something. 

@mpreisler or @WesleyCeraso Would the proposed change break compilation with MinGW?

**Comment by jlcharton** [comment]
I have started to look at all places in the code where there are GCC specific pragma or other special stuff.
At this time, I can't say that introducing #ifdef \_\_GNUC\_\_ will break something.
However, I think there are essentially 2 points here:
- compilers that don't recognize GCC special stuff will most of the time just ignore them and eventually emit a warnings (XLC case for instance), so adding #ifdef \_\_GNUC\_\_ should be OK and will make the compilation more quiet
- if there really are situations where enclosing GCC stuff with #ifdef \_\_GNUC\_\_ would break something, it means that in fact the code is not portable and imposes the GCC compiler (and perhaps even particular versions of GCC; who says?) which is probably not desirable.

And for the second point of my first post, the trailing ";" is definitively not correct whatever the compiler.

Note on some \_\_attribute\_\_:
Like GCC, XLC recognizes \_\_attribute\_\_ ((format (printf, n, m))). However, Oracle C doesn't. The way it works with Oracle C (and previously with Sun Studio) is to use a PRINTFLIKEn comment just above the function declaration.

Examples:
The equivalent of:
```int my_func(const char *fmt, ...)  __attribute__ ((format (printf, 1, 2)));```
is
```
/* PRINTFLIKE */
int my_func(const char *fmt, ...);
or
/* PRINTFLIKE1 */
int my_func(const char *fmt, ...);
```

The equivalent of:
```int my_func(int i, int j, const char *fmt, ...)  __attribute__ ((format (printf, 3, 4)));```
is
```
/* PRINTFLIKE3 */
int my_func(int i, int j, const char *fmt, ...);
```
