### ISSUE TITLE
[RFE] Support --oval-results in oscap-ssh

### ISSUE THREAD

**Issue by yuumasato** [OpenSCAP/openscap#863]
SSG Test Suite relies on `oscap-ssh` command and currently it doesn't get the OVAL results file from remote machine.
The OVAL results file would help debug OVAL definitions, tests scenarios, and remediations tested in SSG Test Suite.

**Comment by mpreisler** [comment]
This is tricky because `oscap` dumps OVAL results into `cwd` with names derived from the path to the OVAL file. It's doable though because we have full control over the remote machine `cwd` and we can be sure everything inside it is a product of the `oscap` tool.

**Comment by sbkg0002** [comment]
+1

**Comment by nathanpeters008** [comment]
+1.  See https://github.com/OpenSCAP/scap-security-guide/issues/2527

In order to work around this, you have to ssh to remote machine manually, install openscap-scanner and scap-security-guide, run oscap xccdf eval with the --oval-results flag and save the results, then scp the results back to your scanning machine.

In fact, I wrote a script to do just that because of the lack of oval-results making troubleshooting much more complex if using oscap-ssh.

```
#!/bin/bash

#Install the latest scap-security-guide and openscap-scanner on the remote system
ssh -t username@remote -dev 'sudo yum -y install wget'
ssh -t username@remote -dev 'sudo wget http://copr.fedoraproject.org/coprs/openscapmaint/openscap-latest/repo/epel-7/openscapmaint-openscap-latest-epel-7.repo -O /etc/yum.repos.d/openscapmaint-openscap-latest-epel-7.repo'
ssh -t username@remote -dev 'sudo yum -y install scap-security-guide openscap-scanner'

#scan the remote system for a failing rule and save an html report with oval-results for easier troubleshooting
ssh -t username@remote -dev 'sudo oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_nist-800-171-cui --rule xccdf_org.ssgproject.content_rule_bootloader_password --oval-results --report /home/username/oscap-results/remote-report.html /usr/share/xml/scap/ssg/content/ssg-centos7-ds.xml'

#get the results back
ssh -t username@remote -dev 'scp username@remote:/home/username/oscap-results/remote-report.html .'
```

**Comment by dahaic** [comment]
@mpreisler is the way we dump oval result into `cwd` mandated by something? Or is it bug that over the years transformed itself to feature we want to keep? :)
