### ISSUE TITLE
pragma omp parallel for

### ISSUE THREAD

**Issue by jlcharton** [OpenSCAP/openscap#865]
Hi,

IBM XLC fails on ./src/OVAL/probes/crapi/digest.c with the following error:
> "digest.c", line 153.33: 1506-814 (S) Branching in or out of structured block and  parallel/work-sharing loop is not allowed."

due to the "pragma omp parallel for" statement just above the for loop.

Of course I could just enclose this pragma with a #if defined(__GNUC__) ... #endif to fix the problem.
However I'm not sure of the ins and outs of this pragma, Why is XLC complaining here whilst GCC stays quiet? Is there really a problem or is it just XLC that is brain-damaged?

**Comment by jan-cerny** [comment]
I think that this pragma is a sort of historic remainder. We don't use OpenMP library. The pragma is useless. I suggest removing it.

**Comment by jlcharton** [comment]
Fixed by 9e84347 (#878)
