### ISSUE TITLE
build instructions to install schemas

### ISSUE THREAD

**Issue by matejak** [OpenSCAP/openscap#871]
When I build and install `openscap` according to build instructions, no files end up being installed in the `<prefix>/share/openscap/schemas/xccdf/...`. There is just an `sce` subdirectory of `schemas`. This is a problem as `scap-security-guide` requires more schemas.
The `openscap` [Fedora RPM package](http://pkgs.fedoraproject.org/cgit/rpms/openscap.git/tree/openscap.spec) contains those files. As I am a `spec` file newbie, so I don't see the reason right away, but ending up with those files installed seems to be a manner of documentation or build setup adjustment.

**Comment by yuumasato** [comment]
Hello, I cannot reproduce this.
I did a build and install and the schemas installed seems to be correct.
Can you share the exact steps?

**Comment by matejak** [comment]
OK, I have followed the build instructions literally and it indeed worked. Which means that while standing in the `openscap` root,
`./autogen.sh && ./configure --prefix=$HOME/.local && make && make install | grep schemas`
works, but `VPATH` build
`./autogen.sh && mkdir build && cd build && ../configure --prefix=$HOME/.local && make && make install | grep schemas`
clearly omits the schemas files.
So this is not a documentation issue, but rather a glitch in the build system - autotools should support VPATH builds out of the box.

**Comment by mpreisler** [comment]
Hmm, this is a good catch. This is something we should be testing in jenkins after we fix it IMO.
