### ISSUE TITLE
Failed to run CVE scan of docker container

### ISSUE THREAD

**Issue by karthik101** [OpenSCAP/openscap#879]
Centos version: 7.3.1611
Atomic version: 1.18.1
opscap version: 1.2.14

I get the followng error while running the scan, Not sure if this is a bug or do i need to install any dependencies.

[root@workstation openscap-test]# oscap-docker container-cve f1568bfb443f

Command: oscap oval eval --id oval:org.open-scap.cpe.rhel:def:7 /usr/share/openscap/cpe/openscap-cpe-oval.xml 2>&1 > /dev/null failed!
Command returned exit code 1.
FAIL: 291:chdir: 2, No such file or directory
OpenSCAP Error: Unable to close probe sd [oval_probe_ext.c:424]
Unable to receive a message from probe [oval_probe_ext.c:579]
Failed to create a new agent session. [oval_session.c:320]

Warning: umount: /tmp/tmphrxP0z: not mounted

Retrying 1/10 to unmount /tmp/tmphrxP0z
Warning: umount: /tmp/tmphrxP0z: not mounted

Retrying 2/10 to unmount /tmp/tmphrxP0z
Warning: umount: /tmp/tmphrxP0z: not mounted

Retrying 3/10 to unmount /tmp/tmphrxP0z
Warning: umount: /tmp/tmphrxP0z: not mounted

Retrying 4/10 to unmount /tmp/tmphrxP0z
Warning: umount: /tmp/tmphrxP0z: not mounted

Retrying 5/10 to unmount /tmp/tmphrxP0z
Warning: umount: /tmp/tmphrxP0z: not mounted

Retrying 6/10 to unmount /tmp/tmphrxP0z
Warning: umount: /tmp/tmphrxP0z: not mounted

Retrying 7/10 to unmount /tmp/tmphrxP0z
Warning: umount: /tmp/tmphrxP0z: not mounted

Retrying 8/10 to unmount /tmp/tmphrxP0z
Warning: umount: /tmp/tmphrxP0z: not mounted

Retrying 9/10 to unmount /tmp/tmphrxP0z
Warning: umount: /tmp/tmphrxP0z: not mounted

Retrying 10/10 to unmount /tmp/tmphrxP0z
Traceback (most recent call last):
  File "/usr/bin/oscap-docker", line 112, in <module>
    args.func()
  File "/usr/bin/oscap-docker", line 44, in cve_scan
    result = OS.scan_cve(self.args.scan_target, self.unknown_args)
  File "/usr/lib/python2.7/site-packages/oscap_docker_python/oscap_docker_util.py", line 241, in scan_cve
    self.helper._cleanup_by_path(_tmp_mnt_dir)
  File "/usr/lib/python2.7/site-packages/oscap_docker_python/oscap_docker_util.py", line 173, in _cleanup_by_path
    DM.unmount_path(_no_rootfs)
  File "/usr/lib/python2.7/site-packages/Atomic/mount.py", line 325, in unmount_path
    raise ValueError("Unable to unmount {0} due to {1}".format(path, result_stderr))
ValueError: Unable to unmount /tmp/tmphrxP0z due to umount: /tmp/tmphrxP0z: not mounted

**Comment by jan-cerny** [comment]
@karthik101
Try to upgrade to OpenSCAP 1.2.15. We have a similiar issue fixed in OpenSCAP 1.2.15.

If upgrade doesn't help, then there is also a known bug in Atomic. https://bugzilla.redhat.com/show_bug.cgi?id=1488385

**Comment by jan-cerny** [comment]
@karthik101 Did the upgrade helped or do you still encounter the issue?

**Comment by karthik101** [comment]
Hey jan-cerny,  Thanks for the quick reply. I'm not working on this anymore, we kept the CVE scan on hold for now and planned to work on it later.
you can close this issue, will open it if it fails with the latest version.

Regards, 
karthik
