### ISSUE TITLE
./src/OVAL/probes/unix/file.c file_cb callback and /proc fs

### ISSUE THREAD

**Issue by jlcharton** [OpenSCAP/openscap#880]
Hi,

Lines 279-282:
```
if (lstat (st_path, &st) == -1) {
                dI("lstat failed when processing %s: errno=%u, %s.", st_path, errno, strerror (errno));
		return strncmp(st_path, "/proc", 4) == 0 ? 0 : -1;
} else {
```

I don't really understand the /proc special processing attempt. If the goal is to handle differently special filesystems; in that case why just look for /proc and not also for /sys for instance?

Moreover, I say "attempt" because I'm pretty sure the test is wrong since strlen("/proc") is 5 and not 4 (magic numbers are evil but this one is not one of mine ;-)).
To fix the test, it should probably be written strncmp(st_path, "/proc", strlen("/proc")) == 0 ? 0 : -1 or strncmp(st_path, "/proc", sizeof("/proc") - 1) == 0 ? 0 : -1.

But even then, is it really correct regarding the test goal? I'm still not sure: what if for some reason lstat() fails and st_path is "/procedure/...." for example; that is a path to a directory on a non special filesystem but that also begins with "/proc"?

So, not to mention /sys, shouldn't the correct test be:
```
return (strcmp(st_path, "/proc") == 0 || strncmp(st_path, "/proc/", sizeof("/proc/") - 1) == 0) ? 0 : -1.
```
I.e. st_path is either /proc itself or strictly some subdirectory of /proc.

**Comment by jan-cerny** [comment]
Hi @jlcharton .
Nice catch, thank you for opening the issue. I have looked into that. I have found that this line was introduced by commit 840ee0cfb5f78b5415e3be182d87c3528ae65362. The commit message says that:
```
    trac#457: Skip transient files when traversing /proc                                                  
                          
    Addressing:           
    lstat failed when processing /proc/27762/task/27762/fd/7: errno=2, No                                 
    such file or directory.                          
                          
    (Where fd=7 was directory openned by openat during fts_read)
```
It looks like the goal was to handle special filesystems. Unfortunately I couldn't find more details. I think that there where unexpected fails with evaluating SCAP content that browsed whole root filesystem.

I agree with you that the test there isn't OK.  Your solution looks better. Feel free to open a pull request.

**Comment by jlcharton** [comment]
Hi @jan-cerny. Ok I better understand the initial purpose of the test now.

But whatever the reason (a /proc entry that has disappeared or any other error on a file elsewhere on a regular filesystem), is it really a good idea to return -1 from file_cb() as soon as lstat fails since then the whole file tree walk in probe_main will stop. Thus a simple lstat failure can break the probe and we may miss results.

Can't we just fix file_cb like this:
```
if (lstat (st_path, &st) == -1) {
                dI("lstat failed when processing %s: errno=%u, %s.", st_path, errno, strerror (errno));
                /* Be gentle with the underlying file tree walk. */
		return 0;
}
```

**Comment by jan-cerny** [comment]
@jlcharton I think you're right. Your solution works for me.

**Comment by matejak** [comment]
I took a look on this and as far as I can tell, this issue is valid and the associated PR is beneficial. The true intention of the code is hidden to us, so why it looked like that in the beginning remains a mystery - the solution proposed by this PR is both simpler and more robust in handling special cases s.a. `/proc` and `/sys`.
