### ISSUE TITLE
[RFE] consolidate subcommand to openscap-containers

### ISSUE THREAD

**Issue by vbatts** [OpenSCAP/openscap#893]
presently there is `openscap-docker` that talks to a docker daemon. I see [a request for `openscap-rkt`](https://github.com/OpenSCAP/openscap/issues/403). 
With kubernetes having a consistent [Container-Runtime-Interface (CRI)](https://github.com/kubernetes/kubernetes/blob/242a97307b34076d5d8f5bbeb154fa4d97c9ef1d/docs/devel/container-runtime-interface.md) grpc protobuf, there are now runtimes like [cri-o](https://github.com/kubernetes-incubator/cri-o) and containerd that only need to expose a unix socket that satisfies the CRI protobuf, for kubernetes or any other tool like OpenScap to communicate on.

Rather than adding each of these, perhaps there is a cleaner way to group them, like a `openscap-containers` subcommand.

**Comment by mpreisler** [comment]
I like this idea. Are you interested in working on this feature?

**Comment by vbatts** [comment]
This is not a feature I could own doing right now. I know @baude contributed in this area in the past, but he may be taxed right now.

**Comment by vbatts** [comment]
working my way towards this ... https://github.com/vbatts/python-kubernetes-cri

**Comment by evgenyz** [comment]
Closing this because of existence of `oscap-podman` and lack of any activity.
