### ISSUE TITLE
Free vs xmlFree

### ISSUE THREAD

**Issue by WesleyCeraso** [OpenSCAP/openscap#898]
We have been using free on memory allocated though libxml2, on their linux implementation they use malloc, so its not a big deal, however, on Windows, it can cause crashes similar to #770 and it can impact @jan-cerny work on #890.

When we clone such pointers we use malloc, so it's not possible to replace every free with xmlFree because the memory could have been allocated in both ways.

**Comment by WesleyCeraso** [comment]
First idea from @mpreisler:
strdup the xmlChar just after retrieving it and then xmlFree the xmlChar.

**Comment by WesleyCeraso** [comment]
My idea:
Use xmlStrdupFunc to duplicate the strings and use xmlFree in every applicable place

**Comment by mpreisler** [comment]
@jan-cerny haven't you fixed this? please report status in this ticket

**Comment by jan-cerny** [comment]
@mpreisler I haven't fixed it. I don't have any status.
