### ISSUE TITLE
probe_partition availability

### ISSUE THREAD

**Issue by jlcharton** [OpenSCAP/openscap#899]
Hi,

I'm not sure this is the right place for this kind of discussion but as far as I can understand, partition_test, partition_object and partition_state seem to be Linux specific. Am I right? If so, I don't understand why since all Unices I'm aware of deal with partitions. And then how can I write a SCAP test on Solaris or AIX to check whether or not a filesystem is mounted; and whether or not it is mounted with particular options such as nosuid, nodev, noexec, ...?

**Comment by matejak** [comment]
Hello, people with deeper knowledge on this topic are not available right now, but please be patient - we will get back to you.

**Comment by jan-cerny** [comment]
Hi, the partition_test is defined as Linux-specific by OVAL specification. It is specified in OVAL Linux Definitions section. I thought that there could be some similar test in AIX or Solaris sections in the OVAL specification, but I couldn't find any. See https://oval.mitre.org/language/version5.11/ I don't know why it is so, it looks to me that partition test could be defined for all unices.

I think this question would be more for the OVAL language itself. Try to open an issue on the OVAL github https://github.com/OVALProject/Language or send them a mail on mailing list http://lists.cisecurity.org/mailman/listinfo/oval_developer_lists.cisecurity.org

**Comment by jlcharton** [comment]
Hi,

Okay, I'm going to contact the OVAL team itself.
However, do you have any idea of how I could check for mount points properties on non Linux Unices just using the core, independent or Unix probes?

Thanks.

**Comment by evgenyz** [comment]
Okay, this is definitely not an issue in the scanner, the implementation follows the standard. Please, ping us if the issue in OVAL Community would be resolved positively.
