### ISSUE TITLE
Static analysis fixes

### ISSUE THREAD

**Issue by matejak** [OpenSCAP/openscap#909]
The static analysis reported some errors ranging from missing includes to errors that could cause crash:
[coverity-warnings.log](https://github.com/OpenSCAP/openscap/files/1474819/coverity-warnings.log)

**Comment by evgenyz** [comment]
We should check is some of these problems still exists. And close bug If they are obsolete.

**Comment by matejak** [comment]
As this is an ongoing code quality effort, I close it as the original issue has been fixed.
