### ISSUE TITLE
Some tests fail if CMake build type is Release

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/openscap#912]
If build type is Release, it defines NDEBUG, which means that `assert()` calls in some of our tests do nothing, and then the test is not performed, and some results are not generated.

An example could be https://github.com/OpenSCAP/openscap/blob/master/tests/API/XCCDF/unittests/test_xccdf_overrides.c test, which uses `assert()`. If the build type is release, it defines NDEBUG, which means that those `assert()` macros are compiled tobasically no operation. Please see `man 3 assert`.
 That means that the checks are not performed. Moreover, in this example the file `test_xccdf_overrides.xml.out` is not created, because it is created iside an assert, and therefore the test fails without any report. The reason for that is that in bash test the test checks if the file exists. Please check https://github.com/OpenSCAP/openscap/blob/master/tests/API/XCCDF/unittests/test_xccdf_overrides.sh#L12

I have set CMake build type on Jenkins openscap-master job to Debug as temporary workaround.

This is the most serious problem, because some of the tests won't test anything with the released version.

Does anybody have any idea how to solve this issue?

**Comment by mpreisler** [comment]
> Does anybody have any idea how to solve this issue?

assert is not meant for unit tests. we need to use something other than assert.

Why does this work on maint-1.2 but not in master? Doesn't maint-1.2 also set NDEBUG?

**Comment by jan-cerny** [comment]
@mpreisler It works on maint-1.2 because in maint-1.2 these tests don't use assert. They use `assume`. During CMake port I have replaced all the `assume` by `assert` in those tests because the tests couldn't build with Cmake.

I think that best solution would be to undefine "NDEBUG" in the affected tests.

It can be related to another issue https://github.com/OpenSCAP/openscap/issues/908

**Comment by mpreisler** [comment]
That sounds like a workaround rather than a solution. We shouldn't use
assert for unit testing. This is not what assert is meant for.

**Comment by jan-cerny** [comment]
Then the original `assume` in maint-1.2 was more correct. But we need to find something that is possible to build with.

**Comment by jan-cerny** [comment]
Fixed in #1078
