### ISSUE TITLE
test probes/rpmverifyfile/all.sh fails on RHEL6 on master

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/openscap#939]
The OVAL result for `capabilities_differ` is `not performed`.

I think there is some problem with incorrect usage C preprocessor macros in the rpmverifyfile_probe or in the CMake script that detects RPM version.

**Comment by jan-cerny** [comment]
```
Definition oval:x:def:1: true
Evaluation done.
+ rpmverifyfile probe test with OVAL 5.11.1                   [ FAIL ]
Failed: expected count: 1, real count: 0, xpath: 'oval_results/results/system/oval_system_characteristics/system_data/lin-sys:rpmverifyfile_item/lin-sys:capabilities_differ[text()="not performed"]'
RESULT: FAILED

TEST: rpmverifyfile probe test with OVAL 5.11
Definition oval:x:def:1: true
Evaluation done.
+ rpmverifyfile probe test with OVAL 5.11                     [ PASS ]
RESULT: PASSED
```

**Comment by jan-cerny** [comment]
This is a big problem for every upstream pull request on master on Jenkins!

**Comment by jan-cerny** [comment]
We don't focus on RHEL6 in master, therefore we remove the BLOCKER label.

**Comment by evgenyz** [comment]
Changing the milestone as 1.3 is not supposed to be released for RHEL6/7.

**Comment by jan-cerny** [comment]
We don't build master branch and maint-1.3 branch on RHEL 6 anymore.
