### ISSUE TITLE
Introduce machine-readable output

### ISSUE THREAD

**Issue by matejak** [OpenSCAP/openscap#950]
The `oscap` scanner is frequently used by higher-level applications to perform scanning and remediations. However, those apps easily run into problems when interpreting the scanner output - for example, `scap-workbench` has occasional problems to distinguish between info and error messages.
Defining an interface for machine-readable output would be an ideal robust fix to this kind of problems once for all.

**Comment by jan-cerny** [comment]
@matejak What information will be contained in the machine readable output?

**Comment by matejak** [comment]
Thanks to discussion with @jan-cerny , it turns out that `oscap` already has this feature - when passing e.g. `--verbose INFO`, all of the info stuff leads line with `I: ` for info, `W: ` for warnings etc.
This output goes to stderr.
