### ISSUE TITLE
How to run OpenSCAP for OpenStack(ubuntu16)

### ISSUE THREAD

**Issue by asingh35** [OpenSCAP/openscap#959]
Hi Team,

I have to run openSCAP on Openstack on ubuntu. I have a test setup ready with Ubuntu and Openstack, I have installed OpenSCAP for ubuntu on it.
Can anyone guide me how to it, I am running run_script but it is giving me very few outputs mainly for file permissions and other things. It is not giving me full fledge output that I was expecting it to give.

How I am running OpenSCAP is below.

#./run_script.sh > report.txt

is there any other way to run it. 

Please assist me on this. I need this urgently.

many Thanks.

Regards,

**Comment by jan-cerny** [comment]
@asingh35 Hi, I would like to help you, but I am not aware of any `run_script.sh` in OpenSCAP. Where did you get this script? What is its purpose?

The command people usually use is "oscap".
Try to check the User Manual https://static.open-scap.org/openscap-1.2/oscap_user_manual.html

**Comment by asingh35** [comment]
Hi Jan-Cerny--

Sorry, I haven't received any notification of your message and it was unread until today. I am messaging you the details that I was talking about.

I tried to install windows version of OpenSCAP but it has nothing for ubuntu as of now. However, I have got an script at Github which is providing me a decent report in xml format (exactly how windows version of openSCAP) works..
---------------------------------------------

Can you assist me with commands..I have all files, XCCDF, xml, OVAL inside OpenSCAP folder where the download happened (through sudo apt-get Openscap8 command)....

How can I import XCCDF and OVAL files in the windows version so that I can run OpenSCAP on remote machines (any flavour)

Please guide...Many Thanks

**Comment by mpreisler** [comment]
@asingh35 Please read the guide @jan-cerny referenced, let us know if anything is missing in it.

> How can I import XCCDF and OVAL files in the windows version so that I can run OpenSCAP on remote machines (any flavour)

You should be able to just open the `ssg-*-ds.xml` files in SCAP Workbench, workbench will transport them to target machines by itself, there is no need to do anything manually. Download the zip files from SSG releases, see https://github.com/OpenSCAP/scap-security-guide/releases
