### ISSUE TITLE
Impossible to find OVAL file when doing an offline remediation

### ISSUE THREAD

**Issue by ptitoliv** [OpenSCAP/openscap#966]
When trying to execute an offline remediation from a different directory from where the OVAL file is installed, the `oscap xccdf remediate command` can't localize the OVAL file with the message

```
WARNING: Skipping ./ssg-rhel7-oval.xml file which is referenced from XCCDF content
```

Steps to reproduce : 

1. Execute a simple eval using the following command 

```
oscap xccdf eval --profile <profile_name> --results scan.xml --cpe /usr/share/xml/scap/ssg/content/ssg-rhel7-cpe-dictionary.xml /usr/share/xml/scap/ssg/content/ssg-centos7-xccdf.xml
```
2. Execute an offline remediaton with the command  :+1: 
```
oscap xccdf remediate --results remediate.xml --cpe /usr/share/xml/scap/ssg/content/ssg-rhel7-cpe-dictionary.xml scan.xml
```
Result;  All the remediation are with the `error` state. The remediation scripts are correctly executed but the check after is not executed because oval file is not detected.

Important things : 
1. There is not problem with an online remediation
2. If I put the ```scan.xml``` in the same directory than the OVAL file, there is no problem.

Environment : CentOS 7.4 with openscap-scanner 1.2.14-2 (It doesn't seem to be fixed by the PR 645)

Is it a bug or a feature which needs a special reference to the OVAL file ? 

Thanks !

**Comment by jan-cerny** [comment]
Hi. It looks like a bug.

Would it help to use a datastream instead?
For example /usr/share/xml/scap/ssg/content/ssg-centos7-ds.xml. (The profile ID name will be different, check `oscap info`). Datastream is a container that combines all the files in a single file.

**Comment by ptitoliv** [comment]
@jan-cerny : Just did the test and when even using the datastream file instead of the XCCDF file, the result file produced by the eval command doesn't contain the OVAL checks. So when doing the remediate action, the bug is still the same.

**Comment by jan-cerny** [comment]
What about trying `--results-arf` instead of `--results`?

**Comment by ptitoliv** [comment]
@jan-cerny It doesn't seem possible for to use a ARF result file for an offline remediation. The given error is : "Error : session input file was determined but it isn't an XCCDF file, a source datastream or an XCCDF tailoring file"

**Comment by MollyJoBault** [comment]
still broken in CentOS 7.5 openscap.x86_64 1.2.16-8.el7_5

**Comment by evgenyz** [comment]
@jan-cerny We forbid remediation in offline mode, don't we? Or I misunderstood "offline" term here?

**Comment by jan-cerny** [comment]
@evgenyz I think the word "offline" is used in a different context here. My understanding is 
* "online" remediation means running remediation as a part of the scan run, ie. `oscap xccdf eval --remediate`
* "offline" remediation means running remediation separately, after scan, based on a previous scan results, ie. `oscap xccdf remediate`.
