### ISSUE TITLE
python for openscap?

### ISSUE THREAD

**Issue by jlozadad** [OpenSCAP/openscap#976]
hello,

I was wondering if there was a python library that I can use to call in some scripts.

**Comment by matejak** [comment]
Openscap Python bindings are installed if you build them (you need SWIG for that). Make sure that you enable those by passing `--enable-python3` to the configure script and examine its output for possible errors.
Then, examine the `<prefix>/lib/pythonXXX/site-packages/` directory and try to `import openscap`.

**Comment by matejak** [comment]
I am closing the issue, if you are unable to find/use the `openscap` module, prease reopen it and tell us what went wrong.
