### ISSUE TITLE
oval_enumerations.c:667: warning: comparison of unsigned expression < 0

### ISSUE THREAD

**Issue by jlcharton** [OpenSCAP/openscap#986]
Hi,

Taking a closer look at this warning, the `if (subtype < 0)` seems broken to me since the subtype variable is initialized to OVAL_SUBTYPE_UNKNOWN (which equals 0) at line 611 and never change above line 667.
So I believe the intended code was `if (subtype_s < 0)` instead.
But then, considering the definitions of the OVAL_SUBTYPE_XXXX_MAP arrays there is still a problem since then oscap_string_to_enum returns OVAL_SUBTYPE_UNKNOWN as default value.

So in my opinion either the default value in OVAL_SUBTYPE_XXXX_MAP arrays should be -1 or the if statement at line 667 should be `if (subtype_s == OVAL_SUBTYPE_UNKNOWN)`.
Can you confirm this?

Regards,
Jean-Louis

**Comment by matejak** [comment]
Thank you for your findings! It is a difficult question for us. The code in question was written 4 years ago by @isimluk and it may take some time for us to find out the true intention of the code.
Here is the link to the incriminated piece for reference: https://github.com/OpenSCAP/openscap/blob/maint-1.2/src/OVAL/oval_enumerations.c#L667

**Comment by jlcharton** [comment]
Further investigations make me think that
```
	int subtype_s = oscap_string_to_enum(map, tagname);
	if (subtype < 0) {
		dW("Unknown OVAL family subtype: %s", tagname);
		subtype = OVAL_ENUMERATION_INVALID;
	}
	else {
		subtype = subtype_s;
        }
```
can simply be replaced by
```
        subtype = oscap_string_to_enum(map, tagname);
        if (subtype == OVAL_SUBTYPE_UNKNOWN) {
                dW("Unknown OVAL family subtype: %s", tagname);
        }
```

Moreover, at the beginning of the function, tagname should be test for NULL after the call to xmlTextReaderLocalName. That is:
```
        char *tagname = (char *)xmlTextReaderLocalName(reader);
        char *endptr = (tagname != NULL) ? strrchr(tagname, '_') : NULL;
```

J-L

**Comment by jan-cerny** [comment]
@jlcharton  I think you are correct. The `if (subtype < 0) {` condition at line 667 makes no sense to me. Try to replace it, and if it works, feel free to open a pull request :smiley:

**Comment by jan-cerny** [comment]
@isimluk That's fine, there's no need to excuse. Thank you very much for looking at this issue.

**Comment by jan-cerny** [comment]
Fixed in https://github.com/OpenSCAP/openscap/pull/991/files
