### ISSUE TITLE
Compilation error during make on Centos7

### ISSUE THREAD

**Issue by yahanvesh** [OpenSCAP/openscap#987]
Im having compilation issues during make on Centos7, tested with python 3.6.3,3.6.4
Tried removing and installing the corresponding devel packages also.
Current packages:-
python36.x86_64                        3.6.3-7.el7                     @epel    
python36-devel.x86_64                  3.6.3-7.el7                     @epel    
python36-libs.x86_64                   3.6.3-7.el7                     @epel    

Error:-
openscap_py_wrap.c:125:20: fatal error: Python.h: No such file or directory
 #include <Python.h>

**Comment by matejak** [comment]
Hello, it may be that the build system got confused by Python3. Have you passed `--enable-python3` to the `configure` script?

**Comment by yahanvesh** [comment]
@matejak i tried as you said- configure --enable-python3
Still same issue
```
openscap_py_wrap.c:125:20: fatal error: Python.h: No such file or directory
 #include <Python.h>
```

**Comment by matejak** [comment]
OK, the next thing that comes to my mind is that you might have Python3 only, and Python2 support is enabled by default. So could you please try to pass both `--enable-python3` and  `--disable-python`?

**Comment by yahanvesh** [comment]
@matejak Thanks for your input, using both the flags works! Can we add a note in the ReadMe adding these details.

**Comment by matejak** [comment]
You have a good point, #990 addresses your suggestion.
