### ISSUE TITLE
crapi and _FILE_OFFSET_BITS=32

### ISSUE THREAD

**Issue by jlcharton** [OpenSCAP/openscap#988]
Hi,

_FILE_OFFSET_BITS=32 is forced in the following places:
src/OVAL/probes/crapi/Makefile.am (unconditionnally)
src/OVAL/probes/crapi/crapi.h (if _FILE_OFFSET_BITS is not defined)

and there is conditionnal compilation depending on _FILE_OFFSET_BITS == 32 in this C files:
src/OVAL/probes/crapi/rmd160.c
src/OVAL/probes/crapi/md5.c
src/OVAL/probes/crapi/sha1.c
src/OVAL/probes/crapi/sha2.c

I'm wondering what can be the consequences of this when building nativelily for x86_64 (in this case _FILE_OFFSET_BITS don't have to be defined since by definition I/O are natively 64 bits and forcing _FILE_OFFSET_BITS=32 seems weird in this case) or when building for x86 with large files support enabled (i.e. with -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 set in CFLAGS)?

Moreover, the use of _FILE_OFFSET_BITS=64|32 to enable|disable LFS is ok on Linux or Solaris but not on AIX (and maybe other platforms). The AIX way is -D_LARGE_FILES -D_LARGE_FILE_API.

Jean-Louis

**Comment by jlcharton** [comment]
More on this.
In fact the code dealing with _FILE_OFFSET_BITS == 32 in the files src/OVAL/probes/crapi/rmd160.c, src/OVAL/probes/crapi/md5.c, src/OVAL/probes/crapi/sha1.c and src/OVAL/probes/crapi/sha2.c is wrong in the way is uses of mmap. One has:
```
#if _FILE_OFFSET_BITS == 32
                buflen = st.st_size;
# if defined(__FreeBSD__)
                buffer = mmap (NULL, buflen, PROT_READ, MAP_SHARED | MAP_NOCORE, fd, 0);
# else
                buffer = mmap (NULL, buflen, PROT_READ, MAP_SHARED, fd, 0);        
# endif        
                if (buffer == NULL) {
#endif /* _FILE_OFFSET_BITS == 32 */
```
The problem here is that when mmap fails, it returns MAP_FAILED which is `(void*)-1` and not NULL which is `(void*)0`. So the test `if (buffer == NULL)` is broken and should be `if (buffer == MAP_FAILED)`.

Jean-Louis

**Comment by matejak** [comment]
Hello Jean, you raise a good question. The code mostly seems to be about 8 years old and written by @dkopecek .
Therefore, it will take us some time before we can answer those questions and possibly fix incorrect usage, so please be patient with us.

**Comment by jlcharton** [comment]
Hello matejak,
As far as I can, I always try to raise good questions :-)
More seriously, I'm pretty sure that there is no need for this _FILE_OFFSET_BITS 32 stuff and that the code could just try mmap first in all cases (i.e. whatever _FILE_OFFSET_BITS) and then handle MAP_FAILED to fall back processing the file with multiple read.

J-L

**Comment by dkopecek** [comment]
@jlcharton Looking at it now, I think it's totally wrong too. +1 for a rewrite.
